### ISSUE TITLE
use webview to use original ui

### ISSUE THREAD

**Issue by lkwg82** [syncthing/syncthing-gtk#100]
What about chaing the ui to use a webview with the original ui?

*Advantages*
- not duplicate ui functionaliy
- html/css is desktop ready
- concentrate on high quality ui against many 'quite ok' uis
- html/css is widely understood vs. complexity of gtk 

Then we could add theme support to the original ui and have some adjusted theme for this ui.

I could imagine in the farer future to create a bundle of synthing and a ui for desktop.

This would really push adoption and this great product!

Cheers Lars

**Comment by AudriusButkevicius** [comment]
The way the web UI is done now, it's not very friendly for embedding inside other windows, because it doesn't have a fixed height, and has modals and stuff which makes it awkward.

If we do go this way, then in that case perhaps we should use Qt, as it's rendered better cross-platform, and has most of the tray icon stuff built already.

**Comment by kozec** [comment]
Sorry, but no. If I wanted to use webapp, I wouldn't start coding desktop application :)

Plus, turning Syncthing's WebUI to web application is one-click feat at least with chrome...

**Comment by lkwg82** [comment]
Have you tried btsync on windows/linux? I'm quiet satisfied from this user experience.

The combination of a window and a systray integration makes in my eyes a desktop integration.
I have no aversion of web apps, as they have good user experience.

So what exactly you dislike?

**Comment by kozec** [comment]
Me disliking webapps is not problem here, problem is that I see no sense in doing it. It's simply not something worth coding, as you can make that sort of "application" simply by creating desktop file which targets `chromium --app=http://localhost:8080`, even with notifications and probably tray icon.

**Comment by lkwg82** [comment]
Fine.
