### ISSUE TITLE
fedora nautilus integration

### ISSUE THREAD

**Issue by napseis** [syncthing/syncthing-gtk#101]
hi,

I havea Ubuntu 14.04 and Fedora 21 machine, each with syncthing-gtk (for the filesystem monitor feature)
On both, i installed python nautilus to have desktop integration. While it works fine on Ubuntu, the option is still greyed out in Fedora. Do we need some other package ?

Thanks

**Comment by kozec** [comment]
It checks if `nautilus/extensions-3.0/libnautilus-python.so` exists in at least one one of prefixes: `	[ "/usr/lib", "/usr/local/lib/",  "/usr/lib/x86_64-linux-gnu/", "/usr/lib/i386-linux-gnu/" ].
Can you list and post files contained in python nautilus integration package?
