### ISSUE TITLE
Not able to run on Windows XP

### ISSUE THREAD

**Issue by mundodisco8** [syncthing/syncthing-gtk#104]
Hi,

Thanks for your work, I really appreciate it.

I'm running syncthing-gtk on a W7 machine without issues. However, when I try to use it in windows XP, it always runs the first run wizard (as is not able to find the syncthing setup), and throws an error on step 3 Download Daemon: 
"Failed to Download Syncthing Daemon package
g-io-error-quark: Get request failed: the message received was unexpected or badly formated. (0). Failed to determine latest Syncthing version".

I tried to move the syncthing config folder to the one mentioned in the intro of the wizard (~\.config\Syncthing), with no luck. 

I understand that XP is and old OS but if you could lead me at least in the direction of what is causing the issues, I would be (even more) grateful. Thanks!

![2015-03-09_1241](https://cloud.githubusercontent.com/assets/8402707/6555082/41812a2a-c65a-11e4-89fd-318ecacbd9a8.png)

**Comment by kozec** [comment]
I didn't even knew that you can run Syncthing (daemon) on XP... If wizard is only problem, just download & run syncthing manually once, ST-GTK will use it if it can find existing configuration.

Error message basically means that there is something between your machine and GitHub mangling HTTP communication. Maybe firewall or web filter of some sort.

**Comment by mundodisco8** [comment]
Thanks for your quick response. Actually, syncthingGTK seems unable to look for the syncthing config folder (currently installed in program files\syntching). I will check the router to see if there are any issues (probably the firewall is misbehaving)

Thanks.

**Comment by kozec** [comment]
Yes, configuration in program files\syntching may be good reason for ST-GTK not working. It expects it to be found in default location - %LOCALAPPDATA%\Syncthing

**Comment by kozec** [comment]
@mundodisco8, About issue on that screenshot. Can you check if you can view `https://github.com/syncthing/syncthing` *and then* `https://api.github.com/repos/syncthing/syncthing/releases` using Internet Explorer on that XP machine?

**Comment by mundodisco8** [comment]
Hi Kozec, thanks for taking my issue into account, I will check that later on, as I was on holidays and didn't had the chance to look. I understand that XP is old and I shouldn't expect support, but is worth to try anyway.

**Comment by kozec** [comment]
Well, 1st run wizard probably doesn't stand a chance running at OS that github refuses communicate with, but manual installation should work.

Just download latest syncthing, run it once and then try to use this build - https://github.com/syncthing/syncthing-gtk/releases/edit/v0.6.2.1

**Comment by mundodisco8** [comment]
Hi,

First of all, I really appreciate the effort you are taking to support this random guy from the internet.

I kind of feel guilty of keeping you working in a relic as WinXP is. I tried the last two releases, 6.2.1 and 6.3. The last one has skips the wizard, as expected, but returns a Can't Invoke the daemon message, asking me to point to the syncthing path. It does both with the syncthing running or not, and pointing to the right path doesn't help. Syncthing-gtk opens an empty window. I don't want to drag you and make you lose your time on this, so please leave it on lowest priority on your to do list. 

Syncthing seems to be using c:\documents and settings\<USER NAME>\Application Data\Syncthing to store the configuration.

**Comment by kozec** [comment]
Note to self: Don't close issue just because something is _supposed_ to work :D

**Comment by kozec** [comment]
Hi again. I probably found where this crazy problem is. Are you using localized Windows XP version? On one of machines where I did test ST-GTK crashed 'cos %APPDATA% were pointing to `C:\Documents and Settings\Tom\Data aplikacˇ` -_-

**Comment by mundodisco8** [comment]
Nope, not my case, unless british english is a different localized version to the one you are using.

Currently running Win XP Pro SP3, 32 bits. I installed the last version, and the problem continues, asks for the syncthing binary location but after pointing to it, it doesn't seem to be able to run it. The syncthing window pops up, but it's empty, except for a couple of buttons (the one with the logo and the one with the gear). The Display Daemon Output is greyed out and the open web interface does nothing. Running the syncthing before Syncthing-GTK doesn't help either

**Comment by kozec** [comment]
That's because that fix above is more recent that latest release :)

**Comment by fastfwd** [comment]
Thanks so much, kozec.  Version 6.5 runs on my Windows XP Pro SP3 box.

**Comment by kozec** [comment]
> Thanks so much, kozec. Version 6.5 runs on my Windows XP Pro SP3 box.

That's great to hear. How about you, @mundodisco8 ? By the way, this new release should create log file named `Syncthing-GTK-somethingrandom.log` in %TEMP% directory when launched with `-d` argument. If it still crashes for you, try to upload that file somewhere.

**Comment by mundodisco8** [comment]
![2015-04-15_1035](https://cloud.githubusercontent.com/assets/8402707/7156010/3206f6d8-e35b-11e4-8102-6c3a055f00c8.png)

Look at that!

Thanks for all the trouble you went through to fix a random issue in a long way out of support operating system :smile:

If you are bored don't hesitate to reopen this case and I will find some random bug to annoy you!

Again, thank you very much.

**Comment by kozec** [comment]
Np, it was pretty funny grave-digging session :D

**Comment by heatvent** [comment]
Hi, I'm using the original Windows Home Server and get the same error as the original post with the current version.  Should the current version address this or is there something different from XP with WHS?

Thanks
