### ISSUE TITLE
Window dimensions. 

### ISSUE THREAD

**Issue by nille02** [syncthing/syncthing-gtk#105]
On a Small Displays, like the 1366x786 Displays, you get troubles to save folder settings, if you has many devices. I've attached a image to show the issue. 

![screenshot 2015-03-10 10 37 39](https://cloud.githubusercontent.com/assets/4272018/6572382/fe6cbbb0-c711-11e4-9269-aed343f8a1b6.png)

The Save and Cancel Button is no longer reachable.

**Comment by kozec** [comment]
I can probably add scrollbar somewhere, but you can always save just by pressing enter...

**Comment by nille02** [comment]
Pressing Enter is not working.  Thats has only a effect on the current item. e.g. a checkbox triggers and in the text field it jumps to the first letter.

If i'm open the edit box the first field that is active is the folder master. 

A scroll bar would fix the problem. as an alternative way i would alter the device table so that i have entry left from the first entry. or make only box where the devices are listed as a scrollable box.

**Comment by nille02** [comment]
with alter the table to the right i mean something like this. 

![screenshot 2015-03-10 10 37 39](https://cloud.githubusercontent.com/assets/4272018/6581391/e2b5843e-c756-11e4-8f03-b17ed79bc5ff.png)

**Comment by kozec** [comment]
Making two columns from them solves problem unless you have <than 8 devices and may cause even bigger window if some of devices has longer name. We need a more permanent solution to our problem :p

**Comment by redjamesg** [comment]
The easy way would be to make the part og the Window listing devices as a scrollable section, giving it the possibility of expanding indefinitely, like the file selection part in any "open" request on your favorite editor.

**Comment by kozec** [comment]
Just as report, I'm trying to do put everything into GTK.ScrollWindow, but can't find way to prevent it from shrinking to smallest-possible size. So, working about it :)
