### ISSUE TITLE
Fails to start on windows if python is already installed

### ISSUE THREAD

**Issue by rhd** [syncthing/syncthing-gtk#106]
At least I think that's the cause.

![2015-03-11 15_06_42-cx_freeze_ python error in main script](https://cloud.githubusercontent.com/assets/3422847/6608411/fa272ffc-c803-11e4-8d06-2db6677af22b.png)

**Comment by kozec** [comment]
What kind of python (version, arch) have you got installed? And do you have pygi package installed?
