### ISSUE TITLE
GUI is shown even though "Minimize to tray on start" is ticked.

### ISSUE THREAD

**Issue by pulb** [syncthing/syncthing-gtk#109]
Since the latest release the syncthing-gtk GUI pops up after system boot. "Minimize to tray on start" is checked in the UI settings dialog. I'm on GNOME 3.14.

**Comment by kozec** [comment]
This usually happens if entry in autostart applications get somehow duplicated. Can you check if that is case? Run `gnome-session-properties` and look for "Syncthing-GTK".
If you can see it twice, please, check your `.config/autostart` directory and try to find how is second entry named - one should be `Syncthing-GTK.desktop` and this is not first case when something created other one. I would like to find what is it.

**Comment by pulb** [comment]
There's only one desktop entry in GNOME Tweak Tool (there is no gnome-session-properties in GNOME 3) and in .config/autostart. The filename is Syncthing-GTK.desktop.

**Comment by pulb** [comment]
Somehow the problem is gone. I unchecked and re-checked  "Minimize to tray on start" in the UI settings dialog, maybe that fixed it.

**Comment by pulb** [comment]
Unfortunately the problem is back again :-\ I did not change anything.

**Comment by kozec** [comment]
Just to be sure, can you run and paste output of `grep -Ru Exec ~/.config/autostart` ?

**Comment by pulb** [comment]
~/.config/autostart/Syncthing-GTK.desktop:Exec=/usr/bin/syncthing-gtk
~/.config/autostart/pidgin.desktop:Exec=pidgin 
~/.config/autostart/mailnag.desktop:Exec=/usr/bin/mailnag --quiet

**Comment by kozec** [comment]
Ok, and what happens when you shut down ST-GTK and try to run it from terminal? Does it prints
`Syncthing-GTK started and running in notification area`
and stays hidden?

**Comment by pulb** [comment]
Yes it prints that message and stays hidden when running from a terminal. The fact that it only appears at startup (randomly) makes me feel like this is some some sort of race condition. Maybe sometimes syncthing-gtk is started before the message tray component of gnome-shell is available and sometimes after.

**Comment by kozec** [comment]
Yes, that's possible, although I don't see reason for gnome to start anything before panel is fully loaded.
I added exception for this case, please, let me know it it helps.

**Comment by pulb** [comment]
Performed a few reboots. So far so good :-) I'll report back again in a few days.

**Comment by pulb** [comment]
Seems you fixed it :-) I'll reopen the issue in case it happens again. Thanks and keep up the great work!
