### ISSUE TITLE
appindicator gnome3

### ISSUE THREAD

**Issue by cedricbrx** [syncthing/syncthing-gtk#110]
Hi,

I justed wanted to know if there is a reason why gnome3 is not using appindicator for the message tray icon. As i can see in the code, unity is using appindictor.

thanks

**Comment by kozec** [comment]
Is there any reason why gnome *should* be using appindicator?

**Comment by cedricbrx** [comment]
In debian jessie, appindicator is more eye-candy than the indicator syncthing is using at the moment. 
The second reason is why use 2 different codes for doing the same thing. Is there a technical reason? I never said that syncthing should do something different it was only a question
![appindicator](https://cloud.githubusercontent.com/assets/11331696/6676898/a39c08d4-cc2b-11e4-9636-88d2866b8dd8.png)
![without_appindicator](https://cloud.githubusercontent.com/assets/11331696/6676900/a72cb57a-cc2b-11e4-950f-0967d28e6f57.png)

**Comment by kozec** [comment]
AppIndicator can't handle left clicking, so it's used only as fallback when reduced functionality is better than no functionality. And while I'd rather have single code for entire notification icon thing, that would not work under Ubuntu :angry:

**Comment by cedricbrx** [comment]
ok, understood, thanks for this anwser and thanks for this great work

**Comment by jhasse** [comment]
> AppIndicator can't handle left clicking

Catching a double-click is possible though and could be used to open the main window :)
