### ISSUE TITLE
Add new device fails with syncthing 0.10.26+

### ISSUE THREAD

**Issue by dcarosone** [syncthing/syncthing-gtk#111]
Trying to add a device with syncthing-gtk fails
![screenshot from 2015-03-16 13 44 30](https://cloud.githubusercontent.com/assets/11495017/6679247/5107c2d4-cc99-11e4-8e9e-7fbca0867d41.png)
![screenshot from 2015-03-16 13 44 40](https://cloud.githubusercontent.com/assets/11495017/6679250/5943dbcc-cc99-11e4-9336-191cb82b4ab4.png)

This seems to be an issue with a change of format of the compression value, the android UI had a similar issue: syncthing/syncthing-android#239

Originally raised as syncthing/syncthing#1467 because of confusion with what turned out to be a separate issue trying to do the same in the web UI.

**Comment by kozec** [comment]
That's probably caused by syncthing/syncthing#1374. TWTF is using 'metadata' instead of FileNotFound.

Btw, while I can understand that API and configuration is far from set in stone, it would be nice to write something like "this changes format of XY" in such commit :)
