### ISSUE TITLE
Error 183 and IOError [Errno 2] while using wizard 

### ISSUE THREAD

**Issue by trilomix** [syncthing/syncthing-gtk#112]
Error Log:
syncthing-gtk: Configuration directory: 'C:\Users\Admin\AppData\Local\syncthing'
syncthing-gtk: Failed to create configuration directory
syncthing-gtk: [Error 183] Impossible de cr?er un fichier d?j? existant: u'C:\\Users\\Admin\\AppData\\Local\\syncthing'
syncthing-gtk: Syncthing configuration directory: C:\Users\Admin\AppData\Local\syncthing
syncthing-gtk: choosen port 8080
syncthing-gtk: Traceback (most recent call last):
  File "c:\syncthing-gui\syncthing_gtk\wizard.py", line 647, in save_settings
IOError: [Errno 2] No such file or directory: u'C:\\Users\\Admin\\AppData\\Local\\syncthing\\config.xml'

**Comment by kozec** [comment]
Can you check if C:\Users\Admin\AppData\Local\syncthing is there and you have write access to it?

**Comment by balazsgrill** [comment]
I've experienced tha same issue on Windows 8.1. The directory is there, syncthing and the RSA keys are present, only the config.xml is missing.
After I manually created a config.xml it started working.

**Comment by kozec** [comment]
Yes, it's looks like Syncthing v0.10.26 will not generate config.xml for whatever reason.
I set v0.10.25 as latest supported version and going to ask what happened.

**Comment by AudriusButkevicius** [comment]
Is there an error coming from syncthing though?

**Comment by kozec** [comment]
@AudriusButkevicius Yes, if you run any ST version but v0.10.26 with -generate parameter, it will create keys *and* config.xml.

But it looks like v0.10.27 doesn't have this problem, so simply skipping over v0.10.26 should be enough.

**Comment by kozec** [comment]
Fixed in <a href=https://github.com/syncthing/syncthing-gtk/releases/tag/v0.6.3>v0.6.3</a>
