### ISSUE TITLE
Installation failure, failed to load configuration

### ISSUE THREAD

**Issue by dr-spangle** [syncthing/syncthing-gtk#113]
Error log:
syncthing-gtk: Configuration directory: 'C:\Users\dr-spangle\AppData\Local\syncthing'
syncthing-gtk: Failed to create configuration directory
syncthing-gtk: [Error 183] Cannot create a file when that file already exists: u'C:\\Users\\dr-spangle\\AppData\\Local\\syncthing'
syncthing-gtk: Syncthing configuration directory: C:\Users\dr-spangle\AppData\Local\syncthing
syncthing-gtk: choosen port 8080
syncthing-gtk: Traceback (most recent call last):
  File "c:\syncthing-gui\syncthing_gtk\wizard.py", line 647, in save_settings
IOError: [Errno 2] No such file or directory: u'C:\\Users\\dr-spangle\\AppData\\Local\\syncthing\\config.xml'

C:\Users\dr-spangle\AppData\Local\syncthing exists, it contains 3 files:
cert.pem, key.pem, syncthing.exe

Also, "chosen port 8080" is misspelt.

**Comment by kozec** [comment]
Sooo... config.xml is missing. This is actually same as #112, but I just now realized where real problem is...
*gone testing*

**Comment by dr-spangle** [comment]
Oops, sorry, it is the same issue. I should have read through other issues, but I was rushing

**Comment by kozec** [comment]
Np, that happens.
