### ISSUE TITLE
Failed to save configuration.Certificat TLS inacceptable

### ISSUE THREAD

**Issue by meradoou** [syncthing/syncthing-gtk#115]
Hello,
I get this message when I add a new device with Syncthing-GTK:

```
Certificat TLS inacceptable
```

When I use http://localhost:8080, it works.

I use Syncthing  v0.10.27 and Syncthing-GTK  0.6.3-1 on archlinux x64.

Thank you

**Comment by kozec** [comment]
So, message appears if you are using Syncthing with HTTPS?

**Comment by kozec** [comment]
By the way, there is pretty good chance that's just glib refusing self-signed certificate used by Syncthing's https...

**Comment by meradoou** [comment]
Yes

**Comment by TiZ-EX1** [comment]
I'm getting the same error when I try to make any sort of configuration change on a host running with HTTPS. I didn't used to get this error.

**Comment by kozec** [comment]
@TiZ-EX1 On Archlinux as well?

**Comment by TiZ-EX1** [comment]
Xubuntu 14.04 64-bit.

**Comment by kozec** [comment]
Ok. I'm idiot :(

**Comment by TiZ-EX1** [comment]
Don't sweat it, dude. Thanks for the fix.
