### ISSUE TITLE
browse on doble click

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#117]
Please, is it possible to open the folders on double click? It's a tiny detail, but I think is a widely used standard.

Thanks!

**Comment by kozec** [comment]
Wouldn't that clash with rolling/unrolling? And you can do right click -> browse...

**Comment by robsonsobral** [comment]
Yeah, I know about the right click menu.

I was thinking to double click the white area below the titles. The context menu on right click is good for secondary actions, but the primary action you can on a Syncthing folder is... Well, to open that folder!

**Comment by kozec** [comment]
Ok, I'm still not sure if this is actually useful, but why not :)
