### ISSUE TITLE
request: config.xml paths

### ISSUE THREAD

**Issue by nem2k** [syncthing/syncthing-gtk#118]
Is it possible to add an option to automatically edit the syncthing config.xml when adding folders (to enable long file paths in windows)?

ref: https://github.com/syncthing/syncthing/wiki/Windows-Troubleshooting-Guide

**Comment by kozec** [comment]
In theory, yes. Is there any side-effect or reason why Syncthing (daemon) doesn't do that automaticaly?

**Comment by Zillode** [comment]
https://github.com/syncthing/syncthing/issues/1295
Undecided at the moment, I think we need to test this properly first.

**Comment by nem2k** [comment]
yeah I realise it hasn't been fully tested yet, which is why I suggested it as an option as opposed to the default state.

For users on windows with deep nested folder structures we have to make those changes to config.xml anyway, there doesn't seem to be any way around it otherwise it will just throw errors. So given a % of the user base will be making the changes manually it might make sense to simplify things a bit for them/us with a checkbox option or something to ease the process

**Comment by kozec** [comment]
Ok, I probably don't get something important here, but you basically want ST-GTK to offer option to convert `C:/some/path/to/something/` value in Path field to `\\?\C:\some\path\to\something` when adding new folder.

That's probably one-liner, but I'm not sure how to make it optional. Some messagebox or checkbox popping up when path is longer than some arbitrary value? Anything I can think of would need more user interaction than clicking to Path field and writing `\\?\` manually.

**Comment by nem2k** [comment]
I'm mostly imagining how difficult it would be for a new user to hit the path length issue, not know what the problem is and not knowing how to solve it, then spend a bunch of time googling an answer before implementing it. Plus its not always obvious what sequence of characters \\?\ to enter without searching for it somewhere (or maybe my memory is just bad)

I guess you could just have a checkbox next to the browse button, which when checked will prepend \\?\ to the beginning of whatever path is in the textfield? default it to unchecked, but give users an easy way to fix the issue by clicking the box. makes the whole thing simpler for new windows users

I dont imagine you would even need to check the path length (I guess the length will actually change depending on the length of individual filenames), just prepend it to all windows paths if the checkbox is ticked

**Comment by Zillode** [comment]
Will be fixed in upstream, see https://github.com/syncthing/syncthing/pull/1590

**Comment by kozec** [comment]
Great, that sounds much more reasonable.
