### ISSUE TITLE
Hardcoded icon path in launcher

### ISSUE THREAD

**Issue by palob** [syncthing/syncthing-gtk#119]
Hi,

currently the icon path specified in the created launcher file is set to: 
*Icon=/usr/share/syncthing-gtk/icons/st-logo-128.png*

(see https://github.com/syncthing/syncthing-gtk/blob/da715b52d71cb50359bdf3abc7e58154786b8b3d/syncthing-gtk.desktop)

This prevents icon theming without editing the launcher file.

I'd like to ask you to change the icon location as well as the icon path line in the launcher according to the freedesktop.org standards.

Please find more info here:
http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
https://github.com/Foggalong/hardcode-fixer/wiki/What,-Why-&-How

---------------------------------
According to the above resources standard icon locations are:

*/usr/share/icons/hicolor/[size]/apps/[icon name]*
*~/.local/share/icons/hicolor/[size]/apps/[icon name]*
*/usr/share/pixmaps/[icon name]*

The standard icon line in the .desktop launcher is:
*Icon=[icon name]*      (without full path, without file extension)

for instance
**Icon=syncthing-gtk**  
(for an icon *syncthing-gtk.svg* or *syncthing-gtk.png* stored in standard location)

Could you please move the icon to one of those and adjust the icon path in the .desktop file accordingly?

**Comment by kozec** [comment]
Sounds reasonable. I'll try to not forget about that in next release.

**Comment by palob** [comment]
Thanks a lot and keep up the good work!
