### ISSUE TITLE
Unshared status for folders

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#121]
Hi, @kozec!

Currently, unshared folders shows "offline" as their status, but on web interface they show "unshared".

Thanks!

**Comment by kozec** [comment]
Yeah, offline is shown even if folder is shared, but all other devices are down. But I can add 'unshared' as well.

**Comment by robsonsobral** [comment]
I'm trying to help you to keep some consistency with web UI, but... I think ST-GTK will become the default interface of ST for most users soon.

**Comment by kozec** [comment]
Well, consistency of this part is already broken, as WebUI doesn't have 'offline' status.

**Comment by robsonsobral** [comment]
Good point! :-p
