### ISSUE TITLE
Button's not accessable on smal display's (e.g. Netbook)

### ISSUE THREAD

**Issue by vohe** [syncthing/syncthing-gtk#122]
I test this fine litte peace of code.
Useful, i guess.

On my thinkpad everything works fine.
But my little Netbook (and eeePC) doesen't shows all the GUI-Buttons. And there's space enought to make them reachable.

I send a screenshot al
![syncthing](https://cloud.githubusercontent.com/assets/7021635/6883233/6a1815a8-d5a4-11e4-82e1-73d6734690a8.png)
ong with this.

**Comment by kozec** [comment]
That's most likely same problem as #105, but seeing how you are on Linux, you should be able to hold alt and click & move window so you can see bottom part.

**Comment by vohe** [comment]
That's quite right, move the windows is possible. But as you see, there is space enought to resize the dialog to fit into 600pixel hight. But it's not possible to resize to that format.

**Comment by kozec** [comment]
-> #105
