### ISSUE TITLE
cross platform folder watcher

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#123]
Hi!

I found this and it maybe can be useful to you: [watchdog](https://github.com/gorakhargosh/watchdog).

There are some reports that it lock the files, but they are old.

Please, forgive me if I'm overstepping.

Thanks for your patience and hard work.

**Comment by kozec** [comment]
Np, but <a href="https://github.com/gorakhargosh/watchdog/blob/master/src/watchdog/observers/__init__.py">it ends using inotify at end, so it would just add wrapper over what ST-GTK is already using...

**Comment by robsonsobral** [comment]
Oh, I saw that. I know about [syncthing-inotify](https://github.com/syncthing/syncthing-inotify).

I was thinking that to replace it for a solution which works natively on Windows and Mac OS too could be more useful.

**Comment by kozec** [comment]
Ah, yeah, that's true. I'll check if it can work recursively.

**Comment by robsonsobral** [comment]
Please, just check if it still locks files.

**Comment by kozec** [comment]
I'm not quite sure how to check that... Is there any report of those cases?

**Comment by robsonsobral** [comment]
I saw one [comment](https://stackoverflow.com/questions/182197/how-do-i-watch-a-file-for-changes-using-python#comment-35386658), but it's from 2011.

---

I just found some [caveats](http://pythonhosted.org/watchdog/installation.html).

---

Maybe [this](http://timgolden.me.uk/python/win32_how_do_i/watch_directory_for_changes.html) can help on Windows.

---

I'm sorry. The only python I ever coded was to fix a Sublime Text plugin.

**Comment by kozec** [comment]
Fixed by b81374d1820f9f909e1997cae896eb723afb8456
