### ISSUE TITLE
Never does automatic syncthing update

### ISSUE THREAD

**Issue by TiZ-EX1** [syncthing/syncthing-gtk#124]
I'm running Syncthing-GTK in the terminal to try and diagnose an issue more related to syncthing itself at the moment, but I had noticed for some time that it often fails to do automatic updates. I see in the terminal:

    I App           updatecheck: too soon
    I App           updatecheck: too soon
    I App           updatecheck: too soon
    I App           updatecheck: too soon
    I App           updatecheck: too soon

This is on a computer that already has upgraded to syncthing 0.10.30 due to running it solo earlier in the day, as well as another computer that is currently stuck on 0.10.29 because it won't go do the update.

Is there any other information I can provide to help you debug this?

**Comment by kozec** [comment]
This time it's intentional, there is issue about this version crashing on Windows, so I thought it may be better to hold autoupdate util it's resolved.

**Comment by TiZ-EX1** [comment]
Oh, okay. Thank you for the info.
