### ISSUE TITLE
QR Code not showing on Ubuntu 14.10

### ISSUE THREAD

**Issue by jamcole** [syncthing/syncthing-gtk#128]
I have Syncthing GTK installed on two different Ubuntu computers, and the QR code doesn't show on the "Show ID" screen (like I assume it should).

I'm using version 0.6.4-1~webupd8~utopic0 (issue was present in 0.6.3-1~webupd8~utopic0 and earlier too) from the Web Upd8 PPA repository: https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8/

I'm probably missing the library  that it needs.  If I can find out which one, I can contact the repo manager and get it added it as an suggested dependency.

![selection_001](https://cloud.githubusercontent.com/assets/2210673/7027652/83a10418-dd05-11e4-85ac-33f5f94df253.png)

**Comment by kozec** [comment]
Any relevant looking output in console?

**Comment by jamcole** [comment]
Nope, nothing of interest, no output change when I click "Show ID" from the menu either:

<pre>
intangible@indignant:~$ syncthing-gtk --verbose --debug
D UIBuilder     Enabled: traditional_header
D UIBuilder     Enabled: icons_in_menu
D UIBuilder     Loading glade file /usr/share/syncthing-gtk/app.glade
D UIBuilder     Enabled conditions: set([u'icons_in_menu', u'traditional_header'])
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Allowed node !is_gnome | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: old_gtk
D UIBuilder     Removed 'child' by attribute: header_bar
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Allowed node traditional_header
D UIBuilder     Allowed node traditional_header | icons_in_menu
W StatusIcon    StatusIcon: Using backend StatusIconAppIndicator (fallback)
V Notifications Error notifications enabled
V Notifications File update notifications enabled

Syncthing-GTK started and running in notification area
V Daemon        Set refresh interval to 5
D InfoBox       V2ZX427 (Unused) state changed to Disconnected
D InfoBox       indignant (Unused) state changed to Disconnected
D InfoBox       jamcole-laptop (Unused) state changed to Disconnected
D InfoBox       mercury (Unused) state changed to Disconnected
D InfoBox       indignant (Unused) state changed to 
W App           Skiping updatecheck: Daemon not launched by me
</pre>

**Comment by kozec** [comment]
Trying to reproduce it, but it works in both Ubuntu 14.10 and 14.04 for me.
What syncthing version are you using? Do you have HTTPs enabled by any chance? Can you open URL like
```
https://127.0.0.1:8080/qr/?text=AX34JMA-71538P4-3KLYOLR-YMO7QTU-OPP4RTQ-CWOYJEA-KROZNBD-YD25XAL
```
in your browser (assuming you are using port 8080 for webui)?

**Comment by jamcole** [comment]
Aha!  Your message gave me the answer, apparently Syncthing-GTK does not show the QR code if you have a username and password set for the Syncthing web GUI.

I'm running the Syncthing web GUI over HTTP (not S) on port 22080 (to avoid conflicts on 8080), but the port change doesn't seem to be a problem. 
I'm setting a username and password to prevent CSRF attacks as well as make sure other users on the machine cannot log into the GUI; That seems to be the problem.
Syncthing GTK probably should dump out an error on the console if the QR code doesn't load in this manner.

Thanks for taking a look.  Is this a code change you will make, or will I need to dig into it?

**Comment by kozec** [comment]
Ok, this makes sense. Unlike everything else, QR download is handled by glib, so it doesn't knows about passwords. Now just how to change that...

**Comment by niemalsnever** [comment]
Hello,
I'm still having this issue with Syncthing-GTK 0.8, Syncthing 0.12.3 running Linux Mint 17.2. I'm using HTTPS, a custom port, user and password authentication and my WebUI listens on 0.0.0.0 .

Excerpt from Syncthing-GTK debug log:

```
E IDDialog      HTTP Client Error: Unauthorized
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/iddialog.py", line 77, in cb_syncthing_qr
    ok, contents, etag = io.load_contents_finish(results)
GError: HTTP Client Error: Unauthorized
```

**Comment by kozec** [comment]
@niemalsnever Is anything else outputted before that? Especially something like
``` W IDDialog      Failed to load image using glib. Retrying with urllib2. ```
?

**Comment by niemalsnever** [comment]
Only this:
```W IDDialog      SSL is not available, cannot verify server certificate.

(syncthing-gtk:4943): Gtk-WARNING **: Invalid icon size 24

E IDDialog      HTTP Client Error: Unauthorized
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/iddialog.py", line 77, in cb_syncthing_qr
    ok, contents, etag = io.load_contents_finish(results)
GError: HTTP Client Error: Unauthorized
```
