### ISSUE TITLE
Program startup error after upgrade from 0.6.3 to 0.6.4 on Win8.1 x64

### ISSUE THREAD

**Issue by Spellshaper** [syncthing/syncthing-gtk#129]
Hi,

after upgrading Syncthing-GTK from 0.6.3 to 0.6.4 on Win8.1 x64 with the installer, I was presented with the following error:
![capture](https://cloud.githubusercontent.com/assets/10774151/7046355/ffa5bfe8-ddfc-11e4-89e8-978a1dbd3b11.PNG)
Attempting to run syncthing-gtk.exe manually resulted in the same error being displayed again.

Running the 0.6.4 installer again fixed the issue. Maybe the installer did not properly shut down the 0.6.3 instance?

If more information is required, I'd be happy to be of help.

**Comment by kozec** [comment]
> Maybe the installer did not properly shut down the 0.6.3 instance?

That's most likely reason. Or Windows left some files locked while after old instance exited - both cases are pretty hard to actually prevent :(

Installer is supposed to download & install this missing file, but I can see how that can fail if anything is still "used". In worst case, just use full installer.
