### ISSUE TITLE
Missing an icon from main window on Xubuntu 14.10

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing-gtk#131]
I have just installed `Syncthing-GTK` from `ppa:nilarimogard/webupd8`, and there's one icon missing from the main window:

![syncthing gtk_001](https://cloud.githubusercontent.com/assets/10074769/7069528/ac3857b8-deaf-11e4-9c5c-318cec7f396b.jpg)

Issue #68 seem to discuss this, although on Ubuntu 14.04, whereas I'm running Xubuntu **14.10**. From the missing icons reported on #68, the only one missing from my install is the one I've just shown.

`Syncthing-GTK` version is **0.6.4-1~webupd8~utopic0**

**Comment by kozec** [comment]
You are using GTK icon theme that doesn't provide `open-menu-symbolic` icon. Is that Xubuntu default?

**Comment by marcelpaulo** [comment]
You're right, @kozec, I can't find any `open-menu-symbolic` icon under `/usr/share/icons`. These are the icon themes I have installed:

*gnome-icon-theme
gnome-icon-theme-full
gnome-icon-theme-symbolic
hicolor-icon-theme
humanity-icon-theme
oxygen-icon-theme
xubuntu-icon-theme*

I searched Ubuntu utopic packages for files with keyword `open-menu-symbolic`, and none were found ([here](http://packages.ubuntu.com/search?searchon=contents&keywords=open-menu-symbolic&mode=filename&suite=utopic&arch=any) are the results).

Which icon theme should I install to have `open-menu-symbolic` ?

**Comment by jaystrictor** [comment]
See https://wiki.gnome.org/Initiatives/GnomeGoals/GearIcons
Maybe Syncthing-GTK should fallback to `emblem-system-symbolic` if `open-menu-symbolic` is not available.
@marcelpaulo Do you have `emblem-system-symbolic`?

**Comment by marcelpaulo** [comment]
Yes, @jaystrictor, I have `emblem-system-symbolic`, it's installed from these icon themes:

*xubuntu-icon-theme
gnome-icon-theme-symbolic*

**Comment by jaystrictor** [comment]
Ahh just checked by digging into the code.
Syncthing-GTK already falls back to `emblem-system-symbolic` for GTK+ version < 3.12

**Comment by marcelpaulo** [comment]
I have GTK+ **3.12.2** installed:

```
paulo@monk:~/tmp$ apt-cache policy libgtk-3-0
libgtk-3-0:
  Installed: 3.12.2-0ubuntu15.2
  Candidate: 3.12.2-0ubuntu15.2
  Version table:
 *** 3.12.2-0ubuntu15.2 0
        500 http://archive.ubuntu.com/ubuntu/ utopic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.12.2-0ubuntu15 0
        500 http://archive.ubuntu.com/ubuntu/ utopic/main amd64 Packages
```

so I'd imagine that's why syncthing-GTK is not falling back to `emblem-system-symbolic`.

**Comment by kozec** [comment]
Problem with falling back (when GTK version is recent enough) is detecting when icon fails to load. That weird looking default fallback icon is, by all means I tested so far, presented as if `open-menu-symbolic` were loaded and displayed there.

**Comment by kozec** [comment]
Ok, this ^^ checks not if icon is loaded, but if it's present in theme. It may fail, especially if GTK theme changes while ST-GTK is running, but worst thing that can happen is that rectangular fallback...

**Comment by marcelpaulo** [comment]
Hey, @kozec, thank you so much for your speedy attention and action !

**Comment by kozec** [comment]
@marcelpaulo Np. Can I consider this fixed?

**Comment by marcelpaulo** [comment]
By all means, yes! Let's close the issue.

**Comment by marcelpaulo** [comment]
Just confirming, latest release **0.6.5** did fix this:
![syncthing gtk_001](https://cloud.githubusercontent.com/assets/10074769/7157556/3a57ff9e-e347-11e4-848f-25c5970da225.jpg)

Once again, thanks @kozec !
