### ISSUE TITLE
Error 'g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)' starting on Xubuntu 14.10

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing-gtk#132]
When I start `syncthing-GTK` from the bash prompt, I see these errors:

```
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 391, in _rest_connected
    con = sc.connect_to_service_finish(results)
```

Everything is working fine, so this connection failure doesn't seem to have any impact, but I thought I should report it.

After starting `syncthing-GTK`, these are the processes listening on **127.0.0.1**:

```
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      10079/syncthing 
tcp        0      0 127.0.0.1:5941          0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:8888          0.0.0.0:*               LISTEN      2396/perl
```

I'm running `syncthing-GTK` version **0.6.4-1~webupd8~utopic0** over Xubuntu **14.10**

**Comment by kozec** [comment]
Ah, yeah that's supposed to happen. Connection is retried until daemon becomes alive, what's typically after two or three retires.

**Comment by marcelpaulo** [comment]
Apologies then, @kozec, for unnecessarily opening this issue.

**Comment by kozec** [comment]
Np, better to have some invalid than bugs nobody knows about :)

**Comment by pik** [comment]
Maybe catch it and display as `info retrying (1..)` etc? Just so it's more clear to users what to expect?

**Comment by MartinX3** [comment]
"Maybe catch it and display as info retrying (1..) etc? Just so it's more clear to users what to expect?"

Yeahr, please.
I try to find the source of my recent system crash and thought, this is a real error.
