### ISSUE TITLE
Editing 2+ shared folders without restarting freezes interface (Xubuntu 14.10)

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing-gtk#134]
I needed to batch edit all my shared folders (to change the scanning interval), so I went about editing them without restarting the daemon, which I would do at the end. After I edited and saved the 2nd shared folder, the interface froze completely, didn't respond to clicks anywhere, and I had to kill the syncthing-gtk process. I resumed editing the shared folder, and the same error happened again: after saving the 2nd shared folder, the interface became unresponsive again. So it seems to be reproducible easily.

Using `syncthing-gtk` version **0.6.4-1~webupd8~utopic0** over Xubuntu **14.10**

**Comment by kozec** [comment]
Maybe it's somehow xubuntu related, asi I'm not able to reproduce it here... Can you, please, try to run syncthing-gtk from console, with debuging enabled (that's `syncthing-gtk -d`) and copy-paste output when freezing occurs?

**Comment by marcelpaulo** [comment]
I'm puzzled: I started syncthing-gtk from the console as you instructed me:

```bash
syncthing-gtk -d &> >(tee syncthing-gtk.log)
```

and it's not freezing anymore. Started syncthing-gtk from the Xubuntu whisker menu, and it didn't freeze either. I'm really puzzled.

Anyway, thanks for your help and please forgive me for another unnecessary issue opened.

**Comment by marcelpaulo** [comment]
This is puzzling: syncthing-gtk is freezing again if I edit 2 folders without an intervening restart.

I ran it from the console, and this is all that was output:
```
paulo@monk:~$ syncthing-gtk

(syncthing-gtk:17558): Gtk-WARNING **: No object called: edit-menu-button-image

(syncthing-gtk:17558): Gtk-WARNING **: No object called: edit-menu-button-image
I StatusIcon    Using backend StatusIconGTK3 (primary)

Syncthing-GTK started and running in notification area
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 391, in _rest_connected
    con = sc.connect_to_service_finish(results)
Error: g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
I App           updatecheck: too soon
I EditorDialog  Configuration (probably) saved
I EditorDialog  Configuration (probably) saved
```

There's activity, output, I can see the folders being scanned, but the interface doesn't take input anywhere.

Any tips on how to debug this further ?

Now I'm running syncthing-gtk **0.6.5** from *ppa:nilarimogard/webupd8*, syncthing daemon *0.10.30*, still on Xubuntu 14.10

**Comment by marcelpaulo** [comment]
I've just uninstalled 0.10 and installed 0.11, so I won't be able to debug this further. I'm closing it for now and will reopen in case 0.11 still behaves the same way.
