### ISSUE TITLE
Make clear that deleting a folder only removes it from ST

### ISSUE THREAD

**Issue by LeoVerto** [syncthing/syncthing-gtk#135]
This is only a minor enhancement but I think making it clear that the delete operation does not remove the folder from disk would get rid of some potential confusion.

**Comment by kozec** [comment]
True, asking about deletion may be little confusing. How about replacing confirmation question with this?

![](http://i.imgur.com/RxawQmd.png)

**Comment by LeoVerto** [comment]
Sounds a lot better, maybe even change it to:
> Do you really want to *permanently* stop synchronizing directory 'test?
