### ISSUE TITLE
Init Configuration not supporting non-latin path

### ISSUE THREAD

**Issue by michaelforge** [syncthing/syncthing-gtk#136]
Hey there,

Can't go through "Download Daemon" step if username folder using non-latin symbols:

![2015-04-13_16-25-22](https://cloud.githubusercontent.com/assets/904839/7116395/f6d732d8-e1f9-11e4-9470-3f7e1463538b.png)

It's unrelated to Syncthing GTK and can't be fixed?

Version: 0.6.4
OS: Windows 7 64bit

**Comment by AudriusButkevicius** [comment]
Duplicate https://github.com/syncthing/syncthing-gtk/issues/97

**Comment by kozec** [comment]
Yes, this is how Windows treats non-ascii usernames. More like feature than something possible to solve, AFAIK :-(

Just out of curiosity, what's hidden behind those question marks?

**Comment by michaelforge** [comment]
@kozec 
"Акробаты" (cyrillic, win1251)

Anyway, thanks for reply!
And thanks for working on this project. Worthy alternative for other sync apps.
