### ISSUE TITLE
syncthing-gtk won’t connect since moving to v0.11.0-beta6

### ISSUE THREAD

**Issue by magian** [syncthing/syncthing-gtk#137]
I am getting the following error when syncthing-gtk starts:

Connection to daemon failed. Check your configuration and try again.

Error message: Invalid HTTP response

Server response:
'HTTP/1.0 404 Not Found
Cache-Control: no-cache
Content-Type: text/plain; charset=utf-8
X-Syncthing-Version: v0.11.0-beta6
Date: Tue, 14 Apr 2015 04:02:02 GMT
Content-Length: 19

404 page not found
'

**Comment by kozec** [comment]
ST-GTK doesn't supports v0.11 yet, as that would break support for v0.10. If you feel like betatester, you can use <a href="https://github.com/syncthing/syncthing-gtk/tree/0.11">0.11</a> branch :)

**Comment by kozec** [comment]
Fixed with new release :)
