### ISSUE TITLE
[0.11] sort folder list alphabetically

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing-gtk#138]
Would it be feasible to sort the folder list alphabetically, like the Web GUI does ?

Running ST-GTK **0.6.9.2**, ST **0.11.0-rc1**

**Comment by kozec** [comment]
Sounds reasonable.

**Comment by marcelpaulo** [comment]
Wow, that was speed-lightning fast. Thanks !

**Comment by kozec** [comment]
Yes. You don't even need installing, you can clone & run `./syncthing-gtk.py` directly.

**Comment by marcelpaulo** [comment]
Perfect, thank you so much, @kozec. It took me some time to discover how to clone a branch other than master (as you can see, I'm also green with `git`...), but got there (grabbed a copy of O'Reilly's *Version Control with Git* and will dedicate some time to get familiar with it).

And yeah, the folder list is being listed alphabetically !
