### ISSUE TITLE
Tray icon is too large and clipped. 

### ISSUE THREAD

**Issue by ManuelSchneid3r** [syncthing/syncthing-gtk#139]
![image](https://cloud.githubusercontent.com/assets/3252315/7229605/f78aec76-e765-11e4-98d8-b22fb3cfb373.png)

**Comment by kozec** [comment]
Distro, version and desktop environment?

**Comment by ManuelSchneid3r** [comment]
Oh sorry. For sure:
Archlinux 3.19.3
Cinnamon DE cinnamon 2.4.8
syncthing-gtk 0.6.5

**Comment by marcelpaulo** [comment]
Same thing here, with a different environment:

- Xubuntu 14.10
- Xfce 4.10
- syncthing-gtk 0.6.9.2

**Comment by ManuelSchneid3r** [comment]
Still an issue in 0.7.0.1 (Daemon v0.11.1)
