### ISSUE TITLE
[0.7.0.1] ST-GTK doesn't stop running on Quit nor closing main GUI window

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing-gtk#142]
ST-GTK 0.7.0.1 doesn't quit, even after:

1. Pressing `Quit` on the main settings
2. Pressing `Quit` on the window warning that the daemon is not running
![1_002](https://cloud.githubusercontent.com/assets/10074769/7334920/9f58dcb8-eb78-11e4-856f-ad91b0aea8e9.jpg)
3. Closing the main GUI window

Even after the GUI is gone, it remains running:
```
paulo@monk:~$ ps -ef | grep syncthing
paulo    29429  1991  2 18:17 ?        00:00:02 /usr/bin/python /usr/local/bin/syncthing-gtk
paulo    29570 24805  0 18:19 pts/5    00:00:00 grep syncthing
```

It only stops if the process is killed.

**Comment by marcelpaulo** [comment]
Thought this might help to debug the issue: ran `syncthing-gtk -v -d &> >(tee no-quit.log)`, then tried to stop it:

1. Settings } Quit
2. Quit on the popup message about syncthing being down
3. Closed the window
4. Killed the process

Here's the [log](http://bpaste.net/show/ef72a8791afa)

**Comment by kozec** [comment]
I'll try to replicate a problem. What distro and desktop environment are you using?

**Comment by marcelpaulo** [comment]
My sincere apologies, I usually don*t forget that. 

I'm running Xubuntu 15.04 with Xfce 4.12

**Comment by acidicX** [comment]
I can confirm that on Arch x64 with Cinnamon.

**Comment by kozec** [comment]
Ok, this is caused by some crazy change in Glib, as it works on my little outdated Arch and on *buntu 14.10, but application's requests to exit are ignored on 15.04 and on Arch after upgrade. I'm trying to find what exactly and with which Glib version broke now...

**Comment by kozec** [comment]
Ok, now it  works on Xubuntu, I just need to check what got broken by change.

**Comment by kozec** [comment]
(tested)

**Comment by acidicX** [comment]
Is the fix already released? It's still happening for me.

**Comment by kozec** [comment]
Not yet - there weren't much to release. But I'll try to make new release tomorrow.

**Comment by kozec** [comment]
Here you are - https://github.com/syncthing/syncthing-gtk/releases/tag/v0.7.1
