### ISSUE TITLE
Border around menu

### ISSUE THREAD

**Issue by chucic** [syncthing/syncthing-gtk#143]
Menu under ST icon or settings icon has no border and since by default first folder and "this" device are opened, white background of those causes loose transition with menu. It is confusing and eye hurting (for me at least). Could there be a border around those two menus (is this even a word?)?

**Comment by kozec** [comment]
I'm not sure if I understand, but knowing your distro, active gtk theme and probably screenshot may help.

**Comment by chucic** [comment]
Yeah, sorry, Windows 7 x64
![syncthing_gtk_left_menu](https://cloud.githubusercontent.com/assets/10828858/7364070/83a8c7c4-ed82-11e4-9f2e-ab8dd2117439.jpg)
![syncthing_gtk_right_menu](https://cloud.githubusercontent.com/assets/10828858/7364071/83b134cc-ed82-11e4-80d2-ff5f0ca05ffc.jpg)

**Comment by kozec** [comment]
This is actually less bug and more like GTK's feature... But it can be overridden. Does this looks separated enough?

blob:http%3A//pasteboard.co/5a4d6bf0-5453-4fe4-aa8c-ec123fa4d37a

**Comment by chucic** [comment]
Much better, thanks :wink:
