### ISSUE TITLE
Upgrade to v0.7 on Windows fails

### ISSUE THREAD

**Issue by acidicX** [syncthing/syncthing-gtk#145]
I just ran the installer (the smaller one without all libs and the big one after that) on a Windows machine to Upgrade to v0.7 (and ST 0.11). Automatic binary update was enabled.
Turns out ST-GTK tries to download v0.10.31 over and over again (download - restart - download - restart ...), and not 0.11.

I then updated the ST binary in AppData/local/syncthing manually, now it works again.

//edit: Windows 8.1 64-bit by the way

**Comment by kozec** [comment]
Well, v0.10.31 IS most recent release -_-. I'll check what can be done about it...

**Comment by kozec** [comment]
Fixed in [v0.7.0.2](https://github.com/syncthing/syncthing-gtk/releases)
