### ISSUE TITLE
Infinite update loop

### ISSUE THREAD

**Issue by fbreve** [syncthing/syncthing-gtk#146]
I installed syncthing-gtk on a new machine yesterday. Now it starts, a popup message say "Your syncthing daemon is too old. Attempting to download recent, please wait...". Then it downloads v0.10.31, extracts it, and the cycle restarts.

**Comment by fbreve** [comment]
Just found a workaround, which is going into .local/bin and triggering the update manually:
./syncthing.x64 -upgrade

**Comment by kozec** [comment]
This should be already fixed by today's release. What ST-GTK version are (were) you using?

**Comment by kozec** [comment]
... actually, yesterdays one :D Please, try to upgrade and re-open issue if it happens again with latest one.
