### ISSUE TITLE
incorrect Dependencies

### ISSUE THREAD

**Issue by dancinglightning** [syncthing/syncthing-gtk#147]
Hi, i was just reading about the 0.10 -> 0.11 break of compatibility.
So when it says in the Dependencies 0.10 or larger, that would be incorrect, yes ?
Should be 0.10, with warning not to use 0.11)
Until such time as you can write 0.11 (and not before!), at which time i'll give it a spin :-)
Good work though
T.

**Comment by chucic** [comment]
There already is client for 0.11 branch of ST: 0.7 and higher. For 0.10 is there 0.6.5. All you need is one look here: https://github.com/syncthing/syncthing-gtk/releases
So I think that Dependencies are fine too because of this.
Or maybe I misunderstood...

**Comment by kozec** [comment]
I'm not sure what list of dependencies you mean, but current version of ST-GTK is compatible with 0.11 onwards and thus not compatible with older ones. But ST-GTK v 0.6.5 is still available and compatible with anything bellow.

**Comment by dancinglightning** [comment]
Sorry, i was unclear:

The README states that Dependencies should be 0.10 or higher, which i think is incorrect (in one way or the other)
