### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by chucic** [syncthing/syncthing-gtk#150]
Is there a way how to translate syncthing-gtk? It might be good idea when syncthing user base is growing and other gui stuff (Syncthing, Syncthing for Android and SyncTrayzor) has it. And if it would be under transifex even better considering all others are. It would help to unite translation of terms used in ST world.

**Comment by kozec** [comment]
Code is pretty-much ready for localization, I just never bothered to actually call gettext. I can enable it and let ST-GTK to read standard po/mo files. Transifex may be bigger problem, I have never used that service :)

**Comment by alexxtasi** [comment]
if I understand correctly from Transifex's [Gettext (PO)](http://docs.transifex.com/formats/gettext/), enabling gettext support is the biggest step on translating syncthing-gtk on Transifex platform.
Anyway ... waiting to help on .po files ;-)

**Comment by dkessel** [comment]
I could provide a German translation. It would be great if your gettext branch could get merged, @kozec .

**Comment by dkessel** [comment]
Maybe we can ask @calmh how he has set up Transifex for the main syncthing project?

**Comment by kozec** [comment]
@dkessel merging is not a problem, I just updated it on par with master.
Transifex can be, because AFAIK it's paid service. And I'm pretty cheap person :P

But I'll check if there is any more economic alternative.

**Comment by AudriusButkevicius** [comment]
I am.oretty sure transifex is free for non-commercial projects.

**Comment by kozec** [comment]
> I am.oretty sure transifex is free for non-commercial projects.

Yeah, I found out about it later.

@dkessel 
Ok, I created [syncthing-gtk project](https://www.transifex.com/syncthing-gtk/syncthing-gtk/) on Transifex and briefly tested it, it looks like it works as expected on both sides.

I'll check what will it do on Windows tomorrow, but but only things missing right now are translations :)

**Comment by dkessel** [comment]
@kocez nice! Soo many strings - I really did not expect so much work :)
Anyway - working through them, looking to finish the DE translation soon.
@alexxtasi - want to race to 100% completion against me? :)

**Comment by alexxtasi** [comment]
hey @dkessel ... good job!! :+1: 
I'll do it my own pace... hope to not affect anyone. Many things for me to do and also... still sunny here in greece... ;-) 

anyway nice to have this project on transifex @kozec ... hope this grows

**Comment by dkessel** [comment]
Great, looking forward to the first release with the now finished German translation :)

**Comment by kozec** [comment]
I added [new pre-release](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.8.0.0.1) with cs,de and sk locales included for anyone who wants to test. On Linux, simply extracting source tarball and running `syncthing-gtk.py` should work.

New or modified locale file can be added simply added as .mo file into `locale/<country_code>/LC_MESSAGES` directory, but for new language on Windows, some translations included in GTK may be missing.

And by the way, thanks for your help with translating :)

**Comment by dkessel** [comment]
I tried the pre-release. The "de" translation is not getting activated here.

**Comment by kozec** [comment]
> I tried the pre-release. The "de" translation is not getting activated here.

And that's why it's called pre-release :) What os/distro and language settings are you using?

**Comment by dkessel** [comment]
Heh, sure, I know :)

I am using Xubuntu 15.10 with German language settings.

LANG=de_DE.UTF-8
LANGUAGE=de_DE


Am 10.11.2015 um 19:55 schrieb kozec:

**Comment by kozec** [comment]
Soo... OK, main problem here is that I forgot to add mo files into repo :D

Please, try to use [zip from locale branch](https://github.com/syncthing/syncthing-gtk/archive/locales.zip).

**Comment by dkessel** [comment]
Excellent - that version works for me, too :)

Am 11.11.2015 um 13:12 schrieb kozec:

**Comment by kozec** [comment]
Localization for sk/cz/de is available in [new release](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.8.1)
