### ISSUE TITLE
Unable to enable nautilus support

### ISSUE THREAD

**Issue by danvari** [syncthing/syncthing-gtk#151]
I am running Fedora 21 and have both nautilus-python and nautilus-python-devel installed (version 1.1-7). But i cannot tick the nautilus support in the UI settings.

**Comment by kozec** [comment]
Does fedora have both nautilus-python and nautilus-python2 packages by any chance?

**Comment by danvari** [comment]
Nope, it is Python 3 only :). I guess they want to push people to Python 3 :D All Python related stuff is almost Python 3 here.

**Comment by kozec** [comment]
Well, pushing stuff that nobody uses is always bad idea :)

Anyway, you need `/usr/lib/nautilus/extensions-3.0/libnautilus-python.so` and `/usr/lib/girepository-1.0/Nautilus-3.0.typelib` to enable nautilus integration. Yum whatprovides says they belongs to packages `nautilus-python` and `nautilus-extensions`. I just hope it's same for F20 and F21...

**Comment by danvari** [comment]
Ok, thats strange, I have those files (in /usr/lib64) and I can import the modules as well:

```
from gi.repository import Nautilus
from syncthing_gtk import nautilusplugin

NautilusExtensionCls = nautilusplugin.build_class(Nautilus)
```

That works fine. So there is some issue inside syncthing-gtk? Some API changes maybe?

**Comment by kozec** [comment]
>  I have those files (in /usr/lib64) and I can import the modules as well:

This sounds like a reason. They are supposed to be in /usr/lib. Is that standard library location in Fedora?

**Comment by danvari** [comment]
Yes thats the standard directory for libs. /usr/lib is for 32-bit only. That may be the reason :).

**Comment by kozec** [comment]
Well, it's not like we have LSB or anything -_-
