### ISSUE TITLE
Missing UI icons

### ISSUE THREAD

**Issue by hotice** [syncthing/syncthing-gtk#152]
All the UI icons are missing in the latest Syncthing GTK 0.7.1 (tested under Ubuntu 15.04 and 14.04). Screenshot: http://i.imgur.com/6lfaErQ.png

**Comment by kozec** [comment]
Cool, I knew this will happen at least somewhere :D I'll check why...

**Comment by kozec** [comment]
Ok, it's fixed and turned into new release: https://github.com/syncthing/syncthing-gtk/releases/tag/v0.7.1.1

Thanks for reporting :)

**Comment by hotice** [comment]
Thanks!
