### ISSUE TITLE
Error when running with the latest 3 release versions.

### ISSUE THREAD

**Issue by disposablereviewer** [syncthing/syncthing-gtk#155]
Install appears to be a success on each version.  I'm seeing the error in the screen shot when opening syncthing gtk.

windows 7 ultimate sp1
![screen shot 2015-05-13 at 11 49 55 am](https://cloud.githubusercontent.com/assets/10820063/7618380/a51ef2e4-f966-11e4-96e0-2ff6cb4c47a6.png)

**Comment by kozec** [comment]
Can you check if you have file named `C:\Program Files (x86)\SyncthingGTK\win32process.pyd` installed?

**Comment by disposablereviewer** [comment]
I do not have that file.

**Comment by kozec** [comment]
Ok, so question is, where did it gone... Can you try to install [v0.7 from "full installer"](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.7) and then upgrade?

**Comment by disposablereviewer** [comment]
yes, that worked.  maybe it has something to do with the upgrade needing to download the daemon update?  not sure why that file would vanish though.  I didn't mess with anything.

I'm on the latest version now though.

**Comment by kozec** [comment]
Great. I'll force next release to download all libraries, just in case.
