### ISSUE TITLE
Tray Icon - Minor Bug (Ubuntu 15.04)

### ISSUE THREAD

**Issue by Paradoxeuh** [syncthing/syncthing-gtk#157]
The tray icon works fine, but not when Unity Dash is open.
Thanks for your work anyway :)
![normal](https://cloud.githubusercontent.com/assets/7406885/7757497/c9433da2-fffa-11e4-969a-0458446913ee.png)
![not normal](https://cloud.githubusercontent.com/assets/7406885/7757502/d0f4343e-fffa-11e4-858f-d9bb2d1aec09.png)

**Comment by kozec** [comment]
What in the world is Unity Dash? :D

Does icon turn blue in any point of time?

**Comment by Paradoxeuh** [comment]
I thought unity dash was the name of the top left menu you open to search softwares/files ! It doesn t turn blue because I have a Upnp issue right now but I think it s not related.

**Comment by kozec** [comment]
> It doesn t turn blue because I have a Upnp issue right now but I think it s not related.

I'm asking because it looks like Unity is trying to recolor that icon to black&white style. There is no white circle icon defined anywhere in ST-GTK...

**Comment by Paradoxeuh** [comment]
Oh ok...Once it's working again, I'll let you know if something has changed.

**Comment by kozec** [comment]
Great, I like this kind of bugs :D

But there is pretty big chance that problem was not in ST-GTK, as only thing that it does in Unity is that it sets filename from which icon should be loaded.

**Comment by Paradoxeuh** [comment]
It turns blue when it works :)

![screenshot from 2015-05-25 10 42 20](https://cloud.githubusercontent.com/assets/7406885/7795345/f21fea44-02cb-11e5-9337-3d5869ad709f.png)
