### ISSUE TITLE
Tray icon seems to be a bit bigger than the other icons in Elementary OS

### ISSUE THREAD

**Issue by THPubs** [syncthing/syncthing-gtk#158]
The tray icon is a bit bigger and a small part of it is clipped. Also better if we can have a monochrome icon (optional). Please look at the Btsync icon (the first one from left). If you can make it to that size it's great! Thanks!

![tray](https://cloud.githubusercontent.com/assets/1212023/7769808/2822bc94-00a5-11e5-94a9-4e317731c0b4.png)

**Comment by kozec** [comment]
> Please look at the Btsync icon (the first one from left)

This probably refers to screenshot that you have forgotten to attach :)
ST-GTK & distro version may be helpful as well...

**Comment by THPubs** [comment]
Oh extremely sorry! Just added the screenshot. Also have a problem in windows, will open a new issue for it :-)

**Comment by kozec** [comment]
Weird thing is that this should be already fixed and I can't replicate issue neither :(

Can you run ST-GTK from terminal? Look for message begining with `I StatusIcon    Using backend` and paste it here along with  version number of ST-GTK you are using.

**Comment by THPubs** [comment]
Sure... Here's the output :


    (syncthing-gtk:6268): Gtk-WARNING **: No object called: edit-menu-button-image

    (syncthing-gtk:6268): Gtk-WARNING **: No object called: edit-menu-button-image
    I StatusIcon    Using backend StatusIconGTK3 (primary)

    Syncthing-GTK started and running in notification area
    W StatusIcon    StatusIcon: Using backend StatusIconAppIndicator (fallback)
    E Daemon        Could not connect to 127.0.0.1: Connection refused
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 386, in _rest_connected
        con = sc.connect_to_service_finish(results)
    GError: Could not connect to 127.0.0.1: Connection refused
    I App           updatecheck: disabled

**Comment by kozec** [comment]
After some testing I came to believe that this is just result of scaling algorithm that Pantheon uses.

![scale1](https://cloud.githubusercontent.com/assets/1282500/7893510/fc9203d6-065e-11e5-9faa-57288ec05021.png)
![scale2](https://cloud.githubusercontent.com/assets/1282500/7893513/01094406-065f-11e5-946b-16d3d7f78262.png)

I'm sorry, but I probably can't fix that.

**Comment by THPubs** [comment]
No issues :-) Then i'll close this issue.
