### ISSUE TITLE
The windows Tray icon is missing

### ISSUE THREAD

**Issue by THPubs** [syncthing/syncthing-gtk#159]
In windows the tray icon is missing as seen on the screenshot (It's the first one from left). The icon is there but the icon file is missing... showing a blank file icon :

![wintray](https://cloud.githubusercontent.com/assets/1212023/7769913/189a6f82-00a6-11e5-94dc-f7ebbd1434d7.png)

**Comment by kozec** [comment]
2 questions:
1. Are you using latest version
2. Does icon ever change? For example, when some other device is connected or synchronization is running.

**Comment by THPubs** [comment]
Im using the latest version and no it does not change even when syncing :-(

**Comment by cedricbrx** [comment]
same problem here

**Comment by zyphrus** [comment]
same problem on Linux
