### ISSUE TITLE
How to install pyinotify in Windows to enable inotify?

### ISSUE THREAD

**Issue by THPubs** [syncthing/syncthing-gtk#160]
How can we install pyinotify in windows and enable inotify? Is there any installer? Is it possible to package it along with syncthing gtk?

PS : Sorry if im opening too many issues :-)

**Comment by kozec** [comment]
inotify is Linux-specific thing, not supported on Windows.

**Comment by THPubs** [comment]
@kozec Ah ok. Any alternatives for Windows?

**Comment by Zillode** [comment]
@THPubs you can run [syncthing-inotify](https://github.com/syncthing/syncthing-inotify/releases)
@kozec Are you open to embed syncthing-inotify in syncthing-gtk? I'd like to have it tested by more ppl before proposing a merge with the main syncthing project.

**Comment by kozec** [comment]
> @kozec Are you open to embed syncthing-inotify in syncthing-gtk? I'd like to have it tested by more ppl before proposing a merge with the main syncthing project.

Sounds like good idea; is it possible to configure it to watch only some directories?

**Comment by Zillode** [comment]
The `-home` parameter might also be of interest. Just link it to the config dir and it will sniff the api key (which is all st-inotify needs)

**Comment by kozec** [comment]
@Zillode Just to check, will 32bit syncthing-inotify have any problem with 64bit syncthing daemon? ST-GTK has only 32bit installer for Windows, so bundling 64bit syncthing-inotify exacutable would be... Not exactly problem, but more trouble than I think is necessary.

**Comment by Zillode** [comment]
I never tried it but all communication is based on http requests, so I think it'll work.
If you only bundle a 64bit syncthing you could also opt for the 64bit inotify. If you bundle dynamically, feel free use the 32bit.

**Comment by kozec** [comment]
@Zillode Ok, it pretty-much works, but I have problem with capturing syncthing-inotify output. Is it doing anything that may prevent reading from its stdout, when it's started as background process?

**Comment by Zillode** [comment]
Not that I know of, all output is written to os.Stdout. The exit codes are documented in the FAQ: https://github.com/syncthing/syncthing-inotify/wiki/FAQ

**Comment by kozec** [comment]
@THPubs So, ST-GTK now includes syncthing-inotify v0.6.3 in [latest release](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.7.2). It would be great if you could give it a test and tell me if it works on more than single (my own :) machine.

**Comment by THPubs** [comment]
@kozec I think it works! :-) Didn't do too many tests... Just added one file and deleted one file... Both worked :-) Thanks for the quick fix!
