### ISSUE TITLE
[Feature Request] Thunar integration

### ISSUE THREAD

**Issue by rodneyrod** [syncthing/syncthing-gtk#161]
Thunar is a pretty popular GTK+ file manager and supporting it would allow greater exposure for syncthing-gtk.

**Comment by kozec** [comment]
I already thought about it, but AFAIK, Thunar has no _official_ python bindings and thunarx-python is usually not available in repositories (at least not for *buntus and Arch).
Anyway, I can try it next time I'll feel bored enough, but enabling support on end-user machine may be considerably harder than enabling other plugins.

**Comment by rodneyrod** [comment]
Well do what you think is best, however I did have a look around and found out that thunarx-python is also available from Webupd8, which I believe is also where syncthing-gtk is hosted for *buntu, and it's also available in the AUR.

**Comment by kozec** [comment]
So, after some playing with thunarx-python I found that it's not possible to load gi.introspection packages used by ST-GTK under GTK2+PyGTK environmnent used by Thunar.
