### ISSUE TITLE
The windows tray icon is missing

### ISSUE THREAD

**Issue by cedricbrx** [syncthing/syncthing-gtk#163]
Hi, i know you already have corrected this bug, but at every logon, my tray icon disappears. I have to shutdown syncthing-gtk.exe an restart the application to get the icon.

![syncthing](https://cloud.githubusercontent.com/assets/11331696/7948307/32f55668-0983-11e5-8a0f-d62c11a6400a.png)

Regards,

**Comment by kozec** [comment]
By disappeared icon do you mean that almost-rectangular thing next to battery icon, or is icon completely missing? And if former, does it ever change if you let it run in this state?

**Comment by cedricbrx** [comment]
Yes

**Comment by cedricbrx** [comment]
It doesn't change, until i shutdown syncthing-gtk and restart it. Then it looks good

**Comment by kozec** [comment]
Ok, thanks. Now if only I had idea what in vast world can cause this behavior...
