### ISSUE TITLE
Inserts an erroneous space into globalAnnounceServer configuration

### ISSUE THREAD

**Issue by chungy** [syncthing/syncthing-gtk#164]
On trying to figure out why syncthing/syncthing#1750 was even an issue for me, I seem to have traced it down to syncthing-gtk. When using the Daemon Settings dialog, it will resave the configuration for the global announce servers, and would often insert spaces at the beginning or end of announce server URLs, most often causing syncthing to report an unsupported URI scheme and the announce server will effectively be disabled.

For example, the config.xml for syncthing might appear as such after re-saving, causing the problem:
```xml
        <globalAnnounceServer>udp4://announce.syncthing.net:22026</globalAnnounceServer>
        <globalAnnounceServer> udp6://announce-v6.syncthing.net:22026</globalAnnounceServer>
```

**Comment by kozec** [comment]
True, that shouldn't happen :)
