### ISSUE TITLE
file watcher not working correctly

### ISSUE THREAD

**Issue by timski** [syncthing/syncthing-gtk#165]
Hej, I wrote about it month ago, and still I cannot pinpoint why the file watcher sometimes
sometimes it just triggered, sometimes it doesn't

currently it does not seem to work at all
probably the reason lies here:
["syncthing-gtk -d" output]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/watcher.py", line 113, in _process_events
    notifier.process_events()
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 1287, in process_events
    self._default_proc_fun(revent)
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/watcher.py", line 102, in _process
    self._report_deleted(event.pathname)
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/watcher.py", line 133, in _report_deleted
    if not enabled: return
NameError: global name 'enabled' is not defined
[/"syncthing-gtk -d" output]
python2-2.7.10-1
python2-pyinotify-0.9.6-1

anyway, whats the reason for not using the syncthing-inotify? seems to work nicely, as far as I could try so far

**Comment by kozec** [comment]
> anyway, whats the reason for not using the syncthing-inotify? seems to work nicely, as far as I could try so far

Because it was not around (or at least I didn't knew about it) when I implemented filesystem watching originally.

Anyway, this part should not be on Linux yet. Which version are you using?

**Comment by timski** [comment]
it's the 0.7.2 version, from the arch-community-repo

**Comment by kozec** [comment]
> it's the 0.7.2 version, from the arch-community-repo

Ok, next time I'll replace skip with **should** in 'Windows-only stuff. If you are on Linux, you can skip this version' :D

**Comment by timski** [comment]
:D well I see

**Comment by timski** [comment]
well maybe a big WINDOWS-ONLY - DO NOT USE ON LINUX just to be sure. ;)

what about moving to syncthing-inotify, would there be any benefits?

**Comment by kozec** [comment]
Well, assuming that internal inotify watcher works as it should, it would mean more complicated installation and another running process in memory :)
But that's exactly what ST-GTK does on Windows now and that's also reason why Linux part is little broken in this release, so I can probably add some sort of switch or option to enable same method on Linux.

**Comment by kozec** [comment]
Should be fixed in [release 0.7.3](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.7.3).

**Comment by timski** [comment]
great, thanks a lot :D
