### ISSUE TITLE
"new device wants to connect" dialogue with IPv6 address shows only the first part of the address

### ISSUE THREAD

**Issue by acidicX** [syncthing/syncthing-gtk#166]
See image:
![screen2](https://cloud.githubusercontent.com/assets/1297454/8081235/8621146c-0f73-11e5-8f22-cdf82520741e.png)

It should state the whole address (as it is show in the web UI). Also, the "ignore" button is missing in ST-GTK.

**Comment by kozec** [comment]
Ignore button is that [X] on right. I'll check what's up with address.
