### ISSUE TITLE
No sync-emblems on some folder (nautilus)

### ISSUE THREAD

**Issue by Coeur-Noir** [syncthing/syncthing-gtk#169]
Hello,

I can't see the problem on all my pc's, only on one. The 3 pc's are running *buntu 14.04.

Don't pay attention here about the "immediate-sync" question, only the "emblems" issue :
https://forum.syncthing.net/t/monitor-filesystem-for-changes-or-time-taken-for-syncing/3001/7?u=coeurnoir

![capture](https://cloud.githubusercontent.com/assets/1895947/8184169/4008aa98-143d-11e5-9b62-8e4aeda9be15.jpg)

Emblems don't show up on desktop folder, unless I do a **nautilus -q**. Emblem show on newly created file.

**Comment by kozec** [comment]
Desktop emblems are probably not refreshed automatically... Does clicking desktop and pressing F5 or ^R help as well?

Is there anything what makes that one PC different? Other distro/version, language, etc...

**Comment by Coeur-Noir** [comment]
F5 or Ctrl+R do not help.

I've just noticed the same problem on an other PC today - still with the same folder "desktop" - one of the file has no emblem (even after nautilus -q) but seems to be sync'ed through the three pc's.

That said, the pc where there is no emblem at all (unless nautilus -q) may be a little different since it was long ago upgraded from ubuntu 13.10 to 14.04 (not a fresh install).

No error message in daemon output.

**Comment by kozec** [comment]
So, if I understood correctly, this happens **only** for desktop? Does same thing happens if you open your desktop folder in normal window?

Are both machines on Ubuntu 14.04?

**Comment by Coeur-Noir** [comment]
Emblems not shown at all → yes, on desktop folder.
Desktop in normal window shows the same behaviour.

Emblems not being updated regarding current sync'state → it seems to be everywhere.

Both machines run ubuntu 14.04

**Comment by kozec** [comment]
Sorry, but I really have trouble trying to replicate this. I have fresh install of Ubuntu 14.04 and latest ST-GTK and emblems on desktop are appearing and changing in same way as on any other folder, exactly as I'd expect.

Try to open terminal and run:

`nautilus -q ; nautilus`

It should restart Nautilus and grab all output into terminal; Check if there is anything what looks like error message written there, especially when you are creating new folder or doing anything else where emblem is not displayed as it should.

**Comment by Coeur-Noir** [comment]
Ok. On pc starting, emblems are not shown on desktop. Then if I do a nautilus -q emblems do appear.

Terminal output : 
>palace@Asgard:~$ nautilus -q ; nautilus
>Impossible d'enregistrer l'application: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
>palace@Asgard:~$ nautilus
>I SyncthingPlugin Initializing...
>I SyncthingPlugin Initialized.
>Initializing nautilus-open-terminal extension
>I SyncthingPlugin Connected to Syncthing daemon
…nothing's printed when I create new folder / new file on desktop. But those newly items do have their emblems.

**Comment by kozec** [comment]
As I'm still not able to replicate problem, can you, please, confirm if it is still present with v0.7.4?

**Comment by Coeur-Noir** [comment]
I can confirm that it is still present with 0.7.4. on that ubuntu 14.04 machine (upgraded from 13.10)

Let's try to sum it up : 

Right after booting pc → on desktop folder → no emblems
but as you can see below, emblems are ok on files inside a folder which is inside desktop folder…
![capture du 2015-07-01 12 19 05](https://cloud.githubusercontent.com/assets/1895947/8452561/39e31580-1fec-11e5-9e36-e6b592d60b79.png)

Now on, If I create a new file or folder on desktop, it comes with its emblem.

If I do a *nautilus -q* and restart nautilus, emblems appear where they were formerly missing.

Then I've also noticed that emblems do not seem to currently update with actual sync-state of files and folders. And that is true on my three machines.

**Comment by Coeur-Noir** [comment]
I now have the same behaviour on my 2 ubuntu/unity machines : 
- no emblems right after startup,
- emblems only on newly created or modified files,
- emblems everywhere if I do nautilus -q
- but emblems not updated with state of sync (for example : double-arrow emblem remain even long after the file has been sync'd between the 3 machines)

It seems to date from syncthing update to v0.11.14 (v0.11.15 now on)

**Comment by kozec** [comment]
I'm sorry, but are you saying that problem is appearing and disappearing randomly?

**Comment by Coeur-Noir** [comment]
Not at all ;-) the problem looks permanent.

It's just that "before" the behavior with emblems was a little different between the two ubuntu/unity machines : I had emblems on my sync'd files on startup (on the office machine).

Now on startup no emblems at all on any machine.

**Comment by kozec** [comment]
Do you have any other nautilus extension enabled?

**Comment by Coeur-Noir** [comment]
Does "open with terminal" count as an extension ?
(it's not installed by default but to be found in official Ubuntu repositories)

**Comment by kozec** [comment]
Yes, it does, although it's probably not reason for a problem. But anything what helps me to replicate problem is good as I have no idea how to fix it only from description.

**Comment by Coeur-Noir** [comment]
I guess we should focus on the "desktop" folder because it's mainly where emblems are not displayed.

![capture du 2015-07-22 11 46 20](https://cloud.githubusercontent.com/assets/1895947/8822668/66bb1090-3067-11e5-8029-ad61de1d05d6.png)

That said, most of my folders are sync'd through two machines. But desktop (Bureau) is shared through 3 machines.

**Comment by Coeur-Noir** [comment]
Did you change anything about emblems in v0.8 ?

On my 2 ubuntu 14.04 unity with nautilus integration,

emblems are only show on currently synching files (double blue circle arrows) and is not updated (they always look as they *are* synching).

No other emblems are ever shown, what ever directory, even after a nautilus -q

I have that same behavior on the 2 ubuntu 14.04 running nautilus (the third machine is Lubuntu with PcManFm).
