### ISSUE TITLE
Allow for removing autoupdate setting

### ISSUE THREAD

**Issue by Somasis** [syncthing/syncthing-gtk#170]
For packaging, we don't want users to be able to set autoupdate stuff. Package mangers handle that. And, if syncthing is compiled without autoupdate, which is probably is if it's packaged, there's no point in the option being around if it can't do anything. So, there should be a way to remove it at build time or perhaps by detecting if the Syncthing daemon has the ability to autoupdate.

**Comment by AudriusButkevicius** [comment]
I thought it already does that?

**Comment by kozec** [comment]
Yeah, I had it done as parameter to setup.py in debian branch, but never merged it. I'll try to redo it on master.

**Comment by kozec** [comment]
Ok, whoever needs it can now do

```
./setup.py build_py --nostdownloader install
```

to 'build' ST-GTK without autoupdater code.

**Comment by Somasis** [comment]
Thank you!

**Comment by Somasis** [comment]
Just a heads up for anyone that finds this issue: I had to run `./setup.py build_scripts`, and then run `./setup.py install --skip-build` to prevent it from trying to build and install stdownloader. Not sure if that's intended or not, but it caught me off guard at first.

**Comment by kozec** [comment]
@Somasis Probably different version of python / distutils?
I can use command as described above on my machine...

```
bash:/tmp$ wget https://github.com/syncthing/syncthing-gtk/archive/v0.7.4.tar.gz -q
bash:/tmp$ tar xfz v0.7.4.tar.gz 
bash:/tmp$ cd syncthing-gtk-0.7.4/
bash:/tmp/syncthing-gtk-0.7.4$ ./setup.py build_py --nostdownloader install --root /tmp/test
fatal: Not a git repository (or any parent up to mount point /tmp)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
running build_py
creating build
creating build/lib
creating build/lib/syncthing_gtk

(snip)

running install_egg_info
Writing /tmp/test/usr/lib/python2.7/site-packages/syncthing_gtk-v0.7.4-py2.7.egg-info

bash:/tmp/syncthing-gtk-0.7.4$ ls /tmp/test/usr/lib/python2.7/site-packages/syncthing_gtk/st*
/tmp/test/usr/lib/python2.7/site-packages/syncthing_gtk/statusicon.py
/tmp/test/usr/lib/python2.7/site-packages/syncthing_gtk/statusicon.pyc
```
(no stdownloader.py installed)

On ArchLinux with python2 2.7.9 and bundled distutils.

**Comment by Somasis** [comment]
The package manager for Exherbo divides the phases of package compiling and installation, so it has to do those in separate steps, which is why I had to do it with separate commands. The assumption that both building and installation should be done at once isn't very intuitive, imo.

**Comment by kozec** [comment]
Ah, ok, that's the difference. Having it divided is, of course, right way, but ST-GTK is not truly compiled or builded. Everything is just python, so setup.py just throws files from one place to another :)
