### ISSUE TITLE
Monitor filesystem for changes - not working ?

### ISSUE THREAD

**Issue by Coeur-Noir** [syncthing/syncthing-gtk#171]
Hello,

I'm running syncthing + syncthing-gtk for some weeks now on three machines (*buntu 14.04).

I may have misunderstood how "monitor filesystem for changes work". Or missed some package to install (inotify ?).

What I had expected : 

- when a file is modified or created on pc-a, this created or modified file should appear on pc-b and pc-c (almost) immediatly.

What actually happens : 

- newly created (or modified) file on **pc-a** does not appear on pc-b or pc-c unless I restart syncthing-daemon on **pc-a**. Then the change is immediatly propagated.

- the same goes if I create/modify file on pc-b or pc-c. I then have to restart syncthing-daemon on the concerned pc in order to see the changes on the other ones.

My current settings on each shared folder are : 
- monitor filesystem for changes = checked
- sync intervall = 14400s.
- no master folder anywhere
- no versionning

I have also waited for the 4 hours sync interval to pass → not better.

**Comment by kozec** [comment]
Can I have versions of everything?

**Comment by Coeur-Noir** [comment]
Of course, sorry for forgetting : 
- syncthing v0.11.9
- syncthing-gtk v0.7.3 (from webupd8 ppa)

**Comment by kozec** [comment]
Ok, and one more thing. Can you check if file count in Local State increases when new file is created?
You can also start syncthing-gtk with -d argument and check if there are lines like...
```
D Watcher       File Changed test /tmp/test/test26 (7th copy) > test26 (7th copy)
```
printed when new file is created.

**Comment by Coeur-Noir** [comment]
I've started syncthing-gtk *with* -d argument.

Waited a moment and created a new file Test_2.

Waited another moment, created another new file TEST_3.

Here is the whole terminal output : 
`palace4@ANTEC:~$ syncthing-gtk -d
D UIBuilder     Enabled: traditional_header
D UIBuilder     Enabled: old_gtk
D UIBuilder     Enabled: icons_in_menu
D UIBuilder     Loading glade file /usr/share/syncthing-gtk/app.glade
D UIBuilder     Enabled conditions: set([u'old_gtk', u'icons_in_menu', u'traditional_header'])
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node !is_gnome | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: !old_gtk
D UIBuilder     Removed 'child' by attribute: header_bar
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'child' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node traditional_header
D UIBuilder     Allowed node traditional_header | icons_in_menu
W StatusIcon    StatusIcon: Using backend StatusIconAppIndicator (fallback)
D Daemon        WebUI listens on 0.0.0.0, connecting to 127.0.0.1 instead
V Notifications Error notifications enabled
V Notifications File update notifications enabled

Syncthing-GTK started and running in notification area
V Daemon        Set refresh interval to 5
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 27: ordinal not in range(128)
Logged from file daemon.py, line 390
D App           Creating connect_dialog
V App           Settinig connect_dialog label Starting Syncth
D InfoBox       ANTEC state changed to Disconnected
D InfoBox       ASGARD-Palace state changed to Disconnected
D InfoBox       POSEO-bureau-gerald state changed to Disconnected
D InfoBox       /home/palace4/Bureau state changed to Disconnected
D InfoBox       /home/palace4/Bureau state changed to Unknown
D InfoBox       /home/palace4/Modèles state changed to Disconnected
D InfoBox       /home/palace4/Modèles state changed to Unknown
D InfoBox       ANTEC state changed to 
I App           updatecheck: disabled
D InfoBox       /home/palace4/Bureau state changed to Up to Date
D InfoBox       /home/palace4/Bureau state changed to Offline
D InfoBox       /home/palace4/Modèles state changed to Up to Date
D InfoBox       /home/palace4/Modèles state changed to Offline
D InfoBox       POSEO-bureau-gerald state changed to Connected
D InfoBox       /home/palace4/Modèles state changed to Up to Date
D InfoBox       /home/palace4/Bureau state changed to Up to Date
D InfoBox       POSEO-bureau-gerald state changed to Up to Date
D InfoBox       /home/palace4/Bureau state changed to Syncing
D InfoBox       /home/palace4/Bureau state changed to Up to Date
D InfoBox       /home/palace4/Modèles state changed to Syncing
D InfoBox       /home/palace4/Modèles state changed to Up to Date
D InfoBox       /home/palace4/Bureau state changed to Syncing
D InfoBox       /home/palace4/Bureau state changed to Up to Date
D InfoBox       ASGARD-Palace state changed to Connected
D InfoBox       ASGARD-Palace state changed to Up to Date
D InfoBox       /home/palace4/Modèles state changed to Syncing
D InfoBox       /home/palace4/Modèles state changed to Up to Date
D InfoBox       /home/palace4/Bureau state changed to Syncing
D InfoBox       /home/palace4/Bureau state changed to Up to Date
V Daemon        Set refresh interval to 1

(syncthing-gtk:4060): Gtk-WARNING **: Invalid icon size 16


(syncthing-gtk:4060): Gtk-WARNING **: Invalid icon size 16


(syncthing-gtk:4060): Gtk-WARNING **: Invalid icon size 16


(syncthing-gtk:4060): Gtk-WARNING **: Invalid icon size 16`

**Comment by kozec** [comment]
And are you sure that you have filesystem watcher enabled on any folder? There should be something like
```
V Watcher       Watching /tmp/test
```
mentioned there. And, this is checked when enabling watcher, but just in case, you need python-inotify package installed.

**Comment by Coeur-Noir** [comment]
python-pynotify is installed

There's a python-notifyx available in ubuntu 14.04 repo but currently not installed.

If filesystem watcher means "monitor filesystem for changes" then yes it's enabled on each folder.

**Comment by Coeur-Noir** [comment]
So, let's try with : 
python-inotify**x**

Have installed it on the three machines and now "monitor filesystem for changes" seems to work ! When I create a file on pc-b it appears within seconds on pc-a and pc-c ! Magic ! And all the way round, with creating, modifying, deleting…

Now what I don't understand : 
- why did not I get warnings about missing dependencies when I installed syncthing-gtk through synaptic package manager (using webupd8/nilarimogard's ppa) ?
- are *python-inotify* and *python-inotify**x*** the same thing or who mispelled and why ?
- was I alone with this "(not) bug" but package misconfiguration ? I don't think my *buntu systems are in any way particular…

…anyway, I'm very glad it works now, and happily goin'on testing !

**Comment by Coeur-Noir** [comment]
I'm lost, now it does not work anymore…

…can it be relative to the syncthing upgrade to v0.11.10 ?

**Comment by kozec** [comment]
I'll check what's python-inotifyx in Ubuntu, but I'm sure that package is named python-inotify everywhere else. As for why ST-GTK didn't warned you about dependency, that dependency check is rather simple and if there is some other, same named python library present, it may not work as expected.

Now about other problem; Only number of files on "Local state" is reliable indicator for telling if inotify is working. Thing is, when ST-GTK notices that file has been changed, it notifies Syncthing daemon on same computer. Daemon then rescans/rehashes changed file and makes it available for remote machines, but it's up to remote machine to notice that global state changed and to request changed file.

And, looking at that log in image, that doesn't happen. Note that "*directory is not empty*" message followed by "*pausing puller for 1m*". That basically means that even if syncthing daemon knows that he misses some files, it's not going to download it for next minute. And if that message really is repeated ad infinium, it's probably not gonna until problem is resolved.

**Comment by Coeur-Noir** [comment]
Thanx for explanations. I've since rebooted the three pc's and did some other tests : sync-updates are done only if I quit or restart syncthing… So python-inotify**x** may not be a solution.

**Comment by kozec** [comment]
And did that *directory is not empty* error disappeared as well?

**Comment by Coeur-Noir** [comment]
Yes that _directory is not empty error_ disappeared.

And actually folder _was not_ empty…

**Comment by hotice** [comment]
In Ubuntu you need to install the ```python-pyinotify``` package. The syncthing-gtk packages in the main WebUpd8 PPA recommend this package but they don't enforce it. In Ubuntu, recommended dependencies should be installed automatically. In Linux Mint however, recommended dependencies are skipped so maybe you're actually using Linux Mint (which is indeed based on Ubuntu 14.04) and that's why you don't have the package? Either way, check if that package is installed using:
```
apt-cache policy python-pyinotify
```

**Comment by Coeur-Noir** [comment]
Hey ;-) I have already checked and python-pyinotify 0.9.4 is installed on the three machines (2 ubuntu, 1 Lubuntu, all 14.04 lts).

Today I've "found" this just after bootup : 
![capture du 2015-06-23 11 30 54](https://cloud.githubusercontent.com/assets/1895947/8303178/63b84264-199c-11e5-89df-84cfafed89da.png)

**Comment by kozec** [comment]
Ok, I *think* I was finally able to replicate problem... Main part of it was me assuming that not outputing errors when doing non-important call is a good idea :(

@AudriusButkevicius would you, by any chance happen to know, why would /rest/db/scan call return error 400?
It doesn't happen for `rest/db/scan?folder=test` call, but it's returned if `sub` parameter is added - `rest/db/scan?folder=test&sub=menu.py` returns HTTP/400 without any message.
Running syncthing with STTRACE=httpfiles,scanner,model display no error message and no sing of failed request when this happens.

**Comment by Zillode** [comment]
Check the output of the request:
```
curl -X POST -k --header "X-API-Key: 12345" "https://localhost:8384/rest/db/scan?folder=test&sub=menu.py"
```
No such folder is one potential cause.

**Comment by kozec** [comment]
Ok, it may be another problem, it looks like syncthing doesn't accept space in request as valid character. That's reasonable, but probably not related to this.

@Coeur-Noir Can you, please, give me full path to any file that was not synchronized without restarting?

**Comment by Coeur-Noir** [comment]
Well, no files are ever synchronized without restarting (machine or daemon).

Some paths to files have "spaces" in them, some don't as you can see below : 
![capture du 2015-06-24 11 17 42](https://cloud.githubusercontent.com/assets/1895947/8326720/47da43a4-1a63-11e5-975a-25edcf92689d.png)

/home/palace/Bureau on ASGARD is shared with /home/gerald/Bureau on POSEO and with /home/palace/Bureau on ANTEC

Most recent file has been created on ASGARD and is named : "Capture du 2015-06-24 11:08:58.png" which is locally in sync regarding its emblem _(there's another issue bout emblems)_, but is not propagated to the other nodes, as you can see above.

**Comment by Coeur-Noir** [comment]
Below is after I have restarted the syncthing-daemon through syncthing-gtk on the machine where I've created new files → new files are then immediatly "propagated" from ASGARD to POSEO (the one in teamviewer window).
![capture du 2015-06-24 11 40 20](https://cloud.githubusercontent.com/assets/1895947/8327131/54c88a0a-1a66-11e5-9971-8b6f6e941c9f.png)

Few minutes later, I have created a folder named "Name_with_no_space" containing one file named "test_name_with_no_space" on /home/palace/Bureau on ASGARD. Have waited for another few minutes and get this screenshot : nothing happens on POSEO side.
![capture du 2015-06-24 11 51 31](https://cloud.githubusercontent.com/assets/1895947/8327275/6bff6e5e-1a67-11e5-9890-254ddb1da06b.png)
You can see on both sides that local and global states count 6 files but actually there are 7 files (or even 8 if a folder count as a file) on /home/palace/Bureau

**Comment by suaefar** [comment]
Maybe you need to install "python3-pyinotify"?
On Ubuntu 15.04 it did the trick as far as I remember.

**Comment by Coeur-Noir** [comment]
Heart full of hope I have installed "python3-pyinotify". Rebooted the pc's.

But not better : sync and files updates are made whenever I re-start syncthing-daemon.

But not "automatically" when I create or modify a file…

**Comment by Coeur-Noir** [comment]
Mmm... I have installed _python3-pyinotify_ on the three machines.

Wait and see.

It seems immediate sync' is working from ANTEC to POSEO - file created on first is immediatly seen on the second. But it's not working in the other way from POSEO to ANTEC…

I'll test further and will pay attention to the local and global states on each machine.

**Comment by kozec** [comment]
No, no, no, python3 has definitely nothing to do with this :D

@Coeur-Noir can you check if problem persists with current git master? Just download https://github.com/syncthing/syncthing-gtk/archive/master.tar.gz , extract it anywhere and run `./syncthing-gtk.py -d` from terminal.

**Comment by Coeur-Noir** [comment]
Guess I'd better test simultaneously on the three machines ?

And before should I uninstall my current syncthing-gtk ?

**Comment by Coeur-Noir** [comment]
I've uninstalled syncthing-gtk 0.7.3 and am currently running the one from git on two machines (the third machine is not connected, not running syncthing for the moment) : 
![capture du 2015-06-25 13 14 35](https://cloud.githubusercontent.com/assets/1895947/8353256/4c59085a-1b3c-11e5-96ea-650f7ab8d650.png)

It seems better ! New created files on one machine are seen on the other and same in the other way. Below is after enabling nautilus integration on both sides : 
![capture du 2015-06-25 13 22 05](https://cloud.githubusercontent.com/assets/1895947/8353364/55278de8-1b3d-11e5-8f41-c5946e5bf48a.png)

So… what did you find / change ?

**Comment by kozec** [comment]
I let it to request full repository rescan every time when file is changed, not only changed file. There is some sort of problem with requests where filename contains space and/or accented characters, but I still can't pinpoint under what exact conditions it fails.

That UnicodeDecodeError is not related to this, that executable is normally expected in something line `/usr/bin` or `/usr/local/something`

**Comment by Coeur-Noir** [comment]
System language is french Fr_fr on the three machines, and yes it means accented characters… I've noticed the _UnicodeDecodeError_ because months ago dejadup/duplicity (default backup software in Ubuntu) showed the same error message and was kind of broken because of somehow the same reasons : unability to "read" the file names with accented characters.

Let's go back to that "most recent version" of syncthing-gtk : 
- on ubuntu no icon for app-indicator, it's ok on Lubuntu (which uses legacy systray)
- nautilus integration seems to be broken (?) no emblems anywhere even after **nautilus -q** and restart nautilus.
    palace4@ANTEC:~$ nautilus
    Initializing nautilus-open-terminal extension
    /opt/extras.ubuntu.com/pushbullet-commons/share/pushbullet-commons
    Traceback (most recent call last):
      File "/home/palace4/.local/share/nautilus-python/extensions/syncthing-plugin-nautilus.py", line 8, in <module>
        from syncthing_gtk import nautilusplugin
    ImportError: No module named syncthing_gtk

**Comment by kozec** [comment]
Yeah, working with Unicode in Python can be funny.
Nautilus plugin will probably not work until ST-GTK is installed from package, as it relies on syncthing_gtk modules being in python path.

**Comment by Coeur-Noir** [comment]
Do you think this problem here has any relation with the "emblems" problem #169 ?

So, now the _sort-of-auto-update-sync_ seems to be fixed, what is next step ? Should I go back to the 0.7.3 version for the moment ? Do you need some other informations ?

_(Have you seen the new Trash Can File Versioning proposed by syncthing webGUI ? And the File Pull Order / Newest First ?)_

**Comment by Coeur-Noir** [comment]
Going back to syncthing-gtk 0.7.3 I get this "crash" at each start on one pc : 
yesterday http://pastebin.com/gy9NA0NF
today http://pastebin.com/MLE1ZBBc

**Comment by kozec** [comment]
That shouldn't be considered as crash, but it's better to not do it anyway :)
