### ISSUE TITLE
syncthing-gtk 0.7.2 and newer won't start on windows

### ISSUE THREAD

**Issue by DerGary** [syncthing/syncthing-gtk#172]
Hello,

I was using synthing gtk for over a month now and i was using version 0.7.1 for Windows on my Windows 8.1 Laptop with syncthing version 0.11.05. Today I tried to update to a newer Version. First I updated syncthing gtk to 0.7.3 but after that it wouldn't start anymore. So I also updated syncthing to 0.11.10 but it made no difference. I also tried gtk version 0.7.2 but that didn't start either. If I install 0.7.1 again it starts and works normal. 

After starting version 0.7.3, I can see it for a second in the Task Manager and after that it's just gone, no error, nothing.

Is there a log I can provide? Because I could'nt find one yet.

Greetings
Gary

**Comment by kozec** [comment]
> Is there a log I can provide? Because I could'nt find one yet.

Yes. If you start syncthing-gtk.exe with -d argument (start -> run -> `c:\Program Files (x86)\SyncthingGTK\syncthing-gtk.exe -d`), it will generate file named *Syncthing-GTK-somerandomstring.log* in %TEMP% directory.

**Comment by DerGary** [comment]
ok here is the log:

>D UIBuilder     Enabled: header_bar
>D UIBuilder     Enabled: is_windows
>D UIBuilder     Enabled: icons_in_menu
>D UIBuilder     Loading glade file .\app.glade
>D UIBuilder     Enabled conditions: set([u'icons_in_menu', u'is_windows', u'header_bar'])
>D UIBuilder     Removed 'property' by attribute: !is_windows
>D UIBuilder     Removed 'property' by attribute: !is_windows
>D UIBuilder     Allowed node icons_in_menu | old_gtk
>D UIBuilder     Removed 'property' by attribute: !is_windows
>D UIBuilder     Removed 'property' by attribute: !is_windows
>D UIBuilder     Allowed node !is_gnome | old_gtk
>D UIBuilder     Allowed node icons_in_menu | old_gtk
>D UIBuilder     Removed 'property' by attribute: old_gtk
>D UIBuilder     Allowed node icons_in_menu | old_gtk
>D UIBuilder     Allowed node icons_in_menu | old_gtk
>D UIBuilder     Removed 'child' by attribute: traditional_header
>D UIBuilder     Allowed node icons_in_menu | old_gtk
>D UIBuilder     Removed 'property' by attribute: !is_windows
>D UIBuilder     Removed 'property' by attribute: !is_windows
>D UIBuilder     Removed node traditional_header
>D UIBuilder     Allowed node traditional_header | icons_in_menu

**Comment by kozec** [comment]
That looks as if it crashes before it logs anything usefull :(
Does full installer from [v0.7.2](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.7.2) helps by any chance?

**Comment by DerGary** [comment]
I also tried the full installer before but it made no difference, i just tried it again and generated a log with -d but it looks exactly like the one i already posted

**Comment by kozec** [comment]
Can you, please, try this build: [SyncthingGTK-v0.7.3-1-g094d699-win32-installer.exe](http://www.kozec.com/SyncthingGTK-v0.7.3-1-g094d699-win32-installer.exe)

It has `syncthing-gtk-console.exe` executable added, that will output all errors and messages to console window. If possible, try to open cmd.exe, navigate to "*\Program Files (x86)\SyncthingGTK*" and start it with -d argument.

**Comment by DerGary** [comment]
of course, here is the output:

>C:\Program Files (x86)\SyncthingGTK>syncthing-gtk-console.exe -d
>D UIBuilder     Enabled: header_bar
>D UIBuilder     Enabled: is_windows
>D UIBuilder     Enabled: icons_in_menu
>D UIBuilder     Loading glade file .\app.glade
>D UIBuilder     Enabled conditions: set([u'icons_in_menu', u'is_windows', u'header_bar'])
>D UIBuilder     Removed 'property' by attribute: !is_windows
>D UIBuilder     Removed 'property' by attribute: !is_windows
>D UIBuilder     Allowed node icons_in_menu | old_gtk
>D UIBuilder     Removed 'property' by attribute: !is_windows
>D UIBuilder     Removed 'property' by attribute: !is_windows
>D UIBuilder     Allowed node !is_gnome | old_gtk
>D UIBuilder     Allowed node icons_in_menu | old_gtk
>D UIBuilder     Removed 'property' by attribute: old_gtk
>D UIBuilder     Allowed node icons_in_menu | old_gtk
>D UIBuilder     Allowed node icons_in_menu | old_gtk
>D UIBuilder     Removed 'child' by attribute: traditional_header
>D UIBuilder     Allowed node icons_in_menu | old_gtk
>D UIBuilder     Removed 'property' by attribute: !is_windows
>D UIBuilder     Removed 'property' by attribute: !is_windows
>D UIBuilder     Removed node traditional_header
>D UIBuilder     Allowed node traditional_header | icons_in_menu
>Traceback (most recent call last):
>  File "c:\syncthing-gui\syncthing_gtk\app.py", line 114, in do_startup
>  File "c:\syncthing-gui\syncthing_gtk\app.py", line 270, in setup_widgets
>  File "c:\syncthing-gui\syncthing_gtk\uibuilder.py", line 31, in add_from_file
>  File "c:\syncthing-gui\syncthing_gtk\uibuilder.py", line 36, in add_from_string
>  File "c:\syncthing-gui\syncthing_gtk\uibuilder.py", line 97, in _build
>  File "c:\Python27\lib\site-packages\gi\overrides\Gtk.py", line 462, in add_from_string
>GLib.Error: gtk-builder-error-quark: Invalid property: GtkImage.icon on line 29 (11)
>
>Syncthing-GTK started and running in notification area
>
>C:\Program Files (x86)\SyncthingGTK>

**Comment by kozec** [comment]
Great, so it's another case of something what can handle missing icon :D

Ok, I think I know how to fix this, but as temporary solution, open regedit, navigate to `HKEY_CURRENT_USER\Software\SyncthingGTK` and change `use_old_header` value to 1.

**Comment by DerGary** [comment]
Thank You, that's it. It starts now and seems to work normal

**Comment by kozec** [comment]
Glade to hear that. Actual problem will be fixed in next release :)
