### ISSUE TITLE
Error upon startup when `http_proxy` is set.

### ISSUE THREAD

**Issue by dschrempf** [syncthing/syncthing-gtk#173]
Hello,

upon startup, I get the following error when the environment variable `http_proxy` is set:

```
Connection to daemon failed. Check your configuration and try again.
Error message: HTTP proxy connection not allowed
```

However, starting syncthing-gtk with `http_proxy=''; syncthing-gtk` works flawlessly.  I don't think if this is the expected behavior, but to me it seems like a bug.

I am using Arch Linux `Linux arbeitsbaer 4.0.6-1-ARCH #1 SMP PREEMPT Tue Jun 23 14:25:08 CEST 2015 x86_64 GNU/Linux`.

community/syncthing 0.11.11-1 [installed]
    Open Source Continuous Replication / Cluster Synchronization Thing
community/syncthing-gtk 0.7.3-1 [installed]
    GTK3 based GUI and notification area icon for Syncthing

Cheers,
Dominik

**Comment by kozec** [comment]
Unless you are intentionally using http proxy to connect to 127.0.0.1, add `export no_proxy=localhost,127.0.0.1` to whenever you have http_proxy set.

**Comment by dschrempf** [comment]
Yes, thank you, this is correct.  If I correctly set `no_proxy`, I get the expected behavior.  However, the error with subsequent exit might be a little bit too harsh for wrong proxy settings!

**Comment by kozec** [comment]
Dunno... What would you expect it to do as "not harsh" thing if environment is missconfigured in such way?

**Comment by dschrempf** [comment]
I don't know, i just thought that it was crashing, that is why I reported the issue and that's what I mean with harsh ;-)!  Maybe ignore the setting and print a warning?

**Comment by kozec** [comment]
Warning like "Error message: HTTP proxy connection not allowed"? :)

Best think I can imagine is checking for http_proxy variable and displaying additional warning about it being possible cause...
