### ISSUE TITLE
getting error message : Failed to load daemon certificate

### ISSUE THREAD

**Issue by imohan** [syncthing/syncthing-gtk#175]
Hi, I am getting "Failed to load demon certificate" error message and on clicking the close button the whole program exit. I think I can correct the config to fix this. its Windows 7 64 bit

Thank you
regards,

-Inder

**Comment by imohan** [comment]
Started syncthing-gtk-console.exe and I see this error on console my installation on C:\

I StatusIcon    Using backend StatusIconGTK3 (primary)
E Daemon        g-tls-error-quark: TLS support is not available (0)
Traceback (most recent call last):
  File "c:\syncthing-gui\syncthing_gtk\daemon.py", line 323, in _read_config
Error: g-tls-error-quark: TLS support is not available (0)

**Comment by kozec** [comment]
Yeah, HTTPS support is not available on Windows. Only way how to "fix" this is by opening WebUI and disabling it in options (or edit config.xml).
