### ISSUE TITLE
Failed to install inotify handler for ...

### ISSUE THREAD

**Issue by griffg** [syncthing/syncthing-gtk#179]
I recently started using Syncthing GTK (V0.7.4-win32). Sometimes when I start it I get "Failed to install inotify handler for ..." errors. I'm sharing 13 folders (is that too many?). Sometimes it starts okay, other times I get 2 or 3 of these errors.

I'm running 64-bit Windows 7. Should I have a 64-bit version of Syncthing GTK (where can I find a Windows installer for that)?

Thanks much for your help.

**Comment by kozec** [comment]
Installing _inotify_ handler on Windows is certainly problem, as there is no such thing on Windows :)
This may be problem with syncthing-notify that is used for filesystem watching there. @Zillode does that error sounds familiar to you?

@griffg could you, please, provide full log or screenshot of whatever is displaying that message?

**Comment by Zillode** [comment]
@kozec yes, this is a syncthing-notify problem.
@griffg how many files do you have in those 13 folders (approx), i'll try to replicate this.

**Comment by griffg** [comment]
I solved the problem. The folders that had the error were Truecrypt volumes there were not mounted. So, the folders didn't even exist. Silly me.

BTW, the errors were at the top of the main Syncthing GTK window.

Thanks much for your help. Perhaps someone else will benefit from my mistake.

**Comment by kozec** [comment]
Great, bug that solves itself is a good bug :)

**Comment by XenGi** [comment]
I get the same message. Running syncthing on Linux 4.3.3 with 13 shared folders with several GB of data in them. mostly MP3s, videos, documents.

**Comment by kozec** [comment]
@XenGi Sorry, but I can only direct you to [syncthing-inotify](https://github.com/syncthing/syncthing-inotify/issues) bugtracker, as I know very little about it's internals.

**Comment by Zillode** [comment]
There has just been a new release of syncthing-inotify a couple of days ago that guides you on how to fix this problem. Please read https://github.com/syncthing/syncthing-inotify#troubleshooting-for-folders-with-many-files-on-linux
