### ISSUE TITLE
Wish: integration with kde desktop

### ISSUE THREAD

**Issue by fsateler** [syncthing/syncthing-gtk#181]
Hi,

It would be awesome if there was integration with dolphin, like there is with gtk based desktops.

**Comment by kozec** [comment]
My experience with dolphin is nonexistent, but I can give it a try, as long as there is some kind of python bindings for plugins.

**Comment by kozec** [comment]
@fsateler Please, correct me if I'm wrong, but it doesn't looks like Dolphin can display emblems at all. Do you know about any plugin that displays them?

Without this feature, best I can do is context menu with "Synchronize with Syncthing" and _probably_ "Remove directory from Syncthing" options.

**Comment by fsateler** [comment]
Hi @kozec

Thanks for your speedy reply.

There are some integrations for VCS repositories. Check for example this
perforce plugin.
http://kde-apps.org/content/show.php/dolphin-perforce-plugin?content=155919

It is done implementing this interface:
http://api.kde.org/4.x-api/kde-baseapps-apidocs/lib/konq/html/classKVersionControlPlugin2.html

I'm afraid I don't know if it is possible to implement this in python.

On 20 July 2015 at 08:42, kozec <notifications@github.com> wrote:

> @fsateler <https://github.com/fsateler> Please, correct me if I'm wrong,
> but it doesn't looks like Dolphin can display emblems at all. Do you know
> about any plugin that displays them?
>
> Without this feature, best I can do is context menu with "Synchronize with
> Syncthing" and *probably* "Remove directory from Syncthing" options.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncthing/syncthing-gtk/issues/181#issuecomment-122858722>
> .
>



-- 

Saludos,
Felipe Sateler

**Comment by kozec** [comment]
No, it is not. I'll check if it is any reasonable way how to call that from pytho, but I'm afraid that reimplementing entire ST-GTK in C++ would be overkill :)

**Comment by fsateler** [comment]
I think that the correct way to do it would be to implement the Daemon class in C/C++, or embed a python interpreter... neither of which sounds nice :(

**Comment by kozec** [comment]
Well, I searched half of Internet without any success.
As there apparently is not a single dolphin plugin written in python, this really doesn't looks doable, at least for now.

Sorry :(
