### ISSUE TITLE
UI doesn't scale to many devices

### ISSUE THREAD

**Issue by sez11a** [syncthing/syncthing-gtk#182]
If you have many devices, the syncthing-gtk window flows off the bottom of the screen: 

![syncthing-gtk](https://cloud.githubusercontent.com/assets/515497/8802188/bfe5affc-2f8d-11e5-9bf2-5a836347bc9e.png)

(image blurred to obfuscate the actual devices)

Maybe the device list (and folder list) could be in a scrollable section within the window or could take up several columns. 

I'm not a UI guy, so my suggestions on how to fix this should be taken with a grain of salt. :-)

**Comment by kozec** [comment]
Scrollbar around list is not a problem, although I'll have to check if it doesn't breaks default window size on Windows & co.
Are you able to check if change above works for you?

**Comment by sez11a** [comment]
I'm not a Python developer, but I am on Arch-based (Manjaro) Linux, so I believe I have all the developer tools installed. I'll give it a try.

**Comment by sez11a** [comment]
It works! Thanks!
