### ISSUE TITLE
Syncthing GTK shows Stopped Folders as Up-To-Date

### ISSUE THREAD

**Issue by DerGary** [syncthing/syncthing-gtk#184]
Syncthing GTK shows Stopped Folders as Up-To-Date. In my case the folder is stopped because the folder marker of syncthing was missing because i deleted it.

Screenshot:
![Screenshot](https://cloud.githubusercontent.com/assets/4302467/9018103/e6c8b6b8-37db-11e5-8719-9f54151101ac.png)

**Comment by kozec** [comment]
Hmm... Looks like way how daemon reports it changed somewhere in middle. This should fix it.
