### ISSUE TITLE
Full dark theme support

### ISSUE THREAD

**Issue by mhspace** [syncthing/syncthing-gtk#186]
I'm using dark GTK theme (Breeze-dark-gtk in my case) and syncthing-gtk forces light colors in some part of it's UI:
![syncthing-gtk](https://cloud.githubusercontent.com/assets/930015/9033992/f3ff8686-39d4-11e5-91ef-b6689ca5ac8b.png)
![syncthing-gtk_highlighted](https://cloud.githubusercontent.com/assets/930015/9033998/f839ea3e-39d4-11e5-9dab-f1163ef8e596.png)
General text and background colors should not be forced.

BTW, thank you for your good work!

**Comment by kozec** [comment]
This is partially related to #11

Main problem with dark theme is with icons on left side of panels. Those are just plain PNGs and I don't know about any sane way how to render them on dark background.

<img src="http://i.imgur.com/AK2MEmh.jpg">

**Comment by mhspace** [comment]
Got it.
So, I see several resolutions:
 * Use SVG icons, set color of objects in the icons to text color at runtime
 * Use something like "filter: invert(100%)" in HTML for icons for dark themes (I don't know if GTK3 supports this)
 * Use separate icon packs for light and dark themes
Least good resolutions:
 * Use white outline for all icons
 * Use rgb(127, 127, 127) as main icon color (if someone prefer theme with background with this color — this will not work too)

**Comment by mhspace** [comment]
I've just noticed that Web UI uses glyph icons.
All of them are available here at different formats: https://github.com/syncthing/syncthing/tree/master/gui/vendor/bootstrap/fonts
So, if GTK3 supports setting custom font from file (that is not installed in OS) to small portion of text — I think that would be a good solution.
BUT, it seems that glyphicons used in bootstrap are not free. So, it not suits.

Where did you get that png icons?

**Comment by kozec** [comment]
That SVG looks good, I'll check if it is possible to cut it somehow, either in inkscape or in GTK.

**Comment by kozec** [comment]
Showing to get comments from all interested parties :p

![dark](https://cloud.githubusercontent.com/assets/1282500/9367149/ea80cffe-46bb-11e5-86dc-407835d460e6.png)

**Comment by mhspace** [comment]
Great.

**Comment by AudriusButkevicius** [comment]
Nice. Will this be available on Windows too?

**Comment by kozec** [comment]
> Nice. Will this be available on Windows too?

It uses default background color of window to determine if inverted colors should be used, so it should work... As long as there any way to make windows dark on Windows :D

**Comment by kozec** [comment]
So, yeah, it is not :D I added checkbox to 'UI Settings' instead.

**Comment by mhspace** [comment]
<blockquote>As long as there is any way to make windows dark on Windows :D</blockquote>
<blockquote>So, yeah, it is not</blockquote>
Are you sure? What about Alt+Shift+Print Screen?

BTW, /me is Archlinux with KDE user.
