### ISSUE TITLE
 Syncthing-gtk startup on window mode in i3wm 

### ISSUE THREAD

**Issue by toketin** [syncthing/syncthing-gtk#188]
Hi, i've discovered that on my **i3wm session**, *syncthing-gtk* starts always on window mode, even if i set the minimized startup option in settings, or if i try to run with this command in my .i3/config file.

 >  exec --no-startup-id syncthing-gtk -m

What is strange is that on an active i3 session, syncthing-gtk starts always minimized instead, so it's just a issue regarding the startup phase of the WM.

Thanks for your support. Marco

**Comment by kozec** [comment]
I'll probably have to check it, but from description and from sleep being help there, I'd say that ST-GTK starts before whatever is hosting tray icons is ready. If that's the case, minimize to tray is ignored as there would be no way to restore window.

**Comment by toketin** [comment]
I tried with 
> exec --no-startup-id "sleep 2; syncthing-gtk -m"

worked the first time i've logged out from my session, but when i restarted the PC it came back.

**Comment by kozec** [comment]
Ok, after some playing I'm almost positive that this is same problem as Gnome has - autostarted application is started before tray is available.

Can you try setting XDG_CURRENT_DESKTOP for autostarted ST-GTK? If something like

```
exec --no-startup-id "XDG_CURRENT_DESKTOP=GNOME syncthing-gtk -m"
```

works, I can add i3wm to list of exceptions.

**Comment by toketin** [comment]
Ok i can confirm this option makes it working right! Thanks!
