### ISSUE TITLE
Incorrect information is displayed after reconnecting to network after sleep

### ISSUE THREAD

**Issue by cbhushan** [syncthing/syncthing-gtk#189]
This is an issue which I have been encountering after (re)-connecting to a network after a sleep cycle on my laptop. After reconnecting after a sleep, syncthing-gtk shows that some of the shares were disconnected. However, when I checked the syncthing web-gui, it showed everything was connected. I also checked other devices after remotely logging in - they also showed that my laptop was connected. I can also confirm that sync was actually working, i.e. files were being transferred from remote devices. So, I am guessing that syncthing-gtk window is not showing correct information even though syncthing seems to be working.

This was initially discussed on forum and I speculate that what was described in the first post was an effect of the incorrect information being displayed on syncthing-gtk: https://forum.syncthing.net/t/issue-with-syncthing-gtk-on-reconnecting-to-network/5388

Following screenshot was taken after waiting for 10 minutes for syncthing-gtk to update the GUI. If it helps, the only device which is shown as connected in syncthing-gtk (in green) was on the local wifi network (same as the laptop). I could reproduce this with syncthing-gtk v0.7.4.1 (Daemon v0.11.20 and v0.11.18).
![Comparison of information](https://forum.syncthing.net/uploads/default/original/2X/2/2f5f2f3f5e564d87e7556dd856a71d8f38a92249.jpg)

**Comment by kozec** [comment]
That restart mentioned in forum sounds like good reason, I'll check if ST-GTK is aware of it right after I find the way how to replicate problem without getting and suspending actual laptop :D

Just FMI, are values in ST-GTK changing after this happens? Or it stays frozen in last known state?

**Comment by cbhushan** [comment]
It seems to stay frozen.

**Comment by cbhushan** [comment]
To add to my last comment, I noticed that all value do not remain frozen. The values in top right corner (one showing RAM utilization etc) in syncthing-gtk does update/change, eg when there is a file sync going on. However, the devices themselves are grayed out and shown to be disconnected.

**Comment by kozec** [comment]
Problem should be fixed, but fix will work only after patch in syncthing gets into release (so, after next sunday, if I remember correctly). I'll close this issue when that happen.
