### ISSUE TITLE
Custom home folder

### ISSUE THREAD

**Issue by jonada** [syncthing/syncthing-gtk#190]
Would really need the possiblity to provice daemon with a custom home folder.

From http://docs.syncthing.net/users/config.html:
Syncthing uses a single directory to store configuration, crypto keys and index caches. The location defaults to $HOME/.config/syncthing (Unix-like), $HOME/Library/Application Support/Syncthing (Mac), %AppData%/Syncthing (Windows XP) or %LocalAppData%/Syncthing (Windows 7+). It can be changed at runtime using the -home flag.

Thanks!

**Comment by kozec** [comment]
`HOME=/whatever/path/you/need sycnthing-gtk`
or
`XDG_CONFIG_HOME=/whatever/path/you/need sycnthing-gtk`
?

**Comment by jonada** [comment]
Was that a question to me? :-)

I tried setting XDG_CONFIG_HOME as a system environment variable, but it had no effect.

**Comment by kozec** [comment]
> Should have mentioned I'm on Windows.

Yes, that detail was somehow important :D

Problem with changing place where Syncthing saves stuff is that ST-GTK reads Syncthing configuration from there. Also, making this some kind of configuration option and then changing Syncthing configuration dir on the fly would basically wipe-out all Syncthing settings from poor user's perspective.

 I'll check how big problem would be to pass -home parameter, but best I can think of would be hidden configuration value.

**Comment by jonada** [comment]
Don't overdo it, but one idea would be to provide folder path in settings GUI and an option to "Move to new location". So, when changes are made syncthing is shut down, folder is moved, and then syncthing is started again with the new home folder. :-)

**Comment by kozec** [comment]
Sorry, but after some thinking I'm fairly sure that I can't do this without introducing at least one way, how user can break his configuration in process. Advanced user, one who *really* knows what is he doing, should be able to run ST-GTK with modified %LocalAppData% variable.
