### ISSUE TITLE
Unable to update daemon in Program Files folder

### ISSUE THREAD

**Issue by jonada** [syncthing/syncthing-gtk#191]
On Windows I "installed" sýncthing in C:\Program Files\Syncthing. This is protected by administrative rights.

I am now testing to run Syncthing GTK as administrator. I cannot be sure this works until I either get a notification that syncthing.exe is read-only or it a new version has been released and updated.

The problem, however, to run syncthing GTK as administrator is that you have to do it manually. Start when logging in is not run as administrator.

**Comment by kozec** [comment]
It may be simpler to let ST-GTK to download and manage daemon by itself. (Re)move `syncthing.exe` and start ST-GTK. It should display "Cannot invoke daemon" message. Check, if path displayed there is something like `C:\Users\<your.user.name>\AppData\Local\syncthing\syncthing.exe` and click to Download button.

**Comment by jonada** [comment]
Great. That seems to work perfectly. Thanks!

**Comment by illaxaer** [comment]
But Syncthing-GTK download pervious version of Syncthing.
Actual is 0.11.23. Mine was 0.11.20.
After delete "C:\Users\<your.user.name>\AppData\Local\syncthing\syncthing.exe" it again download 0.11.20.
Please reopen issue.

**Comment by jonada** [comment]
@illaxaer, that is a completely different issue. Open a new issue instead saying something like "Not updating daemon to latest released version".

**Comment by kozec** [comment]
Please, don't  :D

That should be already fixed - https://forum.syncthing.net/t/syncthing-gtk-ist-not-updating-binarys/5539
