### ISSUE TITLE
Start on windows start (not only logon)

### ISSUE THREAD

**Issue by jonada** [syncthing/syncthing-gtk#192]
On Windows, would it be possible to start the deamon on Windows startup instead of when logging in?

That would start the syncing after an automatic forced reboot after windows update when you are away from the computer.

BTW, thanks for a great GUI!

**Comment by kozec** [comment]
You can start syncthing daemon as service and ST-GTK should be able to pick that daemon, but autoupdate may cause some trouble.

See http://docs.syncthing.net/users/autostart.html#run-independent-of-user-login

**Comment by jonada** [comment]
Thanks. That seems to be a workaround. Secrity issues noted.

**Comment by jonada** [comment]
Sorry, but this did not work. When activating https and setting a password in the web interface, Syncthing is unable to connect to syncthing (of course...). So, syncthing GTK would require to handle user name and password to syncthing as well as https connections....

**Comment by kozec** [comment]
Ah, yeah. Skip that HTTPS part on Windows. You can set username & password, but API key needs to be generated as well.

**Comment by jonada** [comment]
Ok. Thanks.
