### ISSUE TITLE
Problem with the gui on Windows

### ISSUE THREAD

**Issue by eTernal1911** [syncthing/syncthing-gtk#193]
Hi,

please watch this video and you see the problem.

https://app.box.com/s/vkizuixujw8hygm8ctz753grn5o28ful

**Comment by eTernal1911** [comment]
kozec ?

**Comment by kozec** [comment]
Sorry for late answer, I was pronounced dead for last 5 days...

Disappearing border is old problem that Windows port *had* and I really hoped it is already gone. Can I have versions of everything you have there?

**Comment by eTernal1911** [comment]
Windows 7 Pro
syncthing-gtk v0.7.4.1-win32
syncthing Daemon v0.11.23

**Comment by ChrisLahaye** [comment]
v0.7.4.1-win32 (Daemon v0.11.20) on both Windows 10 laptop and desktop, same problem

**Comment by kozec** [comment]
Eh, don't take W10 into this, that's still unsupported :D

@eTernal1911 Two questions:
1. Are you using 'basic theme' or just something that looks like it? I'm asking only so I can replicate exact configuration.
2. Could you try to downgrade to v0.7.4 and check if problem is present there?

**Comment by eTernal1911** [comment]
The video was a test in a VM with the classic theme, but i have the same problem with aero on my desktop pc.
