### ISSUE TITLE
Inotify watchers don't work reliably

### ISSUE THREAD

**Issue by Schroedingers-Cat** [syncthing/syncthing-gtk#194]
I'm using syncthing-gtk 0.7.4.1 (webup8 repo) with syncthing 0.11.23 on Ubuntu Gnome 15.04.

Inotify does recognize newly created files, newly created folders, deleting and renaming/removing a file. What it fails at however is:
* deleting a folder
* renaming a folder
* all file operations inside a renamed folder

This can quickly cause lots of trouble if the rescan interval is as high as recommended by the syncthing devs when using inotify.

**Comment by kozec** [comment]
Just one question, do you have any non-ascii character anywhere near those folders?

**Comment by Schroedingers-Cat** [comment]
Yes, lots of Umlauts and spaces.

**Comment by jjchico** [comment]
Same behaviour here with same synctning-gtk version on Ubuntu 14.04. All sane file/folder names.
