### ISSUE TITLE
Incorrect version in about dialog 

### ISSUE THREAD

**Issue by cbhushan** [syncthing/syncthing-gtk#196]
Minor issue: I am using the git version #570c391 (tag: v0.7.5.1) and running ``./syncthing-gtk.py -a`` still shows ``v0.7.4.1`` as the version.

**Comment by kozec** [comment]
That's not bug, that's feature :)
On Linux, version is determined using distutils which returns last version that was installed to /usr/lib/python2.7. On Windows, it is simply written to file and kept next to "main.py"

Is it possible to determine exact version if ST-GTK is not installed and runs from git checkout, but I'm not 100% sure if it is worth effort.

**Comment by cbhushan** [comment]
Oh! Is running syncthing-gtk directly from git not recommended? I was running from git to get the latest version.

**Comment by kozec** [comment]
Well, there is no problem in doing that, at least not any that I know about. But you will get confused About dialog.

**Comment by kozec** [comment]
Ok, I made it to display "unknown" when running from git checkout or source.
