### ISSUE TITLE
Fails to start on Ubuntu 15.10

### ISSUE THREAD

**Issue by hotice** [syncthing/syncthing-gtk#198]
In Ubuntu 15.10 Wily Werewolf, syncthing-gtk fails to start with absolutely no output. I also tried to run it with "--window" just in case only the indicator/tray fails to show up but still absolutely nothing. I also tried removing its config files (and Syncthing's) but it didn't change anything. How can I force some debug output ("-d" and "-v" didn't show any output either)?

Ubuntu 15.10 is still in development so I guess it's not a priority to fix it, but maybe you can take a look sometime.

**Comment by kozec** [comment]
If not even -d and -v works, it sounds like python crashing. If it is installed, you can try running it from python, if you feel adventurous enough, but I'll check it with VM when I got home.

```
$ python2
Python 2.7.9 (default, Apr  2 2015, 15:34:55) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import os
>>> 
>>> path = "/usr/share/syncthing-gtk"
>>> from syncthing_gtk.tools import init_logging
>>> init_logging()
>>> from syncthing_gtk import App
>>> App(path, os.path.join(path, "icons")).run([])


```
^^ if it just exits anywhere in that, python gave up.

**Comment by hotice** [comment]
Indeed, it seems that's the case. Here's what I get:
```
$ python2
Python 2.7.10 (default, Jul  1 2015, 10:54:53) 
[GCC 4.9.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> path = "/usr/share/syncthing-gtk"
>>> from syncthing_gtk.tools import init_logging
>>> init_logging()
>>> from syncthing_gtk import App
>>> App(path, os.path.join(path, "icons")).run([])
0
```

**Comment by nbonacchi** [comment]
I'm getting this on 14.04 also:

```bash
:~$ Traceback (most recent call last):
  File "/usr/bin/syncthing-gtk", line 14, in <module>
    from syncthing_gtk.tools import init_logging
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/__init__.py", line 16, in <module>
    from infobox			import InfoBox
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/infobox.py", line 8, in <module>
    from gi.repository import Gtk, Gdk, GLib, GObject, Pango, Rsvg
ImportError: cannot import name Rsvg
```
Changing the import to rsvg does not seem to help...

**Comment by hotice** [comment]
@nbonacchi that's a different issue. Did you install the latest syncthing-gtk update from the PPA (as of today)? You can also manually install "gir1.2-rsvg-2.0" and then it should work.

**Comment by nbonacchi** [comment]
@hotice I thought it might be some incompatibility with synergy (mouse and keyboard sharing package), as I installed it right when I updated st-gtk. I purged it, reinstalled syncthing and syncthing-gtk from scratch on all my boxen and it now works as expected. Having an issue with uPnP but I think I'll open another ticket for that. Thanks

**Comment by kozec** [comment]
Should be fixed now. Only thing I don't understand is why it were doing it only on 15.10, as this is exactly what was supposed to happen according to specs :D

**Comment by licaon-kter** [comment]
Getting this since yesterday on Debian Sid as well, 5bb300f fixes it.

**Comment by kozec** [comment]
Ok, I get the point :P
[I added new release](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.7.6) with all (4) fixes since lats one :)

**Comment by licaon-kter** [comment]
That was useful on 0.7.4.1.

On 0.7.5.1 I now get either that exit 0 or if I edit that to -1 I get:
**> syncthing-gtk -d**
```
D UIBuilder     Enabled: header_bar
D UIBuilder     Enabled: icons_in_menu
D UIBuilder     Loading glade file /usr/share/syncthing-gtk/app.glade
D UIBuilder     Enabled conditions: set([u'icons_in_menu', u'header_bar'])
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node !is_gnome | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'child' by attribute: traditional_header
D UIBuilder     Removed 'child' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed node traditional_header
D UIBuilder     Allowed node traditional_header | icons_in_menu
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 113, in do_startup
    self.setup_widgets()
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 271, in setup_widgets
    self.builder.add_from_file(os.path.join(self.gladepath, "app.glade"))
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py", line 31, in add_from_file
    self.add_from_string(file(filename, "r").read())
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py", line 36, in add_from_string
    self._build()
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py", line 97, in _build
    Gtk.Builder.add_from_string(self, self.xml.toxml("utf-8"))
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 462, in add_from_string
    return Gtk.Builder.add_from_string(self, buffer, length)
GLib.Error: gtk-builder-error-quark: .:50:30 Object with ID edit-menu-button-image not found (13)
(syncthing-gtk:26561): Gtk-WARNING **: Invalid icon size 24
(syncthing-gtk:26561): Gtk-WARNING **: Invalid icon size 24
```

**Comment by kozec** [comment]
@licaon-kter 

Well, it's true that image is not defined, but that shouldn't cause app to crash...

```
(syncthing-gtk.py:4966): Gtk-WARNING **: No object called: edit-menu-button-image
```

Can you, please, check what version of glib and gtk are you using? Either with package manager or run

```
$ python2

from gi.repository import Gtk, GLib
print GLib.glib_version
print Gtk.get_major_version(), Gtk.get_minor_version()
```
in python.

**Comment by licaon-kter** [comment]
```
(2, 44, 1)
```
and
```
3 18
```

**Comment by kozec** [comment]
Weird thing is that on every other distro I have at hand right now, this problem is treated as warning, even with same glib & gtk version. I don't know why should it be different on Debian.

Anyway, I added that image, so gtk builder should be happy now.

**Comment by licaon-kter** [comment]
Replaced files from 1a9341a465 and got this: https://i.imgur.com/OAopdUk.jpg aka missing all that stuff.

**Comment by kozec** [comment]
So, it looks like I'm installing debian :-D

Are you using any specific version of anything, or just Sid & stuff from repos?

**Comment by licaon-kter** [comment]
It's called siduction.org although I'm not sure how much the GCC5 transition has anything to do, things are in flux.

**Comment by kozec** [comment]
@licaon-kter 

So, what's up with that GCC5 transition you mentioned? Because even with Siduction installed and fully upgraded, I can't reproduce that last problem neither with git checkout nor web8upd package.

**Comment by licaon-kter** [comment]
No sure it has anything to do with it, just saying that it's tricky to get my exact software config since the GCC packages are in flux ( plenty of package deletes that I keep postponing ).

Anyway, you're on (2, 44, 1) and 3 18 too, right?

**Comment by kozec** [comment]
> Anyway, you're on (2, 44, 1) and 3 18 too, right?

Yes, I'm. But I don't exactly have chance to replicate problem if I don't know what you are using... Especially because [that error doesn't give any sense](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Widget.html#Gtk.Widget.do_size_allocate) and it really looks like you have some really outdated version of _something_ there.

**Comment by licaon-kter** [comment]
Updated to 0.7.6 as of WebUpd8:

Running like this yields a flashing window for a split second and exit:
**> syncthing-gtk -d**
```
** (syncthing-gtk:5776): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Po send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the networ
/usr/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py:16: PyGIWarning: Gtk was imported without spec '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/lib/python2.7/dist-packages/syncthing_gtk/infobox.py:8: PyGIWarning: Rsvg was imported without specif'2.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GLib, GObject, Pango, Rsvg
D UIBuilder     Enabled: header_bar
D UIBuilder     Enabled: icons_in_menu
D UIBuilder     Loading glade file /usr/share/syncthing-gtk/app.glade
D UIBuilder     Enabled conditions: set([u'icons_in_menu', u'header_bar'])
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node !is_gnome | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'child' by attribute: traditional_header
D UIBuilder     Removed 'child' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed node traditional_header
D UIBuilder     Allowed node traditional_header | icons_in_menu
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 113, in do_startup
    self.setup_widgets()
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 271, in setup_widgets
    self.builder.add_from_file(os.path.join(self.gladepath, "app.glade"))
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py", line 31, in add_from_file
    self.add_from_string(file(filename, "r").read())
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py", line 36, in add_from_string
    self._build()
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py", line 97, in _build
    Gtk.Builder.add_from_string(self, self.xml.toxml("utf-8"))
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 462, in add_from_string
    return Gtk.Builder.add_from_string(self, buffer, length)
GLib.Error: gtk-builder-error-quark: .:50:30 Object with ID edit-menu-button-image not found (13)

(syncthing-gtk:5776): Gtk-WARNING **: Invalid icon size 24
(syncthing-gtk:5776): Gtk-WARNING **: Invalid icon size 24
```

but running through *python2* yields: https://i.imgur.com/3gvtWXr.jpg

**Comment by hotice** [comment]
As a follow up to my initial bug report: now it works fine for me under Ubuntu 15.10, that's why I updated the PPA...

**Comment by licaon-kter** [comment]
Still an issue here, should I open a new one since I'm not actually on Ubuntu 15.10?

**Comment by kozec** [comment]
@licaon-kter Yes, that's sounds like good idea. But there is already 0.7.6.1 version already.

**Comment by licaon-kter** [comment]
Yeah, guess it will be fixed once the PPA gets updated.

**Comment by nbxmike** [comment]
Using the "worst case" tarball and just running syncthing-gtk.py on a Banana Pi (Allwinner A20 based board with SATA interface) running bananian 15.08, I get the exact same error reported by  licaon-kter on Oct 7, 2015.
Not sure if I should start a new bug but will if that would be the proper thing; but, starting here as I can't imagine its not related.

**Comment by kozec** [comment]
@nbxmike You mean
```
GLib.Error: gtk-builder-error-quark: .:50:30 Object with ID edit-menu-button-image not found (13)
```
?

Can you run and copy-paste output of
```
$ python2

from gi.repository import Gtk, GLib
print GLib.glib_version
print Gtk.get_major_version(), Gtk.get_minor_version()
```

on that machine?

**Comment by nbxmike** [comment]
Sorry no, I was referring to

** (syncthing-gtk:5776): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Po send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the networ
/usr/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py:16: PyGIWarning: Gtk was imported without spec '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/lib/python2.7/dist-packages/syncthing_gtk/infobox.py:8: PyGIWarning: Rsvg was imported without specif'2.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GLib, GObject, Pango, Rsvg

Stuff, but I will capture the exact terminal output later today, I am not at the same location as the machine at the moment.  

To confirm, no need to create a new bug, this is where to post the errors?

**Comment by kozec** [comment]
> To confirm, no need to create a new bug, this is where to post the errors?

You can create new one, considering that you are using different distro, architecture and experiencing bug that should be already fixed, I'd guess reason will be different :)
