### ISSUE TITLE
Integration with Nautilus in Gnome 3

### ISSUE THREAD

**Issue by fipm** [syncthing/syncthing-gtk#202]
I installed syncthing-gtk in Arch using the AUR package together with python2-nautilus as optional dependency, however I see no integration happening. Other extensions like nautilus-dropbox are working fine. Any suggestions?

**Comment by kozec** [comment]
What package? I don't see any in AUR.

If you were able to enable integration in GUI, dependency part should be ok. Try running nautilus from terminal and check if there is any error displayed.

```
$ nautilus

(nautilus:9179): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
I SyncthingPlugin Initializing...
I SyncthingPlugin Initialized.
```

... is what it displays normally.

**Comment by fipm** [comment]
Sorry, my bad, I meant syncthing-gtk from the arch community repo. Running nautilus from cli does not throw any error, but the plugin is not initialised either. the nautilus-dropbox plugin is instead initialised:

$ nautilus

Initializing nautilus-dropbox 2015.02.12

**Comment by kozec** [comment]
AFAIK, Dropbox is not python extension.

Can you check if this command outputs same thing on your machine?

```
$ cat ~/.local/share/nautilus-python/extensions/syncthing-plugin-nautilus.py
#!/usr/bin/env python2
"""
Nautilus plugin for Syncthing-GTK
See syncthing_gtk/nautilusplugin.py for more info
"""

from gi.repository import Nautilus
from syncthing_gtk import nautilusplugin

NautilusExtensionCls = nautilusplugin.build_class(Nautilus)
```

**Comment by fipm** [comment]
I don't have neither the file nor the directory in my home. Creating it and copying syncthing-plugin-nautilus.py from /usr/share/syncthing-gtk/ does make nautilus initialise the plugin.

**Comment by kozec** [comment]
Ok, so something went wrong when you enabled it... Can you try to run `syncthing-gtk -d` from terminal and check if there is anything interesting outputted when you try to enable intervention in ST-GTK's ui settings?

**Comment by fipm** [comment]
I am sorry, I don't understand what you would like me to enable in the UI settings.

**Comment by kozec** [comment]
Well, it's probably problem when user can't find that menu even on platform for which it was designed for, but that's not for me to decide :D
