### ISSUE TITLE
Accentuated characters into user path seems to not work (W10 X64)

### ISSUE THREAD

**Issue by bambooLoutre** [syncthing/syncthing-gtk#203]
My user folder has accentuated characters (C:\Users\Jérôme )
It seems that syncthing GTK doesn't handle it well and tries to to something with C:\Users\J??r??me.
Impossible to complete first wizard.

BTW synthing only works perfectly.

**Comment by kozec** [comment]
Sorry, but this is OS problem. ST-GTK gets treated as legacy (ansi?) application and every filename is converted to whatever your codepage setting is. There is probably no way how to convert that back to unicode that ST-GTK uses, nor to pass unicode strings back to Windows, as it will try to read them as strings in cpXYZ.

Rest may work if you skip wizard, but I can't give any guarantee for that.
