### ISSUE TITLE
Windows installer ? :'D

### ISSUE THREAD

**Issue by Technowix** [syncthing/syncthing-gtk#205]
Hey, when the windows installer for the lastest version will be out ? <3
Thank a lot for your work !

**Comment by kozec** [comment]
[Right now](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.7.6) :)

**Comment by Technowix** [comment]
Thank ! :)

**Comment by chucic** [comment]
Hi @kozec, using this issue to ask you for windows installer for new pre-release, so I could test it and polish translation a little...

**Comment by kozec** [comment]
@chucic No problem, but only as archive, I'm still trying to get it translatable *and* installable at once.

[syncthing-gtk-v0.7.6.1-11-gb28a15f-win32.7z](http://www.kozec.com/syncthing-gtk-v0.7.6.1-11-gb28a15f-win32.7z)

You can add locale files to "locale" dir, but you'll need something what can generate "mo" files.

**Comment by chucic** [comment]
Thanks!
One think I noticed: This should include all translation I made today, right? Because text in dropdowns (versioning, compression, process priority) is still english for me...

**Comment by kozec** [comment]
@chucic Yes, it should. Rest of ui is translated? If that's the case, I have vague idea where problem is and it's not on your side.

**Comment by chucic** [comment]
Yes, rest is all translated (at least all I can see, I'm on windows and I guess it's not showing me text related when running on linux).
