### ISSUE TITLE
upload to pypi

### ISSUE THREAD

**Issue by FlorianLudwig** [syncthing/syncthing-gtk#206]
This should be as simple as this:

1. register on pypi.python.org
2. run ```python setup.py sdist regist```

**Comment by kozec** [comment]
And why would I want do to that?

**Comment by FlorianLudwig** [comment]
pypi is the standard way of distributing python software.  It is a better option than

> download latest tarball, extract it and run syncthing-gtk.py.

as it `scripts` and `packages` get setup.  And (if added to the setup.py) dependencies are getting installed too.

**Comment by kozec** [comment]
So it basically does what package manager should... I'm sorry, but currently I'm fully content with having to remember just 2 packagings every time I do a release :)

**Comment by nvllsvm** [comment]
I'll take care of this: https://pypi.python.org/pypi/syncthing-gtk/v0.9.3

**Comment by nvllsvm** [comment]
I'll take care of this.

**Comment by nvllsvm** [comment]
Done.

https://pypi.python.org/pypi/syncthing-gtk
