### ISSUE TITLE
crash at startup on fedora 23+ with new GLib/Gtk (from gnome-3.18)

### ISSUE THREAD

**Issue by decathorpe** [syncthing/syncthing-gtk#210]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/app.py", line 113, in do_startup
    self.setup_widgets()
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/app.py", line 271, in setup_widgets
    self.builder.add_from_file(os.path.join(self.gladepath, "app.glade"))
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/uibuilder.py", line 31, in add_from_file
    self.add_from_string(file(filename, "r").read())
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/uibuilder.py", line 36, in add_from_string
    self._build()
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/uibuilder.py", line 97, in _build
    Gtk.Builder.add_from_string(self, self.xml.toxml("utf-8"))
  File "/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py", line 462, in add_from_string
    return Gtk.Builder.add_from_string(self, buffer, length)
GLib.Error: gtk-builder-error-quark: .:31:30 Object with ID edit-menu-button-image not found (13)
```

**Comment by somasis** [comment]
I hit this issue too, it seems to be fixed in the current git master. I haven't bothered to track down whatever fixed it though.

**Comment by kozec** [comment]
It's fixed by 1a9341a465e80719131a5c8da585a6025212305c . But since there was some change in Fedora and there is no longer possible to install packages from OBS there ( https://github.com/syncthing/syncthing-gtk/issues/207#issuecomment-145684978 ), there was no real reason to create new release with it.

**Comment by kjw** [comment]
Can we get a release out including this? Arch currently has a package with this stop stopper start up bug.

**Comment by kozec** [comment]
@kjw [Here you are.](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.7.6.1)

I'd be glad If someone could confirm that it is installable at least on Fedora _without_ /bin mess.

**Comment by kjw** [comment]
@kozec Many thanks!

**Comment by decathorpe** [comment]
I can confirm that the bug has been fixed in version 0.7.6.1, many thanks!
PS: As a result, syncthing-gtk is in my copr repository again (decathorpe/syncthing), so there are working rpm packages for f22, f23, f24 available from there.

**Comment by kozec** [comment]
@decathorpe 

> PS: As a result, syncthing-gtk is in my copr repository again (decathorpe/syncthing), so there are working rpm packages for f22, f23, f24 available from there.

Great, thanks. Can I add link to it to readme, at least until OBS problem gets solved?

**Comment by decathorpe** [comment]
@kozec 
yeah of course
https://copr.fedoraproject.org/coprs/decathorpe/syncthing/
the new st-gtk build is already online.

**Comment by kozec** [comment]
> yeah of course

Ok, thanks :)

**Comment by p2004a** [comment]
On my Debian I'm using `deb http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu vivid` repo and unfortunatelly I'm still affected by this bug.

**Comment by kozec** [comment]
> On my Debian I'm using deb http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu vivid repo and unfortunatelly I'm still affected by this bug.

What version?

**Comment by p2004a** [comment]
Syncthing-gtk 0.7.6 and Debian stretch (testing)

**Comment by kozec** [comment]
> Syncthing-gtk 0.7.6 and Debian stretch (testing)

So you are version below that one, where problem was fixed...

**Comment by p2004a** [comment]
It helped. Great! Thank you.
