### ISSUE TITLE
Ability to run Syncthing-GTK as an portable installation

### ISSUE THREAD

**Issue by TomTheDragon** [syncthing/syncthing-gtk#211]
I really like Syncthing-GTK but the one feature i really miss, is the ability to run Syncthing-GTK as an portable installation.
I would like to put a installation on my USB stick, to sync my data while i am on the go.

**Comment by kozec** [comment]
Running is possible, in theory, but I'm not sure if it can work. Imagine following:

- USB stick is inserted to PC A, mounted as e:\
- New directory with path e:/data is added to syncthing
- USB stick is moved to PC B, mounted as f:\
- e:/data is no longer available, or, even worse, points to some completely different directory.

What should or can be done to avoid such mess?

**Comment by TomTheDragon** [comment]
Thats not really a problem, i could fix it by simply removing the full path information.
For example:
You have Syncthing in "e:\Syncthing" and your folder is "e:\Syncthing\data", Syncthing will save the path as "e:\Syncthing\data" but you simply can open the "config.xml" and remove the "e:\Syncthing\" from the folder path, it then will automatically look for a folder with the name "data" after the folder where is Syncthing running from.
I already could run it like this with the normal Syncthing because you can change where it saves the DB with the parameter "-home" (for example: "syncthing.exe -home=data").
With Syncthing-GTK, it seems to be forced to use the user folder as storage.

**Comment by kozec** [comment]
So, if I understood correctly, letting ST-GTK to understand and pass -home parameter would suffice?

**Comment by TomTheDragon** [comment]
Well.. it would be nice if we could change the home file for Syncthing and Syncthing-GTK over a command line parameter or something like that.
..or maybe just a parameter, this also could be done simply with a file named "portable", would look a bit more clean because you dont have to make a cmd/bat file to use a command line option at start, to let Syncthing-GTK know that it have to save all its settings in the same folder its running from and then an option directly in the GUI where you edit the folder where Synthing is saving its data to.
There are many ways this could be done i think.

**Comment by kozec** [comment]
> Well.. it would be nice if we could change the home file for Syncthing and Syncthing-GTK over a command line parameter or something like that.

That can be done simply by setting %LOCALAPPDATA% environment variable, but making executable that does it automatically is not problem. But allowing to change Syncthing config directory from GUI is bad idea, imho, as doing so will effectively clear user settings. Advanced user knows how to do that without gui and non-advanced one would probably not like the result.

2nd problem is ST-GTK configuration, as that is currently saved to registry. But that's solvable.

By the way, is it expected to move "portable" application from 64 bit to 32 bit machine without problems?

**Comment by TomTheDragon** [comment]
I think a good idea would be to simply ask the user on the first start, if he wants an portable installation. It then could create a file with all the settings Syncthing-GTK needs next to the main executable.
So if the file exists=read the settings and run in portable mode, if the file dont exists=run in the standart mode.
This also would it maybe make a bit simpler to convert a installation to a portable one and/or back again, for a bit more experienced user.

I think the most windows systems are on 64bit by now but the user could just use the 32bit version then.

**Comment by kozec** [comment]
> I think a good idea would be to simply ask the user on the first start, if he wants an portable installation. It then could create a file with all the settings Syncthing-GTK needs next to the main executable.

That's not gonna work. Normal user can't write to /Program Files/ , so offering portable mode like that would basically offer way to run and way to crash.

What can be done is executable or batch file installed alongside with normal one, probably with some additional error message explaining that you have to copy everything to place where you can write in.

**Comment by TomTheDragon** [comment]
But you are not running it from the /Program Files/ folder when youre in portable mode, this would not make that much sense, as a portable app.

That would be an nice idea too ;)

**Comment by kozec** [comment]
Ok, you can try [this build](https://www.dropbox.com/s/t2xzam3vnnrvyle/syncthing-gtk-dfa5aaa-win32.zip?dl=0) with "portable" executable. It stores everything in `./data` directory, so far without any check if it's writable.

But I'm still unsure about merging it to main branch, at least until some method preventing users from moving to another machine and blowing up entire repository with different folder on same path is invented...

**Comment by TomTheDragon** [comment]
Nice one!
It seems to work and i think the console window will be gone later so its just there for debugging i assume ;)
I tested a new ID and i also tested my current one, both did work fine.

The only problem i found so far were the error massages in the console window.
This right here is the first one:

No handlers could be found for logger "tools.py"
I StatusIcon    Using backend StatusIconGTK3 (primary)
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Es konnte kein
e Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.
 (0)

and this one repeats over and over again after the first one: 

Traceback (most recent call last):
  File "c:\syncthing-gui\syncthing_gtk\daemon.py", line 387, in _rest_connected
Error: g-io-error-quark: Could not connect to 127.0.0.1: Es konnte keine Verbind
ung hergestellt werden, da der Zielcomputer die Verbindung verweigerte. (0)
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Es konnte kein
e Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.
 (0)

**Comment by kozec** [comment]
Yes, console window is there only temporally. And those errors are expected, they are printed until Syncthing daemon becomes active (if google translated them correctly)

**Comment by go2null** [comment]
This seems to be included in [v0.8.2](https://github.com/syncthing/syncthing-gtk/commits/v0.8.2), however, it is not mentioned in the [Release Notes](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.8.2), nor is `syncthing-gtk-portable.exe` present when installed using `SyncthingGTK-v0.8.2-win32-full-installer.exe`.

Could someone please confirm whether *Portable Mode* is available in v0.8.2 and if so, how to use it. (I do see an option to specify the `syncthing.exe` in *UI Settings > Advanced*.)

NOTE:  [PortableApps](http://www.portableapps.com/development) has a pretty good infra for portable apps.

**Comment by kozec** [comment]
Making 3rd executable for same thing seemed too crazy for me, so I redone it as '--portable' argument which does same thing. And it's mentioned in [Relase Notes for 0.8.1](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.8.1)
You can create shortcut with `syncthing-gtk.exe --portable` as target, or .bat file with same thing.

**Comment by NIXOYE** [comment]
@go2null @kozec so is a portable version possible cross platform with Linux?

**Comment by kozec** [comment]
@NIXOYE 

You can just extract source tarball and run `./syncthing-gtk.py` on Linux. But it's still bad idea.
