### ISSUE TITLE
Unicode Error During First Start On Windows

### ISSUE THREAD

**Issue by vladipus** [syncthing/syncthing-gtk#212]
I have a Russian version of Windows 7 64 bit with an account named also in Russian. Getting the following error during the first start of the app:

![2015-10-22 13_21_56-getting started syncthing v0 11 documentation](https://cloud.githubusercontent.com/assets/468323/10662880/0541d064-78c0-11e5-9805-a8f32ccb45ca.png)

**Comment by vladipus** [comment]
Also it was not able to detect the previous configuration from original Syncthing (without GUI).

**Comment by kozec** [comment]
Yes, this is Windows limitation. AFAIK, it should be possible to copy syncthing.exe to that location manually and use ST-GTK without wizard, but writing to that kind of path simply doesn't work.

Also related: #97 #136

**Comment by vladipus** [comment]
Are you sure you are handling unicode paths in Python correctly?

**Comment by vladipus** [comment]
Perhaps let user choose a custom path instead?

**Comment by kozec** [comment]
> Are you sure you are handling Unicode paths in Python correctly?

Only if it were that easy :)

![win](https://cloud.githubusercontent.com/assets/1282500/10673307/65ba5d8c-78f5-11e5-82ae-d0f43e078a66.png)
\*just windows things\* :smile: 

Simply put, I have yet to find any way how Python can write *anywhere* in such configuration. But I'm open to any suggestions or patches.

**Comment by vladipus** [comment]
You could just detect the issue, and recommend a user to store files somewhere else. This would be the easiest thing to do, isn't it?

**Comment by kozec** [comment]
> You could just detect the issue, and recommend a user to store files somewhere else. This would be the easiest thing to do, isn't it?

Yes, but I can't really let him to choose where using UI, as that would result in very same problem if he choose any folder inside his home directory.

**Comment by kozec** [comment]
I *think* I managed to fix at least that part about not detecting the previous configuration from Syncthing. You can try [this build](https://www.dropbox.com/s/nj9vzqm1lkmngdg/SyncthingGTK-v0.7.6.1-2-g64e435f-win32-installer.exe?dl=0) and probably report back how far it can work :)

**Comment by vladipus** [comment]
Got this now)
![2015-10-23 11_35_36-](https://cloud.githubusercontent.com/assets/468323/10688071/4401ea54-797a-11e5-9f09-572a4e944afd.png)

**Comment by kozec** [comment]
What the... :D

Try to extract this ... [exe.win32-2.7-g64e435f.zip](https://github.com/syncthing/syncthing-gtk/files/19199/exe.win32-2.7-g64e435f.zip.docx) ... over installation directory. It contains *all* libraries, hopefully including one you are missing. Also, remove ".docx" from extension.

**Comment by vladipus** [comment]
Stuck at this now:
![2015-10-23 12_12_34-syncthinggtk](https://cloud.githubusercontent.com/assets/468323/10688787/6d197c86-797f-11e5-9cb4-bdaef8dc0b7a.png)

**Comment by vladipus** [comment]
Restarted the app. Now loads)) The previous config was successfully loaded. Did you manage to figure out how to deal with Unicode userdir?

**Comment by vladipus** [comment]
> Yes, but I can't really let him to choose where using UI, as that would result in very same problem if he choose any folder inside his home directory.

You could issue a warning, checking for the existence (write-ability) of the folder, after the user has chozen a new dir.

**Comment by kozec** [comment]
> You could issue a warning, checking for the existence (write-ability) of the folder, after the user has chozen a new dir.

But user normally can't write anywhere but in his home directory, so that would be only more annoying way how to male saving impossible anyway :D On other hand, running syncthing *before* should work most times, because without 1st run wizard, ST-GTK doesn't store any files. Configuration is in registry.
