### ISSUE TITLE
Feature: Package For Debian

### ISSUE THREAD

**Issue by vladipus** [syncthing/syncthing-gtk#213]
I saw packages for Ubuntu, but not for Debian systems. That would be cool to have native Debian packages.

**Comment by kozec** [comment]
Shouldn't be Ubuntu package installable on Debian as well?

**Comment by vladipus** [comment]
How to match distros? We have other names. 'jessie' is current stable for ex.

**Comment by nosliwneb** [comment]
Sometimes you can get away with installing an ubuntu package on a debian system, but it's not something you want to do if keeping a stable system is important to you.

**Comment by kozec** [comment]
OBS supports debian since this issue was originally opened, so I it should be possible to add it there.

**Comment by kozec** [comment]
(done for week or so, forgot to close the issue)
