### ISSUE TITLE
notifications showing even when ignored

### ISSUE THREAD

**Issue by acidicX** [syncthing/syncthing-gtk#214]
Hi,

the "unkown device is trying to connect" notification is showing even when X'ed in the ST-GTK GUI...
Only when I click ignore on the web interface the notifications stop.

Cheers,
Carsten

**Comment by kozec** [comment]
So, problem is that there is no "ignore" button there? Frankly, I never thought it'd be needed, but I can add one.

**Comment by acidicX** [comment]
I thought the "X" in the ST-GTK GUI is equal to ignore (as you said in #166)?
Also, the notification does not pop up in the UI itself. It only shows again and again as a desktop notification.

**Comment by kozec** [comment]
That was long time ago, before I learned that message can reappear :)

**Comment by acidicX** [comment]
great :+1: thanks for the work!
