### ISSUE TITLE
Improvement of the strategy that is used to store application related files under Windows

### ISSUE THREAD

**Issue by gnotaras** [syncthing/syncthing-gtk#215]
Hi,

Thanks for this great software. I'd like to point out that under Windows all files are stored under `C:\Users\USERNAME\AppData\Local\syncthing\`. While this is fine for storing the executable, the log file and the index, it is not the ideal location for the configuration files and the keys. Storing the latter under `C:\Users\USERNAME\AppData\Roaming\syncthing\` would make more sense and would be more efficient regarding the users' backup strategy. Although I'm no Windows expert, AFAIK `C:\Users\USERNAME\AppData\Local\` is not meant to be used for configuration files.

Thanks in advance,
George

**Comment by kozec** [comment]
This would be probably better addressed as Syncthing, not Syncthing-GTK issue, but I can tell right away that it's not a good idea.

`Appdata/roaming` is part of roaming profile and it's synchronized between machines in Windows domain. That means that you may end with two or more machines with same Syncthing configuration, including device ID and keys. That sounds like big mess and good way how to lose data, imho.

**Comment by gnotaras** [comment]
Hi kozec,

Yeap, I agree, this is machine specific data and, after a second thought, what I suggested does not seem like a good idea.

I submitted this report while revising my backup strategy. I will now close this issue.
