### ISSUE TITLE
Showing wrong status info for disconnected devices in device list, v0.7.6.2

### ISSUE THREAD

**Issue by chucic** [syncthing/syncthing-gtk#216]
Testing pre-release, my device list shows "connected" status for disconnected devices in device list. Also, in info about this device it shows "disabled" for discovery, although it is clearly running, because I can connect to both local and remote devices.

**Comment by kozec** [comment]
Are you using prerelease of Syncthing 0.12?

**Comment by chucic** [comment]
Yes, currently latest (v0.12.0-rc6).

**Comment by kozec** [comment]
> Yes, currently latest (v0.12.0-rc6).

Then it's expected behavior, locales branch is based on 0.11-supporting version. Everything else should work, but states are represented different between Sycnthing 0.11 and 0.12.

**Comment by chucic** [comment]
Ok, closing. I assumed that everything should work, since release page says "for testing with 0.12" ;-)
