### ISSUE TITLE
Open WebUI with webbrowser module should use xdg-open on Linux

### ISSUE THREAD

**Issue by licaon-kter** [syncthing/syncthing-gtk#219]
Pressing *Open Web interface* tries to open a page to: `openurl%28https//127.0.0.1:8001)`

Running `python2 -m webbrowser -t "http://www.python.org"` opens a page to  `openurl%28http//www.python.org,new-page)`

Apparently it's this [bug](https://bugs.python.org/issue23262)

*xdg-open* works ok

Any chance to use a workaround like that?

> if os.name == 'posix' and not platform.mac_ver()[0]:
>       with open(os.devnull, 'wb') as nul:
>            subprocess.Popen(['xdg-open', request_url], stdout=nul, stderr=nul)
>    else:
>        webbrowser.open_new_tab(request_url)

**Comment by kozec** [comment]
I see 3 problems here:

1. xdg-open is kinda standard, but not granted to have on Linux
2. but if xdg-open is present, webbrowser module uses it

```
$ head -4 /usr/bin/xdg-open 
#!/bin/sh
echo xdg-open called $@
#---------------------------------------------
#   xdg-open

$ python2 -c "import webbrowser; webbrowser.open('http://test.org')"
xdg-open called http://test.org
Created new window in existing browser session.

$
```

\3. This is basically workaround for bug in Firefox. Why and why here?

**Comment by licaon-kter** [comment]
Ok so this is an issue with Opera 34 apparently, I tested again but with other browsers ( Firefox, Vivaldi ) set as default and all is ok there.

Sorry to bother you.
