### ISSUE TITLE
Version info for devices does not show.

### ISSUE THREAD

**Issue by kisolre** [syncthing/syncthing-gtk#220]
0.8-win32 does not show syncthing version for connected devices, web interface shows them ok.
![syncthing-gtk_0 8](https://cloud.githubusercontent.com/assets/15333315/11057113/16b8d718-8791-11e5-8627-ae11e9029e22.jpg)

**Comment by Coeur-Noir** [comment]
Same here in linux-ubuntu 14.04 with syncthing daemon 0.12.2 and syncthing-gtk 0.8
