### ISSUE TITLE
Crash on startup (ubuntu 14.04)

### ISSUE THREAD

**Issue by Coeur-Noir** [syncthing/syncthing-gtk#221]
Hello,

When I log in into my one session where syncthing is used,

syncthing-gtk automatically starts - ok - and then immediatly triggers an apport-gtk windows about crash (although I can't see this crash and syncthing *looks* to work fine…)

![capture du 2015-11-10 10 42 13](https://cloud.githubusercontent.com/assets/1895947/11059681/54edbbe8-879b-11e5-9105-e46d3541700b.png)

I have this "crash" problem on startup only on one out of my three machines running syncthing + syncthing-gtk, all 3 are ubuntu 14.04

**Comment by Coeur-Noir** [comment]
And it's not only on start-up but each time syncthing deamon is started (or re-started).

**Comment by kozec** [comment]
Just an theory; You have ST-GTK starting twice, first one starts as expected, 2nd just pings already running instance and exits, what appport interprets as crash.

If that's not a case, try to get at least traceback an procstatus from that report and post them somewhere.

**Comment by Coeur-Noir** [comment]
mardi 10 novembre 2015, 10:41:24 (UTC+0100) crash report /var/crash/_usr_bin_syncthing-gtk.1002.crash detected
mardi 10 novembre 2015, 10:43:34 (UTC+0100) crash report /var/crash/_usr_bin_syncthing-gtk.1002.crash detected
mardi 10 novembre 2015, 11:28:58 (UTC+0100) crash report /var/crash/_usr_bin_syncthing-gtk.1002.crash detected

http://pastebin.com/y6i5rqnf if of any interest ?

If syncthing-gtk starts twice : 
- why now ?
- how make it start only once ?

**Comment by kozec** [comment]
Sooo... Discard everything I said before :D From that pastebin:

>    File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 1282, in rescan
>     self._rest_post("db/scan?folder=%s&sub=%s" % (folder_id, path_enc), {}, lambda *a: a, on_error, folder_id)
> NameError: global name 'on_error' is not defined

and 

> Title: syncthing-gtk crashed with NameError in rescan(): global name 'on_error' is not defined

is related to #217 and already fixed. What I don't understand is why apport is reporting it as crash.
ST-GTK keeps running, doesn't it?

**Comment by Coeur-Noir** [comment]
« Title: syncthing-gtk crashed with NameError in rescan(): global name 'on_error' is not defined » already appeared on the screenshot ;-)

Yes ST-GTK is still running.

I just got one file out of sync I don't know why for the moment, error message is : 
« peers who had this file went away, or the file has changed while syncing. will retry later »
and indeed I can't find that file anywhere I probably deleted it, around the time I also updated to newer syncthing daemon and ST-GTK…

**Comment by kozec** [comment]
Ok, i'm going to blame it on appreport :) Real problem should be fixed anyway.

**Comment by Coeur-Noir** [comment]
Should be ?

Do you mean in a next release of ST-GTK ?

(what is surprising for me is I have this problem only with one of my three ubuntu 14.04 pc - maybe there's just some "cleaning-up" to do on that machine ?)

**Comment by Coeur-Noir** [comment]
is related to #217 and already fixed. What I don't understand is why apport is reporting it as crash.
ST-GTK keeps running, doesn't it?

Well it's still running, with open window, as if I had clicked on the notification/tray icon.
