### ISSUE TITLE
Update version of syncthing-inotify

### ISSUE THREAD

**Issue by TeutonJon78** [syncthing/syncthing-gtk#223]
Current syncthing-gtk is still running a hardcoded 0.6.3 syncthing-inotify which is from May 24. Several versions have been released since up to 0.6.7.

Perhaps it would be a good idea to have the version not be hardcoded, and then people could update manually as well, or have it pull updates directly from github like it does for the main syncthing binary.

**Comment by kozec** [comment]
You can manually replace executable in /program files/syncthing-gtk. Automating is little problematic, as ST-GTK doesn't normally have write access to that location.

But I'll add upgraded binary to next release.

**Comment by TeutonJon78** [comment]
The only problem with self replacing is that the code is currently hard coded to look for syncthing-inotify-v0.6.3.exe.

So, even if you put a new version, you'd have to rename it. It would probably be good to just change the included version to just be syncthing-inotify.exe and somehow put the version in one of the "about" windows (if it can be pulled at runtime). Or have a configuration selection for which inotify binary to use. (just like the syncthing binary selection). This would allow using the 64-bit one as well since I assume you bundle the 32-bit one.

**Comment by Zillode** [comment]
syncthing-inotify does not have a runtime API

**Comment by kozec** [comment]
done.
