### ISSUE TITLE
Syncthing binary doesn't get updated automatically since 0.12.5

### ISSUE THREAD

**Issue by seiferflo** [syncthing/syncthing-gtk#226]
Hi.
Synching-GTK is no longer updating automatically Syncthing binary since 0.12.5 version so unless I do an update automatically, my computers are stuck with the binary 0.12.5
Thanks for your feedback.
Flo

**Comment by kozec** [comment]
Should be fixed by [new release](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.8.1).

**Comment by seiferflo** [comment]
Thanks for the super fast fix.

**Comment by seiferflo** [comment]
Hi. I'm reposting here because the same thing happens. 
There is no automatic update of the binary above binary 0.12.12. 
Thanks in advance for a fix.

**Comment by kozec** [comment]
Yeah, I had some trouble testing 0.12.12 on my Windows machine, but it looks like .14 works fine.
