### ISSUE TITLE
Some typo in English - how to fix ?

### ISSUE THREAD

**Issue by Coeur-Noir** [syncthing/syncthing-gtk#232]
Very minor issue ! As I was doing some french translation…

109 & 110 https://www.transifex.com/syncthing-gtk/syncthing-gtk/viewstrings/#en/syncthing-gtkpo/

"bellow" → "below" ?

**Comment by kozec** [comment]
That's pretty good question... I'll fix it [in the source](https://github.com/syncthing/syncthing-gtk/blob/c0216379d440d5ffa493e8e66f418a24cec14cba/syncthing_gtk/finddaemondialog.py#L30), but I have to check how it will reflect to already existing translations 1st.

**Comment by Coeur-Noir** [comment]
A first attempt for French is done.

And now it's done I notice that "device" might have been translated with "appareil" better than "périphérique"…

I guess underscores _ are for keyboard shortcuts ? I've tried not to have same letters for different purposes (but double check welcome)

**Comment by kozec** [comment]
Fixed after good fight with Transifex 8-)
