### ISSUE TITLE
Syncthing icons rendered on files too big to see the content

### ISSUE THREAD

**Issue by piratenpanda** [syncthing/syncthing-gtk#234]
Syncthing (0.8.1 (Daemon v0.12.9))overlays almost cover half of the thumbails and make file discovery really hard.
Look at how big the owncloud sync indicators are:
![syncthing](https://cloud.githubusercontent.com/assets/920721/11992847/08ff32e0-aa2b-11e5-9ddb-f2be68c881ac.png)

Also, maybe I'm missing something, but the syncthing overlays are not telling much, right? No info on if it's synced to all connected devices etc. So whats the point of having them at the moment?

**Comment by piratenpanda** [comment]
Owncloud thumbnail is missing:
![owncloud](https://cloud.githubusercontent.com/assets/920721/11992883/6c469ef6-aa2b-11e5-8269-8c364fd9bb6a.png)

**Comment by kozec** [comment]
Sorry for late answer; I understand the problem, but size of emblem should be decided by file manager, so I'm really curious how can owncloud icon be so small.

And yes, you can't tell if file is present on any other device from overlays. Even syncthing doesn't know that, if I'm not mistaken. Currently, there are three states - file being synchronized, file belonging to repository that has no other device connected (gray icon) and idle icon.

**Comment by kozec** [comment]
Ok, so this:
![owncloud_ok](https://cloud.githubusercontent.com/assets/1282500/12095292/f6513dfa-b30d-11e5-91b5-afd98faefe64.png)
is how owncloud does it. It uses 64x64px icon with small image in the corner. Only problem is that it looks like this:
![not-good](https://cloud.githubusercontent.com/assets/1282500/12095488/3a38705a-b30f-11e5-966c-963155828605.png)
when tere is more than one emblem displayed.
