### ISSUE TITLE
Fails to run on Bananian 15.08

### ISSUE THREAD

**Issue by nbxmike** [syncthing/syncthing-gtk#235]
Running the "worst case" tarball on a Banana Pi (Debian Jesse derived ARM architecture Linux running on an Allwinner A20 based SBC) the program will not execute.  Failure output follows:

```
# ./syncthing-gtk.py
/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
Traceback (most recent call last):
  File "./syncthing-gtk.py", line 11, in <module>
    from syncthing_gtk.tools import init_logging, init_locale, IS_WINDOWS
  File "/home/mike/Downloads/syncthing-gtk-0.8.1/syncthing_gtk/__init__.py", line 35, in <module>
    from wizard				import Wizard
  File "/home/mike/Downloads/syncthing-gtk-0.8.1/syncthing_gtk/wizard.py", line 176, in <module>
    class Page(Gtk.Grid):
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'Grid'
```

Admittedly very similar to issue #198, entered separately as different architecture and distro.

// edited for readability -- kozec

**Comment by kozec** [comment]
Ok, so GTK is running in 2.0 mode for some reason. Can you give me installed versions of GTK libraries and gi bindings? Either from package manager or by running
```
$ python2

from gi.repository import Gtk, GLib
print GLib.glib_version
print Gtk.get_major_version(), Gtk.get_minor_version()
```
in terminal.

I have ST-GTK running on similar board, Odroid C1, so it should work in theory...

**Comment by nbxmike** [comment]
Sorry for the delay - but finally the results:
mike@eowyn:~$ python
Python 2.7.9 (default, Mar  1 2015, 13:48:22) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gtk, GLib
/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
>>> print GLib.glib_version
(2, 42, 0)
>>> print Gtk.gtk_major_version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'gtk_major_version'
>>> print Gtk.gtk_minor_version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'gtk_minor_version'

**Comment by nbxmike** [comment]
Wrong button - just should have been a comment.

**Comment by kozec** [comment]
> AttributeError: 'gi.repository.Gtk' object has no attribute 'gtk_minor_version'


Sooo... basically, you either don't have GTK bindings at all, or have them horribly broken. ST-GTK can't run without GTK, so 1st thing to solve should be getting that 3 lines returning something reasonable.
