### ISSUE TITLE
Window decorations dissapear randomly on windows 7/10

### ISSUE THREAD

**Issue by noidexe** [syncthing/syncthing-gtk#237]
On windows 7 and windows 10, window decorations dissapear randomly. A workaround is right-clicking on the taskbar icon and selecting "Hide window". The decorations reappear when you show the window again. 

I'll tell you if I can find any pattern that triggers the bug. 

The version is v.0.8.1 installed using the win32 full installer (I've just noticed that clicking the "about" option in the app menu doesn't show any window or info).

Daemon version is v0.12.12, Windows (64 bit) "Beryllium Bedbug".
Both machines are running 64-bit versions of win 7 and win 10 respectively.

**Comment by kozec** [comment]
Triggering pattern would be good thing, as I can't reproduce problem no matter what I try...

**Comment by xamindar** [comment]
This happens to me as well. Windows 7.

**Comment by kozec** [comment]
Just FMI, are you using "traditional" or GTK Window header? It can be turned on/off in UI Settings.

**Comment by noidexe** [comment]
In my case it's traditional.

**Comment by seiferflo** [comment]
Same issue on W10x64 & W7x64 using traditional both with GTK-0.8.3 & latest syncthing. 
Looking at kozec's reply, I never tried GTK Window header until now and it looks much better so I'll stay with it and will let you know if that bug happens also.
