### ISSUE TITLE
File not found trying to start daemon

### ISSUE THREAD

**Issue by singpolyma** [syncthing/syncthing-gtk#238]
I'm on Windows XP.  Every time I start syncthingGTK, it give me an error about could not start daemon because file not found.  But then I just click "Save" without editing the path (since the path is correct) and then it starts up just fine (the daemon anyway... app still seems to not show some things, but I can see in the browser the daemon is running and the daemon log window in GUI works).

What might be the problem?  Even if the GUI never works having it autostart without a cmd window would be a big bonus.  Thanks.

**Comment by kozec** [comment]
Windows XP is a problem ;-)

There should be `syncthing-gtk-console.exe` right next to regular exe, can you run it and copy-paste output somewhere?

**Comment by singpolyma** [comment]
I did run that one a couple times and saw no errors in the console output (just, "starting gtk tray ui" or whatever)

**Comment by kozec** [comment]
That's really unusual, ST-GTK should output a lot... Try adding -d (run `syncthing-gtk-console.exe -d`)

**Comment by aphirst** [comment]
I'm getting a similar error on Windows 7, and I thought I ought to post it here before making a new Issue in case it happens to be related. (Let me know if I should instead make a new Issue)

When I start the program on my work machine, I always get (in DE Locale):
```
Problem beim Starten von C:\Program
Das angegebene Modul wurde nicht gefunden.
```
but then clicking OK causes ST-GTK to just continue and ultimately then loads the ST daemon correctly without further intervention.

I'm running the program as a normal user, and if I go into the GUI Settings it seems to nonetheless correctly know that my syncthing.exe is stored at `C:\Users\<username>\AppData\Local\syncthing\syncthing.exe`. I don't seem to be able to massage it to not give me this pointless error each startup, so any feedback would be great - and just let me know if any other information would be useful.

Running ST-GTK `v0.8.2-1-g1830d33-win32` with daemon `v0.12.16`

**Comment by kozec** [comment]
@aphirst That sounds like path to syncthing.exe is stored in some wrong way. Can you tell me what's exact value of registry key `HKEY_CURRENT_USER\Software\SyncthingGTK\syncthing_binary` ?

Seeing how Windows tries to start something in Program Files, maybe it's stored as relative path and expanded wrongly.

**Comment by singpolyma** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12770/12703794/97cb662c-c819-11e5-98da-ff5d4334490e.JPG)
![untitled2](https://cloud.githubusercontent.com/assets/12770/12703795/97d07b4e-c819-11e5-8e7c-360b15bc2479.JPG)

**Comment by kozec** [comment]
Can you try to move syncthing.exe to some place without space in path? Sorry, I really don't have any XP machine around to test this...

**Comment by aphirst** [comment]
@kozec the entry you refer to contains
```
C:\Users\<username>\AppData\Local\syncthing\syncthing.exe
```

but I notice that in the same registry folder, we have the InstallPath key set to:
```
C:\Program Files (x86)\SyncthingGTK
```

Might this be part of the problem? I'll try editing them so they're in agreement...

**Comment by kozec** [comment]
Deleting it will surely not work, but changing it to `C:\Users\<username>\AppData\Local\syncthing\syncthing.exe` should fix the problem. Just to check, is there any space in <username> ?

**Comment by aphirst** [comment]
@kozec Nope, there are no spaces in the omitted "username" portion, and setting the key to it does not make the error go away on subsequent starts.

**Comment by kozec** [comment]
@aphirst And error message still shows "C:\Program" even when path is set to C:\Users... ?

**Comment by aphirst** [comment]
@kozec Exactly.

**Comment by kozec** [comment]
@aphirst That makes no sense whatsoever :(

Can you post screenshot with that error, preferably while running `syncthing-gtk-console.exe` ?

**Comment by aphirst** [comment]
@kozec 
![syncthing1](https://cloud.githubusercontent.com/assets/1735556/12782090/30fd3594-ca79-11e5-8d98-86b3bd68c9f6.png)

No further output is given after you click OK other than some generic stuff about it connecting to my other Syncthing devices across the network.

**Comment by kozec** [comment]
Wow... This is really weird, there shouldn't be anything started using RunDLL from Syncthing-GTK. There are only two things started: `syncthing.exe` and, if enabled, `syncthing-inotify-v0.6.7.exe`, placed right next to `syncthing-gtk.exe`. Can you exit ST-GTK and try to run both programs separately?

**Comment by aphirst** [comment]
@kozec There's no syncthing.exe present in the C:\Program Files (x86)\SyncthingGTK folder, only the inotify executable; it's instead in the %APPDATA% related folder I mentioned above.

**Comment by kozec** [comment]
That's ok, only `syncthing-inotify-v0.6.7.exe` should be placed in Progra Files. Does any error message appears when you start `syncthing.exe` and then `syncthing-inotify-v0.6.7.exe` manually?

**Comment by aphirst** [comment]
@kozec No, if I do that the only messages that appear in either command window are those directly related to connecting to my other Syncthing devices, or directly referencing the shared folders.

**Comment by singpolyma** [comment]
I moved to C:/syncthing/syncthing.exe and there's no change. Daemon starts fine when I hit "save" and also workd fine when started by itself.

**Comment by singpolyma** [comment]
turns out this error is because it can't find the syncthing config file, which is a very confusing error message. Pull request to fix the issue (but not the reporting of the error) sent

**Comment by singpolyma** [comment]
The reason for the confusing error is https://github.com/syncthing/syncthing-gtk/blob/master/syncthing_gtk/app.py#L315 -- not found configuration is invalid, invalid configuration triggers wizard, wizard on XP triggers the "where is the binary" dialog.

**Comment by kozec** [comment]
@singpolyma Thanks, this possibility really didn't occurred to me :( I'll change that message to something more descriptive.
