### ISSUE TITLE
Deamon disconnects from GTK with Syncthing v0.12.16 upgrade on ubuntu (debian?)

### ISSUE THREAD

**Issue by kluppy** [syncthing/syncthing-gtk#239]
v0.12.16 introduced Restart on Debian package upgrade (@calmh)
I really appreciate this because I no longer have to manually restart Syncthing.
However after the restart the local deamon was not recognised by syncthing-gtk
In the attached image the local device is XPS
![screenshot from 2016-01-25 12 19 31](https://cloud.githubusercontent.com/assets/15791666/12541151/5390d0e2-c35e-11e5-9c67-14d4f65bcd39.png)

**Comment by kozec** [comment]
You are running daemon as service I guess? Can you restart ST-GTK and check if is daemon recognized after that?

**Comment by kluppy** [comment]
I had to restart my computer before I could do any testing. After the reboot syncthing-gtk returned to normal.

**Comment by kozec** [comment]
@kluppy And how are you running syncthing? Is it managed as system service, or started by ST-GTK?

**Comment by kluppy** [comment]
I can't remember. I spent some time setting up the system service but I can't be sure now without checking. I will get back to you ASAP.

**Comment by kluppy** [comment]
No it seams I removed the upstart configuration and have ST-GTK as a start up application in gnome.
It starts the daemon if it isn't running. I think I did this because I ended up with multiple instances otherwise.

**Comment by kozec** [comment]
Ok, I see where problem may be...

@calmh is there any chance that new feature ignores STNORESTART variable?

**Comment by calmh** [comment]
Yeah. "STNORESTART" doesn't mean "never restart", it means "don't handle restarts internally".
