### ISSUE TITLE
Notification / french translation

### ISSUE THREAD

**Issue by Coeur-Noir** [syncthing/syncthing-gtk#240]
Hello,

I think I made some mistakes about the notifications.

In fact I've just noticed those notifications with v0.8.2 so while translating I was not really aware of where those words would appear.

So… would you explain me when / in which situation notifications are expected ? And maybe which lines they are in transifex ?

I think I made a confusion between "remote folder" and "local" and some words are missing when notifications says something like « a_number (files) out of b_number (files) have been updated »

Thank you !

**Comment by kozec** [comment]
`%s files were updated on remote device` is displayed after Syncthing pulls files changed on other machine. %s is replaced with number of changed files.

`%(updated)s files were updated and %(deleted)s deleted on remote device.` is same thing, but includes number of files that were deleted, because they were deleted on other machine. %(updated)s is replaced with number of changed files and %(deleted)s with number of deleted files.

Number is always numerical  (7 files deleted, 1 files updated...).

**Comment by Coeur-Noir** [comment]
So…

Is the phrase "remote device" really appropriate ? Isn't it "local" device ?

Notifications inform us about what's happening "locally" on the actual device where they're displayed, am I right ? And give no information about other non-local / distant (remote ?) device(s) 

I try to avoid nonsense in french translation and shorten phrases if possible.

And therefore I wonder if there may be a nonsense in actual english translation ;-)

**Comment by kozec** [comment]
It really is _remote_ device. From my understanding, files are synchronized, so whatever happens, happens on all connected machines. If I edit file at home, it's same file as file on my work computer, so it's edited at my work as well. That message doesn't tells you _"Syncthing changed file XY"_, but _"Something changed file XY from some distant, remote place"_.

Showing where exactly was file changed may be useful, but AFAIK, Syncthing doesn't know it. But I'll check on that.

That notification is really shown only for remote changes. Tracking local changes would probably be possible, but if someone sits behind computer, he knows about them anyway.

**Comment by Coeur-Noir** [comment]
Ok, I understand your understanding ;-) _"Something changed file XY from some distant, remote place"_ so we should keep it simple and short to avoid redundancy : it's all about sync'ing, if there's a change _here_ it's because there has been a change _there_ no need to precise "remote" in the notification. It takes room and adds no information.

I did the modifications on transifex, for french.
