### ISSUE TITLE
Save button disabled

### ISSUE THREAD

**Issue by davidgfnet** [syncthing/syncthing-gtk#241]
Hey!

How the #### do I save my settings!?

https://i.imgur.com/D4NXWPW.png

Thanks

**Comment by kozec** [comment]
You have some invalid setting there, most likely "Syncthing binary location" on "Advanced" page.

**Comment by davidgfnet** [comment]
I tried to delete everything. BTW it's the default config (deleted the json file).

**Comment by kozec** [comment]
Ahem... There is nothing in that field :D

"Syncthing binary location" has to be set to something executable, preferably to actual syncthing binary location. If you absolutely can't set it there, you can put /bin/true there, but that may break something else.

For debugging, just run `syncthing-gtk -d` from console and look for errors or just post everything to pastebin.

**Comment by davidgfnet** [comment]
Great! I didn't know it actually checked for binary path. Yes I installed syncthing in a weird path :D Thanks!
