### ISSUE TITLE
Minimize to tray on startup does not work on MATE desktop

### ISSUE THREAD

**Issue by davidgfnet** [syncthing/syncthing-gtk#242]
So it always comes up as a windows :|

http://i.imgur.com/zvwcWWg.png

I rebooted a couple of times to confirm.

**Comment by kozec** [comment]
Is notification icon visible anywhere? Can you right-click on it and select "hide window" ?

**Comment by davidgfnet** [comment]
Yes the icon is there and everything works as expected.

**Comment by kozec** [comment]
So it can hide itself, but doesn't do that on start? There is small detection code that checks if icon really is  visible and forcibly shows window if icon is hidden, so that may be culprit here.

**Comment by TiZ-EX1** [comment]
This used to be fine on my setup, but this is now broken on XFCE4 as of GTK 3.20.

**Comment by kozec** [comment]
> This used to be fine on my setup, but this is now broken on XFCE4 as of GTK 3.20.

What distro?

**Comment by kozec** [comment]
I'm afraid that there is no sane way how to fix this, so I'll just assume that XFCE and MATE has notification area _always_ visible. Please, don't remove it from your panels :)
