### ISSUE TITLE
Caja & Nemo integration not working

### ISSUE THREAD

**Issue by davidgfnet** [syncthing/syncthing-gtk#243]
Hello,
I can't get integration working on MATE nor Cinnamon (Fedora).
I installed python-caja and python-nemo but it just doesn't happen. I don't see anything suspicious in the debug log and also I checked that .so files are installed there. What else should I check?
Oh and a minor thing, in neither computer I can't get the syncthing icon in the notification area. In cinnamon shows up as an "empty" space in the bar whereas in MATE shows up as a generic icon.

**Comment by davidgfnet** [comment]
Icons are under /usr/share but the log says:
    E Notifications Failed to load icon: gtk-icon-theme-error-quark: «syncthing-gtk-error» icon is not present in the system (0)
On the other computer I see a couple of backtraces regarding datatime (datetime.datetime has no attribute datetime and Failed to parse XXX as time). Datetime is installed and I can do an "import datetime" on the python shell.
Thanks!

**Comment by kozec** [comment]
> On the other computer I see a couple of backtraces regarding datatime (datetime.datetime has no attribute datetime and Failed to parse XXX as time).

This was fixed in 8cfa1733c24820bf1f90cbd36a97e3dce7b0acc6 and should already work in latest release. What version are you using?

**Comment by davidgfnet** [comment]
Oh right, in that laptop I checked out an stable release (0.8.1 I recall). Thanks!
What about the integration issue?

**Comment by kozec** [comment]
Are you able to enable it in settings, or it's greyed out?
In 2nd case, run `syncthing-gtk -d` and open UI settings, it should output what files are missing.

If setting is enabled, try to run Caja from terminal ( `killall caja ; caja` ) and check what log says.

**Comment by davidgfnet** [comment]
It's not greyed out. All of them are greyed out except for nemo (in cinnamon computer) and caja (in mate computer). I'll try to check what caja/nemo say on startup. The synchthing-gtk debug log doesn't really complain about missing stuff or broken things.

**Comment by kozec** [comment]
> All of them are greyed out except for nemo (in cinnamon computer) and caja (in mate computer). I'll try to check what caja/nemo say on startup.

Yes, that's how it should be and so there is nothing to complain about. Problem will most likely be in caja plugin or caja itself.

>  I'll try to check what caja/nemo say on startup.

Please, do.

**Comment by davidgfnet** [comment]
There you go:
```
Traceback (most recent call last):
  File "/home/david/.local/share/caja-python/extensions/syncthing-plugin-caja.py", line 7, in <module>
    from gi.repository import Caja
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 39, in <module>
    raise ImportError(_static_binding_error)
ImportError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
Traceback (most recent call last):
  File "/home/david/.local/share/caja-python/extensions/syncthing-plugin-caja.py", line 7, in <module>
    from gi.repository import Caja
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 39, in <module>
    raise ImportError(_static_binding_error)
ImportError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183

```

**Comment by davidgfnet** [comment]
For nemo I have:

```
Initializing nemo-image-converter extension
sys:1: PyGIWarning: Nemo was imported without specifying a version first. Use gi.require_version('Nemo', '3.0') before import to ensure that the right version gets loaded.
/usr/lib/python2.7/site-packages/syncthing_gtk/notifications.py:16: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/site-packages/syncthing_gtk/infobox.py:8: PyGIWarning: Rsvg was imported without specifying a version first. Use gi.require_version('Rsvg', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GLib, GObject, Pango, Rsvg
I SyncthingPlugin Initializing...
I SyncthingPlugin Initialized.
I SyncthingPlugin Connected to Syncthing daemon

But still I don't see the sync icons ...
```

**Comment by kozec** [comment]
Caja problem looks like conflict with some else plugin - Syncthing plugin doesn't import gobject at all, but it is possible something else does. Do you have any other Caja plugins enabled? Especially some that use GTK2?

For Nemo, where exactly are icons being installed? Is there any `/usr/share/icons/hicolor/64x64/emblems/emblem-syncthing*` file?

**Comment by davidgfnet** [comment]
I disabled all of them. Also tried with all disabled but caja-python.

http://i.imgur.com/7Px8rcL.png

Looks good to me

**Comment by kozec** [comment]
Issue on Cinnamon is not same. That one looks simply like icons are missing, while on Mate, Caja gi bindings are refusing to load. If being in GTK2 app is enough of reason for that, it may be impossible to use Caja plugin on Fedora (i've just tested it on Manjaro and Ubuntu and there is no problem importing gobject and Caja at once.

**Comment by davidgfnet** [comment]
Ok gotcha.
In Cinnamon I'm not able to get it working (not just the tray icon) but the nemo integration. Let's forget about MATE and GTK2, how can I get cinnamon fixed?

**Comment by kozec** [comment]
By checking if icons are correctly installed in  /usr/share/icons/hicolor/64x64/emblems/emblem-syncthing* 
If you have plugin that adds emblems page to properties, you should be able to see all syncthing-related emblems there.

**Comment by davidgfnet** [comment]
It works now, no idea why, I just updated my system :D 
BTW, do I need to install syncthing-inotify if I want my files to be automatically synced? (I disable folder scan every N seconds). Does it integrate with syncthing-gtk or do I have to run it manually?
Thanks a lot!

**Comment by kozec** [comment]
> BTW, do I need to install syncthing-inotify if I want my files to be automatically synced?

Syncthing-GTK has inotify support integrated (not syncthing-inotify, just inotify), so if you have pyinotify installed, you can just check "Monitor filesystem changes" checkbox in folder settings. Ofc, you can use syncthing-inotify as well, it basically does same thing.

**Comment by kozec** [comment]
This should be OK if I understood correctly.

**Comment by davidgfnet** [comment]
Just a gotcha. When it boots, no icon. At some point it will show up (like after suspension). It's very weird, isn't it?
