### ISSUE TITLE
Is it possible to run the windows build from non-windows?

### ISSUE THREAD

**Issue by singpolyma** [syncthing/syncthing-gtk#244]
That would be very useful...

**Comment by kozec** [comment]
In theory, yes. cx_Freeze is multiplatform, NSIS as well, but I'm not sure about pywin32 stuff.

And [build_windows.py](https://github.com/syncthing/syncthing-gtk/blob/master/build_windows.py) copies metric ton of dll's, all from hardcoded paths :) Ofc, there is no problem make those configurable.

**Comment by kozec** [comment]
Sooo... It looks like it's not possible after all. pywin32 is, ofc, not available outside of Windows and it doesn't looks like there is an easy way to build it on Linux. For example, it requires MSVS.

Only left option I can think about is installing all build deps under wine.
