### ISSUE TITLE
Lost in french translation

### ISSUE THREAD

**Issue by fredericseiler** [syncthing/syncthing-gtk#249]
Hi @Coeur-Noir , is it possible to follow the [french translation of Syncthing](https://www.transifex.com/syncthing/syncthing/gui/fr/download/for_use/) to maintain consistency between the two interfaces ("A jour" > "Synchronisé") ?

Thanks !

**Comment by Coeur-Noir** [comment]
Well you're right ! I did not really try to match the two so it will be done…

**Comment by fredericseiler** [comment]
Merci ! (If you need any help...)
