### ISSUE TITLE
Windows 10 Network Location Offline

### ISSUE THREAD

**Issue by driscollw** [syncthing/syncthing-gtk#250]
Windows 10 x64, 
syncthing v0.12.19, Windows (64 bit)
syncthing-gtk v0.8.2-1-g1830d33-win32 (Daemon v0.12.19)

network location shows offline in gtk. Syncthing Web UI shows network location up to date. Network location is accessible and syncs with other devices.

**Comment by kozec** [comment]
Sorry, but what's "network location" ?

**Comment by driscollw** [comment]
If I set a folder to \\Computer\Share\ it shows offline in syncthing-gtk but online with the syncthing web iu.

**Comment by kozec** [comment]
I'm not 100% sure if I understand, but ST-GTK shouldn't really care about paths...
Can you provide screenshot with that difference visible?

**Comment by driscollw** [comment]
![syncthing-gtk](https://cloud.githubusercontent.com/assets/1213941/13223053/cb803d60-d950-11e5-93cb-3dbcecdd4691.jpg)
![syncthing-web](https://cloud.githubusercontent.com/assets/1213941/13223067/d1932ffa-d950-11e5-9468-a425e43d0f6e.jpg)

**Comment by kozec** [comment]
Oh :D

Believe me or not, this is not bug, it's a feature. If all devices that directory is shared with are offline, directory is shown with "Offline" status as well **in ST-GTK**.

You can see on your screenshot that Magazines is shared only with "Fire 7", so as long as "Fire 7" is offline, Magazines will be shown as offline.

That doesn't affect other states, so "Scanning" or "Error" may be displayed if appropriate.

**Comment by driscollw** [comment]
Ah, OK, that makes sense. Explains why Videos and Sync are offline now since my other PC is turned off. Thanks for the clearing this up.

**Comment by kozec** [comment]
Np, I can see how it can be confusing with network paths.
