### ISSUE TITLE
Instant sync not working

### ISSUE THREAD

**Issue by mrbrahman** [syncthing/syncthing-gtk#251]
Syncthing-GTK v0.8.2 (Daemon v 0.12.19)

Somehow I'm not able to get the instant sync to work from my Linux Mint laptop. Sync happens only when Syncthing polls the folder. Checked and installed pyinotify (and also did the test on /tmp folder that's mentioned there), but still does instant-sync not work.

Is there some other setup required?

Thanks!

**Comment by kozec** [comment]
Nothing special beside enabling it. Try to run `syncthing-gtk -d` and check if there is anything interesting logged when file is changed. At least it should log ['File changed something something'](https://github.com/syncthing/syncthing-gtk/blob/master/syncthing_gtk/watcher.py#L118)

**Comment by mrbrahman** [comment]
Thanks. Started using `syncthing-gtk -d`.

Didn't notice anything unusual (no errors etc)
Didn't notice "File changed ... " (when I updated the file)

The only warning I see when I do something on the UI is `(syncthing-gtk:8041): Gtk-WARNING **: Invalid icon size 16`

Should the log show anything when inotify is enabled? (searched in the log for `inotify` and `notify` keywords, and didn't find anything)

I verified again that `pyinotify` is working

    $ python -m pyinotify -v /tmp
    [2016-03-01 15:59:30,894 pyinotify DEBUG] Start monitoring ['/tmp'], (press c^c to halt pyinotify)
    [2016-03-01 15:59:30,894 pyinotify DEBUG] New <Watch wd=1 path=/tmp mask=4095 proc_fun=None auto_add=None exclude_filter=<function <lambda> at 0x7fa97bb2b140> dir=True >
    [2016-03-01 15:59:41,105 pyinotify DEBUG] Event queue size: 128
    [2016-03-01 15:59:41,106 pyinotify DEBUG] <_RawEvent cookie=0 mask=0x2 name=test_file.txt wd=1 >
    [2016-03-01 15:59:41,106 pyinotify DEBUG] <_RawEvent cookie=0 mask=0x20 name=test_file.txt wd=1 >
    [2016-03-01 15:59:41,106 pyinotify DEBUG] <_RawEvent cookie=0 mask=0x2 name=test_file.txt wd=1 >
    [2016-03-01 15:59:41,107 pyinotify DEBUG] <_RawEvent cookie=0 mask=0x8 name=test_file.txt wd=1 >
    <Event dir=False mask=0x2 maskname=IN_MODIFY name=test_file.txt path=/tmp pathname=/tmp/test_file.txt wd=1 >
    <Event dir=False mask=0x20 maskname=IN_OPEN name=test_file.txt path=/tmp pathname=/tmp/test_file.txt wd=1 >
    <Event dir=False mask=0x2 maskname=IN_MODIFY name=test_file.txt path=/tmp pathname=/tmp/test_file.txt wd=1 >
    <Event dir=False mask=0x8 maskname=IN_CLOSE_WRITE name=test_file.txt path=/tmp pathname=/tmp/test_file.txt wd=1 >

Is there anything else I can check? Thanks for your help.

**Comment by mrbrahman** [comment]
However, when I click "Rescan" on the UI, I see the below message (in the log)

    I App           Rescan folder My Mobile Documents
    E Daemon        (HTTPCode(u'HTTP error 400 : ',), u'db/scan?folder=My Mobile Documents', {}, u'My Mobile Documents')

And the folder is not scanned for changes. May be this is related?

**Comment by davidgfnet** [comment]
Same happens to me. Debug flag doesn't show any file changed at all. Lots of "invalid icon size 24" and:
Notify was imported without specifying a version first. Use gi.require_version('Notify') to ensure...
Any ideas?

**Comment by kozec** [comment]
That HTTP/400 sounds like good reason. Does manual rescanning of other folders display similar errors?

**Comment by davidgfnet** [comment]
Well in my case I see no 400 http error

**Comment by mrbrahman** [comment]
@kozec No - clicking "Rescan" on other folders is not showing any error, and any updates are applied to other devices.

However, Instant Sync is not working on those folders as well.

Today, I noticed the below logs when syncthing-gtk was starting up in the debug mode.

    Syncthing-GTK started and running in notification area
    V Daemon        Set refresh interval to 5
    E Daemon        Could not connect to 127.0.0.1: Connection refused
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 408, in _rest_connected
        con = sc.connect_to_service_finish(results)
    GError: Could not connect to 127.0.0.1: Connection refused
    D App           Creating connect_dialog
    V App           Settinig connect_dialog label Starting Syncth
    E Daemon        Could not connect to 127.0.0.1: Connection refused
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 408, in _rest_connected
        con = sc.connect_to_service_finish(results)
    GError: Could not connect to 127.0.0.1: Connection refused
    E Daemon        Could not connect to 127.0.0.1: Connection refused
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 408, in _rest_connected
        con = sc.connect_to_service_finish(results)
    GError: Could not connect to 127.0.0.1: Connection refused

**Comment by mrbrahman** [comment]
**Update**: It looks like I had to enable instant sync by selecting "**Monitor filesystem for changes**"! I hadn't noticed this option before :-) Now, all the other folders sync instantaneously! (Is there a reason why that's not enabled by default? I think there's hardly anyone who would not want instant sync)

For this one particular folder, I removed the folder, and let the other devices introduce it again, ensured "Monitor filesystem for changes" is enabled. Now I see "File changed ... " message, but there's still this `HTTP 400` error

    D Watcher       File Changed My Mobile Documents /home/mrbrahman/Documents (Mob)/TODO.txt > TODO.txt
    E Daemon        (HTTPCode(u'HTTP error 400 : ',), u'db/scan?folder=My Mobile Documents&sub=TODO.txt', {}, u'My Mobile Documents')

Any idea what may be causing this?

@davidgfnet, since you're not seeing the 400 error, see if the "Monitor filesystem for changes" is enabled (on Syncthing-GTK) on your shared folder

**Comment by davidgfnet** [comment]
Can you share an screenshot? Is that a syncthing daemon option or a syncthing-gtk option? In one computer I got it working os it might be I forgot to select that in the other. Thanks!

**Comment by kozec** [comment]
Sorry for late response, I literally tested *everything* else before finally realizing this obvious problem. Anyway, this should get rid of HTTP/400's

@davidgfnet _Monitor filesystem for changes_ is per-folder setting. Right click on folder, select edit, [check this checkbox](http://i.imgur.com/937RerY.png).
