### ISSUE TITLE
Outdated security information

### ISSUE THREAD

**Issue by steelman** [syncthing/syncthing-gtk#254]
The security page mentions D26E6ED000654A3E as the key used for signing package releases. Apparently apt-get reports it is not true. 

~~~
W: GPG error: http://apt.syncthing.net syncthing InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2B9FAE4C37C86D31
~~~

Please provide the current key at https://syncthing.net/security.html

**Comment by kozec** [comment]
I think this may be [Syncthing](https://github.com/syncthing/syncthing/issues), not Syncthing-GTK issue.

**Comment by steelman** [comment]
I have moved this issue to [Syncthing #2839](https://github.com/syncthing/syncthing/issues/2839).
