### ISSUE TITLE
Syncthing-GTK fails to detect tray indicators

### ISSUE THREAD

**Issue by eugenesan** [syncthing/syncthing-gtk#255]
On Ubuntu 16.04 (and probably other distros) Syncthing-GTK fails to detect tray indicators and falls back to classic tray icon (if available).
The reason is new XDG_CURRENT_DESKTOP syntax.
Just starting it with "XDG_CURRENT_DESTOP=Unity syncthing-gtk" solves the problem.

More information is available here:  https://bugs.launchpad.net/ubuntu/+source/syncthing-gtk/+bug/1554878

**Comment by kozec** [comment]
What's XDG_CURRENT_DESKTOP set on problematic version of Ubuntu?

**Comment by eugenesan** [comment]
It's "XDG_CURRENT_DESKTOP=GNOME-Flashback:Unity" but other variants might exist.
The idea is to split the variable contents with delimiter ":" and search for "Unity" to enable indicators/dash support.

**Comment by kozec** [comment]
This should do it.

**Comment by eugenesan** [comment]
Great, thanks.
