### ISSUE TITLE
Syncthing-GTK 0.8.3: UI-settings -> 'Use traditional window header' sometimes ignored

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [syncthing/syncthing-gtk#257]
**What happened, steps to reproduce, and what should happen**: I set the 'Use traditional window header' option and it worked; I reverted the change; I set the option again, such that the program should be back to using the traditional header - yet, it is not.
Version Information

**Version information**

Syncthing Version: v0.8.3 (Syncthing -GTK) / 0.12.22 (daemon)
OS Version: Linux Mint 17.3 x64 Cinnamon
Browser Version: not applicable

The attached is a
![screenshot-for-syncthing](https://cloud.githubusercontent.com/assets/9998846/14545588/db130896-0297-11e6-81d4-6a8c82049dad.png)
 screenshot of the situation (the situation that persists _after _I have pressed the 'save' button shown in the screenshot).
![Uploading screenshot-for-Syncthing.png…]()

**Comment by kozec** [comment]
That option is applied only after restarting ST-GTK. May that be source of the problem?

**Comment by ACinnamonUserInUK** [comment]
Yes. It is the source of the problem. I suppose that should of occured to me. Still, nothing wrong with a bit of text telling the user that the option needs a restart.

**Comment by kozec** [comment]
Yes, that's true. I'll try to stuff some kind of message into that dialog.
