### ISSUE TITLE
Dual menu items exist in the right menu

### ISSUE THREAD

**Issue by wsxy162** [syncthing/syncthing-gtk#258]
![2016-04-17 02-01-45](https://cloud.githubusercontent.com/assets/6559703/14582853/ce95ac98-0442-11e6-9038-08d602ead756.png)
Like the above picture, and if I disable integration into nautilus in setting, there will still left one menu item.

I'm using openSUSE Tumbleweed 20160414 GNOME 3.20, syncthing version 0.12.21, syncthing-gtk 0.8.3 .

**Comment by kozec** [comment]
That sounds like there is one additional symlink in extensions directory, althought I have no idea how that can happen.

Try disabling integration in UI Settings and running `ls -l ~/.local/share/nautilus-python/extensions/` to check if symlink is really gone.

**Comment by wsxy162** [comment]
When disabled intergration there is no file in …/extensions/, but still one menu item exist in the right menu.
![2016-04-17 03-44-27](https://cloud.githubusercontent.com/assets/6559703/14583272/63655ace-044f-11e6-8e36-6e68e10d401c.png)

**Comment by kozec** [comment]
Hmmm... How about `ls -l /usr/share/nautilus-python/extensions/` by any chance?

**Comment by wsxy162** [comment]
Yes, I have a syncthing-gtk.py file in that location, and I can easily remove it to solve the issue.
I think this is a  mistake made by the packager, will report it to openSUSE community. Anyway, thanks.
