### ISSUE TITLE
updating/asking for daemon 0.13 beta...

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#259]
...which breaks the connection to other devices.

**Comment by robsonsobral** [comment]
The [version 8.3.2](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.8.3.2) is on PPA.

**Comment by robsonsobral** [comment]
I had an official PPA installed. I'm sorry.

**Comment by kozec** [comment]
Don't scare me like this, I thought I missed non-beta release :D
