### ISSUE TITLE
Desktop notification for when sync-conflict files appear?

### ISSUE THREAD

**Issue by TiZ-EX1** [syncthing/syncthing-gtk#261]
Hi there, this is a feature request. I don't need to see any notifications for file updates or sync completions, but I don't have any way to be notified of sync conflicts unless I go search for those files or run into them while managing my files. Would it be feasible to add a desktop notification for when sync-conflict files appear?

Thanks for all your work on this app, I love it.

**Comment by kozec** [comment]
That sounds doable, but I need to check if Syncthing informs about creation of those files in any way.

**Comment by TiZ-EX1** [comment]
If not, could you utilize the file watches you already have on watched folders to check for the creation of those files? That would restrict this feature to those using folder watches, but it's better than it not being possible.

**Comment by kozec** [comment]
Any comments?

![conflict](https://cloud.githubusercontent.com/assets/1282500/16356955/ec9db82a-3ae8-11e6-94cf-d9da491529c4.png)

**Comment by TiZ-EX1** [comment]
That looks absolutely perfect! :D
