### ISSUE TITLE
"show window" will cause traceback when there is no terminal and its trying to print umlauts on localized machine

### ISSUE THREAD

**Issue by prof7bit** [syncthing/syncthing-gtk#262]
I'm running it on a german localized Kubuntu 16.04 and trying to start it with KDE autostart. It won't be able to show the window when I start it at login with -m parameter.

Steps to reproduce (and actually get some output):

* Switch localization to German
* Open a console
* ````$ syncthing-gtk -m 1>stdout.txt 2>stderr.txt```` (blue icon will appear)
* Right-click "Fenster zeigen" (show window) (observe that nothing will happen)
* Right-click "Beenden" (quit) (it exits and prompt comes back)

Now look into the two files:

stdout.txt: (3 empty lines)
stderr.txt:
````
/usr/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py:16: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/lib/python2.7/dist-packages/syncthing_gtk/notifications.py:16: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/dist-packages/syncthing_gtk/infobox.py:8: PyGIWarning: Rsvg was imported without specifying a version first. Use gi.require_version('Rsvg', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GLib, GObject, Pango, Rsvg

(syncthing-gtk:14131): Gtk-WARNING **: Theme directory  of theme oxygen has no size field

/usr/lib/python2.7/dist-packages/syncthing_gtk/statusicon.py:451: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
W StatusIcon    StatusIcon: Using backend StatusIconAppIndicator (fallback)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 194, in do_activate
    print _("Syncthing-GTK started and running in notification area")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 33: ordinal not in range(128)
I App           updatecheck: disabled
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 194, in do_activate
    print _("Syncthing-GTK started and running in notification area")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 33: ordinal not in range(128)
````

Note the line 'ascii' codec can't encode character u'\xe4' in position 33: ordinal not in range(128)

Now modify the above command line, only redirect stderr and let stdout go to the console which apparently accepts german umlauts:

````
$ syncthing-gtk -m 2>stderr.txt

Syncthing-GTK ist gestartet und läuft im Benachrichtigungsbereich
````

Note the "ä" character!

It seems to me when starting it with a shell script in .config/autostart-scripts or a desktop entry in .config/autostart then it will not attach a console to it and output goes to /dev/null. For some reason it seems easily possible to crash a python program when printing someting with non-ascii characters when output does not go to a console that can accept the required non-ascii encoding.

The only workaround for me at the moment seems to be to modify my autostart script to set the LANG variable to a language without umlauts before starting syncthing-gtk.

You should not let python guess what encoding to use, I'm sure there is a proper way to deal with these kinds of problems, I can remember this has caused me a lot of headaches too many years ago but I don't remember the proper solution for this problem.

**Comment by kozec** [comment]
> You should not let python guess what encoding to use, I'm sure there is a proper way to deal with these kinds of problems

I'm not letting python to guess. Python *sometimes* let's me to decide :D
And no, there is no proper way to do this, but there are hacks that are able to prevent crashing. I'll check which one can be used here.

**Comment by kozec** [comment]
... or I can just use logger that doesn't have same problem :)
