### ISSUE TITLE
All devices appear as offline after suspend

### ISSUE THREAD

**Issue by eugenesan** [syncthing/syncthing-gtk#265]
After system resumes from suspend, all devices appear as offline while daemon web interface is accessible and shows correct status.
Restarting daemon via syncthing-gtk GUI solves the problem.

**Comment by eugenesan** [comment]
This behavior seems to be related to https://github.com/syncthing/syncthing/issues/3087.

**Comment by kozec** [comment]
It may look like I'm ignoring this, but I'm just trying to reproduce it on my laptop...

**Comment by eugenesan** [comment]
On my system (WiFi connection), if you suspend and resume the problem is persistent.
Note, the issue is triggered only if you wait at least several minutes before resuming.

**Comment by eugenesan** [comment]
Seems like the issue was resolved with update to Syncthing-Gtk-v0.9 + Syncthing-0.13.

**Comment by eugenesan** [comment]
After update to syncthing-v0.13.2/syncthing-gtk-v0.9.0.2 all devices once again appear as offline after suspend.
The daemon seems to be fully functional, other peers see the "resumed" host as online and WebUI shows correct status.
Daemon output suggests that the daemon was restarted after resume since the log shows no previous history (before suspend) and shows all normal stages of a clean start.
I guess since the daemon re-opens listen socket rather promptly, syncthing-gtk is not aware of the restart and assumes incorrect daemon status.
