### ISSUE TITLE
UI fails to show correct status after daemon upgrade to 0.13.0

### ISSUE THREAD

**Issue by eugenesan** [syncthing/syncthing-gtk#267]
Since syncthing daemon was upgraded to v0.13.0 UI fails to show any meaningful status.
Daemon status is only partially correct, all devices are offline and folders are not listed.

I guess this will be fixed once next syncthing-gtk version is released.

**Comment by kozec** [comment]
Fixed. There was one configuration format change that I managed to miss completely :(

**Comment by eugenesan** [comment]
Seems like there is at least one more compatibility issue.
Now UI shows all there clients and folders but they all appears as offline.
Debug output complain about "Unhandled event type: ListenAddressesChanged".

**Comment by eugenesan** [comment]
I just realized that "All devices offline" with 0.13 and the situation in https://github.com/syncthing/syncthing-gtk/issues/265 are related.
That behavior might be a result of unhandled events caused by UPNP updates after resume and now with 0.13 on start-up?

**Comment by kozec** [comment]
Unhandled event type shouldn't be a problem, ST-GTK doesn't need to know about everything.

Do I understand correctly that WebUI displays something different than ST-GTK? With what versions of everything?

**Comment by eugenesan** [comment]
Ok, seems like "All devices offline" issue wasn't Syncthing-Gtk related after all.
After restarting all the devices, 0.9.0.1 + 0.13.0 combo is working.
@kozec Thanks!

**Comment by kozec** [comment]
Good to know. Thanks :)
