### ISSUE TITLE
Should not upgrade to 0.13

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing-gtk#268]
If not supported, as  there are reports of being broken.

Perhaps its the format changes causing this?

**Comment by kozec** [comment]
Only problem I'm aware of is change from `folder->readOnly = true` to `folder->type = readonly` in rest/config and that should be already fixed.

By the way, doing this kind of change between last beta and release is not nice ;-)

Is there anything else I missed?

**Comment by AudriusButkevicius** [comment]
I don't think so.
We notified about that specific change in the forum I believe

**Comment by AudriusButkevicius** [comment]
Closing, as I guess all is well now.
