### ISSUE TITLE
Interface is invisible...

### ISSUE THREAD

**Issue by somasis** [syncthing/syncthing-gtk#272]
![screenshot_2016-05-20_21-55-05](https://cloud.githubusercontent.com/assets/264788/15446632/fbf88148-1ef4-11e6-9bf7-d2176b480aeb.png)

- Python 2.7.11
- python-dateutil 2.4.2
- pygobject 3.20.1
- Gtk+ 3.20.3
- syncthing 0.13.1

```
somasis@seneca:~/ % syncthing-gtk
/usr/x86_64-pc-linux-musl/lib/python2.7/site-packages/syncthing_gtk/uibuilder.py:16: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/x86_64-pc-linux-musl/lib/python2.7/site-packages/syncthing_gtk/notifications.py:16: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/x86_64-pc-linux-musl/lib/python2.7/site-packages/syncthing_gtk/infobox.py:8: PyGIWarning: Rsvg was imported without specifying a version first. Use gi.require_version('Rsvg', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GLib, GObject, Pango, Rsvg
I StatusIcon    Using backend StatusIconGTK3 (primary)
I App           
I App           Syncthing-GTK started and running in notification area

(syncthing-gtk:26368): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
Traceback (most recent call last):
  File "/usr/x86_64-pc-linux-musl/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 409, in _rest_connected
    con = sc.connect_to_service_finish(results)
Error: g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
^C
*break*
I DaemonProcess Subprocess finished with code 0
^C
*break*
I DaemonProcess Subprocess finished with code 0
```

**Comment by kozec** [comment]
> Error: g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
^C
*break*
I DaemonProcess Subprocess finished with code 0
^C
*break*
I DaemonProcess Subprocess finished with code 0

There is nothing to display until connection to daemon is done...

**Comment by somasis** [comment]
I've reproduced it with the daemon running for a while, I was just exiting so I could get the screenshot.

**Comment by kozec** [comment]
So, it basically doesn't display any error, just empty window? That's something new.

What distro and ST-GTK version are you using?

**Comment by somasis** [comment]
Exherbo (musl libc), st-gtk 0.9.0.1. Maybe it's a bug involving musl? If you want to try to reproduce it you might be able to on Alpine Linux, another distro using musl. (I'm the person leading musl on Exherbo and it's not very stable yet, so I wouldn't recommend you test it on there)

**Comment by kozec** [comment]
Looking how my fresh Alpine install doesn't include X, I have to ask what environment are you using :D

**Comment by somasis** [comment]
Xfce.

**Comment by kozec** [comment]
By the way, as small status report, I'm literally unable to run X server in Alpine :D
It fails itself on missing functions in distro-provided libraries.

I'm not sure if ST-GTK has any chance to run in such environment :(

**Comment by somasis** [comment]
Maybe you could test on Void Linux instead? I think they might be better on desktop (i.e.: graphical) usage

**Comment by kozec** [comment]
> Maybe you could test on Void Linux instead? I think they might be better on desktop (i.e.: graphical) usage

Good idea, but it not currently downloadable :D https://github.com/voidlinux/voidlinux.github.com/issues/32

But I'll give it a try ASAP.

**Comment by kozec** [comment]
Sorry, but after more attempts I'm able to count I don't believe ST-GTK can run on musl-based system.

**Comment by somasis** [comment]
No idea what happened, but it seems to work for no apparent reason.

![screenshot_2016-06-12_23-17-19](https://cloud.githubusercontent.com/assets/264788/15996270/e69dce50-30f3-11e6-8ce4-1a3fa2578a98.png)

so uh... cool? :)

**Comment by kozec** [comment]
Check log of your package manager and look for install/updates of anything gtk related.
