### ISSUE TITLE
Getting rundll message in windows 10 with both install and run of v0.9.0.1

### ISSUE THREAD

**Issue by rbon44** [syncthing/syncthing-gtk#273]
Installed syncthing-GTK the full installer version: v0.9.0.1-win32 on two windows 10 boxes.
 One box installed fine, the other during the install popped up a message box:
 Title bar: RUNDLL
 There is a problem starting D:\Program
 The specified module cannot be found.

The install completed and the app does run and work, but every time it is started it generates the same message box.

On both PCs the location I specified for the install was my 2nd SATA drive by substituting the appropriate drive letter in place of the standard C: in the dialog window and agreeing to creation of the new folder at that location.

I did uninstall and cleaned the registry, rebooted and retried the install with the exact same results both during the install and when running the app. Would there be a particular log file that might help in troubleshooting this? What other info would be helpful?

**Comment by kozec** [comment]
Try running it from cmd.exe and start syncthing-gtk-console.exe instead normal executable.

If error message about not being able to start something appears *after* program is started, my best guess is that it fails to run either syncthing.exe or syncthing-inotify.exe. What 'syncthing binary location' do you have set in UI Settings, on Advanced page?

**Comment by rbon44** [comment]
It does appear after program is started.  The binary location is:  C:\Users\Ron\AppData\Local\syncthing\syncthing.exe

Which is where the exe is located.   Here’s the text from running the console in cmd window:

 

D:\Program Files (x86)\SyncthingGTK>syncthing-gtk-console

D:\Program Files (x86)\SyncthingGTK\library.zip\syncthing_gtk\windows.py:11: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.

D:\Program Files (x86)\SyncthingGTK\library.zip\syncthing_gtk\infobox.py:8: PyGIWarning: Rsvg was imported without specifying a version first. Use gi.require_version('Rsvg', '2.0') before import to ensure that the right version gets loaded.

I StatusIcon    Using backend StatusIconGTK3 (primary)

E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)

Traceback (most recent call last):

  File "c:\syncthing-gui\syncthing_gtk\daemon.py", line 409, in _rest_connected

Error: g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)

E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)

Traceback (most recent call last):

  File "c:\syncthing-gui\syncthing_gtk\daemon.py", line 409, in _rest_connected

Error: g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)

E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)

Traceback (most recent call last):

  File "c:\syncthing-gui\syncthing_gtk\daemon.py", line 409, in _rest_connected

Error: g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)

I App           updatecheck: too soon

W Daemon        Unhandled event type: {u'data': {u'wan': [{u'RawQuery': u'id=JHVX4N7-SSHW25D-PK4CJU7-EORRKU2-4JSAEL4-QNQFNEY-I5D2SH6-YRPTFAK&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=Bitcoin 1E7SBG7VC2e6q7nfxttsyHMVeYmJSPPTHM', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'64.137.255.199:22067', u'User': None, u'Path': u'/', u'Scheme': u'relay'}], u'lan': [{u'RawQuery': u'id=JHVX4N7-SSHW25D-PK4CJU7-EORRKU2-4JSAEL4-QNQFNEY-I5D2SH6-YRPTFAK&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=Bitcoin 1E7SBG7VC2e6q7nfxttsyHMVeYmJSPPTHM', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'64.137.255.199:22067', u'User': None, u'Path': u'/', u'Scheme': u'relay'}], u'address': {u'RawQuery': u'', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'relays.syncthing.net', u'User': None, u'Path': u'/endpoint', u'Scheme': u'dynamic+https'}}, u'type': u'ListenAddressesChanged', u'id': 100, u'time': u'2016-05-22T22:21:47.9771917-04:00'}

**Comment by kozec** [comment]
So, no actual error there :(

There should be `syncthing-inotify.exe` next to `syncthing-gkt.exe`. Can you try to rename `syncthing-inotify.exe` (or move it somewhere else, so ST-GTK will not find it) and check if error stays?

**Comment by rbon44** [comment]
Renamed all three, still get the error. :(   ST runs okay after responding to it.  :)

**Comment by kozec** [comment]
Frankly, this sounds like some weird conflict with some other application. ST-GTK doesn't call RUNDLL and I got my hands on W10 box and there is no such message anywhere.

You said that it works fine on one your machine. Is there any special difference between those two? Something like different AV program, or different Windows edition...?

**Comment by rbon44** [comment]
They are both the same Windows edition.  The one that works has only MS Office on it, no other special apps.  This one has several audio editing tools.  What baffles me in the message is that it just says D:\Program and doesn’t report an actual app generating the dll error.  Just found that a newer video driver was available so I updated it with a clean install and did a custom install to remove all the 3D graphics and audio drivers as I don’t play games and don’t need them.  Didn’t help.  Guess my next step is try safe mode with networking and maybe edit out any startups one at a time and see if I hit something.

**Comment by rbon44** [comment]
Still happens in Safe Mode.  Startup has very little in it: NVIDIA Backend, Send to OneNote Tool, NVIDIA Capture Server Proxy (these 3 are on both PCs), unique to the problem box is Microsoft OneDrive.

 

In Startup of the problem PC the Windows port of Syncthing GTK has sub-items:

Conhost

Syncthing

TCP/IP Route Command

Windows host process (Rundll32)

Windows Port of Syncthing GTK

 

The working PC shows none of these, just a single entry of Windows Port of Syncthing GTK.

 

Another note about the 2 Win10s,  the working one is a Dell factory install so most likely an OEM version of Windows 10 Home.  This one is a full version of Windows 10 Home if that offers anything.

**Comment by kozec** [comment]
> What baffles me in the message is that it just says D:\Program and doesn’t report an actual app generating the dll error.

Maybe Windows doesn't like spaces in paths? Try installing ST-GTK to something like `D:\Programs`, maybe it'll show rest.

**Comment by rbon44** [comment]
Not liking spaces in the path appears to have been the issue. I de-installed and re-installed in a folder just called D:\Apps and now I no longer get the error message when it starts up.  Prior to doing this, I ran Microsoft’s Sysinternals’ Process Explorer to see what processes it showed using the run.dll.  It only showed one – SPIRUNE.DLL which was tied to audio driver for the audio card’s chipset.  The other box uses a different audio chipset.  So your suggestion of a possible AV conflict may very well be it, but since the re-install to a different location works, I’m going to just leave it there.

Thanks for your help!  Great program from what I’ve seen so far.  I plan to make a contribution shortly.

**Comment by kozec** [comment]
I'm 100% sure that nothing of ST-GTK nor GTK runtime is supposed to load SPIRUNE.DLL on start, so it's most likely caused not by AV, but by some crazy hook in that driver.
