### ISSUE TITLE
Open Web Interface tries to open HTTP address whereas HTTPS is needed

### ISSUE THREAD

**Issue by mclang** [syncthing/syncthing-gtk#274]
I'm using Windows 10 Pro with Edge browser.

When I try to access Syncthing's web interface by clicking "Open Web Interface" button of Syncthing GTK, the address that Edge browser tries to open uses HTTP instead of HTTPS as it should be.

**Comment by kozec** [comment]
Why should it open HTTPS? Syncthing listens on http://127.0.0.1:8080/ by default.

**Comment by mclang** [comment]
Hmm... Then there is something wrong in my default setup.

I just updated both Syncting and Syncthing GTK, and the address Syncthing GTK tries to open is "http://127.0.0.1:8384/".

**Comment by kozec** [comment]
Port may be changed if something else listens on 8080, but that's not the point. HTTP without **s** by default is the important part.

**Comment by mclang** [comment]
Yes, I understand that the 's' is the important part

I just wanted to point that according to this 8384 is the default port:
https://github.com/syncthing/syncthing/commit/960c0cbddf8802ae440f2f9ae33bced4e2d72e44

**Comment by kozec** [comment]
>  I just wanted to point that according to this 8384 is the default port:
> syncthing/syncthing@960c0cb

But ST-GTK overrides it if it's used to create initial configuration to either 8080 or first available port after that :)
