### ISSUE TITLE
Unable to start and/or restart the daemon

### ISSUE THREAD

**Issue by tmlmt** [syncthing/syncthing-gtk#275]
Fresh install of Windows 7 64 bits. Used the latest release of the Win32 installer on github (0.9.0.1), selected all the default options, and I get an error message before Syncthing-GTK crashes:

    127.0.0.1??: Une requ??te d???envoi ou de r??ception de donn??es n???a pas ??t?? autoris??e car le socket n???est pas connect?? et (lors de l???envoi sur un socket datagramme en utilisant un appel sendto) aucune adresse n???a ??t?? fournie. (45)

I have a French version of Windows, and it looks like it's impossible to select the language of Syncthing-GTK.

When I manually run syncthing first (by double clicking on the executable), Syncthing-GTK opens up correctly and seems to run well.

**Comment by kozec** [comment]
Sorry, I can't even swear in french... Any idea what could that message means?

Sadly, error messages in Windows are mostly provided by system and it is not possible to chose language for them.

**Comment by tmlmt** [comment]
Most of the "??" are due to accents. 
It says: "A data send or data receive request has not been authorized because the socket is not connected and (during the sending on a socket datagram using a sendto call) no address was provided"

**Comment by kozec** [comment]
Just to check, if you turn off everything and then start only syncthing-gtk, it will crash?

Can you tell me what "syncthing binary location" is in last tab of UI Settings?

**Comment by tmlmt** [comment]
What do you mean by "turn off everything"? I tried rebooting the computer, same thing. 
The "syncthing binary location" is set to "C:\Users\tmlmt\AppData\Local\syncthing\syncthing.exe" (that was the default) and it is indeed there. 
Now using v0.9.0.2.

**Comment by kozec** [comment]
Rebooting is enough.

I can't imagine any reason why should Syncthing refuse connections when started from ST-GTK. Is `syncthing.exe` process active in task manager while that error message is displayed?

**Comment by tmlmt** [comment]
Thanks for looking at this. 
The ```syncthing.exe``` process is not active in task manager when the error message is displayed, and I don't see it appearing anytime between me starting syncthing-gtk and the error message being displayed. I can only see ```syncthing-gtk.exe``` in task manager.

**Comment by kozec** [comment]
> The syncthing.exe process is not active in task manager when the error message is displayed

Ok, so it either crashes or can't be started at all for some unknown reason.
There is `syncthing-gtk-console.exe` file placed right to regular one, it displays console window with messages. I'm afraid it will be in french, but it may display error message pointing to reason.

**Comment by tmlmt** [comment]
Here is the output of the console:
`I StatusIcon    Using backend StatusIconGTK3 (primary)
I App
I App           Syncthing-GTK is running in the notification area
E Daemon        g-io-error-quark: <error_message> (45)
Traceback (most recent call last):
  File "c:\syncthing-gui\syncthing_gtk\daemon.py", line 409, in _rest_connected
Error: g-io-error-quark:<error_message> (45)
`
Where <error_message> is the error message that I translated in my second message above.

**Comment by kozec** [comment]
Is issue still there with [latest release](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.9.0.3)?

**Comment by tmlmt** [comment]
The issue is gone with 0.9.0.3 ! Thanks a lot
