### ISSUE TITLE
Errormessage "cx_Freeze" after update to 0.9.0.1 via choco

### ISSUE THREAD

**Issue by spacemanspiff2007** [syncthing/syncthing-gtk#276]
Hi,

I upgraded today to 0.9.0.1 through choco.
When I try to start syncthing I get the following error message:

```
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "scripts/syncthing-gtk-exe.py", line 3, in <module>
  File "c:\Python27\lib\site-packages\cairo\__init__.py", line 1, in <module>
  File "ExtensionLoader_cairo__cairo.py", line 22, in <module>
  File "ExtensionLoader_cairo__cairo.py", line 14, in __bootstrap__
ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.

---------------------------
OK   
---------------------------
```

**Comment by kozec** [comment]
Windows 10?

**Comment by spacemanspiff2007** [comment]
Windows 7

**Comment by kozec** [comment]
Good, that's at least something new :)

Does upgrading [with installer](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.9.0.2) show same thing?

**Comment by spacemanspiff2007** [comment]
I did uninstall syncthing-gtk via choco and then reinstalled it again via choco.
The errormessage is no longer shown, but when trying to download the new version of syncthing it always shows an error.

**Comment by kozec** [comment]
Yeah, that's because calmh (most likely him) started to remove older binaries :(

Try it again in about hour, it should download latest version.

**Comment by spacemanspiff2007** [comment]
I downloaded the most recent client myself and put in the directory.
Works now for me. Thank you for you quick help!

**Comment by spacemanspiff2007** [comment]
Just for your information:
I upgraded a second computer (with Win 10) an it showed the same error message.
Uninstalling and reinstalling solved the problem there, too.
