### ISSUE TITLE
Connection to daemon failed: CSRF Error

### ISSUE THREAD

**Issue by vladipus** [syncthing/syncthing-gtk#277]
I'm getting the following error through the dialog pop-up:

```
Connection to daemon failed. Check your configuration and try again.
Error message: CSRF Error
```

Syncthing itself is working fine. Running with the `-d` option gets the following output:

```
/usr/lib/python2.7/dist-packages/syncthing_gtk/notifications.py:16: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
D UIBuilder     Enabled: traditional_header
D UIBuilder     Enabled: icons_in_menu
D UIBuilder     Loading glade file /usr/share/syncthing-gtk/app.glade
D UIBuilder     Enabled conditions: set([u'icons_in_menu', u'traditional_header'])
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node !is_gnome | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: old_gtk
D UIBuilder     Removed 'child' by attribute: header_bar
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'child' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node traditional_header
D UIBuilder     Allowed node traditional_header | icons_in_menu
/usr/lib/python2.7/dist-packages/syncthing_gtk/statusicon.py:451: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
W StatusIcon    StatusIcon: Using backend StatusIconAppIndicator (fallback)
V Notifications Error notifications enabled
V Notifications File update notifications enabled
I App           
I App           Syncthing-GTK started and running in notification area
V Daemon        Set refresh interval to 5
```

Versions: Syncthing: v0.13.2, Syncthing-GTK: 0.9.0.2, Linux: Ubuntu 16.04 (64 bit)

**Comment by kozec** [comment]
Hmm... CSRF Error happens only when ST-GTK uses invalid CSRF token, what shouldn't be possible. In theory.

What of following to you have set in WebUI? GUI password, API key, HTTPS?

**Comment by vladipus** [comment]
GUI password: no
API Key: yes
HTTPS: no

**Comment by kozec** [comment]
And does it happen all the time, or only after, let's say, setting new API key?

**Comment by vladipus** [comment]
Always. I noted it was after updating the Syncthing server itself. It is 0.13.2 now.

**Comment by kozec** [comment]
I'm asking mainly because I have exactly same configuration and only way how I can reproduce this is by generating new API key and restarting daemon from WebUI.
I can add catch for that, but I'm not sure if it will help with your problem.

Last futile attempt, can you run following, while that error message is displayed?
```
grep -R address ~/.config/syncthing/config.xml | tail -1
netstat -lnp | grep syncthing
```

It should output address to which WebUI is configured to use and ip/ports where Syncthing really listens.

**Comment by vladipus** [comment]
Here you go:

```bash
$ sudo grep -R address ~/.config/syncthing/config.xml | tail -1
        <address>127.0.0.1:8384</address>
$ sudo netstat -lnp | grep syncthing
tcp        0      0 127.0.0.1:8384          0.0.0.0:*               LISTEN      15258/syncthing 
tcp6       0      0 :::22000                :::*                    LISTEN      15258/syncthing 
udp        0      0 0.0.0.0:43653           0.0.0.0:*                           15258/syncthing 
udp        0      0 0.0.0.0:21027           0.0.0.0:*                           15258/syncthing 
udp6       0      0 :::21027                :::*                                15258/syncthing 
udp6       0      0 :::47175                :::*                                15258/syncthing 
```

**Comment by kozec** [comment]
@calmh or @AudriusButkevicius looks like I need you help.

Assuming that ST-GTK *always* sends X-API-Key header with key read from config file, is there any case when Syncthing is supposed to respond with CSRF Error?

**Comment by AudriusButkevicius** [comment]
Does it read it from the file or the config rest endpoint?

**Comment by kozec** [comment]
> Does it read it from the file or the config rest endpoint?

From file.

**Comment by kozec** [comment]
By the way, @vladipus, could you tell me what exact API key do you have set?
Maybe that reading somehow fails if key contains very special character...

**Comment by AudriusButkevicius** [comment]
@kozec so as you know 0.13.1 (I think) had much stricter restrictions on how to access the web UI.

If you have the correct API key, no CSRF checks will be performed.
If the key is invalid, then you need a CSRF token. 
CSRF cookie is provided in any page that is not under the /rest path.

**Comment by kozec** [comment]
I'm aware of that and as I said, there is no way how ST-GTK could send request without X-API-Key header, as long as that key is set in config file.

But @vladipus has API key set and yet, Syncthing daemon responds with CSRF Error. It doesn't make any sense and I can't reproduce it...

**Comment by AudriusButkevicius** [comment]
It's not without the header, it's with the incorrect key.

**Comment by vladipus** [comment]
@kozec The API key has only alpha-numeric characters of different cases.

The issue is still present BTW.

**Comment by kozec** [comment]
> The issue is still present BTW.

And I still cannot reproduce it in any way.

Would it be possible to send me your `~/.config/syncthing/config.xml` and `~/.config/syncthing-gtk/config.json` ? If you can, send them by mail to kozec at kozec dot com.

**Comment by vladipus** [comment]
The issue is still present after reinstalling (using purge to remove). Sent you the config files you've asked for.

**Comment by jerome-diver** [comment]
same here, failed to get CSRF cookie. (archlinux)
How to reproduce error ? easy:
My web-ui didn't works... then i go inside my config.xml file (vim ~/.config/syncthing//congih.xml)
search for :/gui tag, then try to remove apikey... save and exit, restart daemon (service is running under syncthing@jerome.service).
After that... boom... no more syncthing-gtk access.
Ok, then remove user and password, but make true for tls.
satrt web-ui fine... then generate new api key, ask for user and password...
check in config.xml file... now there is new apikey and password for user is chipered (fine... it does works now).
Web-ui OK
syncthing-gtk: FAILED... GUI open with white background, and goes inside daemon option show message error: "failed to get CSRF cookie"

It looks like syncthing-gtk application was not informed of new apikey happened... 
I tryed to uninstall and re-install syncthing-grk (same problem)
i also try to find solution in "man syncthing-gtk", but... go to see how much it is poor for informations there...
I stay locked with my syncthing-gtk application who is unable to get CSRF cookie.
I'm now searching for someone who know how to fix this problem. Maybe the syncthink-gtk devs ?
thank you (and happy new year)
