### ISSUE TITLE
Interface is drawn outside the screen on Windows

### ISSUE THREAD

**Issue by pedro7** [syncthing/syncthing-gtk#278]
Interface is drawn outside the screen and I can't find out

- how to move it back

- if there are any settings file I can delete so it loads on the center of the first or second screen (for example).

![2016-06-02 17_05_50-greenshot](https://cloud.githubusercontent.com/assets/220099/15752077/60541f0a-28e4-11e6-8ab3-d6ef6274695f.png)

**Comment by kozec** [comment]
1. How did you got it there?
2. Use registry editor and navigate to HKCU/Software/Syncthing-GTK. Window position is stored in 'window_position_0' and 'window_position_1', set both to zero.

**Comment by pedro7** [comment]
1. No clue. Probably related with occasional use of second monitor. Usually since apps respond to ALT+SPACEBAR where 'Move' is visible, I tend to forget how they get there since I can move them back. Syncthing does not respond to ALT+SPACEBAR, (due to having Client-Side decorations?).
2. Of course, sorry! I completely forgot to check registry.
3. Thanks!

**Comment by pedro7** [comment]
Thank you for your help in Advance :)

I found a corner case:
![2016-06-20 18_21_34-definicoes](https://cloud.githubusercontent.com/assets/220099/16203794/dde8d1ee-3713-11e6-9420-9f79e8d9630d.png)

**Comment by kozec** [comment]
Why would you do that? :D

I don't think that program can check if coordinate within screen space is actually visible on some monitor.

**Comment by pedro7** [comment]
Ya :(
This layout is because I have a high-DPI LCD screen (1) and a bigger, better positioned monitor (2).
(2) is my main monitor, (1) is for unused windows.

**Comment by pedro7** [comment]
Thanks for the "Use traditional window header", should allow to workaround this issue. Thanks!
