### ISSUE TITLE
cx_Freeze error on Windows

### ISSUE THREAD

**Issue by DrStrangepork** [syncthing/syncthing-gtk#279]
Simce upgrading to syncthing-gtk v0.9.0.2, I am getting the following error on all my Windows machines (7, 8 and 10):
![untitled](https://cloud.githubusercontent.com/assets/7307373/15971736/ba82e338-2f08-11e6-8192-6689a2bba1bc.png)
I had Syncthing 0.12.something when this started, but the problem remains after upgrading to 0.13.5. All python modules, etc, are up to date.

**Comment by kozec** [comment]
> All python modules, etc, are up to date.

You have python installation on Windows?

**Comment by DrStrangepork** [comment]
In babun, yes

**Comment by kozec** [comment]
What is babun?

Anyway, it probably clashes with ST-GTK. Could you try to run `syncthing-gtk-console.exe` with PYTHONPATH environment variable unset?

**Comment by DrStrangepork** [comment]
babun is a cygwin clone

```
C:\Program Files (x86)\SyncthingGTK>syncthing-gtk-console.exe
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "scripts/syncthing-gtk-exe.py", line 3, in <module>
  File "c:\Python27\lib\site-packages\cairo\__init__.py", line 1, in <module>
  File "ExtensionLoader_cairo__cairo.py", line 22, in <module>
  File "ExtensionLoader_cairo__cairo.py", line 14, in __bootstrap__
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by DrStrangepork** [comment]
babun is a cygwin clone

```
C:\Program Files (x86)\SyncthingGTK>syncthing-gtk-console.exe
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "scripts/syncthing-gtk-exe.py", line 3, in <module>
  File "c:\Python27\lib\site-packages\cairo\__init__.py", line 1, in <module>
  File "ExtensionLoader_cairo__cairo.py", line 22, in <module>
  File "ExtensionLoader_cairo__cairo.py", line 14, in __bootstrap__
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by kozec** [comment]
Ok, just to check, have you got path to that python installation mentioned in *any* environment variable?

**Comment by DrStrangepork** [comment]
No, not on any of my computers.

**Comment by kozec** [comment]
I'm not really sure it this helps, but can you test it with [latest release](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.9.0.3)?

**Comment by plouj** [comment]
I'm seeing the exact same error with Syncthing-GTK v0.9.1.
I do not have Python installed on my machine. I also do not have a "C:\Python27" directory.

**Comment by kozec** [comment]
@plouj Can you, please open cmd.exe and copy output of `echo %PATH%` ?

**Comment by plouj** [comment]
C:\Users\Plouj>echo %PATH%
C:\Program Files (x86)\Intel\iCLS Client\;
C:\Program Files\Intel\iCLS Client\;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files (x86)\Windows Live\Shared;
C:\Program Files\Intel\WiFi\bin\;
C:\Program Files\Common Files\Intel\WirelessCommon\;
C:\ProgramData\chocolatey\bin;
C:\Program Files (x86)\QuickTime\QTSystem\;
C:\WINDOWS\system32;
C:\WINDOWS;C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common

(newlines added after the semicolons by me)

My syncthing-gtk is installed with chocolatey.

**Comment by kozec** [comment]
> My syncthing-gtk is installed with chocolatey.

Stupid think is that I've just installed syncthing-gtk with chocolatey on fresh Windows install and it runs :(

Can you, please, try running this?

```

C:\>cd "\Program Files (x86)\SyncthingGTK"

C:\Program Files (x86)\SyncthingGTK>set PATH=C:\Windows\System32

C:\Program Files (x86)\SyncthingGTK>echo %PATH%
C:\Windows\System32

C:\Program Files (x86)\SyncthingGTK>syncthing-gtk-console.exe
```

**Comment by plouj** [comment]
It still doesn't work:

C:\Users\Plouj>cd "\Program Files (x86)\SyncthingGTK"

C:\Program Files (x86)\SyncthingGTK>set PATH=C:\Windows\System32

C:\Program Files (x86)\SyncthingGTK>echo %PATH%
C:\Windows\System32

C:\Program Files (x86)\SyncthingGTK>syncthing-gtk-console.exe
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py",
line 27, in <module>
  File "scripts/syncthing-gtk-exe.py", line 3, in <module>
  File "c:\Python27\lib\site-packages\cairo\__init__.py", line 1, in
<module>
  File "ExtensionLoader_cairo__cairo.py", line 22, in <module>
  File "ExtensionLoader_cairo__cairo.py", line 14, in __bootstrap__
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by kozec** [comment]
Sorry, I edited that path right away, but it's look like you were faster. Try just C:\, or even better, some empty folder as a path.

**Comment by plouj** [comment]
Still the same problem:

C:\Users\Plouj>mkdir C:\test-dir

C:\Users\Plouj>cd "\Program Files (x86)\SyncthingGTK"

C:\Program Files (x86)\SyncthingGTK>set PATH=C:\test-dir

C:\Program Files (x86)\SyncthingGTK>echo %PATH%
C:\test-dir

C:\Program Files (x86)\SyncthingGTK>syncthing-gtk-console.exe
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py",
line 27, in <module>
  File "scripts/syncthing-gtk-exe.py", line 3, in <module>
  File "c:\Python27\lib\site-packages\cairo\__init__.py", line 1, in
<module>
  File "ExtensionLoader_cairo__cairo.py", line 22, in <module>
  File "ExtensionLoader_cairo__cairo.py", line 14, in __bootstrap__
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by kozec** [comment]
Latest release uses latest version of GTK runtime on Windows. Could someone affected by this test, if problem still persist with upgraded runtime? Ideally on clean install.

**Comment by seiferflo** [comment]
Hi, I have the same issue with 0.9.2 but with different error lines.
![2016-08-28 15-17-45_cx_freeze_ python error in main script](https://cloud.githubusercontent.com/assets/10022442/18034030/9ba66ae4-6d32-11e6-990a-f3545d61c99f.gif)

No problem going back to 0.9.1. Syncthing version is 0.14 
I do not have python installed on my computer and don't plan to install it.

**Comment by fgenesis** [comment]
Same issue here (win8.1), exactly what seiferflo said. Currently on 0.9.1, that works. I have python2 and python3 in my PATH, so that's not the issue. Error with 0.9.2, while 0.9.1 is fine. Underlying syncthing is 14.5.

**Comment by kozec** [comment]
@fgenesis , @seiferflo I believe that's another error, currently reported with #309

**Comment by seiferflo** [comment]
0.9.2.1 solve the problem for me, thanks @kozec
