### ISSUE TITLE
Unable to save daemon location on Windows 7

### ISSUE THREAD

**Issue by acastaner** [syncthing/syncthing-gtk#284]
I'm trying to setup Syncthing-gtk on Windows 7 (Professional) but I'm running into an issue. Whenever I start the GUI, I get a message that the daemon isn't running, which is correct. I click on "Start daemon" but then the GUI complains that it can't find it. I browse to the location (C:\Users\MyUser\AppData\Local\syncthing\syncthing.exe) but when I try to click on "Save", nothing happens. The window just doesn't close and it seems the setting isn't saved (if I restart the GUI, the same problem happens).

It's on a Windows 7 Professional OS, fully patched and running a French language OS.

Is there any place I could edit the GUI settings to force the path manually?

**Comment by kozec** [comment]
> fully patched and running a French language OS

With french username?

> Is there any place I could edit the GUI settings to force the path manually?

Settings are stored in registry, under `HKEY_CURRENT_USER\Software\SyncthingGTK`
But python on Windows has big trouble working with paths containing non-ascii character, so if you are trying to set it to something like _C:\Users\ **Sébastien** \AppData\Local\syncthing\syncthing.exe_, it may turn kinda unsolvable.
