### ISSUE TITLE
Continuous low-level CPU usage

### ISSUE THREAD

**Issue by jgoerzen** [syncthing/syncthing-gtk#285]
Hi,

top noticed that syncthing-gtk continuously uses about 2% CPU.  This has negative impacts on the ability of my laptop to enter CPU sleep states, and therefore on battery life.

strace shows this:

```
poll([{fd=8, events=POLLIN}, {fd=10, events=POLLIN}, {fd=6, events=POLLIN}, {fd=18, events=POLLIN}, {fd=15, events=POLLIN}], 5, 0) = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3559, ...}) = 0
poll([{fd=13, events=POLLIN}], 1, 10)   = 0 (Timeout)
recvmsg(10, 0x7ffd367e16a0, 0)          = -1 EAGAIN (Resource temporarily unavailable)

```

This could probably be addressed by increasing these timeouts, or better yet adding all the fds to a single poll().

the FDs are these:

syncthing 3075 jgoerzen    8u  0000                0,9        0    7688 anon_inode
syncthing 3075 jgoerzen   10u  unix 0xffff8808168310c0      0t0   26972 socket
syncthing 3075 jgoerzen    6u  unix 0xffff88081679b800      0t0   25448 socket
syncthing 3075 jgoerzen   18r  FIFO                0,8      0t0  714790 pipe
syncthing 3075 jgoerzen   13r  0000                0,9        0    7688 anon_inode
syncthing 3075 jgoerzen   15u  IPv4             831675      0t0     TCP localhost:44685->localhost:8384 (ESTABLISHED)

**Comment by kozec** [comment]
> syncthing 3075 jgoerzen 8u 0000 0,9 0 7688 anon_inode

Hmm... Assuming that syncthing is process name, this should be reported as [Syncthing bug](https://github.com/syncthing/syncthing/issues), I cannot do much with it in ST-GTK.

**Comment by jgoerzen** [comment]
I reported here because it was the syncthing-gtk process, not the syncthing process causing this
--

**Comment by jgoerzen** [comment]
The info I posted was from when the window was closed (only the tray
icon was visible).

Having the window open but no file activity going on makes little
difference to the CPU usage.

This does not appear to be the GTK interface sending requests to the
server -- notice no network traffic actually occurred (the poll() just
times out).

I don't know exactly where the poll() is happening -- obviously in some
library, because grepping the syncthing-gtk didn't return anything
meaningful -- but wherever it is, it should be using a timeout larger
than 0ms and 5ms.

John

**Comment by kozec** [comment]
> I don't know exactly where the poll() is happening -- obviously in some
library, because grepping the syncthing-gtk didn't return anything
meaningful -- but wherever it is, it should be using a timeout larger
than 0ms and 5ms.

Before everything, I'm fairly sure that it happens in syncthing process, not in ST-GTK.

Try starting ST-GTK from [this branch](https://github.com/syncthing/syncthing-gtk/tree/issue-285) and check if it makes any difference. Pooling interval for hidden window is increased to 30s there.
