### ISSUE TITLE
Strange ppa "ppa:nilarimogard/webupd8"

### ISSUE THREAD

**Issue by Mannshoch** [syncthing/syncthing-gtk#286]
If I add "ppa:nilarimogard/webupd8" to my System Ubunt wish to Update many Components which are not part of Syncthing. also I have the strange situation, that many tools in this PPA appear four times in the source. 

Someone should please check this repository. In my opinion there should only appear Syncthing releated tools and also there should only appear every tool once in the repository.

**Comment by kozec** [comment]
webupd8 is repository maintained by guy from http://www.webupd8.org/ and it's not official syncthing repository nor anything like that. It just happens to contain Syncthing-GTK as well.

**Comment by step21** [comment]
Just for the future, @Mannshoch things appearing more often in ppas is entirely normal, most of the time it is one time per Ubuntu release, so one is for Xenial, one for Yakkety etc. Apart from that, it is one of the best and most established ppas I would say.
