### ISSUE TITLE
syncthing-gtk manpage

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing-gtk#287]
Hello!

I am preparing the Debian package for syncthing-gtk and I would love to see a manpage for the syncthing-gtk binary!

I guess this could be included in the https://github.com/syncthing/docs repository and copied over just like its done in the main syncthing repo?

**Comment by kozec** [comment]
Frankly, I never tried to make manpage, but I'll check if there is some fast way to copy output of syncthing-gtk -h there.

**Comment by kozec** [comment]
Ok, I tried to make mangpage and it seems to work :)
