### ISSUE TITLE
incorrect-locale-code cn -> zh

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing-gtk#288]
Hello!

According to lintian, cn should not be used as a local code.

This refers to the folder in which the locales are installed. They are currently installed in ``/usr/share/locale/cn``.

See the [incorrect-local-code](https://lintian.debian.org/tags/incorrect-locale-code.html) description:

> The language codes used in the locale directories are those from the ISO 639-1 and ISO 639-2 standards, not those usually used as TLDs (which are from the ISO 3166 standard).
>
> When both standards define a language code for a given language, the ISO 639-1 code should be used (i.e. the two lettered code).

Lintian is a tool that checks for common errors in Debian packages.

**Comment by kozec** [comment]
Is that debian only thing, or every distro uses same code and it's just something noone spotted before?

**Comment by xduugu** [comment]
I guess the latter. On Arch Linux, syncthing-gtk is the only package that uses `/usr/share/locale/cn`. Most of the packages use `/usr/share/locale/zh_CN`.

**Comment by kozec** [comment]
Ok, this shouldn't break anything.

**Comment by aviau** [comment]
Thank you!
