### ISSUE TITLE
Tray icon does not show on Gnome+Wayland

### ISSUE THREAD

**Issue by fsateler** [syncthing/syncthing-gtk#289]
The tray icon doesn't work when running in Gnome Shell in a Wayland session. Switching to different backends with SYNCTHING_STATUS_BACKEND does not make any difference (tried GTK3, AppIndicator and DBus). Syncthing seems to think the icon works correctly:

> I App           Syncthing-GTK started and running in notification area

**Comment by kozec** [comment]
That's bug more for Gnome devs than for me. IRRC, they are trying to deprecate tray icons altogether, so StatusIcon would most likely not be supported there.

And, ofc, Wayland has no way to support any other X11-based backend.

**Comment by fsateler** [comment]
It appears the concept of tray icons is going away. The preferred way to do something like this would be a gnome applet then....

**Comment by kozec** [comment]
It's not going away, it's just unsupported by Gnome Shell on Wayland. I'm fairly sure that notification icons are going to be added into protocol before Wayland will be pronounced ready for everyday use.

And no, gnome-shell doesn't have support for applets :)
