### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by buttle** [syncthing/syncthing-gtk#291]
Hi,

Here is a [Spanish translation po file](http://gatopelao.org/nube/index.php/s/G8M5Iwlb2SNjkeI). If you need any fixes, please tell me.

Cheers.

**Comment by kozec** [comment]
Thanks. I uploaded it to [transifex](https://www.transifex.com/syncthing-gtk/syncthing-gtk/) and will add it in next release.
