### ISSUE TITLE
Auto-populate fields for new folder / device

### ISSUE THREAD

**Issue by acolomb** [syncthing/syncthing-gtk#294]
In contrast to the Web UI, ST-GTK does not provide default values for some fields of new folders.

When adding a new folder from scratch:
 * A randomly generated Folder ID should be suggested.
 * Initial focus should be on the Folder Label field.
 * File Pull Order should have a default value (currently empty)

When adding a shared folder from a remote device:
 * The proposed Folder Label should be pre-filled, but editable
 * File Pull Order should have a default value (currently empty)

When adding a remote device after receiving its hello message:
 * The Device Name field should be pre-filled, initially focused and editable

These changes would only catch up to what the Web UI already does and make Syncthing-GTK easier to use.

**Comment by acolomb** [comment]
A nice addition would be a button inside any (editable) Folder ID field to generate a new random ID, just in case someone does not like the current value for whatever reason. This might best be implemented within Syncthing core as an API call?

**Comment by kozec** [comment]
> This might best be implemented within Syncthing core as an API call?

Generator in ST-GTK will have better responsibility. What I'm not sure about is if I can make button inside of text field.

Anyway, thanks for suggestions, they all sounds fairly easy to implement.

**Comment by kozec** [comment]
I'm almost sure that Device Name and Folder ID _is_ prefilled when user is adding discovered device or folder, but I'll test it just in case.

**Comment by kozec** [comment]
(tested)

**Comment by acolomb** [comment]
Indeed, Folder ID is pre-filled when adding a folder by invitation from a remote device. However, Folder _Label_ is not. I just noticed, the new folder notification only mentions the ID as well, but should rather show the more descriptive Label (and fall back to ID when it's empty).

The label is definitely available, see Syncthing's message in the Web UI:
> Alice wants to share folder "MyCoolFolder" (abcde-12345). Add new folder?

Device Name is definitely not pre-filled when adding on first connection, just tested it again.

**Comment by kozec** [comment]
Sorry, I have stupid tendency of forgetting about closed issues.

**Comment by acolomb** [comment]
@kozec, that commit only fixes the Folder Label stuff, not the Device Label for unknown connections, right?

I'd like to keep this issue open to track that part also.

**Comment by kozec** [comment]
Hmm... That's weird, where did other one gone...

**Comment by kozec** [comment]
... here, I have no idea what happened :)

**Comment by acolomb** [comment]
Great, thanks!
