### ISSUE TITLE
Not found error

### ISSUE THREAD

**Issue by KokaKiwi** [syncthing/syncthing-gtk#295]
I have a weird error when launching Syncthing-GTK, with no more explanation than just a "Not found" :/

I have the same error after removing the `<APPDATA>/Local/syncthing` folder...

Syncthing-GTK: 0.9.1
OS: Windows 10 (64bits)

![](http://i.imgur.com/kaHZG27.png)

**Comment by kozec** [comment]
You probably have another web server running on same port as webui is configured to use.

Try expanding that "more info" part of dialog.

**Comment by KokaKiwi** [comment]
The problem is that the "More Info" part of the dialog is already expanded in the screenshot...

But I effectively found another web server running on the port 8080 (it was VLC with the web remote control interface), now Syncthing GTK successfuly start when I removed the VLC web interface.

Still, the error message was not really explicit in that case...

**Comment by kozec** [comment]
> Still, the error message was not really explicit in that case...

That message doesn't really know what's wrong and there are more possible reasons.
But I should add something like "Are you running another web server?" to that message, especially when reported error is "Not Found."

**Comment by KokaKiwi** [comment]
I think the root problem is that the software should read what syncthing say when it's running.
I mean, if the problem is that the port is already used, syncthing should say so, then syncthing-gtk should read what syncthing is saying to get an explicit error message and then, displaying it as the "Error message".

But I know that sometime you can't document correctly an unknown error, but here I don't think it's "unknown" in this case...

**Comment by kozec** [comment]
That's not always possible, as ST-GTK supports having Syncthing running separately, started as service or something similar, when it can't read Syncthing output.

Frankly, I would rather prefer if Syncthing just exited with error instead of choosing random ports by itself, but I never considered it to be that big of problem, so I didn't proposed that behavior.

**Comment by kozec** [comment]
This is what's shown now for same error.

![a1](https://cloud.githubusercontent.com/assets/1282500/17455284/24066a60-5bb3-11e6-9456-1b3186bfcc4d.png)

![a2](https://cloud.githubusercontent.com/assets/1282500/17455285/256e28ca-5bb3-11e6-8491-92cd3bb86613.png)
