### ISSUE TITLE
Won't minimize to tray on start

### ISSUE THREAD

**Issue by kc135pirate** [syncthing/syncthing-gtk#296]
At system startup syncthing-gtk does not minimize to tray. This could be a Mate issue (using Ubuntu Mate 16.04).

**Comment by kozec** [comment]
That usually happens when ST-GTK starts before tray area is available, but Mate should have exception to that check.

What's output of `echo $XDG_CURRENT_DESKTOP $DESKTOP_SESSION` on that machine?

**Comment by kc135pirate** [comment]
output => MATE mate

I will delay the start of syncthing-gtk to see if that fixes the problem. Cheers!

**Comment by kozec** [comment]
Soo.. I've tested ST-GTK on Mate, it works as expected. My best guess is that you have it somehow set to start *twice* . You can check that with `ls ~/.config/autostart/` and examining anything what looks suspicious.
