### ISSUE TITLE
KDE plasma: no tray icon

### ISSUE THREAD

**Issue by NeroBurner** [syncthing/syncthing-gtk#297]
After a long time without syncthing-gtk I tried syncthing-gtk once again, but stumbled about an error I can't explain

when starting syncthing-gtk (normal or in the command line) the main window does not show and the tray icon is missing. Notifications are shown (but not in the notification tray from KDE). When starting syncthing-gtk a second time the main window shows.
I've checked the settings and the 'Minimize to tray on start' checkbox is off.

```
$ syncthing-gtk
W StatusIcon    StatusIcon: Using backend StatusIconDummy (fallback)

(syncthing-gtk:6963): Gtk-WARNING **: Invalid icon size 16
I App           updatecheck: disabled
```

then after starting syncthing-gtk on a second console the prompt in the first window shows an extra

```
(syncthing-gtk:6963): Gtk-WARNING **: Invalid icon size 16
```

 and the syncthing-gtk window appears

i'm on KDE plasma

```
$ echo $XDG_CURRENT_DESKTOP $DESKTOP_SESSION
KDE /usr/share/xsessions/plasma
```

edit: there never is a tray icon

**Comment by kozec** [comment]
You can try running 
`SYNCTHING_STATUS_BACKEND=Qt syncthing-gtk`
`SYNCTHING_STATUS_BACKEND=AppIndicator syncthing-gtk` and
`SYNCTHING_STATUS_BACKEND=KDE4 syncthing-gtk`

but my best guess is that you are missing kde python bindings for your distro.

**Comment by NeroBurner** [comment]
AppIndicator and KDE4 are unsupported:
```
$ SYNCTHING_STATUS_BACKEND=KDE4 syncthing-gtk
E StatusIcon    StatusIcon: Requested backend StatusIconKDE4 is not supported

(syncthing-gtk:1914): Gtk-WARNING **: Invalid icon size 16
I App           updatecheck: disabled
^C
*break*
```
```
YNCTHING_STATUS_BACKEND=AppIndicator syncthing-gtk
E StatusIcon    StatusIcon: Requested backend StatusIconAppIndicator is not supported

(syncthing-gtk:1895): Gtk-WARNING **: Invalid icon size 16
I App           updatecheck: disable
```

opening with Qt the window opens right away:
```
SYNCTHING_STATUS_BACKEND=Qt syncthing-gtk
I StatusIcon    StatusIcon: Using requested backend StatusIconQt

(syncthing-gtk:1934): Gtk-WARNING **: Invalid icon size 16

(syncthing-gtk:1934): Gtk-WARNING **: Invalid icon size 16
I App           updatecheck: disabled
```

Tray icons open on none of the mentioned.

I'm running Arch linux
```
$ pacman -Qi syncthing-gtk 
Name            : syncthing-gtk
Version         : 1:0.9.1-1
Description     : GTK3 based GUI and notification area icon for Syncthing
Architecture    : any
URL             : https://github.com/syncthing/syncthing-gtk
Licenses        : GPL2
Groups          : None
Provides        : None
Depends On      : gtk3  libnotify  python2-dateutil  python2-gobject  python2-pyinotify  python2-cairo  syncthing>=0.13
Optional Deps   : python2-nautilus: file manager integration for Nautilus
                  python2-caja: file manager integration for Caja
                  librsvg: to shown menu icons correctly if not using traditional window header [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 1919.00 KiB
Packager        : Bartlomiej Piotrowski <bpiotrowski@archlinux.org>
Build Date      : Mit 20 Jul 2016 07:13:40 CEST
Install Date    : Die 02 Aug 2016 15:26:16 CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

Which bindings could be missing?

**Comment by kozec** [comment]
For KDE4 backend, you need python2-pyqt4 and kdebindings-python2. But frankly, I didn't saw KDE for year or so and now I kind of can't find where are status icons displayed at all, so I have little trouble testing that :D

**Comment by NeroBurner** [comment]
Plasma 5 uses the StatusNotifier specification for systray icons as explained in the following blog post
http://blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next/

hope it helps

**Comment by kozec** [comment]
And what's suggested solution for dealing with application that uses standard tray icon instead?

**Comment by kozec** [comment]
By the way, I'm on Manjaro-KDE right now and ST-GTK icon is shown in "Status and Notifications" area, behind that WinXP-like triangle.

**Comment by alexander255** [comment]
> By the way, @alexander255, if you are still around, isn't this same problem that you solved by using multiple providers and detection back then?

Yes, but the KDE code has gone somewhat dormant in the mean time, because hardly any distro installs `python2-kde4` anymore. Some are stopping to ship it already. The original motivation for the multiple-backend solution was to enable extra functionality under KDE that is not exposed by the *AppIndicator* API (which [only cares about stuff present in Unity](https://bugs.launchpad.net/ubuntu/+source/libappindicator/+bug/621075)). This is obviously not achieved anymore.
My preferred solution for this would still be to just do the whole *StatusNotifier*/*AppIndicator* stuff natively (i.e. in pure Python). I happen to have some stuff lying around for this, that could use some polishing (I've planning on releasing it as a standalone library for a while). If *Syncthing-GTK* would use this it'd be a net reduction in LOC (and a new optional, but recommended Linux-only dependency).

**Comment by kozec** [comment]
> My preferred solution for this would still be to just do the whole StatusNotifier/AppIndicator stuff natively (i.e. in pure Python). I happen to have some stuff lying around for this, that could use some polishing (I've planning on releasing it as a standalone library for a while). If Syncthing-GTK would use this it'd be a net reduction in LOC (and a new optional, but recommended Linux-only dependency).

Yeah, that sounds like reasonable solution right now. I can even do something like using GTK for Windows, GNOME & co and your library as optional dependency for rest.

**Comment by cassava** [comment]
My experience concerning the tray icon is:
 * Works with [trayer-srg](https://github.com/sargon/trayer-srg), but doesn't look awefully pretty at size 24x24 icons. I start trayer with:
```trayer --iconspacing 2 --edge top --align right --widthtype request --height 24 --SetDockType true --SetPartialStrut true --transparent true --expand true --tint 0 --alpha 0 --margin 200```
 * Does not work with stalonetray—there is no icon visible, but I can get a menu by clicking where the icon would be. I use pretty much the default options of stalonetray.

**Comment by ZapperDJ** [comment]
Had the same problem on Antegos KDE, fixed it by installing the libappindicator-gtk3 package

**Comment by Linuturk** [comment]
I just updated to Kubuntu 18.04 and I'm having this issue.

```
$ syncthing-gtk 

(syncthing-gtk:9794): Gtk-WARNING **: 09:54:18.912: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(syncthing-gtk:9794): Gtk-WARNING **: 09:54:18.912: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(syncthing-gtk:9794): Gtk-WARNING **: 09:54:18.912: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
W StatusIcon    StatusIcon: Using backend StatusIconDummy (fallback)

(syncthing-gtk:9794): Gtk-WARNING **: 09:54:18.992: Invalid icon size 24
I App           
I App           Syncthing-GTK started and running in notification area
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 1051, in _connected
    self._connection = self.connect_to_service_finish(results)
Error: g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
I App           updatecheck: disabled
```

I've ensured the libappindicator packages are installed:

```
$ sudo dpkg -l | grep libappindicator
ii  libappindicator1                                12.10.1+18.04.20180322.1-0ubuntu1           amd64        Application Indicators
ii  libappindicator3-1                              12.10.1+18.04.20180322.1-0ubuntu1           amd64        Application Indicators
ii  python-appindicator                             12.10.1+18.04.20180322.1-0ubuntu1           amd64        Python bindings for libappindicator
```

I've also tried the environment variable tweaks above:
```
SYNCTHING_STATUS_BACKEND=Qt syncthing-gtk
SYNCTHING_STATUS_BACKEND=AppIndicator syncthing-gtk
SYNCTHING_STATUS_BACKEND=KDE4 syncthing-gtk
```

**Comment by Linuturk** [comment]
```
$ python2
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version('AppIndicator3', '0.1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

Maybe the package name changed between ubuntu versions?

**Comment by Linuturk** [comment]
I found a package `python-ayatana-appindicator` that seems to be gtk2 bindings for the same setup, but after installing I'm still not seeing the tray icon after attempting to launch syncthing-gtk.

**Comment by kozec** [comment]
gtk2 bindings is not going to work, that's one gtk behind.

You need package that contains file `/usr/lib/girepository-1.0/AppIndicator3-0.1.typelib`

**Comment by Linuturk** [comment]
yep, installing `gir1.2-appindicator3-0.1` fixed it. Maybe this should be made a dependency of the deb package. :) Thanks!

**Comment by Linuturk** [comment]
Maybe something in the error output to hint at the requirement.

**Comment by kozec** [comment]
Ok, that's not a problem.
