### ISSUE TITLE
Announce Server: disabled

### ISSUE THREAD

**Issue by acolomb** [syncthing/syncthing-gtk#298]
In Syncthing's Web UI, I see

> Listeners 	2/2
> Discovery 	8/8

but ST-GTK only shows

> Announce Server: disabled

Is an Announce Server the same as a Discovery Server? Why is it disabled, then?

I could not find anything in the Syncthing docs about "listeners", so what does that mean? Does it have to do with relay servers?

Some GUI cleaning would be good here, maybe those fields are not even interesting to most users and could be hidden in a new "network status" panel or something.

**Comment by kozec** [comment]
Hmm.. weird thing is that my WebUI *does* display value for announce servers. But "disabled" is wrong, I'll check why it displays that.
