### ISSUE TITLE
Syncthing-gtk prepends 'tcp://' to 'dynamic'

### ISSUE THREAD

**Issue by beanaroo** [syncthing/syncthing-gtk#300]
Syncthing fails to dial these devices. "dial tcp: lookup dynamic: no such host"

Editing config.xml or using the web UI to remove the 'tcp://' fixes the issue.

**Comment by kozec** [comment]
Weird thing. Which config option are we talking about?

**Comment by beanaroo** [comment]
The device address option. Using version 0.9.1. Everything else is working wonderfully.
