### ISSUE TITLE
Don't show messages that are repeated

### ISSUE THREAD

**Issue by fbatogo** [syncthing/syncthing-gtk#302]
SyncthingGTK seems to add messages to the UI window without looking to see if the message is already shown.   In general, I usually deal with those messages before too many get listed.   However, last week I was out of town and came home to a list of messages that filled two monitors.   The messages were all the same message.  (That message was to let me know that one of the devices I sync with had been upgraded to a newer version of Syncthing.)

It would be nice if SyncthingGTK could look at the messages that are displayed, and not create another instance of the message if that message is already showing.   Since the strings are identical, I would think a simple string match would be enough to do the job.

Thanks!

**Comment by kozec** [comment]
> It would be nice if SyncthingGTK could look at the messages that are displayed, and not create another instance of the message if that message is already showing.

It actually does exactly that. Are you sure that those strings were identical?
