### ISSUE TITLE
Show devices with incompatible Syncthing versions differently

### ISSUE THREAD

**Issue by fbatogo** [syncthing/syncthing-gtk#303]
I suspect the device list that is shown on the right-hand side of the UI window may be directly pulled from the device list in Syncthing.   If this is the case, then this feature request will probably need to be kicked down to the Syncthing guys.  (If so, let me know and I'll move it down there.)

When a device that you are set to sync with is updated to a version of Syncthing that isn't compatible with the one running is detected, it would be nice if the listing in the right-hand side of the UI was changed from "Disconnected" to something like "Version mismatch", or "Not Compatible".   When this happens, it would be good to update the "last seen" value to the time that the remote device contacted the machine and the compatibility issue was discovered.

Thanks!

**Comment by kozec** [comment]
They should be displayed [in red with status saying 'Incompatible'](https://github.com/syncthing/syncthing-gtk/blob/master/syncthing_gtk/app.py#L766) right now...
