### ISSUE TITLE
Symbolic (monochrome) tray icon option

### ISSUE THREAD

**Issue by skmlcd** [syncthing/syncthing-gtk#304]
I know this is not that important, but it would be really nice option to be able to enable symbolic (monochrome) tray icon that also scales properly. Here is an example how current icon doesn't fit in with the rest:

![screenshot from 2016-08-14 08-38-05](https://cloud.githubusercontent.com/assets/10860015/17647676/a4237208-61fb-11e6-8fa6-5ed33b7a97e1.png)

This current screenshot if from Solus OS, Budgie desktop environment.

**Comment by kozec** [comment]
Those icons are called only by names, so it should be possible to override by theme...

What I'm wondering about more is how should it look without any colors. What would be difference between offline (gray) and online (blue) state?

**Comment by skmlcd** [comment]
You're right they should  be overridden by theme easily. I wanted to make a request to the author of theme that I use, but I posted here first, since not all themes accept tray icon requests and a simple feature like this can help with integration.

I'm not really sure how this works, if there is even a way to create monochrome icons that fit in with every desktop environment. Just wanted to ask. :)

As you can see in my screenshots, not all icons are white. The battery indicator is usually white, but in this picture it is red (because low state). Same can be applied to syncthing, white for online and red for offline. Or blue for online and white for offline. I'm not really sure what is the best way to do this though.

**Comment by kozec** [comment]
> But as you can see qBittorrent icon also doesn't really scale with others. Is this even possible to achieve without manually tweaking the icon?

Nope, that's exactly why icon themes were invented :D But making two-colors icon like this...

![mock](https://cloud.githubusercontent.com/assets/1282500/17651250/5038cc3e-6263-11e6-8536-f50b1de234ea.png)

... that turns red or gray should be possible, I'm just not sure about that selector. Should "normal" be as theme dictates, with default as fallback and dark/light hardcoded?

**Comment by skmlcd** [comment]
Yeah that seems like a good solution to me. Should the dark/light options be combined as (I think) you can probably detect if the icon will be on dark/light background. Or is it more user friendly to give user the option of choosing?
