### ISSUE TITLE
[FEATURE] Configurable desktop notification settings

### ISSUE THREAD

**Issue by ben-kuhn** [syncthing/syncthing-gtk#306]
When syncing a large amount of files, or adding a new device, it is extremely distracting to receive a desktop notification for every file that is synced--especially when a folder contains thousands of files.

Ideally, it would be nice to have the notifications configurable.  One option could be the behavior now with a notification for each file, another might be to send a notification when a sync is complete (for all files, not each individual file), and a third might be to suppress notifications all together.

**Comment by kozec** [comment]
Actually, if two or more notifications are generated in less than 5s, they are consolidated do one "X files was modified on remote device". Maybe I could make that 5s value configurable?

Anyway, notifications are configuration in UI settings, where, if I understood correctly, you can set what you described.

**Comment by ben-kuhn** [comment]
Okay.  Maybe the problem is that I don't have any UI settings.  I'm running Ubuntu Gnome and installed from the webupd8 ppa.  See attached screenshot.
![syncthing](https://cloud.githubusercontent.com/assets/16821405/17854748/5d5fc5ca-683a-11e6-8ac5-566b8f0ffe8b.png)

**Comment by kozec** [comment]
Gnome hides one menu, it's located in top-left corner, where "Files" is [in this image](http://1.bp.blogspot.com/-wLAerUEuG3g/VYlzRd1XdiI/AAAAAAAADmc/d5N_7IGsjn8/s1600/Screenshot%2Bfrom%2B2015-06-18%2B23%253A08%253A13.png).

**Comment by ben-kuhn** [comment]
Good to know.  Thanks.
