### ISSUE TITLE
Pressing "Override changes" being ignored

### ISSUE THREAD

**Issue by michaelforge** [syncthing/syncthing-gtk#307]
Hey there,

GUI: v0.9.1-win32
Daemon: 0.14.4

If folder is "Out of sync", pressing "Override changes" doing absolutely nothing.
The only way to do overriding is to open web interface and do it here.

**Comment by kozec** [comment]
... and it took me only year to adapt 8-)

**Comment by michaelforge** [comment]
@kozec
=D lol
That was quick. Many thanks!
