### ISSUE TITLE
macOS version?

### ISSUE THREAD

**Issue by NIXOYE** [syncthing/syncthing-gtk#308]
is there any plans to get this running on macOS? seems like it would be easier to get it running on macOS than on Windows and the Windows version already works.

**Comment by kozec** [comment]
It should work in theory, but I have no MacOS machine to test it.

**Comment by NIXOYE** [comment]
@kozec I assumed it would but since it wasn't listed i thought maybe someone had tried it with no avail. What would one do to install it to try it?

**Comment by kozec** [comment]
> What would one do to install it to try it?

Well, [dependencies](https://github.com/syncthing/syncthing-gtk#dependencies) :)

I believe most of that should be available in macports repository, [this one](https://trac.macports.org/browser/trunk/dports/gnome/gobject-introspection/Portfile) being probably most important. Then just download zip from github, extract it somewhere and try to run `syncthing-gtk.py`
