### ISSUE TITLE
Brazilian portuguese localization

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#316]
Hi!

May I translate the app to Brazilian Portuguese? I already offered myself on [transifex](https://www.transifex.com/syncthing-gtk/syncthing-gtk/).

**Comment by kozec** [comment]
Sorry, I somehow didn't got notification from that. Approved :)

**Comment by robsonsobral** [comment]
What about the `_`, like in `Sh_utdown Daemon`?

**Comment by kozec** [comment]
That _ makes 'u' hotkey. If you can, add _ before another 'u' in translation and if not, at least try to have different hotkey for each item in menu.

But it will not crash or anything if those rules are not withheld, at worst, it will just inconvenience user.

**Comment by robsonsobral** [comment]
If I created a conflict, by mistake, you can catch it and report back to me, so I can fix it?

**Comment by kozec** [comment]
Yeah, I can check that.

**Comment by robsonsobral** [comment]
Cool!

**Comment by robsonsobral** [comment]
Where is `Auto_update downloaded binary` used?

**Comment by kozec** [comment]
> Auto_update downloaded binary;

In 1st run wizard, when user has no Syncthing installed and chooses to download it using that wizard.

> to %s and keep it up-to-date, but this option is meant as;

At same place, it's part of multi-line message.

```
  message += _("Alternatively, Syncthing-GTK can download Syncthing binary") + " "
  message += _("to %s and keep it up-to-date, but this option is meant as") % \
                                  (target_folder_link,) + " "
  message += _("last resort and generally not suggested.")
```

> (watch)

Here,

![a](https://cloud.githubusercontent.com/assets/1282500/18229130/8b8ac8e6-726c-11e6-93e3-f359e320d184.png)

if filesystem monitoring is activated. Use something short, if possible :)

**Comment by robsonsobral** [comment]
Ok! Here we go! Can we test it?

**Comment by kozec** [comment]
Ok, it almost works :)

There is one hotkey conflict in folder context menu, bot "Edit" and "Explore" are using _E. And left-side menu is not translated. Did you skipped over it or is it a bug?

I'll commit generated mo file into repo, so you can pull it or download is as tarball and test it for yourself by calling `LC_ALL=pt_BR.UTF-8 ./syncthing-gtk.py`

**Comment by robsonsobral** [comment]
I gonna fix the issues. I'm sorry about them.

**Comment by robsonsobral** [comment]
Well... I can't find `Edit` or `Explore` strings. Is the `syncthing-gtk.po` up to date on transifex?

**Comment by kozec** [comment]
Sorry, correct English string is "_Browse" (without ...). And Edit is actually provided and translated by GTK.

**Comment by robsonsobral** [comment]
Houston, we have two problems:

- I can't find any untranslated string. Where's this left-side menu?
- the string `Skiping updatecheck: Daemon not launched by me` is missing;

**Comment by kozec** [comment]
> the string Skiping updatecheck: Daemon not launched by me is missing;

That's for console / debug only, that's not supposed to be translated.

> I can't find any untranslated string. Where's this left-side menu?

When you click on Syncthing icon on top-left side. But there is something else broken around, because I can see those strings traslated on Transifex. "Open _Web Interface" is one of them.

Working on it...

**Comment by robsonsobral** [comment]
> > the string Skiping updatecheck: Daemon not launched by me is missing;
>
> That's for console / debug only, that's not supposed to be translated.

I'm sorry. It's just that there are other strings translated on terminal, like `Syncthing-GTK iniciou e está rodando na área de notificações`.

> When you click on Syncthing icon on top-left side. But there is something else broken around, because I can see those strings traslated on Transifex. "Open _Web Interface" is one of them.

I can see them on my test. They're translated.

(It's soooo weird to look at something translated on ubuntu... I prefer everything in English)

**Comment by robsonsobral** [comment]
Here we go again... New strings done!

**Comment by kozec** [comment]
Thanks!

**Comment by kozec** [comment]
Brazilian Portuguese is now included in [latest release](https://github.com/syncthing/syncthing-gtk/releases).
