### ISSUE TITLE
Tray icon design

### ISSUE THREAD

**Issue by BengaloBongali** [syncthing/syncthing-gtk#318]
I have an idea for a clean tray icon design. I'm sure I can do the design part, but I never really coded, so I'm sceptical about implementation. Maybe you find the time to tell me what kind of files are needed or just tell me where to find the ones currently used and I'll repeat the process with my ideas or if you have a tutorial or something on the implementation part (I really have no idea how difficult that might be), I could try that as well.

Thanks for your work.

**Comment by kozec** [comment]
Well, you need everything starting with "si-syncthing-" from [here](https://github.com/syncthing/syncthing-gtk/tree/master/icons/32x32/status), in 32x32, 24x24 and 16x16 pixels. Add some word just to differentiate it from rest, just like -white- and -black- is there. Then, for testing, just edit `.config/syncthing-gtk/config.json` and set 'icon_theme' so it matches names on those files.

**Comment by BengaloBongali** [comment]
Doesn't sound too complicated, I'll try that! I need to download all files and make test builds, right? Can you direct me to a tutorial to do that? All I did on GitHub until now is commenting...

**Comment by kozec** [comment]
Just downloading everything and running `./syncthing-gtk.py` should work.
