### ISSUE TITLE
Syncthing vs binary vs daemon

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#319]
Should I discuss this on transifex? Is it possible? I don't know.

My point is that Syncthing is mentioned using three different terms on Syncthing-GTK interface:

- Syncthing
- Syncthing Daemon
- binary

Shouldn't we try to create some kind of standard? My vote is for "Syncthing daemon".

**Comment by kozec** [comment]
Well, that binary refers to file, not to Syncthing daemon as instance.

Unifying "Syncthing" and "Syncthing Daemon" would probably make sense, but it would require to re-translate every changed string :(

**Comment by robsonsobral** [comment]
I agree. Example: "Browse for Syncthing binary" could be "Browse for Syncthing daemon binary". Or "Browse for Syncthing daemon file". "File" is less obscure than "binary".

**Comment by kozec** [comment]
That one is on purpose, if you don't know what binary is, you shouldn't really touch that setting :D

**Comment by kozec** [comment]
(closing this in favor of other one)
