### ISSUE TITLE
A directory among folders

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#320]
Shared folders are always referred as it, except for the string `Do you really want to permanently stop synchronizing directory '%s'?`.

Isn't better to use "folder" in this case too?

**Comment by kozec** [comment]
Yeah, that one is ST-GTK specific, so it was not changed when Syncthing suddendly decided to call directories "folder".

Anyway, what can be done here an in #319:
I can add fixed strings as duplicates, so there would be both `Do you really want to permanently stop synchronizing directory '%s'?` and `Do you really want to permanently stop synchronizing folder '%s'?.` but that 2nd one will be unused. Then, after at least most of translations will be updated, I can switch ST-GTK to actually use them.

**Comment by robsonsobral** [comment]
I like the idea.

However, you're the boss, here. I opened it more to help you document what needs to be done.

**Comment by kozec** [comment]
Ok, I've fixed pretty much all those "Syncthing without daemon" inconsistencies and made Syncthing upper case when I was on it. Now I'll upload it to transifex and watch all localisations to get wiped out :D

**Comment by kozec** [comment]
Soo... This and #319 is now fixed in branch and transifex, but that leads to most funny part :)
