### ISSUE TITLE
Connection to daemon failed after Syncthing upgraded to v0.14.6

### ISSUE THREAD

**Issue by zp2133** [syncthing/syncthing-gtk#322]
Hey all...
Same problem that gabkdlly  posted in another thread. Since he was told it was unrelated, I thought I'd post that I'm also having the exact same problem. After upgrading this morning to syncthing v.0.14.6, Syncthing-GTK is popping a 'Connection to daemon failed' error. 

Screenshot:
![screenshot at 2016-09-06 18-41-14](https://cloud.githubusercontent.com/assets/16648151/18294887/45299808-7462-11e6-8c71-2d015eb8e382.png)

Just a semi-technical user, so if more info is required, please let me know.

**Comment by mrbrahman** [comment]
Facing the same issue (Linux Mint Cinnamon).

One thing I notice is that Syncthing daemon is actually running, as I'm able to access Syncthing via browser. However, as soon as I hit "Close" on the error pop-up, Syncthing daemon stops.

**Comment by kozec** [comment]
You mean #321, that another thread, where issue is fixed already? :)

It should work either with ST-GTK v0.9.2.2 or with `insecureSkipHostcheck` set to false in Advanced config of WebUI. I really suggest first option.

**Comment by zp2133** [comment]
Ahh...didn't see that. Thanks kozec.
