### ISSUE TITLE
Empty interface

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing-gtk#326]
I get empty ui. Both sides (folders/devices) are emtpy.

Debian Testing x64

syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:123:44: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:127:19: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:128:32: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:129:38: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:133:19: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:133:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:134:32: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:134:44: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:135:38: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:135:50: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:145:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:146:38: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:147:44: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:151:19: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:152:32: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:153:38: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:157:19: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:157:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:158:32: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:158:44: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:159:38: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:159:50: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-backdrop.css:151:33: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gtk-widgets-backdrop.css:158:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gnome-applications.css:50:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gnome-applications.css:71:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gnome-applications.css:72:35: The :prelight pseudo-class is deprecated. Use :hover instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: gnome-applications.css:107:47: The :prelight pseudo-class is deprecated. Use :hover instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: granite-widgets.css:10:30: The style property GtkNotebook:tab-overlap is deprecated and shouldn't be used anymore. It will be removed in a future version

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: granite-widgets.css:11:30: The style property GtkNotebook:initial-gap is deprecated and shouldn't be used anymore. It will be removed in a future version

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: granite-widgets.css:99:33: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: granite-widgets.css:255:39: The :prelight pseudo-class is deprecated. Use :hover instead.

(syncthing-gtk.py:16629): Gtk-WARNING **: Theme parsing error: xfce.css:90:21: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'
I StatusIcon    Using backend StatusIconGTK3 (primary)

(syncthing-gtk.py:16629): Gtk-WARNING **: Invalid icon size 16

(syncthing-gtk.py:16629): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(syncthing-gtk.py:16629): Gtk-WARNING *_: Invalid icon size 16
syncthing-gtk:17940): Gtk-WARNING *_: Theme parsing error: xfce.css:90:21: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'
I StatusIcon    Using backend StatusIconGTK3 (primary)
V Notifications Error notifications enabled
V Notifications File update notifications enabled
V Daemon        Set refresh interval to 1

(syncthing-gtk:17940): Gtk-WARNING **: Invalid icon size 16

(syncthing-gtk:17940): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(syncthing-gtk:17940): Gtk-WARNING **: Invalid icon size 16

**Comment by kozec** [comment]
Sounds like you have broken GTK theme. What DE, theme and what version of GTK are you using?

**Comment by gerroon** [comment]
@kozec

I am using xfce , cleanice and not sure about version of my gtk.

**Comment by kozec** [comment]
> I am using xfce , cleanice and not sure about version of my gtk.

Sorry, but that part is kinda important :D
Try searching for "gtk" in your package manager and copy or screenshot all numbers that it shows.
