### ISSUE TITLE
BUG: Sporadic change language from Russia to Chinese

### ISSUE THREAD

**Issue by heX16** [syncthing/syncthing-gtk#327]
Some times after reload program, language set to Chinese.

Version: v0.9.2.2

OS Version: Win10 x64, Win7 x64.

**Comment by kozec** [comment]
How? :D

What's your OS language and what do you have set in UI Settings -> Language?

**Comment by robsonsobral** [comment]
Same thing with two friends of mine. The language suddenly change from Brazilian Portuguese to... Chinese? Japanese? I have no idea.

Both running Windows 10.

**Comment by kozec** [comment]
So, there is good chance it is Windows 10 problem...

But I still need to know at least if they are using default (autodetected) language, or have it set to something in configuration dialog.

**Comment by robsonsobral** [comment]
I guess the language is autodetect. I just take a look at another Windows machine and I can't find any Language configuration.

**Comment by kozec** [comment]
In that case, setting it to desired language instead of taking what Windows currently says may help.

**Comment by robsonsobral** [comment]
I can't find this setting, @kozec . Where should it be?

**Comment by robsonsobral** [comment]
No candy for Synthing GTK!

![photo_2016-10-17_16-08-21](https://cloud.githubusercontent.com/assets/931642/19449364/0ec1690c-9484-11e6-9ce7-a07c551560de.jpg)

Version V0.9.2.2-3 running on Windows 10. No Portuguese option. Set as English doesn't work either.

**Comment by kozec** [comment]
Ok, now how could this get broken :(

**Comment by kozec** [comment]
Ok, I'm great on this one... bff7e2a7045a1385c30972321ade28ac520435d9, 327, not 237.

I'll try to make new release with this...

**Comment by kozec** [comment]
Problem should be fixed with [latest release](https://github.com/syncthing/syncthing-gtk/releases)

**Comment by heX16** [comment]
> What's your OS language and what do you have set in UI Settings -> Language?
OS language: Russia.
set in UI Settings: "Русский" (Russia).
