### ISSUE TITLE
Cannot save UI Settings

### ISSUE THREAD

**Issue by williehk** [syncthing/syncthing-gtk#328]
Windows 10 Version 1607
Fresh windows installation, no syncthing daemon pre-installed before running the syncthing-gtk installer.
The UI Settings dialog can be brought up clicking the syncthing logo, the save button is clickable but not working, changes ain't getting saved.
The daemon console does not seems to provide related info.
Any help is appreciated.

I have another windows 10 machine of the same version running syncthing gtk and the save button works.
This particular PC I have the ProfileList registry values pointed to another hard drive other than the %systemdrive%, I am not sure if that is the problem.

**Comment by kozec** [comment]
> ProfileList registry values pointed to another hard drive other than the %systemdrive%, I am not sure if that is the problem.

Depends on what is ProfileList registry :D

There should be `syncthing-gtk-console.exe` located next to regular exe. Try running it and check if there is any error message displayed when you are clicking that button.

**Comment by williehk** [comment]
Thanks, it turned out the installation was having issues with some py scripts
When I clicked the save button it gave TypeError nolen() and same goes for opening the setting dialogs, maybe you could add some checking in there?

A re-installation resolved the issue
