### ISSUE TITLE
No desktop notification option on Windows

### ISSUE THREAD

**Issue by saxaddict591** [syncthing/syncthing-gtk#330]
Hi there, I'm using Windows 10 Pro - 1607 and in UI Settings, my desktop notifications are greyed out.

![image](https://cloud.githubusercontent.com/assets/9093267/19612908/f6e214a2-97ae-11e6-8900-26d18dc603f5.png)

Is this not supported on Windows? This is one reason I would like to use Syncthing-GTK.

Thanks

**Comment by kozec** [comment]
Well, Windows doesn't have desktop notifications, so no, there is no way how to support it there...

**Comment by saxaddict591** [comment]
What about on Windows 10. That has the notification system now.

**Comment by kozec** [comment]
> What about on Windows 10. That has the notification system now.

I don't really have any W10 machine, so W7 is last one supported for ST-GTK.
Plus, AFAIK, only "Universal" Windows Platform applications are able to use those :(
