### ISSUE TITLE
"Host Check Error" on Windows 10

### ISSUE THREAD

**Issue by acastaner** [syncthing/syncthing-gtk#332]
I saw several issues where the "Host Check Error" message was seen from ST version 0.14.6. I think this issue might be different?

I'm running SyncThing 0.14.9 on Windows 10 Pro. Locale is French but OS language is set to US English. I can start SyncThing just fine from the command line. However when trying to use SyncThing-GTK I always meet this error message:

http://i.imgur.com/1TbuOsy.png

It says the GUI is unable to connect to the daemon and that the error is "Host check error."

I know ST itself is fine since it can start manually from the command-line. Could it be the way the GUI spawns the daemon (some command-line parameter) ? The ST API from the daemon is listening on 127.0.0.1:8080

**Comment by acastaner** [comment]
Note that the exact same problems happens on another Win10 computer of mine as well as a Win7 one.

**Comment by kozec** [comment]
What are your settings in webui and what's your version of ST-GTK?

**Comment by acastaner** [comment]
These are my WebUI settings in config.xml:

`<gui enabled="true" tls="false" debugging="false">
        <address>127.0.0.1:8080</address>
        <apikey>ds599usyfpksb0ua1pxh2s9epq25qr</apikey>
        <theme>default</theme>
    </gui>`

ST-GTK version is 0.9.1

**Comment by acastaner** [comment]
Upgrading to 0.9.2.2, which I should probably have done before opening this, fixed the issue. Sorry.
