### ISSUE TITLE
Sign git commits & releases (tags)

### ISSUE THREAD

**Issue by rugk** [syncthing/syncthing-gtk#333]
You should consider signing git commits & releases.
- [onionshare#221 (comment)](https://is.gd/7vU4oK)
- It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
- Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/
- And here is how you can properly sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by kozec** [comment]
Releases are in my OBS repo, on GitHub there are only Windows installers (and no singing can save you there :D)

As for commits, I'll check what's possible, but it looks like big hassle for no recognizable gain...

**Comment by rugk** [comment]
> (and no singing can save you there :D)

Veery funny. Actually also Windows users may care about their security.
And yes, they may find it okay to use Windows.

> Releases are in my OBS repo,

These are the binaries. However I talk about **git** signing of the tags (& therefore the source code of the releases) and not about binaries there. Please have a look at the links I gave.

> As for commits, I'll check what's possible

Okay. You might also go the way the authors of the main repo (https://github.com/syncthing/syncthing/issues/3693) do: Sign tags and not commits.

**Comment by rugk** [comment]
So you close this because of "wontfix" or because you have implemented it?
