### ISSUE TITLE
Please update version in chocolatey

### ISSUE THREAD

**Issue by fsateler** [syncthing/syncthing-gtk#335]
As of this writing the latest version is 0.9.1. Unfortunately it appears that syncthing-gtk just downloads the latest syncthing version, thus now I have v0.14.9, which doesn't work with s-gtk 0.9.1 😢

**Comment by kozec** [comment]
@GeoffreyFrogeye are you still around?

**Comment by GeoffreyFrogeye** [comment]
I am around yet I'm rather busy at the moment. I'll let you know when I'll have fixed #323 and updated the chocolatey package.

**Comment by kozec** [comment]
Great, thank you :)

**Comment by robsonsobral** [comment]
Should chocolatey be removed from the readme for now?

**Comment by GeoffreyFrogeye** [comment]
Ooops, I totally forgot. I have some free time now, doing that today :)

**Comment by GeoffreyFrogeye** [comment]
Done. I think you can close the issue now, @fsateler.
However I think we'll need another co-maintainer since I no longer can test and upload new versions as regularly as before. Preferably someone that uses Windows as its main operating system. I'll add an issue for that.

**Comment by kozec** [comment]
@GeoffreyFrogeye

Is there any chance to get updating in chocolatey at least somehow automated? I have build VM that makes those Windows builds, so running some script that would inform chocolatey about build being ready at very end shouldn't be big problem.

**Comment by GeoffreyFrogeye** [comment]
@kozec Actually there is! This is the point of the [`chocolatey_update.py`](https://github.com/syncthing/syncthing-gtk/blob/master/chocolatey_update.py) script. There should be enough information on how to set the system up in the header comment. It should not be too much of a hassle to adapt it to your build system. It uses GitHub releases though, since the package needs a valid download link to get the installer from.
Also, I realize that the testing I was doing is pretty much useless since the chocolatey servers are testing the packages automatically before a package is allowed to show up.

**Comment by kozec** [comment]
Thanks. I'll try it with next release.

**Comment by acolomb** [comment]
@kozec, care to take this up again? You've recently released 0.9.2.7, but Chocolatey is still on 0.9.2.5. Especially for the recent Windows fixes, a new release on Choco would be great.

Did you ever finish automating this process with `chocolatey_update.py`? Making this part of the regular release process would free you from the burden of remembering :-)

**Comment by ishitatsuyuki** [comment]
For those who really need a chocolatey package: use the script in #406 and install manually.

**Comment by kozec** [comment]
> Did you ever finish automating this process with chocolatey_update.py? Making this part of the regular release process would free you from the burden of remembering :-)

Problem is that there is no automated release process for Windows, neither OBS nor my Jenkins supports such "advanced" stuff. So I still have to build and test this thing manually...

**Comment by robsonsobral** [comment]
Does Travis can help? I don't know. Just thinking out loud.

**Comment by kozec** [comment]
Nope, it's Linux-only, just like OBS as far as I know. I also have Jenkins-based buildserver at home, but it uses docker and so is Linux-only...

TBH, I'm not sure if there even _is_ something that can do this kind of job - installing Python & runtimes, running setup.py and NSIS script and then uploading results - automatically on Windows.

**Comment by fsateler** [comment]
There is appveyor.com (free for Open Source projects), and here is a demo for building python wheels (is this project a python wheel?) applications: https://github.com/ogrisel/python-appveyor-demo.

**Comment by robsonsobral** [comment]
It's outdated again, @kozec .

Sadly, I think isn't possible to install using chocolatey and update using the EXE.

Any recomendation? Should I uninstall SyncthingGTK using Chocolatey?

Thank you!

**Comment by robsonsobral** [comment]
https://chocolatey.org/packages/ChocolateyPackageUpdater

**Comment by GeoffreyFrogeye** [comment]
I just pushed an overdue update for 0.9.4.4, it's awaiting automated review.

I now do have a way to access a Windows machine from time to time again, so I should be able to update the package more regularly than every two years, but no promises 😅 .

> @robsonsobral 
> 
> https://chocolatey.org/packages/ChocolateyPackageUpdater

Thanks, but this solution requires a continuously running Windows system, which I don't have.

**Comment by digitalcoyote** [comment]
Have you considered setting this up in an AU repository? (automatically updates package when it detects a release)
