### ISSUE TITLE
Namespace Rsvg not available

### ISSUE THREAD

**Issue by slaecker** [syncthing/syncthing-gtk#336]
Hi,

just installed syncthing-gtk on my fully updated openSUSE Leap 42.1 from the OBS at http://software.opensuse.org/download.html?project=home%3Akozec&package=syncthing-gtk

I'm on Gnome 3.16.2

When clicking the launcher icon nothing happens. Launching it via terminal reveals the following:

```
$ syncthing-gtk                                                                                      :(
Traceback (most recent call last):
  File "/usr/bin/syncthing-gtk", line 24, in <module>
    gi.require_version('Rsvg', '2.0')
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 100, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Rsvg not available
```

**Comment by kozec** [comment]
Check if there is any package with "rsvg" in name available in distro repositories.

**Comment by slaecker** [comment]
Searching for rsvg I get:

Status | Name | Description
------- |----- |----------------
installed | gdk-pixbuf-loader-rsvg | A Library for Rendering SVG Data -- gdk-pixbuf loader
- | gdk-pixbuf-loader-rsvg-32bit | A Library for Rendering SVG Data -- gdk-pixbuf loader
installed | librsvg-2-2 | Eine Bibliothek zum Rendern von SVG-Daten
- | librsvg-2-2-32bit | Eine Bibliothek zum Rendern von SVG-Daten
- | librsvg-devel | Enthält Dateien und Bibliotheken, die zum Programmieren benötigt werden
- | rsvg-view | SVG Betrachter welcher die GNOME Render SVG Bibliothek benutzt.
- | rsvg2-sharp | Mono bindings for rsvg
- | typelib-1_0-Rsvg-2_0 | A Library for Rendering SVG Data -- Introspection bindings

Which one do I need?

Thanks in advance

**Comment by kozec** [comment]
> Which one do I need?

Now that's great question :D
What you really need is file named `/usr/lib/girepository-1.0/Rsvg-2.0.typelib`, which should belong to librsvg-2-2 package. But seeing you have **typelib-1_0-Rsvg-2_0** available as well, I'd try install that one.

**Comment by slaecker** [comment]
Installing ``typelib-1_0-Rsvg-2_0`` did the trick, syncthing-gtk is now running smoothly. Thanks.
