### ISSUE TITLE
Status difference between Syncthing GTK and Syncthing

### ISSUE THREAD

**Issue by copiis** [syncthing/syncthing-gtk#337]
As seen in the picture, Syncthing GTK remains at 97% and in the web interface everything is up-to-date. Also on another computer everything is up-to-date.
![screenshot-2016-11-28-182538](https://cloud.githubusercontent.com/assets/12480023/20698858/32e0982a-b604-11e6-81a9-272df16f8895.png)

**Comment by kozec** [comment]
Sorry for not reacting sooner... I actually managed to reproduce this and attempted to fix it, but not managed to. And only now I've noticed that problem on mine side is different - some folders are stuck at 97% not only in ST-GTK, but also in WebUI and even on Syncthing-Android.

I'd like to ask if problem still persists on your side an what version of ST-GTK and Synchting are you using.
