### ISSUE TITLE
Small typo in tray context menu

### ISSUE THREAD

**Issue by fiechr** [syncthing/syncthing-gtk#338]
It says "Ongoing rate limit", but shouldn't it be "Outgoing rate limit"?

See [app.glade on line 737](https://github.com/syncthing/syncthing-gtk/blob/bff7e2a7045a1385c30972321ade28ac520435d9/app.glade#L737)

**Comment by kozec** [comment]
Yes, Outgoing is what's supposed to be there :(

**Comment by kozec** [comment]
I have to check how much will this break translations.
