### ISSUE TITLE
Tray icon not fully functional on GNOME

### ISSUE THREAD

**Issue by flexo3001** [syncthing/syncthing-gtk#342]
When starting Syncthing-gtk on Fedora 25 with X11 i get an tray icon inside GNOME but there isn't a menu for control Syncthing as in Unity on Ubuntu. I don't know if this should go to  #297.

Syncthing/-gtk versions:
syncthing.x86_64       0.14.15-1.fc25
syncthing-gtk.noarch  0.9.2.2-2.fc25

**Comment by kozec** [comment]
Ok, now that's more interesting :) Can you try running Syncthing-gtk from terminal and check if there is any error message displayed when tray icon is right-clicked?

**Comment by flexo3001** [comment]
The only output which is relevant:

```
~ $ syncthing-gtk 
I StatusIcon    Using backend StatusIconGTK3 (primary)
```
Everything else are errors because of the connections from device to device.

**Comment by kozec** [comment]
Soo... I ended up installing fedora. Tray icon is actually displayed for a while and it seems fully working, but it gets removed shortly after by _something_ for whatever reason.

I'll investigate further.

**Comment by kozec** [comment]
By the way, on possibly related note, do you have some missing icons anywhere on your side?

**Comment by kozec** [comment]
So, I'm on fresh Manjaro with Gnome 3.22.2, no settings applied, and Syncthing-GTK tray icon is displayed and works as expected.

http://i.imgur.com/Q6qzwqV.png

**Comment by flexo3001** [comment]
I'm getting an icon as well but there is no menu (for shutting down the daemon e.g.) after clicking on it.

**Comment by TheLoko** [comment]
My tray icon has been broken on Gnome for months. I'm actually using Gnome 3.22.2 on Arch. I tried removing the syncthing-gtk config file but it still happens.

**Comment by kozec** [comment]
Hmm... I have 3.22.2 on Manjaro and tray works normally. Left click hides window, right shows menu.

Do you have any specific configuration? Is there _anything_ displayed in console when you click tray icon? It should at least show info about changing refresh interval when you run ST-GTK with `syncthing-gtk -d`

**Comment by flexo3001** [comment]
Nothing shows up in console when clicked. This is what shows up while starting

D UIBuilder     Enabled: header_bar
D UIBuilder     Enabled: is_gnome
D UIBuilder     Enabled: icons_in_menu
D UIBuilder     Loading glade file /usr/share/syncthing-gtk/app.glade
D UIBuilder     Enabled conditions: set([u'icons_in_menu', u'is_gnome', u'header_bar'])
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed node !is_gnome | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'child' by attribute: traditional_header
D UIBuilder     Removed 'child' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed node traditional_header
D UIBuilder     Allowed node traditional_header | icons_in_menu
I StatusIcon    Using backend StatusIconGTK3 (primary)
D Daemon        Reasing syncthing config /home/flexo/.config/syncthing/config.xml
V Notifications Error notifications enabled
V Notifications File update notifications enabled
V Daemon        Set refresh interval to 1

(syncthing-gtk:8947): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Maybe we are missing packages as dependencies?

**Comment by flexo3001** [comment]
Okay, i tried a bit and the result is really strange. I installed a new Fedora with Syncthing-gtk in an virtual machine and the statusicon showed up but wasn't clickable. Then i installed python-appindicator and it worked for some reason. After a few restarts of Synchting-gtk it stopped working.
Afterwards i removed ~/.config/syncthing-gtk and restarted Syncthing-gtk or just restarted Syncthing-gtk multiple times with the option "Minimize to tray on start" on and off. Everytime it is on: the menu is working. Everytime the option is off: the menu stops working.
I hope this helps investigating the problem.

**Comment by computerfr33k** [comment]
The tray icon doesn't work for me as well when using Gnome 3.22 with Wayland, but it does work when using X11.

**Comment by flexo3001** [comment]
@computerfr33k look at #343

**Comment by kozec** [comment]
Just an idea, does running ST-GTK with `GDK_BACKEND=x11 syncthing-gtk` change anything?

**Comment by flexo3001** [comment]
Nope, for me it doesn't change anything.

**Comment by lenucksi** [comment]
@kozec starting with the X11 backend while running on Wayland helped my case.

**Comment by kozec** [comment]
As @argv-minus-one let me know, icon should work on Gnome with [AppIndicator Support extension](https://extensions.gnome.org/extension/615/appindicator-support/).

If it doesn't works automatically in some case, you can force using AppIndicator icon with `SYNCTHING_STATUS_BACKEND=StatusIconAppIndicator syncthing-gtk`


I'm sorry, but since this really is problem in Gnome, not in ST-GTK, this is most likely best solution we can have.

**Comment by argv-minus-one** [comment]
[It's a *design decision* in Gnome](https://wiki.gnome.org/Design/Whiteboards/StatusIcons), actually. I'm sure many disagree (I'm not sure I agree myself), but it's not merely an oversight.
