### ISSUE TITLE
 Tray icon not fully functional on GNOME under Wayland

### ISSUE THREAD

**Issue by flexo3001** [syncthing/syncthing-gtk#343]
When starting Syncthing-gtk on Fedora 25 with Wayland there's no tray icon show up.

Syncthing/-gtk versions:
syncthing.x86_64 0.14.15-1.fc25
syncthing-gtk.noarch 0.9.2.2-2.fc25

**Comment by kozec** [comment]
That's "bug" in Gnome, they dropped trayicons in Wayland backend.

**Comment by flexo3001** [comment]
![screenshot from 2016-12-21 14-40-59](https://cloud.githubusercontent.com/assets/1415596/21391357/ace64a46-c78b-11e6-9806-27729d07af4f.png)

**Comment by kozec** [comment]
https://wiki.gnome.org/Design/Whiteboards/StatusIcons ...

**Comment by flexo3001** [comment]
To bad, the syncthing-gtk tray icon was really useful. Thanks for the link.

**Comment by kozec** [comment]
Well, it will continue to work anywhere _but_ Gnome + Wayland. By the way, does any of those icons in screenshot belong to GTK application? Maybe I could check how they are dealing with it, but I recognize only VLC, which is QT-based.

**Comment by flexo3001** [comment]
I thought it was an malfunction after coming from X11. But if it's seen as deprecated i'm cool with it. Two programs were QT, one Electron and the other i suspect to be https://github.com/fedora-selinux/setroubleshoot which maybe uses GTK.

**Comment by argv-minus-one** [comment]
Syncthing-gtk's indicator works in Gnome on Wayland if this shell extension is installed: https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by jtojnar** [comment]
GNOME suggests to use [libcloudproviders](https://gitlab.gnome.org/World/libcloudproviders) (see [nextcloud PR](https://github.com/nextcloud/desktop/pull/55). Unfortunately, it [does not seem to support introspection](https://gitlab.gnome.org/World/libcloudproviders/merge_requests/23) yet.

**Comment by kozec** [comment]
Gnome removing support for tray doesn't mean I'm going to use different library, it means just that tray icon will not work under Gnome :)

libcloudproviders may be useful thing to eventually integrate, but it's not tray replacement.
