### ISSUE TITLE
[tiny] "syncthing" link in README is broken

### ISSUE THREAD

**Issue by zbentley** [syncthing/syncthing-gtk#345]
The link to the main syncthing page in the first line of the main README in this repo's root is broken; it reads `[Syncthing][syncthing]` in the GitHub readme viewer. The markdown should be corrected to have parentheses.

**Comment by JohnVeness** [comment]
Issue is still present lower down in the dependencies. Also, shouldn't the Syncthing dependency be top of the list? It wasn't immediately obvious to me whether Syncthing-GTK included/reimplemented Syncthing or not.

**Comment by kozec** [comment]
Fixed.

Syncthing is actually least important dependency, as ST-GTK will run without it and can download it when needed. Without those deps above, ST-GTK will not even start.
