### ISSUE TITLE
"Send only" vs "master folder"

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#347]
Now "master folders" are called ["send only"](https://github.com/syncthing/syncthing/issues/2679) on [Syncthing 0.14.17](https://github.com/syncthing/syncthing/releases/tag/v0.14.17). Shouldn't we update the language files?

**Comment by kozec** [comment]
Yeah, will do, but I'm not looking forward to that :)

**Comment by kozec** [comment]
Ok, updated.

**Comment by robsonsobral** [comment]
Transfiex is bugged. I gonna try again later.

I guess you mean "receive", not "recieve". ;-)

**Comment by kozec** [comment]
Yes, I did. Fixed.

**Comment by robsonsobral** [comment]
PT done!

"Outgoing Rate Limit" is duplicated.

**Comment by kozec** [comment]
Yeah, it's on two places with different shourtcuts, but I'll check if it can be unified.
