### ISSUE TITLE
Spanish translation with some errors

### ISSUE THREAD

**Issue by lupa18** [syncthing/syncthing-gtk#351]
There are some Spanish errors on the client. 

How can I help to fix it ? Editing directly po file ?

**Comment by kozec** [comment]
[Transifex](https://www.transifex.com/syncthing-gtk/syncthing-gtk/dashboard/) would be ideal. Otherwise, it will end with someone who knows exactly _uno_ Spanish word (e.g. me) replicating those changes there.

**Comment by lupa18** [comment]
Ok, I did it on Transifex ;)
