### ISSUE TITLE
Issue with plasma and high cpu(fixed itself please remove)

### ISSUE THREAD

**Issue by popcorn9499** [syncthing/syncthing-gtk#352]
So im running syncthing-gtk on kde neon and I've been having problems with syncthing interacting with plasma. Specifically when the notification icon is animated. It causes plasma to have a high cpu usage. I've seen other applications do this fine but for some reason syncthing-gtk doesnt seem to do something right and this inturn makes plasma use alot more memory and slowly leaks until it kills the process. This is a slight annoyance. I figured I'd talk to someone here and see if there are any solutions to my issue.

versions
plasma 5.9 (happened in 5.8 as well)
syncthing-gtk 0.9.2.3 (daemon V0.14.21)

Anything else needed and ill gladly give it to you guys.
Thanks for reading

**Comment by popcorn9499** [comment]
Never mind some updates came through a bit ago that seem to of fixed this. I feel dumb Anyways sorry for creating a useless issue that either was fixed or something to my system only that fixed itself

**Comment by kozec** [comment]
No problem, I self-solving issues are best issues :)
