### ISSUE TITLE
Next/Continue in first run wizard

### ISSUE THREAD

**Issue by JohnVeness** [syncthing/syncthing-gtk#353]
The first run wizard body text refers to a button called Next, but the button actually says Continue. See:
![syncthing-gtk](https://cloud.githubusercontent.com/assets/2512915/22661101/00f2fa78-ec9c-11e6-9746-0ac36b410b0c.png)
Strangely, this is the exact opposite of issue #183 so I don't know what's going on here.

Does the Next/Continue button text depend on GTK version, or OS version, or language, or something?

**Comment by kozec** [comment]
> Does the Next/Continue button text depend on GTK version, or OS version, or language, or something?

Definitely, on all of that and probably even on you using American or British English. But GTK version sounds most probable, what version are you using?

**Comment by JohnVeness** [comment]
I'm not sure how to find out GTK version? I'm on Ubuntu 14.04 and have libgtk2.0-bin 2.24.27-0ubuntu1~trusty1 and libgtk-3-bin 3.10.8-0ubuntu1.6 packages installed, among others.

**Comment by kozec** [comment]
libgtk-3-bin **3.10**.8, so 3.10 would be it. That's pretty archaic, so there is good chance it got changed in later revisions.

**Comment by auntunif** [comment]
เมื่อ 7 ก.พ. 2017 1:43 ก่อนเที่ยง "JohnVeness" <notifications@github.com>
เขียนว่า

**Comment by JohnVeness** [comment]
Well it is (as far as I know) the version in the Ubuntu 14.04 repos, which is still supported for another couple of years.

Is there a string you can lookup that will dynamically insert whatever the button text says into your sentence above?

**Comment by kozec** [comment]
> Is there a string you can lookup that will dynamically insert whatever the button text says into your sentence above?

Good idea. It should be possible to simply get text displayed on button, but I'm not sure if will be translated or original one. I'll check on that.

**Comment by kozec** [comment]
This is fixed, but I'll leave it open so I don't forget to update translation files.

**Comment by JohnVeness** [comment]
Thanks. I wonder if it would be a good idea to do the same for the "Quit" text, just in case it's called "Exit" or something in a different version.

**Comment by kozec** [comment]
> I wonder if it would be a good idea to do the same for the "Quit" text, just in case it's called "Exit" or something in a different version.

I don't think so, for two reasons:

1. That code already is ugly hack and adding more will just make it uglier
2. I can see how Next/Continue may be confusing, as they are sometimes used in different context. But if someone can't find "Quit" button because it's named "Exit", he has much bigger issue than ST-GTK :)

**Comment by kozec** [comment]
Fixed and released.

**Comment by voxspox** [comment]
I've just installed 0.9.2.6-1~webupd8~xenial0
Text here is:
"Please click **Cancel** to create..." and the button label is **Next**
waiting for update...

**Comment by core01** [comment]
@voxspox same Fedora 27, syncthing-gtk 0.9.3.1 ![Imgur](http://i.imgur.com/kWNwptl.png)
