### ISSUE TITLE
Windows Commandline Options

### ISSUE THREAD

**Issue by maiofalmo** [syncthing/syncthing-gtk#356]
Is there any command line options for Windows, I'd like to start it quietly without any popups such as starting daemon, etc.

**Comment by kozec** [comment]
```
[tom@win64 SyncthingGTK] ./syncthing-gtk-console.exe --help
Usage:
  syncthing-gtk-console.exe [OPTION...]

Help Options:
  -h, --help                 Show help options
  --help-all                 Show all help options
  --help-gapplication        Show GApplication options
  --help-gtk                 Show GTK+ Options

Application Options:
  -w, --window               Display window (don't start minimized)
  -m, --minimized            Hide window (start minimized)
  -s, --header               Use classic window header
  -q, --quit                 Quit running instance (if any)
  -v, --verbose              Be verbose
  -d, --debug                Be more verbose (debug mode)
  -1, --wizard               Run 'first start wizard' and exit
  -a, --about                Display about dialog and exit
  --home                     Overrides default syncthing configuration directory
  --add-repo                 Opens 'add repository' dialog with specified path prefilled
  --remove-repo              If there is repository assigned with specified path, opens 'remove repository' dialog
  --display=DISPLAY          X display to use
```

You can ignore that last one, unless you are using X on Windows.

**Comment by maiofalmo** [comment]
That isn't what I'm looking for.

I'm looking to start it silently in the background with no pop-ups, or indication it has started.
Running the console minimized pops up a Command Prompt window minimized.

I take it this functionality doesn't exist?

**Comment by kozec** [comment]
Non-console exe takes same arguments. But just checking "Start when I login to my desktop" and "Minimize to tray on start" in settings dialog should do what you are trying to do...

**Comment by maiofalmo** [comment]
Thanks Kozec.

To start Syncthing-GTK silently use -m switch on the regular exe.

In Powershell: 

Start-Process "C:\Program Files (x86)\SyncthingGTK\syncthing-gtk.exe" -ArgumentList "-m"
