### ISSUE TITLE
FR: Custom File Manager Support

### ISSUE THREAD

**Issue by subaru22b** [syncthing/syncthing-gtk#357]
Ola kozec!

I like to request for custom file manager support, you set the file manager that you like, and when you browse for the folder, you open it on the chosen file manager. 

TIA!

**Comment by kozec** [comment]
Browsing folder uses `xdg-open`, `gnome-open` and `kde-open` in that order, so it should use whatever filemanager you've set in your environment. What desktop are you using?

**Comment by subaru22b** [comment]
I'm not sure about those folder, but I'm on windows, when you right-click on a folder to browse, it will use windows explorer file manager.

**Comment by kozec** [comment]
And what you are using as file manager? I didn't know you can swap them on Windows.

**Comment by kozec** [comment]
So, anyway, from next release onward (or with git version), you can change file browser with registry key `HKCU\Software\SyncthingGTK\file_browser`
