### ISSUE TITLE
Can't set 'logfile' argument on syncthing daemon

### ISSUE THREAD

**Issue by madumlao** [syncthing/syncthing-gtk#358]
Using syncthing-gtk 0.9.2.4 and syncthing 0.14.23 on ubuntu 16.04. Installed from [webupd8 ppa](https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8).

On syncthing-gtk, if I click UI settings -> Advanced -> Daemon arguments and variables, there's a space there for adding arguments. One of the arguments you can set to syncthing is logfile, which allows you to set a logfile for syncthing.

If I add `--logfile="/path/to/log"` and attempt to stop / restart syncthing daemon from syncthing-gtk, it fails to start the daemon.

![cant-invoke-daemon](https://cloud.githubusercontent.com/assets/326612/23644493/8d92b132-0342-11e7-85d8-0a68b1fc8b44.png)

Error persists across any form of logfile argument:
 - /absolute path
- relative path
- quoted with double quotes
- `-logfile=path` (equals)
- `-logfile path` (space)
- `--logfile` form (double dash)
- `-logfile` form (single dash)

However, I can manually start syncthing with the same arguments as `/usr/bin/syncthing --logfile="/path-to-log"` without issues. Syncthing-gtk will detect the daemon as being started.

I am also able to use -logflags with no such errors should syncthing be started.

Does syncthing-gtk do anything special with the logfile that prevents `--logfile` from being read? Is there any advice you can give on setting the logfile in syncthing-gtk? I would like to be able to review the changes shown in the gui after closing the app.

**Comment by kozec** [comment]
I'll have to check this at normal PC, but ST-GTK starts daemon in mode without its supervising process, so logfile flag probably doesn't works.

**Comment by calmh** [comment]
Correct, Syncthing will reject the `-logfile` parameter in that case.

**Comment by madumlao** [comment]
Is there anything I can do to make it log to a file then? Not seeing anything in the manpage that references the supervising process or how to control it.

**Comment by calmh** [comment]
In this setup that's the responsibility of Syncthing-GTK.

**Comment by kozec** [comment]
Well, syncthing-gtk captures daemon output and displays it in window, but it shouldn't be problem to add option to write it to stdout so it can be captured, if that's what @madumlao is trying to do.

**Comment by calmh** [comment]
Yep. I have no opinion on that, just happened to note the discussion about the root cause. :)

**Comment by kozec** [comment]
So, with above, `syncthing-gtk -o` outputs Syncthing daemon output in same way as just running `syncthing` would, so it can be captured normally.
