### ISSUE TITLE
Ambiguous use of passive voice in syncthing notifications

### ISSUE THREAD

**Issue by madumlao** [syncthing/syncthing-gtk#360]
Syncthing-gtk notifications use an ambiguous form that can be confusing for new users. For example:

~~~
100 files were updated on the remote device
~~~

In English this can mean either of 2 things - which are actually opposites of each other
- we updated 100 files on the remote device using syncthing
- we detected that 100 files on the remote device were updated, so we are going to update 100 files on our device

For more clarity, you can specify the two things separately:
- what was updated
- what action was taken

For example:
~~~
(100 files)[http://link-to-log-entry] on `lenneth` are going to be updated by syncthing.
~~~

Or alternate form:
~~~
(100 files)[http://link-to-log-entry] on this device are going to be updated by syncthing
~~~

**Comment by kozec** [comment]
Ok, I see how that is confusing, as that message actually means "We've downloaded 100 files after they were updated on the remote device".

So, shortest way to expres that would be "100 files were updated **from** the remote device". Is that clear enough?

(Sorry, I'm nowhere near native English speaker)

**Comment by kozec** [comment]
Does this sounds unambiguous enough?

`Updated file something.txt was downloaded from remote device.`

`20 updated files were downloaded from remote device.`

`20 files were downloaded and 5 deleted to reflect changes on remote device(s).`


There is also `The file 'something.txt' was deleted on remote device.` that is not changed.

**Comment by madumlao** [comment]
basically pick actions, events, or both, but be consistent.

So if you have one message that says

`Updated file something.txt was downloaded from remote device`

In format (event ->action)

then all your status messages should be in "event -> action" format. So the first two are ok together:

`Updated file something.txt was downloaded from remote device.`

`20 updated files were downloaded from remote device.`

The third breaks the pattern:

`20 files were downloaded and 5 deleted to reflect changes on remote device(s).`
(action -> event)

The fourth is ambiguous.

`The file 'something.txt' was deleted on remote device.`
(not sure if event or action).

By making the pattern consistent, the user spends less mental energy determining what happened. Or in other words, consistent notifications are basically just "prettied up" log messages.

---

The (action -> event) pattern seems most flexible if you want to combine multiple events. All of the following messages are in the same form:

`The file something.txt was downloaded to reflect changes on Computer A`
`10 files were downloaded to reflect changes on Computer A`
`10 files were downloaded to reflect changes on remote devices`
`10 files were downloaded and 5 deleted to reflect changes on remote devices`


There is merit in being able to view the specifics, which is why I suggest a link to the logs in the last case, though Im not sure there is infra in syncthing to filter the logs that specifically.

**Comment by madumlao** [comment]
I just thought of an edge case while typing this, hoping not to complicate matters that much.

Sometimes I run syncthing-gtk both on my laptop and the laptop across the room via `ssh -X` - for obvious reasons, of course, it's a syncing app. In which case the assumed localhost destination is ambiguous if I get notifications from both of them.

Maybe the pattern (host: action -> event) or (destination -> source) is least ambiguous in that vein.

---
## host: action -> event
`lenneth: downloaded "something.txt" to reflect changes from lezard`
`lenneth: downloaded 10 files to reflect changes from lezard`
`lenneth: downloaded 10 files and deleted 5 files to reflect changes from lezard`
`lenneth: downloaded 10 files and deleted 10 files to reflect changes from remote devices`

PROs:
- wording consistency
- eye always looks in same place for destination, changes, source
- if the notification daemon truncates the text, the most important part is first (dest and changes)

CONs:
- kinda wordy (maybe another wording could be picked)

---
## destination action -> source event
`"something.txt" on lenneth was updated from lezard`
`10 files on lenneth were updated from lezard`
`15 files (10 updates, 5 deletions) on lenneth were updated from lezard`
`20 files (10 updates, 10 deletions) on lenneth were updated from remote devices`

PROs:
- can be shorter

CONs:
- position of the destination host moves a lot, eye tracking

**Comment by kozec** [comment]
Trouble with host > event is that ST-GTK (and syncthing probably neither) knows from which host was file downloaded. Those notifications are always talking about changes performed locally, so

`lenneth: downloaded "something.txt" to reflect changes from lezard`
`lenneth: downloaded 10 files to reflect changes from lezard`
`lenneth: downloaded 10 files and deleted 5 files to reflect changes from lezard`
`lenneth: downloaded 10 files and deleted 10 files to reflect changes from remote devices`

... sounds best. Especially because, IIRC, hostname can be placed in bold line above, so it's separated visually.

**Comment by madumlao** [comment]
that sounds good.

**Comment by kozec** [comment]
Fixed and released.
