### ISSUE TITLE
Web interface password

### ISSUE THREAD

**Issue by Index-true** [syncthing/syncthing-gtk#361]
The Web interface password is kept in clear in the ~/.config/syncthing/config.xml preventig from login in using the password on the web GUI. Solution is to hash the password using bcrypt before putting it in the config file.

**Comment by kozec** [comment]
Weird... I though that syncthing daemon is supposed to hash it when started.

**Comment by Index-true** [comment]
That may be a bug from the core id don't realy know

**Comment by calmh** [comment]
Auto-converting cleartext passwords was removed in Syncthing v0.12.0 (hashed passwords were added in v0.8.1). Since then, a cleartext password in the config should simply mean it's impossible to log in.

**Comment by kozec** [comment]
> was removed in Syncthing v0.12.0 

(fixed in timely-manner as usual :) )
