### ISSUE TITLE
Keys cannot be generated on first startup

### ISSUE THREAD

**Issue by bmjstau** [syncthing/syncthing-gtk#362]
When starting the program for the first time, generating keys fails with
`syncthing-gtk: Configuration directory: '/home/ben/.config/syncthing'`
`syncthing-gtk: Syncthing configuration directory: /home/ben/.config/syncthing`
`04:51:55 WARNING: chmod /home/ben/.config/syncthing: permission denied`
`04:51:55 FATAL: Create certificate: save cert: open /home/ben/.config/syncthing/cert.pem: permission denied`

Starting syncthing-gtk as `sudo syncthing-gtk` does not fix this issue.

**Comment by kozec** [comment]
Sorry for late response, notification somehow ended in spam folder :(
Just in case you didn't managed to solve it already:

Starting syncthing-gtk or syncthing with sudo is most likely what caused that issue. Check if  `~.config/syncthing` has permissions set to 700 and make sure you are owner of it. Running syncthing with sudo most likely changed ownership to root.
