### ISSUE TITLE
Option to disable Tray animation?

### ISSUE THREAD

**Issue by pantar85** [syncthing/syncthing-gtk#363]
hey looking for a way to disable the syncthing tray from being able to make any animations. thank you. on windows [grr]

**Comment by kozec** [comment]
Well, you can probably just replace all icon "stages" in icons/16x16/status/ with first one :)

**Comment by kozec** [comment]
So, with git or after next release, toggle _animate_icon_ option to false with registry editor :)

**Comment by pantar85** [comment]
wow cheers thank, such an obvious fix. also going to use the icon as default for my actual syncthing folders so they stand out a bit more. thank you for your work!!
