### ISSUE TITLE
Change Icon - Custom

### ISSUE THREAD

**Issue by nebutron** [syncthing/syncthing-gtk#364]
Sorry if this isn't the right place but I am wondering how I can change the icon that is being used.

I know you have default, black and white. I have my own that I'd like to use. How/where can this be changed?

Using Antergos Cinnamon Desktop.

**Comment by kozec** [comment]
There is no "official" way other than maybe including icons in icon theme that GTK is using, but you can as well just create icons named `si-<something>-0.png` and then set that "<something>" as `icon_theme` value in config file.

**Comment by nebutron** [comment]
I have no idea where that config file is? Please and thanks

**Comment by kozec** [comment]
`~/.config/syncthing-gtk/config.json`

**Comment by nebutron** [comment]
Found that, now I just don't know where to put the icons. I put them where the other default icons are and it does not seem to work.

**Comment by kozec** [comment]
> I put them where the other default icons are and it does not seem to work.

Where is that?

**Comment by nebutron** [comment]
~/usr/share/icons/hicolor/32x32/status (they are in 16x16 and 36x36 as well)

At least that is where I found the default icons.

**Comment by kozec** [comment]
That path is weird, but I just tested that placing them in `~/.local/share/icons/hicolor/16x16/status` works. But you may need to call `gtk-update-icon-cache` to let GTK know about change.

**Comment by nebutron** [comment]
I do have ~/.local/share/icons/hicolor/16x16 but there is only a folder apps within it not status. Just some random icons inside of it.

So clearly my cinnamon desktop places things in different places. The location I found them in I did reboot and all that, but didn't do any updating of cache. Not sure how to do that (just type what you typed in the terminal?).

You are getting me closer though. Thanks. Not sure why it isn't working :( Should I have them in only 16x16, or within the other ones as well (32 and 36)?

**Comment by kozec** [comment]
> Not sure how to do that (just type what you typed in the terminal?).

Yep, exactly.

Both /usr/share... and ~/.local/share... should work, but ~/.local/... is where user "overrides" are supposed to go, so that one is probably better.

> Should I have them in only 16x16, or within the other ones as well (32 and 36)?

Just 16x16 should be enough, but if icon shows with scaling artifacts, you can use 22x22, 32x32 etc to get better looking image.

**Comment by nebutron** [comment]
Well that sucks. Not working.

Maybe I should create the Status folder in the  .local area? Thanks for the help though. I will try to keep at this.

**Comment by kozec** [comment]
Weird...

Make sure that ST-GTK doesn't run, check if this output matches on your side

```
[tom@silver ~]$ gtk-update-icon-cache 
[tom@silver ~]$ file ~/.local/share/icons/hicolor/16x16/status/si-test-unknown.png 
/data/tom/.local/share/icons/hicolor/16x16/status/si-test-unknown.png: PNG image data, 32 x 32, 8-bit/color RGBA, non-interlaced
[tom@silver ~]$ grep icon_theme ~/.config/syncthing-gtk/config.json 
    "icon_theme": "test",
```

and try starting ST-GTK. It should load and shown that `si-test-unknown.png` icon right after start.

**Comment by nebutron** [comment]
I created the Status folder under the URL you shared and it seems to sort of work.

When syncthing is offline/or devices offline, its working. Once its syncing or online it shows a error icon like before.

I currently have si-syncing-0.png all the way to 10 and then one called si-syncing-unknown.png. All used for the animation of loading. Yet only the unknown one is being used now.

**Comment by kozec** [comment]
Sorry for late response, I had to test it. Aren't you missing `si-syncing-idle.png` by any chance?

**Comment by nebutron** [comment]
Thanks. Not sure why that was not shown in the other area.

Anyways, adding that seems to have worked. I don't think the animation is working, but I can live with that. It shows online when online and the offline one when offline.

Cool
