### ISSUE TITLE
Whose fault is that ?

### ISSUE THREAD

**Issue by Coeur-Noir** [syncthing/syncthing-gtk#365]
Hi,
well a picture of the problem : 
![capture du 2017-04-20 12 27 25](https://cloud.githubusercontent.com/assets/1895947/25226532/a3a6f6cc-25c5-11e7-80dc-8517f7caef7b.png)

Syncthing is v0.14.26 on Ubuntu 14.04 64 bits.
Syncthing-gtk is 0.9.2.4-1 from webupd8 ppa.

**Comment by kozec** [comment]
Looks cool :)

Have you removed any fonts recently? Does any other GTK application something similar?

**Comment by Coeur-Noir** [comment]
If you like squares ;-)

This happens on one machine and not the other two ( all ubuntu 14.04 ).

I quite often deal with fonts - so yes I might have removed somes, added others - but mostly trying to store them into my personal folder.

Problem solves itself when I quit and relaunch syncthing-gtk.

**Comment by kozec** [comment]
Dunno, this looks like some issue with GTK itself or maybe even memory error. You can try running `syncthing-gtk -d` in console to check if there is any error message, but there is no font-handling code in ST-GTK, so this really doesn't looks like caused by ST-GTK itself.

**Comment by fifthrider** [comment]
Can confirm same problem with syncthing-gtk 0.9.2.4-1 and syncthing 0.14.26. No font problems elsewhere on my system, either, nor am I experiencing memory errors. Also, as it manifests in my case, it appears to be more than just a font-handling bug:

![screenshot at 2017-04-25 10 23 00](https://cloud.githubusercontent.com/assets/2129790/25390432/82963d1e-29a1-11e7-80f9-f4638af73089.png)

**Comment by fifthrider** [comment]
Update:
Stranger still, when I went back and checked four hours after relaunching syncthing-gtk, certain of the icons (but not all of them) crashed to placeholders when I moused over them, but the text continued to render correctly. It looks like this now: (I've matted out the actual shares, for obvious reasons.)

![partialcrash](https://cloud.githubusercontent.com/assets/2129790/25398058/953b80d4-29b8-11e7-9bbd-97d4974afd42.png)

**Comment by kozec** [comment]
Output from that `syncthing-gtk -d` would be really helpful if you can replicate it reliably. Are you on Ubuntu 14.04 as well, @fifthrider?

**Comment by fifthrider** [comment]
Yes; I'm running Mint 17.3 MATE on this device, which is based on 14.04.
I'll let it run for a few hours with the debug output enabled and see what
comes of it.

**Comment by fifthrider** [comment]
I've noticed something already in the stderr output: every time the window is closed to tray, and about half the time when the window loses focus, I get this:

```
(syncthing-gtk:19064): Gtk-WARNING **: Invalid icon size 24


(syncthing-gtk:19064): Gtk-WARNING **: Invalid icon size 24
```

There's nothing in the stdout. If it helps, I'm running with numix-circle icons and am using Marco + compositing as my window manager mode.

**Comment by kozec** [comment]
> (syncthing-gtk:19064): Gtk-WARNING **: Invalid icon size 24

This shouldn't matter, it'll just use upscaled 22px or downscaled 32px icons.

> I'm running Mint 17.3 MATE on this device, which is based on 14.04.
> There's nothing in the stdout. If it helps, I'm running with numix-circle icons and am using Marco + compositing as my window manager mode.

Ok, thanks. I'll try to install same combination in VM and enable every debug it has :D

**Comment by Coeur-Noir** [comment]
Sorry, very busy those days…

I forget an important detail : when that problem happens, icons no longer work. I mean it's as if syncthing-gtk does not work anymore - but yet syncthing is still doing its job in background.

**Comment by Coeur-Noir** [comment]
Today I get this few minutes after booting my computer : 
![capture du 2017-05-02 10 17 34](https://cloud.githubusercontent.com/assets/1895947/25609804/159afa80-2f21-11e7-8fc2-4ec9d830fff7.png)
…don't know if it's related.

**Comment by kozec** [comment]
@Coeur-Noir any chance of getting entire message? There should be Traceback shown on bottom of that list.

**Comment by Coeur-Noir** [comment]
`palace4@ANTEC:~$ syncthing-gtk 
W StatusIcon    StatusIcon: Using backend StatusIconAppIndicator (fallback)
I App           
I App           Syncthing-GTK en cours d'éxécution dans la zone de notification
E Daemon        Impossible de se connecter à 127.0.0.1 : Connexion refusée
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 413, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Impossible de se connecter à 127.0.0.1 : Connexion refusée
E Daemon        Impossible de se connecter à 127.0.0.1 : Connexion refusée
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 413, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Impossible de se connecter à 127.0.0.1 : Connexion refusée
I App           updatecheck: disabled
`
is what I get today.

Regarding Traceback, is this info saved somewhere ?

**Comment by kozec** [comment]
So, no error at all :(

> Regarding Traceback, is this info saved somewhere ?

It should got to /var/crash, but I'm reading that from [their wiki](https://wiki.ubuntu.com/Apport)
