### ISSUE TITLE
rundll32.exe does not allow Windows XP machine to shut down

### ISSUE THREAD

**Issue by NCDanielH** [syncthing/syncthing-gtk#367]
When I try to shut down/restart a Windows XP machine running SyncthingGTK, it hangs for a bit and then asks to force close `rundll32.exe`, continuing with shutdown normally if I click "End Now". If I don't click it, `syncthing.exe` and `rundll32.exe` are both present in the Task Manager afterwards, but `syncthing-gtk.exe` is not.

I've been running the current version of Syncthing on this computer since its release, but the issue only appeared yesterday when I installed Syncthing-GTK.

Syncthing-GTK exits properly and allows the computer to shut down if I close it manually via _Syncthing icon_>Quit. Reopening it before shutting down brings back the issue. Closing it and then running `syncthing-gtk-console.exe` does NOT bring back the issue. I haven't tried every flag, but I have tried `-d`, so I unfortunately can't provide you any useful logs that way.

The computer runs 32-bit Windows XP SP3 (I know, I know) and does not connect to the internet, only the local network. I've tested it on one other computer configured similarly, and the issue persists. I installed and tested another GTK application (gedit), and it does not produce this issue.

Syncthing-GTK `v0.9.2.4-win32` (Syncthing `v0.14.27`)

**Comment by kozec** [comment]
Thing is, ST-GTK doesn't do anything that should start rundll32, ever. Plus code called when ST-GTK is getting close is pretty simple - kill syncthing daemon, kill syncthing-inotify, Gtk.Application.quit().

There was similar issue #273 where similar problem was caused by audio driver hooking to random processes. Another possibility is antivirus. IIRC, you can [display full command line](https://social.technet.microsoft.com/Forums/getfile/160213) in windows task manager and rundll32.exe take name of dll as argument. Can you check if there is anything interesting displayed there?

**Comment by NCDanielH** [comment]
Task Manager doesn't have the command line option in Windows XP, but [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) does, so I used that to get `"C:\WINDOWS\system32\rundll32.exe" C:\PROGRA~1\SYNCTH~1\LIBGIO~1.DLL,g_win32_run_session_bus@16` for the full command line. The `\SYNCTH~1\` matches `\Syncthing-GTK\`, as Syncthing is installed to a different directory.

The process description for `rundll32.exe` is "Run a DLL as an App." Killing it also causes Syncthing-GTK to close (without visible error).

**Comment by kozec** [comment]
So, I've ended up installing Windows XP, but found that it can't run exes generated on W7 build machine at all...

Have you done anything special to get ST-GTK running there?

**Comment by NCDanielH** [comment]
I didn't make any changes to the system. Just ran the installer file `SyncthingGTK-v0.9.2.4-win32-full-installer.exe`, and it worked fine except for this issue. I can't say for sure whether the machine's previous maintainer had set up any compatibility workarounds for other programs; it's possible, but pretty unlikely.
