### ISSUE TITLE
Gnome on Wayland: Syncthing-gtk lingers with no windows open and no indicator

### ISSUE THREAD

**Issue by argv-minus-one** [syncthing/syncthing-gtk#369]
Per #343, syncthing-gtk's indicator does not appear when running on Gnome on Wayland. Despite this, when syncthing-gtk's main window is closed, its process does not terminate.

When running under a shell that lacks indicator support, syncthing-gtk should terminate when its window is closed. Also, “minimize to tray on start” (in the UI settings) should be grayed out.

Note that [this Gnome Shell extension](https://extensions.gnome.org/extension/615/appindicator-support/) *adds* indicator support. If that extension is running, syncthing-gtk's indicator will function as normal, so lingering and minimize-to-tray are fine.

**Comment by kozec** [comment]
Sorry, but running on Wayland is simply not supported.

There is currently no way to detect that indicator icon is not shown on Gnome Shell, as GTK reports it as present even if there is no tray area. So if appindicator with that extension works, you know better solution as I do :)

**Comment by argv-minus-one** [comment]
Wayland is the future of the Linux desktop. To flatly declare it “not supported” is to flatly declare the imminent irrelevance of your own project. I understand the problem you have with this issue in particular, but I urge you to reconsider your general attitude toward Wayland support.

**Comment by kozec** [comment]
> Wayland is the future of the Linux desktop. 

Then Linux desktop is deeply screwed :)

You have this problem wrong way around. It's not like ST-GTK blocks tray icon, it's Gnome (and Wayland in general) what simply doesn't have that feature.
