### ISSUE TITLE
Please allow disabling the indicator

### ISSUE THREAD

**Issue by argv-minus-one** [syncthing/syncthing-gtk#370]
Since you're unable to do anything about #369 and #342, please add some way to turn off syncthing-gtk's indicator. In this mode, it would not attempt to show an indicator, and would not linger after the main window is closed.

**Comment by calmh** [comment]
At that point, what functionality does syncthing-gtk add over the plain syncthing ui?

(Genuine question from a non-syncthing-gtk-user because I'm curious, not argumentative.)

**Comment by argv-minus-one** [comment]
syncthing/syncthing#3983 proposes to add a way to control Syncthing over a Unix socket instead of loopback TCP. As discussed there, this will greatly improve security and ease-of-use. But because browsers don't [and will never](https://bugs.chromium.org/p/chromium/issues/detail?id=451721) support HTTP over Unix sockets, the only way to use this feature is with a tool like syncthing-gtk.

Also, because I can put syncthing-gtk into Gnome Shell's dock for easy access, but I can't do that with a browser-based application.

**Comment by kozec** [comment]
`SYNCTHING_STATUS_BACKEND=none syncthing-gtk` will start ST-GTK without tray icon.

**Comment by calmh** [comment]
I see, thanks. I don't use Gnome, but it sounds like it would be useful if they allowed adding bookmarks or commands like "syncthing -browser-only" to the dock. Perhaps that could be a feature request.

The unix socket support is a good point. If that gets implemented it will indeed require a separate application for the GUI.
