### ISSUE TITLE
setup.py installs syncthing-gtk.desktop with potentially-incorrect Exec

### ISSUE THREAD

**Issue by argv-minus-one** [syncthing/syncthing-gtk#371]
I used `./setup.py install --user` to install syncthing-gtk under `~/.local`. This works fine, except that the resulting `~/.local/share/applications/syncthing-gtk.desktop` contains `Exec=/usr/bin/syncthing-gtk`. This should be rewritten during installation to wherever the script was actually installed to.

**Comment by kozec** [comment]
Can you run `syncthing-gtk` (without any path) with --user installation? In that case, I can just remove /usr/bin part and let PATH do its magic.

**Comment by argv-minus-one** [comment]
Only if `~/.local/bin` is in PATH. On Debian (which I use), it isn't. On this distribution, by default, PATH is `/usr/local/bin:/usr/bin:/bin`. There is no entry in PATH that the user can write to.

I'm not sure what other desktop Linux distributions do. I understand that `~/bin` is semi-common, but I'm not sure how many (if any) have that in PATH by default.

You could have the install script look through the PATH it's executed with, and see if any of the entries are owned and writable by the user running the installer. If one is found, write the script there, and use PATH in the .desktop file. But there's no guarantee that this will work—again, on Debian, it won't—so it's not a complete solution.

The only sure-fire way is to have the absolute path to syncthing-gtk in the .desktop file. It is inelegant, but it also doesn't depend on user or system configuration like relying on PATH does. Perhaps this should be a fallback option in case there is nothing user-owned in PATH.

**Comment by kozec** [comment]
My main problem with this is that both changing copied desktop file _and_ determining where exactly your ~/.local/bin is seems equally impossible with setuptools :(

**Comment by argv-minus-one** [comment]
Damn.

Well, you're right that you should probably rely on PATH in the .desktop file. At least that has a *chance* of working if installed with `--user`, and it should still work if installed in `/usr/bin`.

**Comment by argv-minus-one** [comment]
I was mistaken in my earlier comment. On Debian, the default PATH includes `~/bin`, if it exists. So, installing the executable there will work on a default Debian system.

Note that `~/bin` doesn't *exist* by default, so it needs to be created during installation.

**Comment by kozec** [comment]
> Note that ~/bin doesn't exist by default, so it needs to be created during installation.

That should be done automatically for any folder setup.py is trying to place files in.
