### ISSUE TITLE
Problems with dmrc permissions

### ISSUE THREAD

**Issue by lupa18** [syncthing/syncthing-gtk#372]
Helo, 
After installing syncthing-gtk I began having a problem with $HOME/.dmrc permissions and now I can't make automatic login. I tried to fix it without success. Sscreenshot:

![img_20170428_134049](https://cloud.githubusercontent.com/assets/463429/26322314/719f6ef6-3ef8-11e7-969d-ebcb27b1e1e8.jpg)

**System:** linux mint 18.1

Can someone help me? thanks in advance!

**Comment by kozec** [comment]
Sorry, but I don't think this is in any way related to Syncthing nor ST-GTK...

**Comment by lupa18** [comment]
I'm sure thar this appeared when I install S-GTK using Web Upd8 PPA. Do you think I should open a ticket in their bug tracker?

**Comment by kozec** [comment]
You can try that, but just setting correct permissions on file and your home folder may be faster.

**Comment by lupa18** [comment]
I think I just try it.

I will do it again.
