### ISSUE TITLE
Crash with UnicodeEncodeError

### ISSUE THREAD

**Issue by jtojnar** [syncthing/syncthing-gtk#381]
I am using Syncthing-GTK 0.9.24 on Ubuntu. Suddenly it crashed with the following error:

```
Traceback:
 Traceback (most recent call last):
   File "/usr/lib/python2.7/dist-packages/syncthing_gtk/notifications.py", line 140, in cb_syncthing_item_updated
     print "cb_syncthing_item_updated", folder_id, path
 UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 63: ordinal not in range(128)
```

**Comment by kozec** [comment]
That's already fixed, but there was no release since then. I have small problem with build machine, but I'll try to get at least Linux releases out there.

As temporary fix, you can just delete that line, it's there just to show what's being done.

**Comment by kozec** [comment]
(... and that release happened yesterday)
