### ISSUE TITLE
Unclear Notifications

### ISSUE THREAD

**Issue by abueide** [syncthing/syncthing-gtk#382]
When it says "X files updates/deleted on remote device" its unclear whether its telling you that syncthing updated x files on the remote device, or if there were x files that were updated on the remote device and it is now syncing onto the local device. The wording just kind of confuses me.

**Comment by kozec** [comment]
Yeah, this was discussed in #360 and that sentence should read "Downloaded _file.txt_ to reflect remote changes"

**Comment by abueide** [comment]
oh sorry I didn't notice that issue, thanks @kozec
