### ISSUE TITLE
cannot start syncthing-gtk under the newest archlinx

### ISSUE THREAD

**Issue by chxp** [syncthing/syncthing-gtk#384]
When start syncthing-gtk in terminal, it shows:

    (syncthing-gtk:7762): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
    
    (syncthing-gtk:7762): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
    
    (syncthing-gtk:7762): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
    
    (syncthing-gtk:7762): GLib-GIO-CRITICAL **: g_dbus_proxy_get_name_owner: assertion 'G_IS_DBUS_PROXY (proxy)' failed
    /usr/lib/python2.7/site-packages/syncthing_gtk/app.py:120: Warning: GError set over the top of a previous GError or uninitialized memory.
    This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
    The overwriting error message was: The name org.freedesktop.portal.Desktop is not owned
      Gtk.Application.do_startup(self, *a)
    Segmentation fault (core dumped)

no window shows.

syncthing-gtk version
community/syncthing-gtk 1:0.9.2.4-1

**Comment by kozec** [comment]
That's weird, it still works on my Arch machine. What desktop environment are you using?

**Comment by chxp** [comment]
after `echo $GDMSESSION` , it shows:

    /usr/share/xsessions/plasma

**Comment by kozec** [comment]
Ok, so I've ended up installing Arch + Plasma and there are multiple problems here.

Everything appears OK on my side. ST-GTK works and none of those errors and warnings appears, especially not that one about not having DBUS. So I'd guess that's your main problem. Check if you are not running Wayland or have something else broken.
That version is outdated, so upgrading _may_ help, but I wouldn't bet on that.


Also, entire plasma desktop appears to crash when I press delete, but that's most likely unrelated problem :D

**Comment by chxp** [comment]
I don't know how to check the Wayland...

I have tried to install the newest syncthing-gtk through code (through python2 setup.py install), however, I installed and end up with:

    synchting-gtk

    Traceback (most recent call last):
      File "/usr/bin/syncthing-gtk", line 26, in <module>
        from syncthing_gtk.tools import init_logging, init_locale
      File "/usr/lib/python3.6/site-packages/syncthing_gtk/__init__.py", line 4, in <module>
        from timermanager		import TimerManager
    ModuleNotFoundError: No module named 'timermanager'

Further:
    
    sudo pip2 install timermanager
    
    Collecting timermanager
      Could not find a version that satisfies the requirement timermanager (from versions: )
    No matching distribution found for timermanager

`pip2 search timermanager` shows nothing... something boring...

So I will wait for the new release of syncthing-gtk in pacman database... Maybe the newer version will works...

**Comment by kozec** [comment]
Sorry for late answer, I somehow missed 2nd part of your message.

timermanager is module in syncthing-gtk, you don't need pip for it. Also, sorry, but I really missed this 1st time :(

> /usr/lib/python**3.6**/site-packages/syncthing_gtk/__init__.py

I'm not sure how, but you are hitting Arch's bug no. 1. Try removing everything ~~and use sane distro~~ and install it again, but make extra sure to use python**2** during all steps.

**Comment by chxp** [comment]
Ha, I am in home now, while the laptop with archlinux is in dorm.

So I will try it when school opens, about September. Thank you very much.
