### ISSUE TITLE
Syncthing-GTK 0.9.2.5 fails to autostart on reboot in  W10

### ISSUE THREAD

**Issue by hugalafutro** [syncthing/syncthing-gtk#385]
Hi,
as the title says, here is the screenshot of the error: https://turbomrak.ddns.net/s/Z0EZGHx6SUeybVJ

More Info:
All following is identical in behaviour on 2 machines, both W10 Creators Update 64bit.

0.9.2.4 worked as expected. Installed 0.9.2.5 over, error happens on reboot. Subsequent manual launch of Syncthing-GTK after closing the error window works as expected. Tried clean install (uninstalled syncthing-gtk, deleted program files/syncthing-gtk folder, installed 0.9.2.5). Ran out of ideas.

Should you need any further info about my system just tell me what you need to know.

**Comment by kozec** [comment]
Sounds like start directory is not being set.

Can you try running syncthing-gtk-console.exe using cmd.exe, from some random directory and then from directory where it is located?

**Comment by hugalafutro** [comment]
Hi,
did what you asked the results are in the screenshot: https://turbomrak.ddns.net/s/NRqL1LZwTE3AaCW

**Comment by kozec** [comment]
Ok, now try to add path to executable in that first case :)

**Comment by hugalafutro** [comment]
Hi,
doing that produces i think the same error as in the first screenshot just as text output in console: https://turbomrak.ddns.net/s/QYbT1SQtnwjLjme

**Comment by kozec** [comment]
Ok, great, so error is where I thought, but I can't really imagine what's causing it.

As workaround for now, you can simply disable autostart and drag&drop syncthing-gtk shortcut into "Start up" program group, it should do same thing and start from where it is supposed to.

**Comment by hugalafutro** [comment]
Thanks for the workaround, can confirm it works. Not sure if i should close this, will leave that your consideration, seeing as the issue isn't fixed.

**Comment by kozec** [comment]
> Not sure if i should close this, will leave that your consideration, seeing as the issue isn't fixed.

Definitely not, I'm able to forget about it otherwise :)

**Comment by pantar85** [comment]
can also confirm this error. but unlike OP i cannot start up client afterwards. so have no way to run it at all.

**Comment by seiferflo** [comment]
Hi. I have the same issue. It appeared with 0.9.2.5 as well on W10x64b16251. 
I can start properly manually Syncthing.

**Comment by kozec** [comment]
Closing this in favor of #391, if anyone is still watching, please try if [build in this comment](https://github.com/syncthing/syncthing-gtk/issues/391#issuecomment-329954230) works with your Windows 10 installation.
