### ISSUE TITLE
Installer considered as malware

### ISSUE THREAD

**Issue by justpusher** [syncthing/syncthing-gtk#387]
Windows installer v.0.9.2.5 is considered as malware by Avast and 3 more antiviruses.  

Here are detection results on VirusTotal: https://virustotal.com/ru/file/7e706df5d108bea954eec980dbabb0bf6fe2cf4400342705500282cbe9f3ac57/analysis/1501408913/

**Comment by ProactiveServices** [comment]
This is not a bug in Syncthing, it is a bug in Avast. Please report it to them.
