### ISSUE TITLE
gtk ui not in sync with web interface

### ISSUE THREAD

**Issue by CookingCookie** [syncthing/syncthing-gtk#392]
OK my system setup might be a bit weird and might be the cause of the problem here.
I have syncthing-gtk installed on Ubuntu 16.04 which is installed inside a VMware Workstation virtual machine. After I had syncthing-gtk installed and connected to another device I created a snapshot of the state of the virtual machine. When I reverted back to the snapshot the syncthing web interface would reconnect to the other device but the gtk UI would simply say "disconnected". In order to fix this I had to pause and then unpause the connection to the other device in the gtk UI. It seems to me the gtk UI fails to stay in sync with the web interface.

**Comment by kozec** [comment]
Have you reverted that another device or machine where ST-GTK was running on?

**Comment by CookingCookie** [comment]
The one where ST-GTK was running on
