### ISSUE TITLE
Interface opens on plugging external monitors

### ISSUE THREAD

**Issue by somini** [syncthing/syncthing-gtk#393]
I'm using i3 on Arch Linux.

When I plug in an external monitor, autorandr kicks in an adjust the monitor configuration. This causes syncthing-gtk to show its main window unprompted.

Is there a way to disable this behaviour?

**Comment by kozec** [comment]
There is no code that would just randomly display main window, so my best guess is that this is done by window manager.

**Comment by somini** [comment]
It's a strange bug that I can always reproduce but can't identify where is this coming from.
I'll reopen if I ever find any reason for this.
