### ISSUE TITLE
"No write access to daemon binary" error

### ISSUE THREAD

**Issue by tiubuk** [syncthing/syncthing-gtk#394]
Hi!
I'm using Syncthing-GTK on Solus (on 2 machines, same error). Strangely, when I start Syncthing first (in terminal) then Syncthing-GTK, all works correctly. But when I launch Syncthing-GTK first (with Syncthing launched inside), I have this error:

> Warning: no write access to daemon binary; Skipping update check.

Then, I can't modify any configuration of shares or machines.
I understand the second part concerns the auto-update. But, what about of the first one? Is it a problem with Solus? Or not a bug, just a "feature"? :)

Thanks for answer!

**Comment by kozec** [comment]
It's not really error, it's warning. You most likely have syncthing installed by package manager, in `/usr/bin/` and so ST-GTK is not able to overwrite it with updated version. And it shouldn't be, upgrading should be left on package manager. So when ST-GTK detects such situation, it displays warning and skips entire update check procedure.

**Comment by tiubuk** [comment]
OK, thanks! It works perfectly without the auto-update!
