### ISSUE TITLE
Failed to Generate Keys

### ISSUE THREAD

**Issue by JefiServices** [syncthing/syncthing-gtk#395]
Error on generating RSA keys for syncthing-gtk
"Failed to Generate Keys
Syncthing daemon failed t generate RSA keys or certificate

Output from error log

syncthing-gtk: Configuration directory: 'C:\Users\Jefi Services\AppData\Local\syncthing'
syncthing-gtk: Failed to create configuration directory
syncthing-gtk: [Error 183] Cannot create a file when that file already exists: u'C:\\Users\\Jefi Services\\AppData\\Local\\syncthing'
syncthing-gtk: Syncthing configuration directory: C:\Users\Jefi Services\AppData\Local\syncthing

**Comment by kozec** [comment]
Check if `C:\Users\Jefi Services\AppData\Local\syncthing` is there and if it is a directory. Sounds like you have remains of previous installation of syncthing in you home directory.

**Comment by JefiServices** [comment]
Yes I did check and deleted the directory. even after reboot and no directory I get the same issue.

**Comment by kozec** [comment]
You are getting `Cannot create a file when that file already exists` even though that file doesn't exists?

**Comment by JefiServices** [comment]
this PC  running windows 10 was a clean install. it has never completed this processes and crashes out of the setup. I am going to try and remove ALL aspects of syncthing, reboot and try again. I have never used syncthing on this PC previously.
