### ISSUE TITLE
caja: Super ugly huge syncthing icon

### ISSUE THREAD

**Issue by HaoZeke** [syncthing/syncthing-gtk#397]
Hi.
The syncthing integration has an icon size issue.
This is only a problem for icon view and compact view... It's ok in list view.

It's really a huge problem for compact view because the icon blots out a few icons nearby as well...

Any ideas on what could be causing it?
![Icon View](https://user-images.githubusercontent.com/4336207/30773171-c2938210-a088-11e7-82f0-b39db0ec4473.png)
![Compact View](https://user-images.githubusercontent.com/4336207/30773172-c299c6a2-a088-11e7-86d5-618735448728.png)

Aux details: Archlinux with BSPWM. The theme is arc-grey.

**Comment by kozec** [comment]
How emblems are rendered is up to filemanager, so this is probably not caused by ST-GTK directly. How are other emblems? Are they drawn at expected size?

**Comment by HaoZeke** [comment]
Everything else seems to be alright... I thought it might have something to do with with the icon pack, but changing that doesn't help...

**Comment by Hapoofesgeli** [comment]
Is there a way I can just disable those emblems? (sorry if kinda unrelated to the bug report, tough can't find anything in docs and forum, and no help on IRC)

**Comment by kozec** [comment]
Either by disabling integration in settings or by deleting those icons, if you need to keep rest of integration working.

**Comment by kozec** [comment]
Sorry, I was wrong about about caja-specific set of icons. Those emblems are common for all filemanagers, so creating set for only one of them doesn't looks possible.

I'm afraid that only thing I can do is to disable icons in caja or simply caja integration entirelly...
