### ISSUE TITLE
v0.9.2.6 for Windows - missing library

### ISSUE THREAD

**Issue by WarmChocolateCake** [syncthing/syncthing-gtk#399]
Hi,
  I've just installed v0.9.2.6 for Windows - which installs fine.

  However, when I close syncthing-gtk and then re-start it, I get:
"The program can't start because libgnutls-28.dll is missing from your computer. Try reinstalling the program to fix this problem."

  Looking at the downloaded installer, that file doesn't exist...

  Apart from that, it then seems to work...?!

Keep up the good work! :)

**Comment by jantograaf** [comment]
Same issue here on a clean Win7 Pro install of version 0.9.2.6. 

Other than this, keep up the good work!

**Comment by kozec** [comment]
(im not ignoring this, but I'm in process of getting out of 6th layer of DLL hell right now :( )

**Comment by WarmChocolateCake** [comment]
> (im not ignoring this, but I'm in process of getting out of 6th layer of DLL hell right now :( )

No worries

**Comment by kozec** [comment]
... aaand fixed in last release.
