### ISSUE TITLE
File managers integration

### ISSUE THREAD

**Issue by gentoo90** [syncthing/syncthing-gtk#40]
Users shoud be able to manipulate syncronization from their file managers.
I wrote simple [integration script](https://gist.github.com/gentoo90/f7fdb8284643b1c175a9) for Caja (MATE file manager).
For now it can only add/remove folders to syncthing and show emblems on added folders:
![caja-syncthing](https://cloud.githubusercontent.com/assets/1297574/5323921/91dc4be2-7cdd-11e4-93b5-b949ee66b46f.png)

What do you guys think? Maybe there's something else implemented already?

**Comment by kozec** [comment]
Just FMI, would Caja pick plugin written for Nautilus? That means plugin placed in `~/.local/share/nautilus-python/extensions`,  importing Nautilus extension library. Other option is to have separate plugin for each Nautilus derivate. So far there are Nautilus, Caja, Nemo, Files and other one also named Files.

That'll get messy really fast...

**Comment by gentoo90** [comment]
RabbitVCS has [separate plugins for each](https://github.com/rabbitvcs/rabbitvcs/tree/master/clients)
Maybe something like
```python
if check_if_in_nautilus_folder():
    from gi.repository import Nautilus as FM
elif check_if_in_caja_folder():
    from gi.repository import Caja as FM
elif...
...
class SyncthingMenuProvider(GObject.GObject, FM.InfoProvider, FM.MenuProvider):
...
```
will do the trick. But I'm not sure if they all have fully compatible interfaces.

**Comment by kozec** [comment]
I think I just understood why is fragmentation problem in opensource space :D

But yeah, it's not a big problem.

**Comment by kozec** [comment]
This is now implemented and (pre)released.
Thanks for suggestion :)
