### ISSUE TITLE
configuration error (something about locales + ascii)

### ISSUE THREAD

**Issue by vn971** [syncthing/syncthing-gtk#401]
It's not my computer, but here's what I see when trying to launch syncthing-gtk the first time on a win7 computer:

```
syncthing-gtk: Configuration directory: 'C:\Users\TN\AppData\Local\syncthing'
syncthing-gtk: Failed to create configuration directory
syncthing-gtk: [Error 183] ?????????? ??????? ????,: u'C:\\Users\\TN\\AppData\\Local\\syncthing'
syncthing-gtk: Syncthing configuration directory: C:\Users\TN\AppData\Local\syncthing
syncthing-gtk: chosen port 8080
syncthing-gtk: Traceback (most recent call last):
File "C:\syncthing-gtk\syncthing_gtk\wizard.py", line 725, in save_settings
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1115-1116: ordinal not in range(128)
```

The main locale of this user/computer is Russian.

Since saving the configuration fails, I cannot use syncthing on this computer at all, yet. (Which would mean the bug is serious enough.) Any thoughts as to why that could happen? Thank you.

**Comment by kozec** [comment]
Error 183 is "Cannot create file when that file already exists", it shouldn't be fatal. But that 2nd one indicates  some mess. Do you have some non-latin characters in your username, path to home directory or anywhere else? Windows doesn't handle those well..

**Comment by vn971** [comment]
> anywhere else
yes of course.:D But in the username, no, IIRC. Anyway, syncthing should be able to run when the user has a non-latin name, shouldn't it?
I hope it's not a "won't fix", is it?

**Comment by kozec** [comment]
> Anyway, syncthing should be able to run when the user has a non-latin name, shouldn't it?

Syncthing most likely, syncthing-gtk nope, at least not on Windows. But if this is not a case, it should be fixable. I can try some blind fixes, but finding what exactly is causing the crash would help. Is there any config.xml in that directory? Can you check if there are any Cyrillic characters in it?

**Comment by vn971** [comment]
I tried to re-install on this computer. The only path I didn't know about (that I could get) is this:
* "Download Daemon" > "Установка завершена" (installation completed) > path: `C:\Users\TN\AppData\Local\syncthing\syncthing.exe`

BTW, somewhy the error reason got changed. Here's what I'm getting now:
```
syncthing-gtk: Configuration directory: 'C:\Users\TN\AppData\Local\syncthing'
syncthing-gtk: Failed to create configuration directory
syncthing-gtk: [Error 183] ?????????? ??????? ????,: u'C:\\Users\\TN\\AppData\\Local\\syncthing'
syncthing-gtk: Syncthing configuration directory: C:\Users\TN\AppData\Local\syncthing
syncthing-gtk: chosen port 8080
syncthing-gtk: Traceback (most recent call last):
File "C:\syncthing-gtk\syncthing_gtk\wizard.py", line 685, in save_settings
File "C:\Python27\lib\xml\dom\minidom.py", line 1928, in parseString
File "C:\Python27\lib\xml\dom\expatbuilder.py", line 940, in parseString
File "C:\Python27\lib\xml\dom\expatbuilder.py", line 223, in parseString
ExpatError: no element found: line 1, column 0
```

**Comment by vn971** [comment]
This is weird BTW, dut I don't have neither `C:\syncthing-gtk`, nor `C:\Python27`.

**Comment by vn971** [comment]
Some more details:

* when I try to run syncthing-gtk as root, it fails to start "Unable to run program because libgnutls-28.dll is not present on the computer. Try to re-install the program" (I translated from Russian as I could, it's not the precise wording).
* I also tried to re-run syncthing-gtk installer as root. It was hard. At first it complained something about already present file (or something like that). I tried to uninstall syncthing*, but after running the thing from Control Panel > uninstall programs, the path `C:\Program Files (x86)` was still present. I tried to remove it to no avail. Then I tried to find it in running processes, and succeeded (it was silently running itseems, probably half-dead). After killing the process I was able to remove the mentioned directory.

**Comment by vn971** [comment]
* If I run `syncthing-gtk-console.exe` from normal user from console, I get a tiny bit more details. Now the log says:
```
'C:\Program Files (x86)\SyncthingGTK\lib\gio\modules\libgiognutls.dll' module not found.
Failed to load module: C:\Program Files (x86)\SyncthingGTK\lib\gio\modules\libgiognutls.dll
```

**Comment by vn971** [comment]
Is it hopeless, or can we fix it?.. Now that I understood it's python under Windows, the sense of doom became more pronounced for me.:D

**Comment by vn971** [comment]
UPD:
I tried to install just the "core" syncthing from `github.com/syncthing/syncthing/releases/**` It's a zip file, I unzipped. When I try to run it, it fails, and I get this:
```
C:\Users\TN\Downloads\vasya\syncthing-windows-amd64-v0.14.39>syncthing.exe
[monitor] 15:23:10 INFO: Log output saved to file "C:\Users\TN\AppData\Local\Syn
cthing\syncthing.log"
[monitor] 15:23:10 INFO: Starting syncthing
[JAVL5] 15:23:10 INFO: syncthing v0.14.39 "Dysprosium Dragonfly" (go1.9 windows-
amd64) teamcity@build.syncthing.net 2017-09-25 06:05:21 UTC
[JAVL5] 15:23:10 INFO: My ID: JAVL5EL-VV6LZ2H-2SONYVV-AZDNWVT-ZPOJ4Z2-IQJHTXJ-YR
UO3Q3-A7KUZQU
[JAVL5] 15:23:11 INFO: Single thread SHA256 performance is 318 MB/s using minio/
sha256-simd (215 MB/s using crypto/sha256).
[JAVL5] 15:23:11 INFO: Default folder created and/or linked to new config
[JAVL5] 15:23:11 FATAL: Config: EOF
[monitor] 15:23:11 INFO: Syncthing exited: exit status 1
[monitor] 15:23:12 INFO: Starting syncthing
[JAVL5] 15:23:12 INFO: syncthing v0.14.39 "Dysprosium Dragonfly" (go1.9 windows-
amd64) teamcity@build.syncthing.net 2017-09-25 06:05:21 UTC
[JAVL5] 15:23:12 INFO: My ID: JAVL5EL-VV6LZ2H-2SONYVV-AZDNWVT-ZPOJ4Z2-IQJHTXJ-YR
UO3Q3-A7KUZQU
[JAVL5] 15:23:13 INFO: Single thread SHA256 performance is 312 MB/s using minio/
sha256-simd (211 MB/s using crypto/sha256).
[JAVL5] 15:23:13 INFO: Default folder created and/or linked to new config
[JAVL5] 15:23:13 FATAL: Config: EOF
[monitor] 15:23:13 INFO: Syncthing exited: exit status 1
[monitor] 15:23:14 INFO: Starting syncthing
[JAVL5] 15:23:14 INFO: syncthing v0.14.39 "Dysprosium Dragonfly" (go1.9 windows-
amd64) teamcity@build.syncthing.net 2017-09-25 06:05:21 UTC
[JAVL5] 15:23:14 INFO: My ID: JAVL5EL-VV6LZ2H-2SONYVV-AZDNWVT-ZPOJ4Z2-IQJHTXJ-YR
UO3Q3-A7KUZQU
[JAVL5] 15:23:15 INFO: Single thread SHA256 performance is 315 MB/s using minio/
sha256-simd (213 MB/s using crypto/sha256).
[JAVL5] 15:23:15 INFO: Default folder created and/or linked to new config
[JAVL5] 15:23:15 FATAL: Config: EOF
[monitor] 15:23:15 INFO: Syncthing exited: exit status 1
[monitor] 15:23:16 INFO: Starting syncthing
[JAVL5] 15:23:16 INFO: syncthing v0.14.39 "Dysprosium Dragonfly" (go1.9 windows-
amd64) teamcity@build.syncthing.net 2017-09-25 06:05:21 UTC
[JAVL5] 15:23:16 INFO: My ID: JAVL5EL-VV6LZ2H-2SONYVV-AZDNWVT-ZPOJ4Z2-IQJHTXJ-YR
UO3Q3-A7KUZQU
[JAVL5] 15:23:17 INFO: Single thread SHA256 performance is 313 MB/s using minio/
sha256-simd (212 MB/s using crypto/sha256).
[JAVL5] 15:23:17 INFO: Default folder created and/or linked to new config
[JAVL5] 15:23:17 FATAL: Config: EOF
[monitor] 15:23:17 INFO: Syncthing exited: exit status 1
[monitor] 15:23:18 WARNING: 4 restarts in 7.9464545s; not retrying further

C:\Users\TN\Downloads\vasya\syncthing-windows-amd64-v0.14.39>
```

**Comment by vn971** [comment]
I've created an issue in the main project: https://github.com/syncthing/syncthing/issues/4431
IDK if it's relevant to syncthing-gtk or not.

**Comment by calmh** [comment]
I'm guessing that

 - the config included non-ascii data, which is fine and expected but syncthing-gtk failed to encode the XML, creating an empty config file
 - syncthing fails from that point on due to the empty config file

**Comment by vn971** [comment]
@calmh agree on both statements. @kozec I guess you decide what to do best with the issue now. I don't mind closing.

**Comment by kozec** [comment]
Yes, that's seems to be case, I just don't have any mean to test it :) Anyway, assuming _that_ was entire problem, it should be fixed in latest release.

**Comment by vn971** [comment]
Could actually be a fix. Considering the first error was about encoding, and all others were different. Thank you!
