### ISSUE TITLE
Nautilus integration problems

### ISSUE THREAD

**Issue by petko10** [syncthing/syncthing-gtk#404]
Hello, firstly thank you for the great app! I've been using it for a while (mostly for the notifications), and yesterday I saw that there actually is file manager integration. I'm using Manjaro and installed the python2-nautilus dependency, but the nautilus integration isn't activated (no special icon on ST folders, no context menu item). The output when I run syncthing-gtk via the terminal isn't very helpful:
```
I StatusIcon    Using backend StatusIconGTK3 (primary)
I App           
I App           Syncthing-GTK started and running in notification area
I App           updatecheck: disabled

(syncthing-gtk:7243): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

So, can you give me some pointers to what might be broken ? I'm pretty sure it's something in my configuration, since there's no info (that I've managed to find) on the internet on such a problem.

**Comment by kozec** [comment]
Output from syncthing-gtk doesn't say anything, you have to get output from nautilus.

IIRC, it's `nautilus -q` to kill all nautilus-related and then just `nautilus` to see output from new process.

**Comment by petko10** [comment]
Nautilus doesn't say much either. There's a Dropbox initialization message (the only Nautilus addon that seems to be working) and after that there's :
`sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.`
Is there a chance that the Nautilus integration is disabled in the Arch build. Or is there a special way to configure/activate this functionality?

**Comment by kozec** [comment]
I'd like to say that I know why this fixes everything while doing exactly same thing using factory method doesn't, but I have no idea...

Anyway, it should work now.

**Comment by petko10** [comment]
Finally I had time to look into it more, and I figured out that the problem was from the Arch installation and not ST-GTK itself . Sorry for the trouble . Here's a link to the bug report (the script file for the extension is just misplaced) https://bugs.archlinux.org/task/57123
