### ISSUE TITLE
Window borders disappear in windows 10

### ISSUE THREAD

**Issue by rafaelhipercg** [syncthing/syncthing-gtk#405]
![2017-10-29](https://user-images.githubusercontent.com/10676754/32149139-68376ee6-bce7-11e7-80d4-b3bbbdfd62e7.png)

I'm using the v0.9.2.7. every time I change some folder setting, the border disappears and moves to the corner of the screen. Is this a bug? because this has already happened on 3 computers that I have, all are windows 10.

**Comment by kozec** [comment]
Yes, and it is one of those bugs that are reappearing randomly no matter I do :(

Best workaround currently is to go to UI Settings and disable "Use traditional window header", as the new one doesn't have this problem.
