### ISSUE TITLE
OSX High Sierra Safari Version 11.0.1 (13604.3.5) will not open Syncthing Page.

### ISSUE THREAD

**Issue by CaptainKhan** [syncthing/syncthing-gtk#407]
Cookies allowed, no ad blocker installed, no flash blocking, added exceptions for non https secured or certificate revoked connection in Safari. No cigar. Same works fine in Firefox.

I did add UI password and username to change settings, same username/password works in firefox, doesn't login in Safari.

Please fix, this is a BUG.

Safari:
![screen shot 2017-11-01 at 9 08 50 pm](https://user-images.githubusercontent.com/23108558/32309510-43585f36-bf49-11e7-9d0a-2c99c3ced6fb.png)
Firefox:
![screen shot 2017-11-01 at 9 12 16 pm](https://user-images.githubusercontent.com/23108558/32309520-610a2e6a-bf49-11e7-9fa1-85aa75f11a95.png)

**Comment by kozec** [comment]
Wrong repository? ST-GTK doesn't work on OSX and Syncthing errors are here - https://github.com/syncthing/syncthing/issues
