### ISSUE TITLE
Does not start syncthing anymore

### ISSUE THREAD

**Issue by teresaejunior** [syncthing/syncthing-gtk#408]
I had syncthing-gtk configured to open the daemon by itself. After the last upgrade, syncthing-gtk refused to start, so I found that now it expects the daemon to be already running. If I don't manually run syncthing before syncthing-gtk, the following error appears:

```
E Daemon        g-io-error-quark: Não foi possível conectar-se a 127.0.0.1: Conexão recusada (39)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 413, in _rest_connected
    con = sc.connect_to_service_finish(results)
Error: g-io-error-quark: Não foi possível conectar-se a 127.0.0.1: Conexão recusada (39)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 691, in cb_syncthing_con_error
    if check_daemon_running():
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/tools.py", line 306, in check_daemon_running
    p = Popen(["killall", "-u", os.environ["USER"], "-q", "-s", "0", "syncthing"])
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 37: ordinal not in range(128)
```

Also, the option to autostart syncthing-gtk on login now always appears as unchecked, although `~/.config/autostart/Syncthing-GTK.desktop` is still properly created.

**Comment by kozec** [comment]
> I found that now it expects the daemon to be already running.

It shouldn't expect that, it just fails to determine if one is running, as shell fails to work with your usename. May I ask how did you managed to get non-ascii characters in it? :D

I can fix that one, but I'm not sure if it not going to break anywhere else.

**Comment by teresaejunior** [comment]
Hi, thanks for your answer! Do you mean in my username? The username is just "teresaejunior"!

**Comment by kozec** [comment]
Ok, that's weird. Where is that UnicodeDecodeError comming from...

What locale are you using? Portuguese?

**Comment by teresaejunior** [comment]
pt_BR.UTF-8

**Comment by teresaejunior** [comment]
The Unicode error was in `child_exception`, which contained `os.environ["PATH"]`. $PATH indeed contained non-ascii directories, so I'm closing this, because I don't really expect other programs to work well with a non-standard $PATH (I had recently included a few directories to PATH with scripts that I was still testing).

**Comment by kozec** [comment]
Great, thanks for letting me know. I'm not sure if this still isn't a bug, but in Python, not in st-gtk.

**Comment by calmh** [comment]
Python's handling of character sets is a bug. :)

`</unpopular-opinion>`

**Comment by kozec** [comment]
> `</unpopular-opinion>`

I don't think anyone ever doubted that :D
