### ISSUE TITLE
Add "UI Settings" item to other menus

### ISSUE THREAD

**Issue by gaelanlloyd** [syncthing/syncthing-gtk#410]
Hey there!  I'm a big fan of the project and have an enhancement request.

I was trying to find a way to disable sync notifications but couldn't find anything.  I even read [this](https://github.com/syncthing/syncthing-gtk/issues/390) and got even more stumped because there was no "Settings" menu that I could find.

Then almost by accident I clicked on the Syncthing icon in the top left of the program's interface and was surprised to find out that it also was a menu with unique items under it!

To help others in the future, could "UI Settings" be added to the very prominent gear menu?  It would also be a great addition to the system tray icon menu.  It seems like a good menu item to have quick access to.

I'm using the Arch Linux version of syncthing-gtk, v 0.9.2.7-1 under XFCE.

![ui-settings](https://user-images.githubusercontent.com/1403649/32927077-6fc4b68e-caff-11e7-9417-f5865af0c546.png)

**Comment by kozec** [comment]
Dunno, logic here is that everything that affects Syncthing is under "gear" and everything that affects GUI is under icon of GUI.

Maybe I should add some tooltip that displays buble with "Hello, I'm the menu" randomly...

**Comment by gaelanlloyd** [comment]
What about adding "UI Settings" to the system tray icon menu?  That menu has "About," which is also under the GUI icon menu.

**Comment by kozec** [comment]
Yeah, that is not a problem.

**Comment by gaelanlloyd** [comment]
Sweet, thanks!
