### ISSUE TITLE
is inotify in use?

### ISSUE THREAD

**Issue by voxspox** [syncthing/syncthing-gtk#411]
I can specify a rescan interval. I wonder what is the purpose of this setting with installed syncthing-inotify package. How can I test if inotify is used? 

syncthing-gtk                               0.9.2.6-1\~webupd8\~xenial0
syncthing-inotify                           0.8.7
syncthing                                   0.14.40

**Comment by kozec** [comment]
If you have inotify enabled in ST-GTK, running syncthing-inotify and rescan interval enabled, you have three things monitoring same thing. It will not cause any harm, but it's pretty redundant.

**Comment by kozec** [comment]
It's that "Monitor filesystem for changes" option right bellow rescan interval.

**Comment by voxspox** [comment]
ok, thx!! The note about too low rescan intervals was puzzling for me. I thought inotify will be completely responsible for file changes. What is the purpose of the rescan interval then?

**Comment by kozec** [comment]
> What is the purpose of the rescan interval then?

It makes sense when inotify is _not_ used, or if you are not using ST-GTK all the time while leaving Syncthing in the background.

**Comment by voxspox** [comment]
This means, if I start/close ST-GTK then syncthing-inotify is also started/stopped. Thus if I choose to don't stop the daemon when quiting ST-GTK then syncthing runs without inotify and the rescan interval option becomes effective. Is this correct?
