### ISSUE TITLE
Tray icon blur in high DPI screen (Windows 10)

### ISSUE THREAD

**Issue by Reeeeeemi** [syncthing/syncthing-gtk#419]
Blur UI in high DPI windows. Override high DPI scaling behavior make it look better, but the tray icon is still a blur.
![image](https://user-images.githubusercontent.com/14024960/35665161-cc3b3072-075f-11e8-9d57-c908da34e615.png)

**Comment by kozec** [comment]
Sadly, tray is rendered in 32x32 or 16x16px no matter what image you give it, so this is most likely unfixable.
