### ISSUE TITLE
Can't use on systems with proxy

### ISSUE THREAD

**Issue by MisterY** [syncthing/syncthing-gtk#421]
After the installation, the app was unable do download daemon from my internal network. I was unable to set the proxy from the GUI.
After timeout the app crashed and I am unable to run it again.

Is there a parameter or a config setting for proxy? It should at least try to read HTTP_PROXY environment variable.

**Comment by kozec** [comment]
Download is done through gio library, which should use proxy configured in dconf or gconf (or windows registry, depending on where you are running :))

But on Linux, it's usually better to use syncthing package from repository.
