### ISSUE TITLE
Poppnig up dialogues gets in the way

### ISSUE THREAD

**Issue by muelli** [syncthing/syncthing-gtk#424]
When switching networks, for example, st-gtk produces a popup with only one quit button. This dialogue has the focus and grabs the input.
That is really annoying when typing texts in other applications. Especially when you type the space bar, because then st-gtk quits.

I think a more useful (for me at least) design involves getting rid of dialogues altogether and replaces them with something like interactive libnotify notifications.

**Comment by kozec** [comment]
That's weird, that dialog should not grab focus at all. What distro and desktop are you using? Don't you have some setting that automatically gives focus to any new window enabled somewhere?

**Comment by muelli** [comment]
I run a relatively freshly installed Ubuntu 17.10 with the default GNOME desktop. No surprises there. And I am not aware of having configured any setting.
But I'm not surprised by that behaviour. I think it's what Gtk does if you produce a new modal dialogue.

**Comment by kozec** [comment]
So, after playing with Gnome a little, I'm 99% sure this is window manager problem. That dialog requests attention, but does not asks for focus.

Best I can suggests is to check if that behavior can't be disabled in gnome-tweak.

**Comment by kozec** [comment]
Well, dialog is created [here](https://github.com/syncthing/syncthing-gtk/blob/master/syncthing_gtk/app.py#L1290) and there is no call to focus nor present, so there shouldn't be any reason for it to be raised or given focus.

**Comment by muelli** [comment]
Interesting. Do you also happen to have a link to the relevant piece of the documentation that supports your expected behaviour?

**Comment by kozec** [comment]
Nope, I don't have documentation saying that _shouldn't_ be done :D 

I've just tried same thing with Compiz, XFWM, Openbox and Metacity (ie every WM I have installed) and seen no such behavior anywhere else.

**Comment by kozec** [comment]
By the way, I just checked and normal Gnome Shell doesn't do that either, only Gnome Shell on Wayland does. I'm not entirely sure if that's bug or feature though...

**Comment by kozec** [comment]
In that case, it will still be both weird and specific to those distros, I see no problem with that label :D
