### ISSUE TITLE
0.9.3 can't connect to daemon

### ISSUE THREAD

**Issue by TrueXakeP** [syncthing/syncthing-gtk#426]
Syncthing-GTK 0.9.3 can not connect to Syncthing daemon (v0.14.45-rc.3, Windows (64 bit) nor 0.14.44).
A window which is telling that connection to daemon is lost pops up and then disappears. A tray icon blinking from gray to blue.

I've done some research and find `400 Bad Request` responses from Syncthing. They appears in two cases.

First case is about missing `Host` header in 
https://github.com/syncthing/syncthing-gtk/blob/8efafb6c05635f65fa504ce0d161a21f2ce2c52f/syncthing_gtk/daemon.py#L1344
req: `GET /rest/events?since=4455 HTTP/1.1\r\n`
res: `HTTP/1.1 400 Bad Request: missing required Host header\r\n`
Request from Syncthing itself have the `Host` header and `X-CSRF-Token-F5DWQ` header which is also duplicated as a cookie.

Second case is that I have folder with ID=`Phone memory` with space inside (I've create it far ago with old version of Syncthing before the folder-id concept was introduced). And it's not urlencoded in the request so Request URI is becoming `/rest/db/status?folder=Phone`.
req: `GET /rest/db/status?folder=Phone memory HTTP/1.0\r\n`
res: `HTTP/1.1 400 Bad Request\r\n`
Correct request from Syncthing itself is: `GET /rest/db/status?folder=Phone%20memory HTTP/1.1\r\n`

I don't have this issue with Syncthing-GTK 0.9.2.7

Wireshark dump which illustrates the problem: [SyncthingGTK.pcapng.gz](https://github.com/syncthing/syncthing-gtk/files/1750837/SyncthingGTK.pcapng.gz)
Windows 8.1 Enterprise x64
Syncthing-GTK 0.93
Syncthing 0.14.45-rc3 and 0.14.44

P.S. Sorry for my english.

**Comment by kozec** [comment]
Only thing weird about all of this is that none of those problems occurs for me. Maybe it's somehow Windows 8, but not Windows 7 specific.

**Comment by TrueXakeP** [comment]
Thank you for the fix and the program itself. It is very handy.
Just tested right now. It works like a charm.
