### ISSUE TITLE
Allow ignoring the daemon path configuration

### ISSUE THREAD

**Issue by jtojnar** [syncthing/syncthing-gtk#427]
On Nix, each update of a software is installed to a different path – it may be in `/nix/store/qg2z50kid1h3swhkg6l1vr2g4yxvjqzi-syncthing-0.14.36/` one time, and in `/nix/store/0xv109h6hpccdhy4pqqywxqx17jf4d9b-syncthing-0.14.37/` the next. The system takes care of setting the `PATH` correctly.

Now, syncthing-gtk finds the syncting deamon on `PATH` and saves it to config. This setting will persist after an update, pointing to an old version, and it will break after the old version is garbage collected.

At the moment we solve it by patching the configuration to ignore the stored setting:

```patch
--- a/syncthing_gtk/configuration.py
+++ b/syncthing_gtk/configuration.py
@@ -30,7 +30,7 @@
        "autokill_daemon"           : (int, 2), # 0 - never kill, 1 - always kill, 2 - ask
        "daemon_priority"           : (int, 0), # uses nice values
        "max_cpus"                  : (int, 0), # 0 for all cpus
-       "syncthing_binary"          : (str, "/usr/bin/syncthing"),
+       "syncthing_binary"          : (str, "@syncthing@"),
        "syncthing_arguments"       : (str, ""),
        "minimize_on_start"         : (bool, False),
        "folder_as_path"            : (bool, True),
@@ -168,6 +168,8 @@
            yield k
    
    def get(self, key):
+       if key == "syncthing_binary":
+           return self.REQUIRED_KEYS[key][1]
        return self.values[key]
    
    def set(self, key, value):
```

But since this could be confusing, we are also disabling or hiding the interface for changing it.

<details><summary>(patch)</summary>

```patch
--- a/glade/find-daemon.glade
+++ b/glade/find-daemon.glade
@@ -112,6 +112,7 @@
                   <object class="GtkEntry" id="vsyncthing_binary">
                     <property name="visible">True</property>
                     <property name="can_focus">True</property>
+                    <property name="sensitive">False</property>
                     <property name="margin_right">20</property>
                     <signal name="changed" handler="cb_check_value" swapped="no"/>
                   </object>
@@ -126,6 +127,7 @@
                     <property name="label" translatable="yes">_Browse...</property>
                     <property name="visible">True</property>
                     <property name="can_focus">True</property>
+                    <property name="sensitive">False</property>
                     <property name="receives_default">True</property>
                     <property name="use_underline">True</property>
                     <property name="yalign">0.51999998092651367</property>
--- a/glade/ui-settings.glade
+++ b/glade/ui-settings.glade
@@ -943,6 +943,7 @@
                     <property name="label" translatable="yes">_Browse...</property>
                     <property name="visible">True</property>
                     <property name="can_focus">True</property>
+                    <property name="sensitive">False</property>
                     <property name="receives_default">True</property>
                     <property name="use_underline">True</property>
                     <property name="yalign">0.51999998092651367</property>
@@ -974,6 +975,7 @@
                   <object class="GtkEntry" id="vsyncthing_binary">
                     <property name="visible">True</property>
                     <property name="can_focus">True</property>
+                    <property name="sensitive">False</property>
                     <property name="hexpand">True</property>
                     <signal name="changed" handler="cb_check_value" swapped="no"/>
                   </object>
--- a/syncthing_gtk/finddaemondialog.py
+++ b/syncthing_gtk/finddaemondialog.py
@@ -163,7 +163,7 @@
        self["lblDownloadProgress"].set_markup(_("Download failed."))
        self["btDownload"].set_visible(True)
        self["pbDownload"].set_visible(False)
-       self["vsyncthing_binary"].set_sensitive(True)
+       self["vsyncthing_binary"].set_sensitive(False)
        self["btBrowse"].set_sensitive(True)
        self["btSave"].set_sensitive(True)
    
@@ -179,7 +179,7 @@
    
    def cb_extract_finished(self, downloader, *a):
        """ Called after extraction is finished """
-       self["vsyncthing_binary"].set_sensitive(True)
+       self["vsyncthing_binary"].set_sensitive(False)
        self["btBrowse"].set_sensitive(True)
        self["vsyncthing_binary"].set_text(downloader.get_target())
        self["lblDownloadProgress"].set_markup("<b>" + _("Download finished.") + "</b>")
--- a/syncthing_gtk/wizard.py
+++ b/syncthing_gtk/wizard.py
@@ -60,7 +60,6 @@
        self.quit_button.connect("clicked", lambda *a : self.emit("cancel"))
        # Pages
        self.add_page(IntroPage(self))
-       self.add_page(FindDaemonPage())
        self.add_page(GenerateKeysPage())
        self.add_page(HttpSettingsPage())
        self.add_page(SaveSettingsPage())
```

</details>

Obviously this is not very maintainable, so we would prefer an upstream solution. Only saving the settings that changed would solve this problem.

**Comment by kozec** [comment]
Okay, wow. This is one of those problems I would never even dream about :)

How about adding option for `setup.py`? There is already one for disabling support for updates, so adding something like `--nodaemoninhome` should be trivial.

Checking what settings were changed would require bigger recode.

**Comment by jtojnar** [comment]
That would be cool. Would it mean moving the daemon locator to a separate module and not installing that? I would gladly implement it but StGTK is still frozen for me even on 0.9.3.

**Comment by kozec** [comment]
Yes, that would be exactly it. Plus short code that would always search for daemon in actual PATH if locator is not installed.

**Comment by kozec** [comment]
So, setup.py now has `--nofinddaemon` argument, that simply doesn't copy module which displays "daemon locator" window.

If that module is not found at runtime, "1st run wizard" is used to find syncthing binary in `$PATH` and if even that fails, error message is shown and user has to exit ST-GTK.

With that and `--nostdownloader` option enabled, there is no way for user to override default value.

**Comment by jtojnar** [comment]
Building 0b2f16995e8bec2a09cb433e548f26b6d657ec69 with `--nofinddaemon --nostdownloader`, I am getting the following error, when I try to open UI Settings:

```
Traceback (most recent call last):
  File "/nix/store/fnmv5kiwv62gdf7a36n9v0bjngrcwvcw-syncthing-gtk-0.9.3.1/lib/python2.7/site-packages/syncthing_gtk/app.py", line 1759, in cb_menu_ui_settings
    from syncthing_gtk.uisettingsdialog import UISettingsDialog
  File "/nix/store/fnmv5kiwv62gdf7a36n9v0bjngrcwvcw-syncthing-gtk-0.9.3.1/lib/python2.7/site-packages/syncthing_gtk/uisettingsdialog.py", line 15, in <module>
    from syncthing_gtk.stdownloader import StDownloader
ImportError: No module named stdownloader
```

**Comment by kozec** [comment]
I forgot about that one :(

By the way, there is, in fact, option to change binary path in that dialog. Should it be disabled as well in configuration you are trying to create?

**Comment by jtojnar** [comment]
Yes, the option should be disabled – the package manager already offers a way to use specific version of software (two in fact: [overrides](https://nixos.org/nixpkgs/manual/#sec-overrides) and [overlays](https://nixos.org/nixpkgs/manual/#chap-overlays)).

**Comment by kozec** [comment]
Ok, that should be simple change.

**Comment by jtojnar** [comment]
This is almost perfect, except I am still getting a find daemon dialog on first run when built with `--nofinddaemon`:

![screenshot from 2018-06-05 18-09-48](https://user-images.githubusercontent.com/705123/40988638-e2df1562-68eb-11e8-9e18-a38b3c2a216f.png)

The daemon path is set correctly and it works but the wizard ignores it.

```ShellSession
$ rg syncthing_binary result
result/lib/python2.7/site-packages/syncthing_gtk/configuration.py
33:		"syncthing_binary"			: (str, "/nix/store/cwkwr2hnlfvb5z1kkjmkkqchgfg1y311-syncthing-0.14.48-rc.4/bin/syncthing"),
```

**Comment by jtojnar** [comment]
If I temporary add `syncthing` to `PATH`, the wizard finishes successfully. Deleting the file listed as `syncthing_binary` in `~/.config/syncthing-gtk/config.json` triggers the wizard again. The wizard should probably respect `config.get_default_value("syncthing_binary")` too.

**Comment by kozec** [comment]
> If I temporary add syncthing to PATH, the wizard finishes successfully.

Well, that's where it searches in. But I'll add get_default_value as very first thing to try.

**Comment by jtojnar** [comment]
Thanks, works great.
