### ISSUE TITLE
Use fsWatcherEnabled

### ISSUE THREAD

**Issue by jtojnar** [syncthing/syncthing-gtk#430]
Since syncthing 0.14.40, there is [apparently](https://github.com/syncthing/syncthing/releases/tag/v0.14.40) built-in filesystem monitoring, which [replaced](https://github.com/syncthing/syncthing-inotify#exclamationdeprecationexclamation) syncthing-inotify. Could it be used instead of pyinotify?

Pyinotify is not available on Nix on MacOS, so we cannot offer syncthing-gtk there.

**Comment by kozec** [comment]
Interesting, I was not aware that's already done. I have branch that remove filesystem watching, I'll try to merge it and see what it does.

Byt ST-GTK is really not supported on MacOS, I have no machine to test it with it.

**Comment by kozec** [comment]
@calmh sorry to bother you, but release notes for 0.14.40 sounds like fsWatcherEnabled is there just for testing. Is it good idea to remove watching from ST-GTK and rely on it now, or would it be better to wait?

**Comment by calmh** [comment]
I’d suggest waiting as there is no UI to control it properly from Syncthing yet. I’ll be there in a release or two.

**Comment by kozec** [comment]
Ok, thanks. @jtojnar, I made sure that pyinotify is optional dependency, so until that's ready, ST-GTK can be used as it is, but inotify option will be disabled.

**Comment by hackel** [comment]
What is the current status of this issue?  Syncthing 0.14.47 is out, and I just got a message about enabling "Watching for changes" in the web interface, along with the Warning: "If you are using an external watcher like syncthing-inotify, you should make sure it is deactivated."  I certainly don't want two have two watchers running.

**Comment by kozec** [comment]
> I certainly don't want two have two watchers running. Is it enough to just uninstall python-pyinotify?

Yes, but you may need it for other things as well :D I'm currently little busy, but I'll try to get support for soon.
