### ISSUE TITLE
empty syncthing-gtk window [resolved]

### ISSUE THREAD

**Issue by jerome-diver** [syncthing/syncthing-gtk#431]
on archlinux, after some updates, syncthing-gtk windows is emty.
http interface is working, daemon is running.
syncthing-gtk 1:0.9.3-1 installed from arch local repo

Same on other one computer with antergos (same version of syncthing-gtk from same repo)

i tryed to restaure config files from backup system (.config/syncthing*) but same result.
I don't know where is the log file (not in /var/log) so i can not read it.

But i run syncthing-gtk from terminal emulator with option -do and give you the output:
[ptpb paste](https://ptpb.pw/GImB)

**Comment by kozec** [comment]
> self.connect("event", self._socket_event)
> TypeError: TypeError: argument connectable: Expected Gio.SocketConnectable, but got unicode
> argument connectable: Expected Gio.SocketConnectable, but got unicode

That looks like some API change in Gio, suddenly it connects to server instead to glib signal..

Can you tell me version of Gtk you are using? Output of `pacman -Q gtk3 gobject-introspection` would be ideal.

**Comment by jerome-diver** [comment]
yes @kozec gtk3 3.22.26-1 for gtk3 version
output for:
`
pacman -Q gobject-introspection
gobject-introspection 1.54.1-1
`

**Comment by kozec** [comment]
> apply the change works for me, i confirm.

Great, thanks for confirmation :)

**Comment by thiswillbeyourgithub** [comment]
Hi, excuse me but I have the same issue on ubuntu and I can't understand how to fix it.

My version of gobject-introspection seems to be `1.46.0-3ubuntu1`.

I don't understand the "change" @jerome-diver seems to have applied...

**Comment by kozec** [comment]
@thiswillbeyourgithub if possible, updating to latest ST-GTK is fastest way to fix it.

**Comment by thiswillbeyourgithub** [comment]
@kozec I just saw that I had in fact not installed the apt repository and found it there : https://apt.syncthing.net/

This did in fact not solve my problem. But running the latest package from this link `https://github.com/syncthing/syncthing/releases/download/v0.14.45/syncthing-linux-amd64-v0.14.45.tar.gz` actually works if I go straight to the web interface. But the indicator icon stays grey.

What should I do ? I liked the indicator and the infos it provided..
