### ISSUE TITLE
DEB package classified as proprietary by Ubuntu

### ISSUE THREAD

**Issue by yaomtc** [syncthing/syncthing-gtk#433]
Not sure if this is an issue with Ubuntu's software manager or with the DEB package, but when I open `syncthing-gtk_0.9.2.6-1~webupd8~artful0_all.deb` in Ubuntu 17.10, under Details, it shows the license as proprietary. Doesn't say why. This isn't proprietary software, so I don't know where this classification is coming from.

**Comment by kozec** [comment]
Sorry, I really don't know how Ubuntu determines that. Does that cause any problems?

**Comment by calmh** [comment]
There is a license field in the package that should be set when the license is created. Whoever is creating the deb file should set it appropriately.

**Comment by kozec** [comment]
@hotice are you still one building these? :)

**Comment by kozec** [comment]
For now and for anyone to who this posses a problem, [Ubuntu packages built automatically in OBS should not have this problem.](http://software.opensuse.org/download.html?project=home%3Akozec&package=syncthing-gtk)
