### ISSUE TITLE
pyinotify isn't optional

### ISSUE THREAD

**Issue by vallon** [syncthing/syncthing-gtk#435]
It seems that since df042bcbbee88b1ca4fdd3a8613dbf39568dff34, pyinotify is not an optional dependency.  I am on MacOS X, and it seems there is no pyinotify.

My understanding is that setuptools does support optional dependencies (I think structured as optional features which can trigger dependencies).

Possible solutions:

1) Make dependency optional
2) Fix docs
3) Use a different fs monitor

**Comment by kozec** [comment]
I'm thinking about just adding check there, so pyinotify is required only on Linux.

What does python reports as sys.platform on MacOS? Running `python2 -c "import sys; print sys.platform"` in shell should say.
