### ISSUE TITLE
Syncthing-GTK 0.9.3 Blank GUI/Broken Daemon Interaction on Ubuntu 17.10

### ISSUE THREAD

**Issue by Forger125** [syncthing/syncthing-gtk#437]
Platform: Ubuntu MATE 17.10 (64-bit)
Syncthing Version: 0.14.45
Syncthing-GTK installed from the WebUpd8 PPA

I recently upgraded from Syncthing-GTK 0.92.x --> 0.9.3, and after the upgrade Syncthing-GTK successfully creates the inactive tray icon, but fails to start the syncthing daemon and displays a blank GUI when the window is opened (see images below). The menus which control the Syncthing-GTK GUI settings are functional, but all the menu items and GUI elements which interact with the daemon are non-functional. If the daemon is started separately while Syncthing-GTK is running, daemon functionality is still not available. Starting Syncthing-GTK from the terminal yields the output displayed below. Problem is not resolved by reinstalling/purge reinstalling Syncthing-GTK.

> I StatusIcon    Using backend StatusIconGTK3 (primary)
> I App           
> I App           Syncthing-GTK started and running in notification area
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 398, in _request_config
>     RESTRequest(self, "system/config", self._syncthing_cb_config, self._syncthing_cb_config_error).start()
>   File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 1045, in __init__
>     self.connect("event", self._socket_event)
> TypeError: argument connectable: Expected Gio.SocketConnectable, but got unicode
> 
> (syncthing-gtk:25371): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

![image](https://user-images.githubusercontent.com/786092/37433486-81b51874-27b2-11e8-9840-013275deba53.png)

![image](https://user-images.githubusercontent.com/786092/37433878-09adee12-27b4-11e8-9358-418c24cdb967.png)

**Comment by trymz** [comment]
exactly the same concern with me under linux mint 18.3 whether using ppa or Appimage.
No problem with 0.9.2.x

**Comment by ShaunPCcom** [comment]
I also have this issue on Arch. Downgrading to 0.9.2 also worked for me.

**Comment by catb0t** [comment]
Also had this, I confirm fixed by downgrade to 0.9.2

**Comment by kozec** [comment]
It should be fixed in next release, but I'm fighting over it with Build Service right now...

**Comment by kozec** [comment]
Hopefully fixed in [latest release](https://github.com/syncthing/syncthing-gtk/releases/latest)

**Comment by Forger125** [comment]
Thank you for all your hard work, and your responsiveness to this issue!

**Comment by trymz** [comment]
thanks for your efforts, but release 0.9.3.1 don't solve the probleme for me

`I StatusIcon    Using backend StatusIconGTK3 (primary)
V Notifications Error notifications enabled
V Notifications File update notifications enabled
I App           
I App           Syncthing-GTK en cours d'éxécution dans la zone de notification
V Daemon        Set refresh interval to 5
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 398, in _request_config
    RESTRequest(self, "system/config", self._syncthing_cb_config, self._syncthing_cb_config_error).start()
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 1045, in __init__
    self.connect("event", self._socket_event)
TypeError: argument connectable: Expected Gio.SocketConnectable, but got unicode

(syncthing-gtk:5595): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
`

**Comment by kozec** [comment]
> thanks for your efforts, but release 0.9.3.1 don't solve the probleme for me

Something is horribly wrong there, because what that error displays is not [what should be on line 1045.](https://github.com/syncthing/syncthing-gtk/blob/master/syncthing_gtk/daemon.py#L1045). What repository are you using for updates?

**Comment by trymz** [comment]
I used the repository webup8 file:
syncthing-gtk_0.9.3-1~webupd8~xenial0_all.deb
When I go into "about" , the version says is 0.9.3 not 0.9.3.1
There must be something wrong with my system not your app, but I don't see which one.
When I use the latest tarball with syncthing-gtk.py it works well with the right version.

**Comment by niemalsnever** [comment]
@trymz syncthing-gtk_0.9.3-1webupd8xenial0_all.deb is not actually 0.9.3.1, as that package was released to the WebUpd8 repository on 2018-03-12, while the actual release of version 0.9.3.1 by @kozec happened on 2018-03-18 (according to Github). So whoever builds the DEBs for the WebUpd8 repository, needs to update the version in the repo.

**Comment by trymz** [comment]
Thank you very much @niemalsnever for this explanation!
For a while I thought I was crazy, I didn't understand why this version 0.9.3 systematically installed instead of the other one.
Thank you again.

**Comment by niemalsnever** [comment]
@trymz Also notice how the package is called syncthing-gtk_0.9.3-1... (with a dash) and not syncthing-gtk_0.9.3.1... (with a dot). My guess is, that the dash (and the number thereafter) is used to denote the revision of the package, should the first uploaded package turn out to be faulty.

**Comment by kozec** [comment]
I've finally managed to get Debian and Ubuntu packages for Syncthing-GTK to build in OBS, so there will be less lagging repository available soon. I just need to test those on actual Ubuntu and Debian machines :)

**Comment by trymz** [comment]
@kozec 
Works great on my end.
A very big thank you.
