### ISSUE TITLE
README.md: link to outdated fedora package source

### ISSUE THREAD

**Issue by decathorpe** [syncthing/syncthing-gtk#438]
The `syncthing-gtk` package for fedora is no longer available from the linked COPR repository, but from the official package repositories (`syncthing-gtk` package, as expected) instead. It would be best to update the README.md file to reflect that change.

**Comment by kozec** [comment]
That's great. Is there any link I can put up there, or just "search for `syncthing-gtk` in package manager" ?

**Comment by decathorpe** [comment]
The only "useful" link I can give you would be one to the "dist-git" repository (<https://src.fedoraproject.org/rpms/syncthing-gtk>), but that page isn't of any actual use for users who want to install the package, just for those interested in the packaging itself.

I think saying "search for "Syncthing-GTK" in the software installer or install the `syncthing-gtk` package manually" is probably the most user-friendly solution.
