### ISSUE TITLE
AppImage is not bundling all required components

### ISSUE THREAD

**Issue by probonopd** [syncthing/syncthing-gtk#442]
```
  File "<string>", line 1, in <module>
  File "/run/firejail/appimage/.appimage-7125/usr/lib/python2.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /run/firejail/appimage/.appimage-7125/usr/lib/python2.7/site-packages/gi/_gi.so: undefined symbol: g_irepository_get_immediate_dependencies
Syncthing-GTK requires GTK and gobject-introspection packages.\n Please, install GTK3 and gobject-introspection packages using your package manager
Parent pid 7125, child pid 7129
```

Need to bundle Python, PyGTK and gobject-introspection inside the AppImage.

Reference:
https://github.com/AppImage/appimage.github.io/pull/469#partial-pull-merging

**Comment by kozec** [comment]
Haven't we discussed this already? :D

gobject-introspection should be bundled and st-gtk doesn't use PyGTK. Only not bundled are python and GTK, as that adds ~100MB to package size.

But I've tested this combination on all desktop distros I could think about and it works. What are you trying to do and where is it failing?

**Comment by probonopd** [comment]
Here is the full log:
https://api.travis-ci.org/v3/job/360511088/log.txt

To replicate, the easiest way is to run a Ubuntu 14.04 Live ISO and then run the AppImage there.

**Comment by svandragt** [comment]
Doesn't work on Ubuntu 16.04 LTS
```
$ ./SyncthingGTK-0.9.3.1-x86_64.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_Syncthsfhx5j/usr/bin/syncthing-gtk", line 24, in <module>
    gi.require_version('Rsvg', '2.0')
  File "/tmp/.mount_Syncthsfhx5j/usr/lib/python2.7/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Rsvg not available

```

**Comment by kozec** [comment]
So, I've ended up bundling entire GTK :(

It works down to xUbuntu 14.04, although UI looks weird thanks to not entirely compatible theme. I'm not sure if there is way how to have it both ways.

**Comment by kozec** [comment]
By the way, @probonopd , at this point, I'm fairly sure there is no way to actually create Python + GTK appimage that works "everywhere" :(

Image with no added GTK stuff and then it doesn't work on KDE-based distros.
Image with dependencies builded manually crashes because of incompatibile libstdc++ on older distro releases.
And image with dependencies extracted breaks theming to unusable level - [rendering of most of widgets is broken, including window header](https://user-images.githubusercontent.com/1282500/42177098-b970de68-7e2b-11e8-9628-2d2f8b460363.png)

Have you considered creating some runtime or default build environment?

**Comment by probonopd** [comment]
> Image with dependencies built manually crashes because of incompatibile libstdc++ on older distro releases.

You must not bundle libraries in versions newer than what would come with the oldest distribution you are targeting. In practice, targeting the oldest still-supporting Ubuntu LTS (currently 14.04) has been working well for us. This means, if you bundle Gtk+, either bundle the Gtk+ from Ubuntu 14.04 or, if you absolutely need a newer Gtk+ version, compile it on Ubuntu 14.04 and then bundle it.

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems for details.

This is nothing AppImage-specfic. You would be running into the same issues if you wanted to distribute a bundled version of your application in a zip file.

**Comment by probonopd** [comment]
> Have you considered creating some runtime or default build environment?

Ubuntu 14.04 on Travis CI (or a Docker container on GitLab) is curently my default build environment. Another good option is the Open Build Service.
