### ISSUE TITLE
"Start Syncthing-GTK when I login to my desktop" won't stay checked on Fedora 27

### ISSUE THREAD

**Issue by tristanbrown** [syncthing/syncthing-gtk#444]
In the UI Settings, when I check the box "Start Syncthing-GTK when I login to my desktop" and click "Save," the program never starts on login. When I return to that option in the UI Settings, the box is once again unchecked.

**Comment by kozec** [comment]
Can you check if Syncthing-GTK.desktop file is correctly created in `~/.config/autostart`? Does it contain "hidden=true" value? There is chance that another configuration tool is disabling autostart, maybe even intentionally :)

Assuming you are running Gnome, going to ["Startup applications"](https://scognito.files.wordpress.com/2014/11/gsettings_set.png) and enabling or adding Syncthing-GTK there may be best way to make sure it stays.

**Comment by tristanbrown** [comment]
Syncthing-GTK.desktop has `Hidden=false` and `X-GNOME-Autostart-enabled=true`. 

I'm adding it to the "Startup applications."

**Comment by martinrotter** [comment]
Same on Archlinux.

**Comment by kozec** [comment]
> Same on Archlinux.

Distro shouldn't really play role here, desktop environment should. What are you and @tristanbrown using?

**Comment by martinrotter** [comment]
MATE here. Autorun .desktop file seems to get created correctly and app autostarts after reboot. Its just visual thing here that the checkbox is not checked altough it should be.

**Comment by samuel141** [comment]
It seems that the \n at the end of the line is the problem. So line 454 in tools.py is always false.

**Comment by tristanbrown** [comment]
For me, it's definitely not running on reboot. In fact, I have to execute the binary _twice_ each time to get it to actually run. Why would this happen?

**Comment by samuel141** [comment]
This file as `.config/autostart/Syncthing-GTK.desktop` works for me on Ubuntu 17.10.  Only the checkbox is not working.
```
[Desktop Entry]
Name=Syncthing-GTK
Exec=/usr/bin/syncthing-gtk
Icon=/usr/share/syncthing-gtk/icons/st-logo-128.png
Comment=GUI for Syncthing
X-GNOME-Autostart-enabled=true
Hidden=false
Type=Application
```
