### ISSUE TITLE
Zombie process on Windows

### ISSUE THREAD

**Issue by PrototypeNM1** [syncthing/syncthing-gtk#445]
When closing Syncthing-gtk via the system tray right click menu or the prompt after shutting down the Syncthing daemon: Syncthing is successfully closed but Syncthing-gtk remains as a zombie process which is visible in the Task Manager's Details tab.

**Comment by kozec** [comment]
That may happen when syncthing-inotify is used, its waiting for it to shut down as well.

And since syncthing-inotify function should be integrated into syncthing soon, this problem should solve itself :)

**Comment by kozec** [comment]
Problem should be fixed with next release, as code that used `syncthing-inotify` was just removed in favor of scanning integrated into syncthing.

**Comment by PrototypeNM1** [comment]
I don't think the issue was syncthing-inotify, just checked with 9.4 and syncthing-gtk zombie processes are still a thing.

**Comment by kozec** [comment]
That's weird, there isn't anything else started by it.

There should `syncthing-gtk-console.exe` placed next to regular exe. Can you try to run that one, replicate issue and check if there is anything displayed when it happens?

**Comment by PrototypeNM1** [comment]
When running syncthing-gtk-console.exe:

> I StatusIcon    Using backend StatusIconGTK3 (primary)
> I App
> I App           Syncthing-GTK started and running in notification area
> E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)
> Traceback (most recent call last):
>   File "C:\syncthing-gtk\syncthing_gtk\daemon.py", line 1051, in _connected
> Error: g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)
> I App           updatecheck: too soon

No errors on shutdown, console stays open after closing Syncthing GTK but successfully closes if exited from, no longer leaves zombie syncthing-gtk.exe in Details tab of the task manager when launched from syncthing-gtk-console.
