### ISSUE TITLE
Failed to download Syncthing daemon package

### ISSUE THREAD

**Issue by ahogen** [syncthing/syncthing-gtk#447]
I'm new to Syncthing and was just trying to install Syncthing-GTK on my Windows 7 machine when I got this error, in the title.

> Failed to download Syncthing daemon package
>
> g-io-error-quark: GET request failed: WinHttp error: SECURE_FAILURE (0)

This seemed similar-ish to something I encountered when trying to install updates for the Julia programming language. I tried applying the [Windows TLS1.2 Default Easy fix](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in), mentioned [here](https://discourse.julialang.org/t/git-ssl-errors-while-installing-packages/9347/6), and then re-tried Syncthing-GTK.

What do you know, it started to download, and it seems the daemon is installed and set up now.

I'm not confident this was the solution, but it looks like it could have been so I thought I'd mention it.

Cheers!

**Comment by kozec** [comment]
I believe that Github is gradually increasing min. required protocol version, probably in some deal with MS to wipe out their older systems from face of earth :D

Similar problem prevents updates on XP with no solution AFAIK, so your solution for W7 is definitely better :)

**Comment by ahogen** [comment]
Ah okay, I didn't realize it was pulling the daemon from Github. So [this Github notice](https://githubengineering.com/crypto-deprecation-notice/) applies then.

**Comment by kozec** [comment]
I've ended up adding message with link to that fix for affected machines.
![w7](https://user-images.githubusercontent.com/1282500/39083135-d34e3fce-455f-11e8-9696-fcba05eeefc1.png)
