### ISSUE TITLE
Ubuntu packages missing on Opensuse site

### ISSUE THREAD

**Issue by danstowell** [syncthing/syncthing-gtk#450]
Hi - I read the readme, then for "Ubuntu packages" I clicked the link which takes me to the OpenSUSE package site. On there, though, your repository only seems to offer a program called **sc-controller** (which is something do do with steam?) and not anything for syncthing. Since syncthing seems to be under active development, perhaps a mistake occurred in packaging?

**Comment by kozec** [comment]
Hmm... something sounds very broken, I can see Syncthing-GTK package both under `Grab binary packages directly` and when in file listing for repository.

What Ubuntu version are you running?

**Comment by danstowell** [comment]
Thanks - I'm using 16.04 LTS. The listing [here](https://download.opensuse.org/repositories/home:/kozec/xUbuntu_16.04/Packages).

(The link I clicked in the readme was [this url](http://software.opensuse.org/download.html?project=home%3Akozec&package=syncthing-gtk) but unfortunately today that gives a 503 error for me)

I notice now that the listing for 17.10 does have it. I see - perhaps you're knowingly only supporting that. I didn't expect that since I'm on an LTS, but then I guess it's up to you.

**Comment by kozec** [comment]
Ok, turns out that I've enabled build for all, but publishing only for first and last Ubuntu in list :)

Build should be finished any time now.

**Comment by danstowell** [comment]
Works! Installed and running - thanks!
