### ISSUE TITLE
Some icons don't match the overall L&F

### ISSUE THREAD

**Issue by memeplex** [syncthing/syncthing-gtk#459]
The menu has some coloured icons (settings, shutdown, show id) that don't play well with the rest of the icons and also modern gnome/gtk design. There is a lot of high quality svg icons in https://github.com/PapirusDevelopmentTeam/papirus-icon-theme to pick from.

**Comment by memeplex** [comment]
Also "Edit ignore patterns".

**Comment by memeplex** [comment]
Some suggestions:

* settings -> Papirus/16x16/actions/settings.svg
* shutdown -> Papirus-Adapta/16x16/panel/system-shutdown-panel.svg
* edit ignore patterns -> Papirus/16x16/actions/image-red-eye.svg

The last one is not an eye but a crossed eye, which I think is more meaningful because these are patterns to ignore (not look at).

**Comment by kozec** [comment]
Both settings and shutdown are taken from theme, but "edit ignore patterns" isn't. I'll  have to check if GPL3 icon can be used with GPL2 program.

**Comment by memeplex** [comment]
What are the names of settings and shutdown icons? They really don't look
like most icons in my theme, by all means not like menu/toolbar icons.

**Comment by kozec** [comment]
`preferences-system` and `system-shutdown`. Maybe your theme doesn't include them and so fallbacks from Adwaita are used?

**Comment by kozec** [comment]
Sorry, but I found this to be surprisingly hard change _and_ potential licence mess, so I decided that current icons are fine :)
