### ISSUE TITLE
ImportError: Typelib file for namespace 'Atk', version '1.0' not found

### ISSUE THREAD

**Issue by irregularisnotrandom** [syncthing/syncthing-gtk#462]
Previous version used to work, 0.9.4 does not

Debian Testing Buster

```
apt install gobject-introspection                                                                                                      :(
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gobject-introspection is already the newest version (1.56.1-1).
gobject-introspection set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded

```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/.mount_syncthbIPSiF/usr/lib/python2.7/site-packages/gi/importer.py", line 140, in load_module
    raise ImportError(e)
ImportError: Typelib file for namespace 'Atk', version '1.0' not found
Syncthing-GTK requires GTK and gobject-introspection packages.\n Please, install GTK3 and gobject-introspection packages using your package manager
/usr/bin/zenity: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or director
```

**Comment by kozec** [comment]
Atk should be part of gobject-introspection, but Debian tends to split packages randomly. Check if there is package with Atk in name.

**Comment by irregularisnotrandom** [comment]
Yeah I checked it already, I do not see any Atk there.

**Comment by pirinto** [comment]
@kozec , I got the same issue as @irregularisnotrandom regatrding the Atk1 part

`File "<string>", line 1, in <module>
  File "/tmp/.mount_SyncthPgvKgg/usr/lib/python2.7/site-packages/gi/importer.py", line 140, in load_module
    raise ImportError(e)
ImportError: Typelib file for namespace 'Atk', version '1.0' not found
Syncthing-GTK requires GTK and gobject-introspection packages.\n Please, install GTK3 and gobject-introspection packages using your package manager
/usr/bin/zenity: symbol lookup error: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: gdk_wayland_display_get_ty`
