### ISSUE TITLE
First run wizard german translation

### ISSUE THREAD

**Issue by culmat** [syncthing/syncthing-gtk#465]
![syncting-gtk-intro-german-2018-07-21 22-32-59](https://user-images.githubusercontent.com/638519/43044455-6a6a6dc2-8da6-11e8-843f-1382c2ca2b43.png)

Text says **Zurück** - should be **Weiter** as on the button?
Text says **Quit** - should be **Beenden** as on the button?
 

See #150

**Comment by kozec** [comment]
I kinda hoped for someone who actually speak German to chime in, but now when I looking at it, this may be different problem.

Buttons on top are provided by GTK and using system-wide language files. Text is from ST-GTK. And what that system-wide translation says differs from distro to distro and from version to version. So fixing it here means breaking it for someone else.

May I assume you are using as recent as possible release of your distro of choice?

**Comment by kozec** [comment]
That may work, I can even "rig" translation temporary so it displays old message where new text is not yet translated.
