### ISSUE TITLE
Unparsed HTML in notification popup on Gnome

### ISSUE THREAD

**Issue by benruijl** [syncthing/syncthing-gtk#478]
When a file is synchronized, the gnome notification popup contains an unparsed html link, as shown in the image below:

![popupbug](https://user-images.githubusercontent.com/280089/44308108-6f7f0600-a3af-11e8-9357-5ccd94138e77.png)

### Version Information

Syncthing Version: v0.14.48
OS Version: Arch Linux
Gnome version: 3.26

**Comment by benruijl** [comment]
This issue appears to be a problem in `libnotify`. I have filed a bug report here: https://gitlab.gnome.org/GNOME/libnotify/issues/2

**Comment by benruijl** [comment]
This is the answer from the Gnome Shell development team: https://gitlab.gnome.org/GNOME/gnome-shell/issues/549#note_311728. So `syncthing-gtk` should get if the `body-hyperlinks` is set. If not, the HTML should not be in the output.

**Comment by benruijl** [comment]
I understand now: the current release is quite old, and this bug has been fixed since https://github.com/syncthing/syncthing-gtk/commit/d352ce18bc81c7cda24153b55b210d94a0424f14.

**Comment by kozec** [comment]
Sounds like it's time to make another.
