### ISSUE TITLE
Flatpak package maintenance

### ISSUE THREAD

**Issue by jurf** [syncthing/syncthing-gtk#480]
Hey.

I started to package this as a [Flatpak](https://flatpak.org/). You can check the progress here: flathub/flathub#615.

I will most likely finish packaging it, it’s looking quite good, but I have two questions for you:

1. Would you be interested in having read/write access to the build files on @flathub and/or (co-)maintaining the package?
2. Would you mind merging the AppData file upstream, once it’s done?

Cheers.

**Comment by kozec** [comment]
I doubt Flatpak can support most of what Syncthing-GTK does, starting at very important task of executing `/usr/bin/syncthing` from actual filesystem :)

But to answer your question, 1. no, I would not be interested and 2. I don't mind merging it. There should already be one [here](https://github.com/syncthing/syncthing-gtk/blob/master/scripts/syncthing-gtk.appdata.xml), used by AppImage build.

**Comment by jurf** [comment]
The syncthing binary will be packaged and kept updated with Syncthing GTK, that’s not a problem. It should be fine, though file manager integration probably won’t work, and there _might_ be problems with syncthing itself, but then again might not, we’ll see.

Thanks for the AppData, I’m currently using the one from Fedora, I’ll merge them and get them up to shape.

If you ever change your mind about the access/maintainership, just ask anywhere Flathub related, or heck, just reopen this. :slightly_smiling_face:

**Comment by jurf** [comment]
Turned out fine! Would be appreciated if you’d link to [the Flathub page](https://flathub.org/apps/details/me.kozec.syncthingtk) in the package section. Thanks!
