### ISSUE TITLE
i3 not being detected properly

### ISSUE THREAD

**Issue by laelath** [syncthing/syncthing-gtk#494]
I am encountering the same issue as #188, but this is fixed by calling `XDG_CURRENT_DESKTOP=i3 syncthing-gtk -m` which leads me to believe that the method previously used to detect an i3 desktop is no longer working.

**Comment by kozec** [comment]
Then i3 desktop is broken :)

What gives `echo $XDG_CURRENT_DESKTOP` to you in freshly spawned terminal?

**Comment by laelath** [comment]
Ahh, looks like that environment variable is no longer getting set. I'll submit the issue with i3.

**Comment by laelath** [comment]
Apparently i3 has never set that variable, now I'm not sure why starting minimized ever worked, weird. Guess i3 users just have to set it before launching

**Comment by kozec** [comment]
Well, considering that i3 is "just" a WM, it makes sense. If there is any sure way to detect it, I can change code handling detection, otherwise just set XDG_CURRENT_DESKTOP in .xinitrc or .profile.

**Comment by laelath** [comment]
Looking at the output of `env`, the only one I see that mentions i3 is `DESKTOP_STARTUP_ID` which begins with `i3/`, not sure how standard this variable is though.
