### ISSUE TITLE
contradiction?

### ISSUE THREAD

**Issue by paolobenve** [syncthing/syncthing-gtk#495]
syncthing-gtk 0.9.4.2, syncthing 0.14.50

![syncthing](https://user-images.githubusercontent.com/1417508/48665411-03936300-eaae-11e8-912f-f4143bb366a2.png)

The host is said to be up to date, while the corresponding folder is still syncing

**Comment by kozec** [comment]
Well, while Honor may already be up-to-date with latest changes from Paolo, Paolo may still be downloading data from Honor.
