### ISSUE TITLE
Does not shutdown syncthing daemon on SIGHUP or SIGTERM (Linux)

### ISSUE THREAD

**Issue by nemoinis** [syncthing/syncthing-gtk#496]
When the option "When exiting after daemon..." is set to "terminate daemon", syncthing-gtk does terminate the daemon when quit manually.

But it does not do it upon SIGHUP or SIGTERM, which makes it difficult to script an orderly session  logout, for example. This can lead to problems in situations where the home must be unmounted, or the systemd user daemon waits for all processes to terminate, etc...

Workaround is to terminate syncthing directly, but it would be cleaner if syncthing-gtk did it.

**Comment by justpusher** [comment]
I'm not sure this is syncthing-GTK issue. 
I tried running syncthing daemon directly from shell startup, and it does not exit on logout. 
syncthing exists on SIGTERM but ignores SIGHUP.
