### ISSUE TITLE
Folder Settings not recorded

### ISSUE THREAD

**Issue by dmbortz** [syncthing/syncthing-gtk#498]
I'm using syncthing 0.14.52 and syncthing-gtk 0.9.4.2 on my Ubuntu 18.04 laptop.  It is syncing with a Synology NAS with syncthing 0.14.49-15 on it.

I recently upgraded syncthing-gtk to the 0.9.4.2 (I don't know what version it was previously), and there's some problematic behavior in the Folder Settings tab (on my laptop).

Without me selecting it, the "Receive Only Folder" is active.  Since this is my laptop, it should *not* be "Receive Only". If I unclick the button and then "Save", this change is not recorded, i.e., editing the folder shows that "Receive Only" is active again.  Note that I've also tried changing the folder to "Send Only", but it gets reverted back to "Receive Only".

I can access the web GUI on my laptop and from there I can make sure the directory is "Send & Receive".  This information does get propagated to syncthing-gtk as after changing the property using the web GUI, the "Receive Only" option became unselected.

In looking at the properties of the folder using the web GUI on the NAS, the folder is also listed as "Send & Receive".

Is this a bug or am I misunderstanding how these options work?  It just looks like synching-gtk has issues with setting/changing this option.

**Comment by catb0t** [comment]
#484 / #493 ?

**Comment by carltonwhitehead** [comment]
On a tangentially related note, I see the [OpenSUSE build service](http://download.opensuse.org/repositories/home:/kozec/xUbuntu_18.04/) still has `0.9.4.2`, which would explain why some people are still seeing this bug despite running their software updates. Should I file a separate issue for that?

**Comment by kozec** [comment]
> On a tangentially related note, I see the OpenSUSE build service still has 0.9.4.2

That sounds like something went horribly wrong, I'll check on that.

**Comment by dmbortz** [comment]
Just did an update/upgrade and syncthing-gtk is now at 0.9.4.3 and the behavior I described above is gone.

Thanks so much!

**Comment by kozec** [comment]
Looks like all builds got done this time :)
