### ISSUE TITLE
Uncompress man page?

### ISSUE THREAD

**Issue by simonvanderveldt** [syncthing/syncthing-gtk#499]
First of all, thanks for this piece of software, very useful! :+1: 

Whilst packaging syncthing-gtk for gentoo I got this QA warning:
```
 * One or more compressed files were found in docompress-ed directories.
 * Please fix the ebuild not to install compressed files (manpages,
 * documentation) when automatic compression is used:
 * 
 *   /usr/share/man/man1/syncthing-gtk.1.gz
```
When looking at the code I noticed that the man page is stored as `.gz` file in this repo instead of being plain text. Is there any particular reason it's done that way? Normally one doesn't commit binaries into git/version control.
Anyway, would it be possible/OK to change the man page to just be plain text?
I believe normally the package manager will do the compression anyway, so no need to do that upfront.

[edit] Btw. I can also make sure it doesn't get compressed when packaging to prevent this QA warning, but imho it makes more sense to store the manpage as plaintext.

**Comment by kozec** [comment]
I don't really remember why was it compressed in 1st place, so I'll just uncompressed it in next release and check what will go wrong.

**Comment by kozec** [comment]
... or I do it right now so I don't forget about it.
