### ISSUE TITLE
A whole cluster of problems

### ISSUE THREAD

**Issue by ghost** [syncthing/syncthing-gtk#501]
I tried Syncthing about a year ago. I've tried again just now. I wish I had not, frankly. Synthing-gtk, running on Linux:

- shows windows to do with (I think . .) accepting new folders that I cannot type anything into (pictured)

![image](https://user-images.githubusercontent.com/9998846/49680040-3797ed80-fa88-11e8-9ead-f03c0f0d57ca.png)

- shows my single local syncthing folder in triplicate;
- has a counter-intuitive UI (discovering how to edit any of the items it showed was too hard)
offered to set up a circular sync (from X to Y back to X; I suppose I had misused the 'introducer' function;
- just won't sync anything, because I can't set it up properly.

Also, the instructions in the installer about web credentials are, I submit, thoroughly confusing.

Syncthing 0.9.<something> [the field in the 'about' window is not copyable]
Daemon 0.14.54
Linux Mint 19 x64 Cinnamon.

Still, the software is still in alpha.

(Edited.)

**Comment by catb0t** [comment]
"shows my single local syncthing folder in triplicate" should be opened as a separate bug from the unfocusable window (I've seen it too but haven't reported yet) 

do you have a suggestion to improve "discovering how to edit any of the items it showed"?

**Comment by calmh** [comment]
> I tried Syncthing about a year ago. I've tried again just now. I wish I had not, frankly. 

This is no way to start a bug report. People here put in their time and energy into a project for your benefit, and if it didn't work for you for whatever reason that's unfortunate but we don't deserve your derision for it. This isn't specifically my subproject so I'll leave it, but if it were I would close and lock the issue regardless of merit.

Be courteous to your fellow open source developers.
