### ISSUE TITLE
Ubuntu 18.04 key is no longer valid

### ISSUE THREAD

**Issue by andr-uv** [syncthing/syncthing-gtk#507]
Dear developers,

The release key for Ubuntu 18.04 is no longer valid. Would it be possible for you to solve this issue. Thanks in advance.

![captura de pantalla_2019-02-07_19-51-49](https://user-images.githubusercontent.com/18691740/52452734-47789000-2b12-11e9-8144-b6ef9f76fc2b.png)

**Comment by magicvince** [comment]
+1 with Linux Mint Debian Edition (Debian Stretch)

**Comment by calmh** [comment]
The key expiry is not dependent on your distribution. There is no need for more plus-one:ing.

**Comment by kozec** [comment]
I _think_ I managed to get it extended, please let me know if it doesn't work for you.

**Comment by buck2202** [comment]
Resolved for me after re-adding the key per https://software.opensuse.org/download.html?project=home%3Akozec&package=syncthing-gtk

**Comment by andr-uv** [comment]
Thanks, @kozec. The issue is already solved. After re-adding the key, it shows it has been extended. Thank you, again.

![captura de pantalla_2019-02-10_12-50-15](https://user-images.githubusercontent.com/18691740/52537271-cea44e80-2d32-11e9-87da-c3f0ed19eee2.png)
