### ISSUE TITLE
Override Changes button does not appear

### ISSUE THREAD

**Issue by olafklingt** [syncthing/syncthing-gtk#512]
I have a "send only folder" when i create a file on the other computer this is seen as out of sync file. But the folder status stays "Up to date". therefore no "Override Changes" button appears in the gtk gui.

In the web-ui the out of sync file is recognized as making the folder out of sync and the "Override Changes" button does appears. 

I am on arch Linux with 0.9.4.3. and daemon v1.1.1.

**Comment by NKSHV** [comment]
same, I am trying to sync music library, I replaced 100 files on send-only device (changed their idv3) and deleted some, but they won't send to receive-only. On receive-only it says "idle", while really files were not replaced and deleted.
