### ISSUE TITLE
Using "Monitor filesystem for changes" triggers permanently  "Receive Only Folder" option.

### ISSUE THREAD

**Issue by MatthiasSiewert** [syncthing/syncthing-gtk#514]
I just had an issue where I wanted to try the "Monitor filesystem for changes" option applied in Syncthing GTK. After working a bit, I noticed that my files got reverted to an older state. I restarted Syncthing and Syncthing-GTK, but it didn't help. After a while I noticed, that the folder had been changed to a receive only folder, which it never was before. When I changed the setting in Syncthing GTK it reverted back to "receive only folder" as soon as i closed the folder settings. Restarting Syncthing didn't help. Eventually, I managed to reverse the setting in the Web interface.

Running on Ubuntu Gnome 16.04, Syncthing gtk 0.9.4.2 and 1.1.3 Daemon.

**Comment by kozec** [comment]
I was not able to reproduce this back then nor now, but I'm guessing it was caused by same issue as #518.

Please, reopen issue if it still happens with latest release.
