### ISSUE TITLE
Share folders list has all combinations listed and minimal device info

### ISSUE THREAD

**Issue by brechmos** [syncthing/syncthing-gtk#516]
I have 3 machines that are each sharing the same folder with each other. The topology may not be the best, but it is what it is for now.  When I do a right click on one of the devices I see the "Edit Device" page which, at the bottom, has the Shared Folder list.
The Shared Folder list appears to have an entry for each share in both directions.  So, given my 3 machines, fully connected I see the same share listed 6 times. That seems like overkill or a bug (?).

Second, I can't tell which Share is from which machine as all that is listed there is the folder.  So, using the checkbox gets difficult.  If they all truly should be there, it might be good to show "device 1 -> device 2 - folder name" so I can tell the direction of share (which device to which device).

![image](https://user-images.githubusercontent.com/887675/58953938-c8186780-8765-11e9-8cb1-d47098181e2c.png)

**Comment by jjakob** [comment]
Can confirm, same behaviour here.

> Second, I can't tell which Share is from which machine as all that is listed there is the folder. So, using the checkbox gets difficult. If they all truly should be there, it might be good to show "device 1 -> device 2 - folder name" so I can tell the direction of share (which device to which device).

I don't think this should have any relevance as the share should be between this particular instance and the remote device. I don't think it's possible to share a folder from a remote device to a remote device. In any case, only one of each folder should be displayed as that's the way it's shown in the Web UI.

**Comment by kozec** [comment]
I was not able to reproduce the issue nor find any reason why should it be happening, but I've added "blind" fix that should prevent it in any case.

**Comment by jjakob** [comment]
Mine happens on Ubuntu 16.04, I can look up the version of dependency packages if this would be of any help.
