### ISSUE TITLE
Nautilus extension not working

### ISSUE THREAD

**Issue by trashcan55** [syncthing/syncthing-gtk#520]
The nautilus-integration doesn't work for me on manjaro

I read in a previous bugreport on a similar issue that for the arch-package `syncthing-plugin-nautilus.py`  is not installed in the proper directory by default, but I ensured there is a symlink in `~/.local/share/nautilus-python/extensions/` pointing to `/usr/share/syncthing-gtk/syncthing-plugin-nautilus.py`:

```
cat ~/.local/share/nautilus-python/extensions/syncthing-plugin-nautilus.py
#!/usr/bin/env python2
"""
Nautilus plugin for Syncthing-GTK
See syncthing_gtk/nautilusplugin.py for more info
"""

from gi.repository import Nautilus
from syncthing_gtk.nautilusplugin import NautiluslikeExtension

NautiluslikeExtension.set_plugin_module(Nautilus)

class SyncthingNautilus(NautiluslikeExtension, Nautilus.InfoProvider, Nautilus.MenuProvider):
	pass
```

this is my output when starting nautilus in a terminal:
```
Traceback (most recent call last):
  File "/home/user/.local/share/nautilus-python/extensions/syncthing-plugin-nautilus.py", line 8, in <module>
    from syncthing_gtk.nautilusplugin import NautiluslikeExtension
ModuleNotFoundError: No module named 'syncthing_gtk'
Initializing Nextcloud-client-nautilus extension
Using python version sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by kozec** [comment]
> Using python version sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

Looks like it using python 3. Most likely intentionally, considering it's Arch derivate. Syncthing GTK is python2 application and so is that plugin.

**Comment by trashcan55** [comment]
how unfortunate, thanks for your help

**Comment by OdinVex** [comment]
Any chance of migrating Syncthing to Python 3?
