### ISSUE TITLE
Latest version missing from OpenSUSE Build Service

### ISSUE THREAD

**Issue by volt4ire** [syncthing/syncthing-gtk#522]
Version v0.9.4.4 is missing from [OpenSUSE Build Service][1], which only has version .9.4.3. Can you please have it build the latest version for Ubuntu? Thanks!

[1]:https://software.opensuse.org/download.html?project=home%3Akozec&package=syncthing-gtk

**Comment by kozec** [comment]
I whacked it few times and it seems to be there now.

**Comment by volt4ire** [comment]
@kozec thanks so much!
