### ISSUE TITLE
Adopting qsyncthingtray

### ISSUE THREAD

**Issue by es20490446e** [syncthing/syncthing-gtk#529]
[Comment this on the forum](https://forum.syncthing.net/t/adopting-qsyncthingtray/13844).

**Comment by calmh** [comment]
I'm not a syncthing-gtk maintainer, but I'm pretty sure at asking here (a Python & GTK wrapper) for someone to maintain qsyncthingtray (a C++ and Qt wrapper) is the wrong thing.
