### ISSUE TITLE
App Indicator Gone in GNOME Shell 3.34.1

### ISSUE THREAD

**Issue by TheRoarkster** [syncthing/syncthing-gtk#534]
After upgrade to GNOME Shell 3.34.1 (Manjaro 18.1), there is no indicator for the app in the top bar.  It was working in 3.32.

**Comment by kozec** [comment]
Gnome removed support for tray and appindicators some versions ago. This is not bug, but feature of Gnome -_-

Anyway, I'm guessing you have some extension that restores appindicator support, which got broken in update. That's also feature of Gnome.
