### ISSUE TITLE
GUI is blank

### ISSUE THREAD

**Issue by lnmaurer** [syncthing/syncthing-gtk#54]
The syncthing-gtk window is blank:

![syncthing-gtk](https://cloud.githubusercontent.com/assets/200698/5540533/300063fa-8a92-11e4-8f7f-26be3165b3fd.png)

I'm using version 0.5.5 downloaded from the webupd8 ppa, and I'm running Kubuntu 14.10. Syncthing itself seems to be working normally. (The web interface is normal.) FWIW, I had syncthing installed before installing syncthing-gtk.

**Comment by blomstertj** [comment]
I know this was fixed a long time ago but I think I have the same issue on Arch.  It works on my laptop though so I'm not sure what the problem is.
