### ISSUE TITLE
Syncthing version used is 6 months behind

### ISSUE THREAD

**Issue by Pantar2205** [syncthing/syncthing-gtk#549]
Todays date = 2020-01-12
Syncthing current release version = 1.3.3
Syncthing version in Syncthing-GTK = 1.2.0 (Released 2019-07-09)

Is there big changes after 1.2.0 that are holding things up or are people just busy?

Thank you for this great project.

**Comment by kozec** [comment]
Sadly, it's later case, people (i.e. me) are incredibly busy. Sorry about that.

I tested 1.3.3 briefly and it appears to work, ST-GTK should autoupdate it in next 24 hours.

**Comment by Pantar2205** [comment]
> Sadly, it's later case, people (i.e. me) are incredibly busy.
Completely understandable.

> Sorry about that.
Absolutely not at all!! I am enormously grateful for your work! I work 6-7 days a week myself and its near impossible to get time for my hobbies. My dream is to learn a language and to one day make a contribution to an open source project. Maybe when the kids are older!!

> ST-GTK should autoupdate it in next 24 hours
Amazing!
