### ISSUE TITLE
error: Info: org.gnome.Platform//43 is end-of-life

### ISSUE THREAD

**Issue by valtoree** [syncthing/syncthing-gtk#603]
hi everybody,
I get an error when I go to update my flatpak
on my Linux mint xfce

Info: org.gnome.Platform//43 is end-of-life, with reason:
   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   me.kozec.syncthingtk

how do I fix pls?
ty.

**Comment by K0-RR** [comment]
@valtoree there is nothing you can do (unless you are also a developer that is). It's up to the developer to update the runtime. Don't worry tho, the app will probably work for a few years even if not updated.

**Comment by valtoree** [comment]
Thanks bud 👍

**Comment by valtoree** [comment]
I think someone has fixed it. It does now not appear anymore. I'm going to close this. Ty to the person/s who fixed it 🙏
