### ISSUE TITLE
Mac OSX installer similar to the Windows installer

### ISSUE THREAD

**Issue by marclaporte** [syncthing/syncthing-gtk#61]
Hi!

The Windows installer is great. 

Any chance we could have something similarly easy for the Mac?
https://github.com/syncthing/syncthing/tree/master/etc/macosx-launchd
https://github.com/syncthing/syncthing-mac

Thanks!

M ;-)

**Comment by kozec** [comment]
Well, both NSIS and Python+GTK works on OSX, in plain theory. But I have no Macs around to test...

**Comment by kozec** [comment]
Both NSIS and Python+GTK should work on OSX, in plain theory. But I have no Macs around to test it.

So it may be better to open issue directly in syncthing or in one of those ports...

**Comment by marclaporte** [comment]
If you had an account to something like http://www.macincloud.com/pricing/payg, would it help?

Thanks!

**Comment by kozec** [comment]
Probably not, services like that usually restricts usage of non-standard software and it's hard to get more non-stadard than GTK on Mac. Specifically, this one:
> **Software that is currently BANNED from all servers:**
> Any torrent clients or P2P software

If you have access to Mac, try to get GTK 3.10 (or newer), python and gobject-introspection installed there (it should be possible using Homebrew manager, I believe) and run this simple application:

```
from gi.repository import Gtk

class Win(Gtk.Window):
	def __init__(self):
		Gtk.Window.__init__(self)
		self.set_title("Hello world!")
		self.add(Gtk.Label("Hello from GTK %s.%s" % (Gtk.get_major_version(), Gtk.get_minor_version())))
		self.set_size_request(640, 480)

Win().show_all()
Gtk.main()
```

**Comment by kozec** [comment]
If you, or anyone else is interested, <a href="https://github.com/syncthing/syncthing-gtk/tree/wizard-only">in this branch</a> is First run wizard stripped of everything else. It will just download Syncthing daemon, set keys, basic configuration and exit.

Also, running this will ***overwrite*** syncthing configuration, even if it already exists.

**Comment by Zillode** [comment]
Any idea how to fix this:
```
Traceback (most recent call last):
  File "/Users/user/tmp/syncthing-gtk/syncthing_gtk/stdownloader.py", line 131, in _cb_read_compatibility
    success, data, etag = f.load_contents_finish(result)
Error: g-io-error-quark: Operation not supported (15)
```
I guess it tries to write to a non-existing directory?

**Comment by kozec** [comment]
> I guess it tries to write to a non-existing directory?

No, it tries to download https://api.github.com/repos/syncthing/syncthing-gtk/tags . Error sounds like GLib implementation doesn't support loading from HTTPS.
