### ISSUE TITLE
Duplicate text in wizard - v0.5.6

### ISSUE THREAD

**Issue by alexxtasi** [syncthing/syncthing-gtk#62]
Hi and synthing-gtk is great!

I fresh installed this (v0.5.6) and I see the info-text in the wizard in double:
![syncthing-gtk_text](https://cloud.githubusercontent.com/assets/2122948/5644853/ce386b46-9670-11e4-8d03-fe4adc0307dd.png)
It's the sentence ```Please, use package... directory.```

I am using Ubuntu 14.04
regards

**Comment by kozec** [comment]
Yep, that shouldn't be there. Thanks.
