### ISSUE TITLE
minimize_on_start should be true by default?

### ISSUE THREAD

**Issue by RyuzakiKK** [syncthing/syncthing-gtk#63]
The default value in configuration.py of minimize_on_start is false. So syncthing-gtk start not minimized.
But in the help I found that there is only the option of command line -w that "Display window (don't start minimized)" but there isn't the option for start minimized.
So I guess that at the beginning the minimize_on_start variable had to be set true and not false.

Or at least I think it can be useful to add an option for start syncthing gtk minimized without edit the config.json

**Comment by kozec** [comment]
Well, having window minimized by default may be not best idea, as new user may not even realize that there is some window around. But I can add parameter like `-m, Start minimized`.

**Comment by RyuzakiKK** [comment]
You are right. A new parameter would be perfect.

**Comment by kozec** [comment]
Ok, here you are.
