### ISSUE TITLE
Configuring to listen on all interfaces is broken

### ISSUE THREAD

**Issue by jonohill** [syncthing/syncthing-gtk#64]
Using v0.5.6 on Windows 8.1.

The setup wizard prompts whether the WebUI should listen locally or on all interfaces. The selected options are saved as expected into the config.xml:

```xml
<gui enabled="true" tls="false"><address>0.0.0.0:8080</address><user>myuser</user><password>mypass</password></gui>
```

However syncthing-gtk tries to connect to 0.0.0.0:8080 which obviously does not work.
Changing the config.xml to only listen locally, but still with username / password:

```xml
<gui enabled="true" tls="false"><address>127.0.0.1:8080</address><user>myuser</user><password>mypass</password></gui>
```
Results in a 403 forbidden error.

The only workaround solution appears to be to revert the configuration to be local only with no authentication.

```xml
<gui enabled="true" tls="false"><address>127.0.0.1:8080</address></gui>
```

**Comment by kozec** [comment]
Hmm... I'm pretty sure I had special handling for zero address. I'll look where it gone to.

**Comment by kozec** [comment]
May I ask you if you had API key generated in config.xml?

**Comment by AudriusButkevicius** [comment]
0.0.0.0 is also fine on Windows, this whole issue is bogus, as the 403 is because of invalid session cookie or no auth credentials
