### ISSUE TITLE
Missing icons on Ubuntu 14.04

### ISSUE THREAD

**Issue by johannesgunnar** [syncthing/syncthing-gtk#68]
Several icons missing in Ubuntu 14.04. (also, on a related note, app feels slightly out of place with menu icons as Ubuntu 14.04 is set to not display icons in menus)

![menubar](https://cloud.githubusercontent.com/assets/2924543/5736952/ca1b296e-9bd3-11e4-8274-613894001bfa.jpg)
![headerbar](https://cloud.githubusercontent.com/assets/2924543/5736951/ca19c97a-9bd3-11e4-886f-aaf03ec34ee9.jpg)
![settingsmenu](https://cloud.githubusercontent.com/assets/2924543/5736953/ca1f668c-9bd3-11e4-9b07-4d518a316d96.jpg)

**Comment by kozec** [comment]
Hmm... I'm pretty sure that I have menu icons on my Ubuntu 14.04 installations, at least in that notification area parody thing.

But there is option to disable menu icons in ST-GTK, so it shouldn't be problem to display it under Ubuntu (Unity) and make it enabled by default.
