### ISSUE TITLE
Folder and Device updated status

### ISSUE THREAD

**Issue by nbonacchi** [syncthing/syncthing-gtk#71]
Hi, 
st-gtk seems to have a static impression of what the status of the folders and devices. After last update it now uses the same -lingo- as the web interface however I have multiple folders being synced that show as up to date as the device itself that is synchronizing at ##% in the web ui in st-gtk is shown as up to date. I also noticed that the indications of the download rate by folders doesn't match the info given by the web UI. Also I believe it's the same problem, if a node disconnects and no node is connected to current pc st-gtk's indicator and window remain blue instead of gray, not updating changes. All these problems go away if the app is restarted, so the first check is done correctly but somehow subsequent checks of the status of nodes is not coming through...

On a separate but related issue, in the web UI when a folder is being synced I can press a link of the files that have yet to be downloaded and a nice window with contextual information pops up telling me what files are missing which ones are being downloaded etc..... Any plans to do this also for st-gtk? (the issue is related because this would imply fixing the 'refresh rate' at which st-gtk displays information about shares)

Thanks

**Comment by kozec** [comment]
Ok, so from bottom: Yes, there is plan to implement download list, but it's long-term plan.

Transfer rate between WebUI and ST-GTK may differ a little, as they are sampled at different time and thus computed from different data. But result should be precise enough to work as informative estimation.

Now for what shouldn't happen :D
Did I understood correctly that ST-GTK displays some folders as "Up to date", while WebUI displays them as being synchronized? I have trouble to replicate this, along with indicator icon problem. Can I have some info about your configuration (OS, distro, ST-GTK version, daemon version...) and probably log generated by running ST-GTK with `syncthing-gtk -d` ?

**Comment by fcastilloec** [comment]
I'm having the same problem of st-gtk displaying "Up to date" when the webUI shows "Scanning". I thought there was a problem with syncthing not sending my files but then I realized that it was just scanning the folder, even though st-gtk showed "Up to date".
This happened with a folder with many files, each file was almost 1Gb. Maybe that could help you replicate the issue. I restarted the app and the issue went away, so it's hard to send a log file.

**Comment by kozec** [comment]
Did up-to-date status changed to scanning after some delay or it stayed until you hidden window? Event pooling is restarted with higher pool rate when window is shown, so problem may be caused by event loop crash. I'll try to replicate problem, but if event loop crash causing it, log (ideally with `-d` flag enabled) would be really helpful.
