### ISSUE TITLE
GNOME application menu gone

### ISSUE THREAD

**Issue by pulb** [syncthing/syncthing-gtk#72]
I'm using v0.5.8 on Arch linux and somehow te gnome application menu (in the top panel) is not available anymore.

**Comment by kozec** [comment]
Is normal, top-left menu button with Syncthing logo visible?

**Comment by pulb** [comment]
No, unfortunately not. Just the top-right three-stripes menu button.

**Comment by kozec** [comment]
Ok, thanks for reporting. Should be fixed by 95480c049fb7dbfdec556a0c0859a207168ea210
