### ISSUE TITLE
include syncthing

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#77]
Hi!

Is it possible to include syncthing on the installer? I'm suggesting this because it's weird for most people to have to install two programs to use one. Today, the process looks too complicated for a lot of people I want to share files with.

Could the Syncthing GTK installer detect if the system is 32 or 64 bits, download the right version and install it?

Thanks!

**Comment by AudriusButkevicius** [comment]
I think it does that on Windows?

**Comment by kozec** [comment]
> I think it does that on Windows?

Yes, it should do that anywhere unless  `syncthing` binary is found at some known location.

@robsonsobral I'm guessing that you are using Windows. What you are describing is pretty much what is supposed to happen when you are installing current version of Syncthing-GTK. What happened instead?

**Comment by robsonsobral** [comment]
Really? I didn't know that! I gonna uninstall everything and install back to check. Just one moment!

**Comment by robsonsobral** [comment]
I'm sorry, guys! I installed the Syncthing a long time before the Syncthing GTK and missed this feature. I'm really sorry for bother you on this.

I just installed the GTK again. The process could be a little easier for newbies, but I believe it's simple enough for a so young project. You're doing a great job!

May I suggest you something to think about? To rename "syncthing" to "syncthing daemon" and "syncthing GTK" to just "syncthing". Most people who needs the GTK have no idea about what "daemon" or "GTK" mean.

Bye, guys! Thank you so much for the attention! And for the useful software!

**Comment by kozec** [comment]
> May I suggest you something to think about? To rename "syncthing" to "syncthing daemon" and "syncthing GTK" to just "syncthing". Most people who needs the GTK have no idea about what "daemon" or "GTK" mean.

I have feeling that @calmh wouldn't exactly like this idea :D

And, to be honest, I don't like it either, as I believe that it would cause not confusion for anyone who already uses Syncthing, but also crazy mess for all related projects.
