### ISSUE TITLE
Conflicts with other apps running on localhost

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#79]
Hi! It's me (again) bothering you!

After a reboot, I notice that the GTK kept waiting for the daemon forever. If I start the daemon by myself, GTK works, but if I restart the daemon the GTK loses its connection again.

Then I found the issue: [YAC Reader Library](http://yacreader.com/), the app I use to serve my comics.

Isn't the first time I see it happens, but, this time, I can't just close one of then. I need them both running.

I changed the order both launch on system boot and now they're working together. Except that I can't restart the daemon without restart the YAC Reader Library.

But other people can have the same issue and any simple way to solved it.

Is there a way to avoid this issue by default?

Bye, guys!

**Comment by kozec** [comment]
By any chance, does YAC Reader listens on port 8080? Syncthing-GTK check for open port when doing 1st run wizard thing and sets Syncthing so it will not conflict with anything else, but if you install new application listening on same port, bad stuff will happen.

I should probably add check for that...

Anyway, you can fix this simply by shuting down both Syncthing and ST-GTK and editing `%LOCALAPPDATA%/syncthing/config.xml`.  Search for `<gui>` tag, `<address>` subtag and set it to, for example, 127.0.0.1:**9089** or any other port you most likely will never use.

**Comment by robsonsobral** [comment]
Yeap! Port 8080! So as SSH Tunnels I use too. But Syncthing-GTk was the last one to be installed.

Thanks for the tip! It worked!

Do you ever thought about a random port or something like that?

OFFTOPIC P.S.: Man, is really strange to have the settings split by two button son opposite sides of the interface.

**Comment by robsonsobral** [comment]
I just found the [issue #1296](https://github.com/syncthing/syncthing/issues/1296) on Syncthing.

I'm not the first one having issues and this isn't the right place for me to report it.

I'm sorry!
