### ISSUE TITLE
restore button

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#80]
Hi!

If _use traditional window header_ is disabled on Windows, the _minimize_ and the _maximize_ buttons are fine, but **restore** button uses the same icon as the right settings button.

I'm sorry for not fix this by myself, but I couldn't find where in the code the bug is.

**Comment by kozec** [comment]
Probably stupid question, but what is restore button? :D
There is probably image missing from windows build... Can you, please, take screenshot?

**Comment by robsonsobral** [comment]
This is the restore window down button on traditional header:

![untitled-1](https://cloud.githubusercontent.com/assets/931642/6009916/854831be-ab15-11e4-866c-e000211184a3.png)

And now, the missing button:

![untitled-2](https://cloud.githubusercontent.com/assets/931642/6009981/f7b7c138-ab15-11e4-9293-e5bf42317b80.png)

**Comment by robsonsobral** [comment]
Now, I see... There's two missing buttons! :D

**Comment by robsonsobral** [comment]
I should have notice that. I'm sorry. I'm so tired.

**Comment by kozec** [comment]
Np, I got this :)
