### ISSUE TITLE
Network info freeze in syncthing-gtk on Windows

### ISSUE THREAD

**Issue by chucic** [syncthing/syncthing-gtk#81]
After "amount of data downloaded counter" reaches 2.00 GB all net info stuff displayed in syncthing-gtk freeze while rest of info like CPU and RAM utilization are working well. I have to turn on WEB-UI to see correct net info.

![syncthing-gtk_network_bug](https://cloud.githubusercontent.com/assets/10828858/6018921/41dea7b0-ab9b-11e4-8e18-20d1d7d778b3.JPG)

**Comment by kozec** [comment]
Sounds like a overflow... 32 bit OS, I guess?

**Comment by chucic** [comment]
Yes, Windows 64bit, binary 32bit (if is there 64bit, i didn't find it), on linux i can't test it because i'm not able to run it on Debian...
