### ISSUE TITLE
Caja integration not working

### ISSUE THREAD

**Issue by hotice** [syncthing/syncthing-gtk#82]
Caja file manager integration can't be enabled in Ubuntu / Linux Mint - the option is grayed out (screenshot: http://i.imgur.com/CyNaZ7V.png )

This is the syncthing-gtk output:
```
W UISettingsDialog Cannot find caja/extensions-2.0/libcaja-python.so required to support Caja
```
I believe this occurs because it searches for libcaja-python.so under /usr/lib/caja/ while on Ubuntu / Linux Mint, that's available under /usr/lib/i386-linux-gnu/caja/ and /usr/lib/x86_64-linux-gnu/caja/

Tested with Ubuntu MATE 14.04 and Linux Mint 17.1 MATE.

(the Nautilus and Nemo integration works)

**Comment by kozec** [comment]
Can you, please, list content of python-caja package and check if there is `caja/extensions-2.0/libcaja-python.so` library either in `/usr/lib` or `/usr/local/lib` listed there?

**Comment by kozec** [comment]
Ok, I can probably add `/usr/lib/x86_64-linux-gnu` to search path when checking for availability, but  there is something I really don't understand here...
```
tom@ubuntu-vm:~$ dpkg-query -L python-caja | grep so
/usr/lib/caja/extensions-2.0/libcaja-python.so
```
On Ubuntu 14.04.1 LTS with Caja packages from official Mate-desktop repo...

**Comment by hotice** [comment]
It's because they were built with multi-arch support in Mate's official repo and without multiarch in Linux Mint and Ubuntu MATE.

Here's the python-caja deb from Linux Mint 17.1:
- 64bit: http://packages.linuxmint.com/pool/upstream/p/python-caja/python-caja_1.8.1-2+rebecca_amd64.deb
- 32bit: http://packages.linuxmint.com/pool/upstream/p/python-caja/python-caja_1.8.1-2+rebecca_i386.deb

**Comment by hotice** [comment]
Also, I believe that the official MATE Ubuntu repository has been replaced with the Ubuntu MATE PPAs: https://launchpad.net/~ubuntu-mate-dev

**Comment by kozec** [comment]
Ok, thanks for explanation. It should work now, with newly added paths.
