### ISSUE TITLE
Application error on O/S shutdown (windows 7)

### ISSUE THREAD

**Issue by disposablereviewer** [syncthing/syncthing-gtk#83]
I've seen this behavior on four windows 7 boxes now.  On shutdown of the o/s, an application error is repeatedly displayed for syncthing.  Force restart is the only option.  Event viewer did not provide much additional detail:

Application popup: syncthing.exe - Application Error : The application was unable to start correctly (0xc0000142). Click OK to close the application. 

System 

  - Provider 

   [ Name]  Application Popup 
 
  - EventID 26 

   [ Qualifiers]  16384 
 
   Level 4 
 
   Task 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2015-02-03T21:46:39.000000000Z 
 
   EventRecordID 33920 
 
   Channel System 
 
   Computer
 
   Security 
 

- EventData 

   syncthing.exe - Application Error 
   The application was unable to start correctly (0xc0000142). Click OK to close the application.

**Comment by kozec** [comment]
Does 0xc0000142 means anything by any chance?

**Comment by kozec** [comment]
I can't replicate this, no matter what I'm doing :( Does same problem occur if you run Syncthing daemon manually, without ST-GTK?

**Comment by AudriusButkevicius** [comment]
As far as I understand there are some service business involved here, right?
Or is this just plain syncthing not installed as a windows service?

If it is a windows service then I think it could be something todo with windows service control, as I guess syncthing gets killed as you are shutting down and restarts, or perhaps the service wrapper doesn't listen to the OS asking it to stop.

**Comment by disposablereviewer** [comment]
I had no issues running the daemon manually.  I just was looking for a UI so it was easier for my wife and this error occurs on several of our home computers when we restart or shutdown.

I don't know why an error about starting correctly happens during a windows shutdown for me.  I can manually close the program without an error, but if it's running on shutdown, it throws this error.

If you can think of any other info that would be helpful for me to provide, I will, but otherwise all I've got is the error.

**Comment by kozec** [comment]
I'm not completely sure how shutting down works on Windows, but I'd imagine that traditional SIGTERM to everything -> wait 2 sec -> SIGKILL to everything is not the case. So there is one possible reason for this behavior...
If Windows decides durring shutdown, for whatever reason, to kill Syncthing daemon before ST-GTK (its parent process), ST-GTK will detect Syncthing daemon crashing and try to restart it. And, as I learned today, trying to run anything after shutdown is initiated will result in this exact message.

Now, @disposablereviewer, could you, please, try to confirm that this is what's happening? Open ST-GTK so you can see window on screen and initiate either shutdown or logout. If you'd get <A href="http://i.imgur.com/Vv9SVTW.png"error message about Syncthing daemon being restarting or shut down</A>, then this is exactly what's happening.

**Comment by disposablereviewer** [comment]
Yes, I do.  The message says:

"The connection to Syncthing daemon lost.  Syncthing is probably restarting or has been shutdown."

Also (and this may be obvious at this point), if I do not choose 'start the daemon in the background' or 'ask me what to do’ (in the GTK UI settings), I do not receive this error on shutdown.  When I have the GTK 'wait for daemon' and I start the daemon manually, it’s fine.

**Comment by kozec** [comment]
Ok, thanks. I'll check if is possible to detect when windows is trying to shutdown and if not, simple timeout before daemon restart would probably solve this as well...

**Comment by kozec** [comment]
@disposablereviewer Can you, please, test if error still appears <A href="www.kozec.com/SyncthingGTK-v0.6-7-g806974e-win32-full-installer.exe">with this build?</A>

**Comment by disposablereviewer** [comment]
Unfortunately, I am still seeing the same behavior with this version.

**Comment by disposablereviewer** [comment]
Just out of curiosity, why are these settings grayed out and unavailable?

![settings](https://cloud.githubusercontent.com/assets/10820063/6067171/69c58ad6-ad27-11e4-82da-ce50f0a29855.png)

**Comment by kozec** [comment]
Well, there are no desktop notifications on Windows :) And for last two, probably due to some weir bug in GLib, Syncthing daemon turns into zombie process, if it's not terminated along with ST-GTK on Windows. So it's better to not change that setting yet.
---

Anyway, I'm setting up clean W7 VM to replicate this problem and if everything fails, "timeout before restarting daemon"  plan should work.

**Comment by AudriusButkevicius** [comment]
> Well, there are no desktop notifications on Windows

Lie! You have balloon popups!

**Comment by kozec** [comment]
> Lie! You have balloon popups!

Which is not same thing :) Popups are queued, so if application decides to display 10 of them, user will see 2nd only after 1st is dismissed or timeouts. And, ofc, there are no Python+GTK bindings for them.

**Comment by AudriusButkevicius** [comment]
While reading changelog for Python 3.5 I found this:
https://www.python.org/dev/peps/pep-0475/#control-events

**Comment by kozec** [comment]
> While reading changelog for Python 3.5 I found this:

Nope, it looks like window using application doesn't get those. Window using app is supposed to handle <a href="https://msdn.microsoft.com/en-us/library/windows/desktop/aa376889%28v=vs.85%29.aspx">WM_ENDSESSION</a> message, what I did in commit up there, but it looks like even that is not sent always.

I'm trying that timeout thing right now.

**Comment by kozec** [comment]
Ok , running out of options how to actually detect shutdown and unable to replicate this anywhere, <a href="https://github.com/syncthing/syncthing-gtk/releases/tag/v0.6.1">new Syncthing-GTK release</a> has 5s timeout before dead daemon is respawned.
@disposablereviewer, can you, please, check if this helps with problem?

**Comment by disposablereviewer** [comment]
@kozec, Sorry, I'm still seeing the same issue with that release.  

It's odd you can't replicate it.  I even was able to see the issue on a Virtualbox VM of Win7 Ultimate SP1.  Wish there was more I could add to help.

**Comment by kozec** [comment]
Sooo... hi there. It may looks like I forgotten about issue, but this is just how long it took me to get hands on laptop showing same bug.
As it turns out, only _reliable_ way how to detect windows being shut down is old `GetSystemMetrics` API originating from Windows 95 -_-

Problem should be fixed in next release.
