### ISSUE TITLE
Device ID on GTK doesn't match the one on Syncthing web interface

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#85]
Hi!

I was testing the Syncthing for iOS and... Boom! The QR codes don't match!

![qr](https://cloud.githubusercontent.com/assets/931642/6089544/6d00c4ac-ae4b-11e4-9056-fa4f03e31e09.png)

Web interface on the left and GTK on the right.

version 0.6 on Windows 8.1 64-bits

**Comment by kozec** [comment]
Weird thing... Alphabetical ID is shown correctly?

**Comment by robsonsobral** [comment]
Yeap, they match.

I'm sorry. I'm probably who most bothered you of all times!

**Comment by kozec** [comment]
> I'm sorry. I'm probably who most bothered you of all times!

Np, you have talent for finding bugs :D

That invalid QR code is same as this one, am I right?

![](http://i.imgur.com/fmnjeXW.png)

It translates to `10 00 00 ec 11 ec 11 ec   11 ec 11 ec 11 ec 11 ec` and makes no sense, but it looks like Syncthing returns it for any request ST-GTK makes on Windows...

**Comment by AudriusButkevicius** [comment]
Strange, device ID display has no OS specific code.

**Comment by robsonsobral** [comment]
I don't if this info helps, but sometimes the GTK simply doesn't show the device ID and I have to restart it.

Weird...

**Comment by chucic** [comment]
This happened to me few days ago, but i thougth i have bad QR reader in phone, so i tried another one and QR from WEB-GUI, i didn't compared the two QR's so i didn't noticed... I feel stupid now :)
