### ISSUE TITLE
Font size of folder headers 

### ISSUE THREAD

**Issue by tvld** [syncthing/syncthing-gtk#87]
Great-great product. One little little cosmetic thing: the headers in the folders now have: green background, larger font size & bold. One of three would be enough, for example only green background & bold. Now it just looks uncool on my Lenovo Yoga (3200px screen)
![font-gtk](https://cloud.githubusercontent.com/assets/986182/6097414/73573764-afbd-11e4-9012-347dfa8368f4.png)

**Comment by kozec** [comment]
Well, I don't see bold & not large font as better, but I can make it configurable, at least as "hidden" option.

**Comment by tvld** [comment]
It's detail for sure ... Still from UI perspective my opinion would be to choose smaller font ;)  .. or you could take over same font size as windows titles? In that way you dont need additional config. Just an idea )

**Comment by robsonsobral** [comment]
Yeah, that's a interesting idea. Can you get the font settings from the OS?

**Comment by kozec** [comment]
> Can you get the font settings from the OS?

Probably not. Titlebar font is decided by windowmanager and there is no unified way how am settings are stored, so it would require writing methods at least for most commonly used. And that's direction where craziness lies :)

**Comment by robsonsobral** [comment]
Dammed! I thought the OS provide these values.

![font-sizes](https://cloud.githubusercontent.com/assets/931642/6110737/e67061b4-b06a-11e4-86f8-9dc05784221a.png)

This is sad, but... No problem. I gonna find something else to bother you.

**Comment by tvld** [comment]
Oops...sorry, Forgot that there are still developers not using Ubuntu ;)

**Comment by marclaporte** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  marc@laporte.name
    Domain marclaporte.com has exceeded the max emails per hour (312/300 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:15554)
	by uskm12.fastbighost.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.84)
	(envelope-from <bounces+848413-0bd8-marc=marclaporte.com@sgmail.github.com>)
	id 1YKrdk-002Ton-2G
	for marc@marclaporte.com; Mon, 09 Feb 2015 18:56:52 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=D8q5c+MMlu0hwMKIho5MA1xUFZo=; b=WOYwCNOnNw3ABZ23
	Sk3TWr8wPqHG/CV1WIrHFcLhk8+si1/ocRPAsZ3db3Y2zGXt4O2SSh3jcWKQzHEW
	MTlF9U495Hly+WWBD9b+Xs/8eSuwV5q/XTJLFzXemuebhvGgsfdG2aVYIuOQe+Mn
	K7qQvnQnODjjJj2zMMGj4YKggLo=
Received: by filter0018p1mdw1.sendgrid.net with SMTP id filter0018p1mdw1.12033.54D8E6C84
        2015-02-09 16:56:40.679449766 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd-035 (SG) with ESMTP id 14b6f457fb3.4ee.e9d72
	for <marc@marclaporte.com>; Mon, 09 Feb 2015 16:56:40 +0000 (UTC)
Date: Mon, 09 Feb 2015 08:56:40 -0800

**Comment by kozec** [comment]
> Oops...sorry, Forgot that there are still developers not using Ubuntu ;)
Don't mention that name before me... ST-GTK still has more distro-specific code for Ubuntu than it has for Windows :D

Anyway, I added option to config file (that's `~/.config/syncthing-gtk/config.json`) where you can set style using <a href="https://developer.gnome.org/pango/stable/PangoMarkupFormat.html">Pango Markup Format</a>. But note that screwing this setting may cause app to crash ;-)

**Comment by tvld** [comment]
It is goo surely. But was more a "nice to have" than a problem :)

**Comment by kozec** [comment]
Ok, it's already included in latest release.
