### ISSUE TITLE
icons inconsistency

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#88]
Hi!

I first thought that some Adwaita icons are because there are no equivalent on the Bootstrap Glyphicons Halflings, but it doesn't look the case.

Is there some reason for it? Can we look for a more complete icon pack?

**Comment by kozec** [comment]
Where, what, how? Panels are using glyphicons because that is what webui is using and rest (parts not present in webui) uses icons from system theme. I plan to replace glyphicons with svgs or something that can be used with dark themes, but that's more like long-term goal.

**Comment by robsonsobral** [comment]
I'm sorry. Newbie doing newbie things!

So these nasty icons came from Windows itself?

![icons](https://cloud.githubusercontent.com/assets/931642/6133961/f24c92b6-b144-11e4-8cf1-42358a153dc2.PNG)

I'm sorry! I thought I could help to replace them. I'm sorry!
