### ISSUE TITLE
Syncthing Update

### ISSUE THREAD

**Issue by nille02** [syncthing/syncthing-gtk#89]
Since some Days now there is the Syncthing 0.10.22 Update. Unfortunately ST-GTK don't Update and forbid Syncthing to update himself. Stop ST-GTK and and start syncthing direct and he immediately  start the update. 

That happens on all my Windows 7 and Win 8.1 installations.

**Comment by kozec** [comment]
> Since some Days now there is the Syncthing 0.10.22 Update

Since yesterday. ST-GTK checks for update once per day, so update can be delayed.
