### ISSUE TITLE
Content of folders and devices UI boxes not displayed

### ISSUE THREAD

**Issue by silopolis** [syncthing/syncthing-gtk#90]
Hi,

Installed Syncthing and Syncthing-GTK from PPAs on a fresh Linux Mint KDE 17.1. Everything seems to work except that I can't see the content of folders and devices UI boxes. A picture's worth a thousand word:
![syncthing-sshot01](https://cloud.githubusercontent.com/assets/414540/6145736/6048b402-b1e5-11e4-85aa-c0e22d75108b.png)

These are the packages present on my system:
> syncthing                     0.10.20-3   amd64
> syncthing-gtk                 0.6-1~webupd8~trust   amd64
> libgtk-3-0:amd64              3.10.8~8+qiana   amd64
> gir1.2-gtk-3.0                3.10.8~8+qiana   amd64
> gir1.2-appindicator3-0.1      12.10.1+13.10.20130   amd64

**Comment by kozec** [comment]
Wouldn't that be same problem as #54? 
If not, please, try to run Syncthing-GTK from terminal and copy-paste whatever it outputs.

**Comment by silopolis** [comment]
Hi,

Installing python-gi-cairo indeed solved the issue, thanks :)
Note that in my case, even launched with the `-v` switch, no relevant log
was output:
> ~ > syncthing-gtk -v
> ** (syncthing-gtk:19403): WARNING **: Error retrieving accessibility bus
address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus
was not provided by any .service files
> Syncthing-GTK started and running in notification area
> V Daemon        Set refresh interval to 5
> I App           updatecheck: disabled

Hope next release will add dependency as this is only a suggest for
python-gi (tried to report this but gave up after 10 min searching how to
file a ticket on the package on Launchpad :( )

Bests


2015-02-11 18:38 GMT+01:00 kozec <notifications@github.com>:

> Wouldn't that be same problem as #54
> <https://github.com/syncthing/syncthing-gtk/issues/54>?
> If not, please, try to run Syncthing-GTK from terminal and copy-paste
> whatever it outputs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncthing/syncthing-gtk/issues/90#issuecomment-73925981>
> .
>



-- 
--
Jérémie Tarot
http://about.me/silopolis

**Comment by kozec** [comment]
> Hope next release will add dependency as this is only a suggest for python-gi (tried to report this but gave up after 10 min searching how to file a ticket on the package on Launchpad :( )

That's probably something that should @hotice know about :D

**Comment by hotice** [comment]
PPA updated, thanks!

**Comment by kozec** [comment]
Great :) Thank you.

**Comment by silopolis** [comment]
Thanks :)
