### ISSUE TITLE
wrong file references on 0.6.1

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#91]
I've an impression that GTK shouldn't be looking for these files at these paths:

![0 6 1](https://cloud.githubusercontent.com/assets/931642/6191421/755378c6-b390-11e4-8a09-99eaed0ba165.PNG)

**Comment by kozec** [comment]
Yeah, sorry, I forgot to remove that requirement. Updated installer is already in place.

**Comment by robsonsobral** [comment]
Does GTK updates itself?

**Comment by kozec** [comment]
Nope, it's bundled in Syncthing-GTK "full" installer or downloaded if needed on by normal one.
