### ISSUE TITLE
grayed options

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-gtk#92]
Hi!

Why there's some grayed options?

![gray](https://cloud.githubusercontent.com/assets/931642/6192800/cfef3322-b39c-11e4-975f-154114e4183c.png)

**Comment by kozec** [comment]
I'm pretty sure someone asked this already :D
Windows has no support for desktop notifications, so it's not possible to enable those. And leaving daemon running causes buggy behavior, so it's temporally not possible as well.

**Comment by robsonsobral** [comment]
I'm pretty sure somebody asked, but I couldn't find. I'm sorry, I know you have other issues to deal with. ;-)
