### ISSUE TITLE
Syncthing not connected to the repository

### ISSUE THREAD

**Issue by John-uln** [syncthing/syncthing-gtk#95]
Can't connect to peer.
Version: v0.6.1-1-g4c58ac5-win32 (Daemon v0.10.22)
OS: Windows 8.1 Corporative
Upnp enabled.
Others everything is fine
![disc](https://cloud.githubusercontent.com/assets/7571890/6314118/95ffb412-b9e0-11e4-830a-612643bbe499.png)

**Comment by kozec** [comment]
That's most likely <a href="https://github.com/syncthing/syncthing/issues">Syncthing</a> problem, not bug in ST-GTK, but for start, you should click on left-side menu (blue round icon), select `Display Daemon Output` and paste what sounds like error, or just everything to some observable place.

**Comment by John-uln** [comment]
[HBHOM] 19:59:41 INFO: syncthing v0.10.22 (go1.4.1 windows-386 default) unknown-user@syncthing-builder 2015-02-09 22:03:31 UTC
[HBHOM] 19:59:41 INFO: My ID: HBHOMRM-6UXTG46-2VGUJVT-HHXYMBQ-ISVSCRK-WGLBZNA-RMU34FA-JHAZUAL
[HBHOM] 19:59:41 INFO: Starting web GUI on http://127.0.0.1:8080/
[HBHOM] 19:59:43 INFO: Starting UPnP discovery...
[HBHOM] 19:59:49 INFO: UPnP discovery complete (found 0 devices).
[HBHOM] 19:59:49 INFO: Starting local discovery announcements

**Comment by AudriusButkevicius** [comment]
UPnP is failing, hence why you cannot connect.
I suggest you setup fixed port forwarding.

**Comment by John-uln** [comment]
Well. How it make? Can you please tell me.

**Comment by AudriusButkevicius** [comment]
It's specific per router, setup port forwarding, and forward routers 22000 to 22000 of your machine (port has to be the same).

**Comment by John-uln** [comment]
I setup porf forwarding for my router, but this doesn't working again. I forward port 22000/TCP and 21025/UDP. And I enabled UPnP for my router, but this doesn't working.

**Comment by John-uln** [comment]
Thank you very much for your answers. They helped me a lot and now it worked. We had to wait a bit after setting upnp! Thank you:)
