### ISSUE TITLE
add build instructions

### ISSUE THREAD

**Issue by lkwg82** [syncthing/syncthing-gtk#99]
I'd like to play a bit with the app and need the build instructions to create the executables.

Would you be so kind to add them?

Cheers Lars

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing-gtk/blob/master/build_windows.py#L4

**Comment by AudriusButkevicius** [comment]
And:
```
Or, in worst case scenario, download latest tarball, extract it and run syncthing-gtk.py.
```

**Comment by lkwg82** [comment]
ah ok, and for linux the package maintainer does this, r?

thx.

**Comment by kozec** [comment]
There is standard setup.py included root directory of repo. It is used to build packages at least on Arch Linux and SuSE and should work anywhere.

**Comment by lkwg82** [comment]
I'm a developer but sometimes it is tricky just to guess from code, what can happen and how it should.

I expected some packages rpm/deb from this setup.py, it just copies it to build.

Maybe some lines in the Readme can clarify the build process.

Thx anyway!

**Comment by kozec** [comment]
Well, setup.py is standard python way of doing build and installation and as readme states, you don't actually need to build anything - it's just python, run `syncthing-gtk.py` and you are good to go ;-)

**Comment by lkwg82** [comment]
I already worked it out ;).
